### ISSUE TITLE
Use reverse domain notation for tool speficific standards for terminals

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1002]
For future tool-specific standards for terminals, in https://fmi-standard.org/docs/3.0-dev/#_terminals it is recommended 

> [It is recommended that vendor specific rules start with _vendorName or _toolName to avoid namespace clashes.]

However, in two other places of the FMI standard, where we refer to layered standards (namely the /extra directory (in https://fmi-standard.org/docs/3.0-dev/#fmu-distribution) and the new Annotations  (https://github.com/modelica/fmi-standard/pull/949) ) we explicitly prescribe to use a reverse domain name.
In order to be consistent, shouldn't we demand the same for layered standards describing terminals?
This could look like `org.modelica.ssp.something` or `com.vendorname` or `com.vendorname.toolname`

@pmai : could you please comment on this?

**Comment by pmai** [comment]
@chrbertsch we followed the reverse domain name way in SSP, and that translated to the extra and annotations in FMI. It is a common way of allowing distributed namespaces by leveraging the DNS to provide clash-resistance, and allowing intermediate stuff (not vendor-specific, yet not core standard). So I think terminal standards should probably switch to this as well, unless there are strong reasons not to...
