### ISSUE TITLE
Why must initial dimension sizes be positive?

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1003]
In https://fmi-standard.org/docs/3.0-dev/#definition-of-model-variables it is stated

> All initial dimension sizes (i.e. prior to any configuration or reconfiguration) must be positive integers (i.e. not zero), so that no dimension is initially vanished. Changes to dimension sizes are constrained by the min/max attributes of the referenced structural parameters, which can be any non-negative integer, including zero. Specifying a minimum size of zero on a structural parameter allows any related dimension sizes to be changed to zero in Configuration Mode or Reconfiguration Mode, thus causing the respective array size to go to zero, which leaves the respective array variable without any active elements.

Why do we have the restriction, that no dimension may initially vanish, while later in re-configuration we allow this?

( I do not understand the argument 

>  [This allows importing tools to ignore structural parameters because that start value reflects the internal default setting of that structural parameter].

in https://fmi-standard.org/docs/3.0-dev/#structuralParameter

**Comment by andreas-junghanns** [comment]
@klausschuch : Can you please comment? I remember we exchanged arguments, but the description can be improved, I agree with @chrbertsch here. (You may leave the argument here as comment, we can work it into the text.)

**Comment by pmai** [comment]
As discussed in design meeting on 2020-06-17: The rationale is that this avoids importers having to deal with vanishing dimensions if they do not want to deal with them (or even with changing sizes at all). If we allowed 0 dimension sizes, tools that do not even care about changing dimension sizes must be prepared to handle vanishing dimensions.

Note that this is a pragmatic trade-off, not the only defensible option.
