### ISSUE TITLE
What is a "master clock"?

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1005]
In https://fmi-standard.org/docs/3.0-dev/#definition-of-model-variables in the definition of `initial`, it is written

> If `causality = input` the value for `initial `has to be set to exact and it is required to provide a `start` value for describing the expected initial contidion of master `clocks` for that FMU. 

What is a master clock? Is this correct?

(Also fix contidion -->condition)

**Comment by andreas-junghanns** [comment]
The next sentence also as "...an start..." which needs fixing.

However, someone should explain the entire paragraph - it makes little sense to me.

Who can help here?
