### ISSUE TITLE
canHandleMultipleSetPerTimeInstant still references CS FMUs, should be changed to xCS

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1006]
The text in https://fmi-standard.org/docs/3.0-dev/#canHandleMultipleSetPerTimeInstant still references CS FMUs, should be checked and changed to xCS

possibly related to https://github.com/modelica/fmi-standard/issues/793 (Feedthrough at events of HCS?)

**Comment by andreas-junghanns** [comment]
In the glossary, we have:
"...Any reference to all three Co-Simulation interfaces (BCS, HCS and SCS) are referred to as Co-Simulation interface, or xCS."

A CS FMU is then any of the three: BCS, HCS and SCS - isn´t that sufficient?

**Comment by chrbertsch** [comment]
> A CS FMU is then any of the three: BCS, HCS and SCS - isn´t that sufficient?

OK
