### ISSUE TITLE
Improve table for default value of initial

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1008]
Due to a light form of red–green color blindness, I personally cannot clearly distinguish between  the colors of the table

![grafik](https://user-images.githubusercontent.com/16363372/82734184-74f24880-9d19-11ea-8d94-dcd4dc50a0b7.png)
in https://fmi-standard.org/docs/3.0-dev/#definition-of-model-variables

Looking at the adoc-file, I see that we have  green, maroon, red, aqua. ....
But even if I could distinguish it: what does it mean? This is not explained.
If this is important information, we could change the background information of the whole cell accoordingly, which would make it much easier readable. (Perhaps we need this workaround to reach this https://github.com/asciidoctor/asciidoctor/wiki/How-to-set-the-background-color-of-a-table-cell)

And why do we define 
![grafik](https://user-images.githubusercontent.com/16363372/82734218-c0a4f200-9d19-11ea-9e74-1da157867e9c.png)
and not just write "--" in the table? What is the difference between "--" and "---"?`

Why do we distinguish between (A) and (F), which both have default=possibles values=exact?
![grafik](https://user-images.githubusercontent.com/16363372/82734368-e8488a00-9d1a-11ea-9fc7-094ff187d2a0.png)

Why are the notes
![grafik](https://user-images.githubusercontent.com/16363372/82734290-635d7080-9d1a-11ea-94e8-0978342a1051.png)
non-normative? Defining, what is allowed and what not, sounds quite normative. Or is this duplicate information? Why do we need it then?

(The tables would perhaps  look nicer, if they were of fixed-column width. But this we could only reach through breaking  long names like  `calculatedParameter` into two-lines
```
calculated 
Parameter
```
)

**Comment by andreas-junghanns** [comment]
Masoud: enter the value directly into the first table and underline the default value.
Torsten: Drop all colors.

**Comment by andreas-junghanns** [comment]
PR #1109 deals with these proposals. All accepted and implemented.
I went one step further and merged column 2 and 3 to reduce the width of the table.
