### ISSUE TITLE
Improve table for allowed combinations of variability and causality

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1009]
similar to #1008, for a discussion on the colour coding see there.

The colour coding for the entry for clocks is wrong:
![grafik](https://user-images.githubusercontent.com/16363372/82734893-1c717a00-9d1e-11ea-8994-754127fea90e.png)
should be green, right?

The comment (18) on allowed combinations is meaningless: 
![grafik](https://user-images.githubusercontent.com/16363372/82734906-3743ee80-9d1e-11ea-9016-86275740ed84.png)

see also https://github.com/modelica/fmi-standard/issues/958

**Comment by andreas-junghanns** [comment]
Masoud: enter the value directly into the first table and underline the default value.
Torsten: Drop all colors.
