### ISSUE TITLE
Improve 2.4 Common concepts for Co-simulation

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1012]
- ~~"In FMI for Co-Simulation, both functions ... " --> "... both groups of functions".~~
- ~~" ... evaluates the subsystem inputs u(tci), ..." can be misunderstood. --> "... determines ..."?~~
- ~~" the ability to provide derivatives of outputs w.r.t. time, to allow interpolation (Section 4.2.1)," should be changed to "... to allow input approximation"~~
- ~~throughout the documentation we synonoymously use "tool coupling" or "simulator coupling", but none of these is in the glossary~~
- ~~Shouldn't in https://fmi-standard.org/docs/3.0-dev/#_coupling_scenarios DCP be referenced?~~
- ~~The sentences~~

> Early return is even helpful if the FMU or the Co-Simulation master do not support the advanced handling of events based on the Hybrid Co-Simulation functionalities. In this way, multiple event types and also outputClock ticks or interrupts can be supported based on the early-return functionality and additional functionalities provided by Hybrid Co-Simulation.

~~are not clear to me. Could someone please provide and example?~~
If an FMU detects an (internal) event, it can return early to force an communication time point at which the master can propagate a/the clock if it can detect it. This is not the same as proper event handling, but for some simple type of events, this is sufficient.

**Comment by chrbertsch** [comment]
> If an FMU detects an (internal) event, it can return early to force an communication time point at which the master can propagate a/the clock if it can detect it. This is not the same as proper event handling, but for some simple type of events, this is sufficient.

@andreas-junghanns : but what does the last part of the sentence 
![grafik](https://user-images.githubusercontent.com/16363372/82998134-a0ba4a80-a007-11ea-92a1-08e0ec131418.png)
mean?

**Comment by andreas-junghanns** [comment]
Events in the Modelica sense require quite some machinery to properly handle.
In many simpler use cases, it is sufficient to know that an event occurred at a given point in time, notify everyone about the event and the timing, give them a chance to do "their thing" and then go on.
Use case: a plant model triggers crank-shaft synchronous interrupts for the controller to handle injection and ignition computations.
This use case only requires the plant model to create an early return, signal an output clock to be active and the master forwards this clock to the controller (along with all the IO exchange usual for each communication time point) and then all can happily continue.
