### ISSUE TITLE
Review 3.1 (ME mathematical description)

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1015]
- ~~What does "that give the smallest time instant" in the sentence~~ Use "earliest" as suggested previously. 

> An event instant ti is defined by one of the following conditions that give the smallest time instant:

~~mean?~~

- ~~add line break before "All the following events are internal events."~~

- ~~fix formatting of  "stem[t_0]" in 3.1.2.1~~

- ~~Generally, https://fmi-standard.org/docs/3.0-dev/#math-model-exchange seems not to be adapted enough for the new clock features. Especially: Change sentence " In FMI 2.0 there is no mechanism that the FMU can provide the information whether a discrete-time variable is active or is not active (is not computed) at an event instant. Therefore, the environment has to assume that at an event instant always all discrete-time variables are computed, although internally in the FMU only a subset might be newly computed." in https://fmi-standard.org/docs/3.0-dev/#_event_mode for FMI 3~~

- [x] Bad quality of figure 10, using fmiSetXXX / fmiGetXXX instead of fmi3SetXXX / fmi3GetXXX in pseudocode.  #1045

- [x] Pseudocode should be moved out of the picture and converted to C-Code that can be validated. -> #1045

- ~~Change "In reality, every scalar output argument is computed by one fmi3Get{VariableType} function call." to " ... might be computed ..."~~

- ~~before the sentence "When connecting FMUs together, loop structures can occur that lead to particular difficulties because linear or non-linear algebraic systems of equations  ..." a new section 3.1.3, e.g. with title "Model evaluations, dependencies and calling sequence" should be started, because the following texst no longer belongs to 3.1.2 "computation modes"~~

- ~~The information contained in "[Remark 1 - Calling Sequences:" seems to be too important to be hidden in non-normative text. Shouldn't this be moved to https://fmi-standard.org/docs/3.0-dev/#ModelStructure?~~ Important, yes, but not normative: this is something that Pierre might want to place into the implementer´s guide.

- How is the example 
![grafik](https://user-images.githubusercontent.com/16363372/82749659-fd6cf980-9daa-11ea-8366-8ce1a08ee695.png)
related to the new clock features in ME in FMI 3.0? We should not use the FMI 3.0 formatting and referencing
![grafik](https://user-images.githubusercontent.com/16363372/82749682-29887a80-9dab-11ea-83cc-009f3d44caf3.png)
for Modelica Clocks!

- ~~Fix formatting in remark 3: 
![grafik](https://user-images.githubusercontent.com/16363372/82749748-af0c2a80-9dab-11ea-8f86-7c49586e5dac.png)~~

 - ~~Explain or remove "Modelica slang" "impure function" in Remark 3~~ Added as TODO into the glossary.

- ~~Add non-normative-text end-bracket "]" after remark 3~~

**Comment by andreas-junghanns** [comment]
> What does "that give the smallest time instant" in the sentence "An event instant ti is defined by one of the following conditions that give the smallest time instant" mean?

I think we can improve clarity here with "that give the earliest time instant". Does that make more sense to you?

**Comment by chrbertsch** [comment]
> I think we can improve clarity here with "that give the earliest time instant". Does that make more sense to you?

I would state it that way:
An event can occur due to one of the following conditions; the next event instance t_i is defined by the earliest occurance of one of them:

**Comment by andreas-junghanns** [comment]
> I would state it that way:
> An event can occur due to one of the following conditions; the next event instance t_i is defined by the earliest occurance of one of them:

Can we find a shorter description, preferably without semicolon?
What about removing everything until and including the semicolon?

"The next event instance t_i is defined by the earliest occurance of one of the following conditions:"

Note: PR #1028 does not contain this fix yet - feel free to change the PR if you like this proposal.

**Comment by andreas-junghanns** [comment]
@chrbertsch : Can we both go through the remaining points to create a PR together? Please let me know when you are available.

**Comment by chrbertsch** [comment]
Ticket-viewing-meeting

regarding the figure 21:

Torsten B: don't use 3d blocks
Klaus: use a notation like FMU2.u1
Klaus: make it more c-style with comments
