### ISSUE TITLE
Rename providesDirectionalDerivative and providesAdjointDerivative to plural

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1017]
The singular sounds strange. 
I would rename these capability flags to `providesDirectionalDerivatives `and `providesAdjointDerivatives`

Other opinions?

**Comment by andreas-junghanns** [comment]
Discussion at web design meetings:
Poll: agree with proposal:
Agree: Christian, AndreasJ, Otto, TorstenB, Pierre, 
Disagree: None
Abstain: 

Accepted!
