### ISSUE TITLE
Review of 3.3 (ME schema)

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1018]
- ~~providesAdjointDerivative
![grafik](https://user-images.githubusercontent.com/16363372/82761846-c2e07c80-9dfd-11ea-9686-08b3656cb0c4.png)
--> addresssed by PR #1021~~

- ~~reformat
![grafik](https://user-images.githubusercontent.com/16363372/82762447-55cee600-9e01-11ea-9401-5e1f4472397d.png)
(at least chaning "." to ":", possibly creating a list and stating "for return values of data type boolean ..." -->fixed in https://github.com/chrbertsch/fmi-standard/tree/fix-formatting-issues~~

**Comment by andreas-junghanns** [comment]
Can we close this issue? Your points are all deleted...
