### ISSUE TITLE
Is NULL allowed for argument resourceLocation of fmi3InstantiateXXX functions?

### ISSUE THREAD

**Issue by TorstenBlochwitz** [modelica/fmi-standard#1020]
I think we should explicitly clarify if NULL is allowed or not for the argument "resourceLocation" of the fmi3InstantiateXXX functions.

**Comment by chrbertsch** [comment]
As the resources directory was made mandatory with https://github.com/modelica/fmi-standard/pull/833, 

```
resources                     // resources needed by the FMU
   // data in FMU specific files which will be read during initialization;
   // also more folders can be added under resources (tool/model specific).
   // In order for the FMU to access these resource files, the resource directory
   // must be available in unzipped form and the absolute path to this directory
   // must be reported via argument "resourceLocation" of fmi3InstantiateXXX.
```
a NULL pointer for resourceLocation should be forbidden. As a NULL pointer is no URI, IMHO it is already forbidden (see https://github.com/modelica/fmi-standard/issues/814) . Perhaps we should write this  more explicitely. @TorstenBlochwitz : could you please propose wording?

Or are there targets without a file system? If yes, what should  we do then?

**Comment by TorstenBlochwitz** [comment]
I see two possibilities here:

1. If the FMU runs on a target without file system or without network connection (https, http and ftp are allowed as URI too) NULL is provided for resourceLocation.

2. We forbid NULL as argument here, which implicitly implies that FMUs can trust to be executed on platforms with file system (or a network connection).

**Comment by chrbertsch** [comment]
> I see two possibilities here:
> 
>     1. If the FMU runs on a target without file system or without network connection (https, http and ftp are allowed as URI too) NULL is provided for resourceLocation.
> 
>     2. We forbid NULL as argument here, which implicitly implies that FMUs can trust to be executed on platforms with file system (or a network connection).

I think 1. is incompatible with making the resources folder mandatory. We even require, that the FMU must handle file URIs, so an network connection is not enough ... If we go for 1., we should revert making the resources folder mandatory and allow a return of NULL for resources location only, if the resources folder in the FMU is not present. (Otherwise how could the FMU be simulated, if it relies on resources?)

**Comment by andreas-junghanns** [comment]
We have always also targeted embedded platforms without file systems.
We (I) missed this point back then and unless we want to restrict target platforms, the resourceLocation must be optional and NULL must be valid.
Many FMUs do not need additional resources and many tools have special options for exporting to platforms without file access (e.g. Silver has that).

**Comment by sjoelund** [comment]
Why not simply allow returning an error code if `NULL` was passed and the FMU cannot simulate without the resources? Because it might be that there is something essential there (such as a lookup table)

**Comment by andreas-junghanns** [comment]
> Why not simply allow returning an error code if `NULL` was passed and the FMU cannot simulate without the resources? Because it might be that there is something essential there (such as a lookup table)

Of course, this is the error handling. We are discussing here what the standard should mandate. We are trying to be strict wherever we can to remove ambiguities and simplify implementations and ease error detection. We just detected that we cannot be as strict as we thought a few days ago.

**Comment by pmai** [comment]
At the time I was very slightly favouring keeping the resource folder optional and allowing NULL, which seems to me the less restrictive solution (and implementations will have to guard against NULL anyway, just for sanity, regardless of what we specify in the standard).
