### ISSUE TITLE
Review of Chapter 5 (HCS)

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1022]
5.2.1 :

- ~~Delete sentence "In other cases a null pointer can be assigned to the fmi3CallbackIntermediateUpdate callback, for instance when the interface type is Model Exchange." as this is the HCS Description.~~

- ~~Define "Newtonian time instant" in glossary.~~

- ~~"There may be an event iteration in Event Mode at a Newtonian time instant and have super-dense time instants." sounds strange~~ I tried to improve this

5.2.2. : 

- ~~Change "If the early-return request of the Co-Simulation master " to "If an ..."~~

- ~~"In Event Mode and only after fmi3DoStep returned with earlyReturn == fmi3True the function fmi3NewDiscreteStates may be called. " ???? Why not always in event mode???~~ See PR #1038

- ~~Remove sentence "It is not allowed to call fmi3EnterEventMode or fmi3EnterStepMode for an FMU with interface type Basic Co-Simulation and Scheduled Co-Simulation." as this is about HCS~~

- ~~Remove sentence "The Co-Simulation master should indicate the FMU that the master has recognized the clock capabilities of the FMU and supports the clock handling by calling the Hybrid Co-Simulation interface instantiation function fmi3InstantiateHybridCoSimulation.", as this chapter is about HCS~~

- ~~I do not understand "If an FMU provides clocks, but the Co-Simulation master does not support or does not want to support early-return or clocks, by setting the interface to Hybrid Co-Simulation, the activation of model partitions inside of the FMU has to be handled internally within fmi3DoStep."~~ I changed this paragraph to "If an FMU provides <<clock,`clocks`>> and the Co-Simulation master is using the interface type Hybrid Co-Simulation, the Co-Simulation master must handle these <<clock,`clocks`>> and early return requests by the FMU.
If the Co-Simulation master does not support or does not want to support early-return or <<clock,`clocks`>>, it must set the interface type to Basic Co-Simulation if supported by the FMU.
If the FMU provides the Basic Co-Simulation interface type and is instantiated with it, the FMU must internally handle all events during <<fmi3DoStep>>."

**Comment by andreas-junghanns** [comment]
I think we can now close this ticket. @chrbertsch : do you agree? Can you please check if PR #1038 addresses the 5th point above?

**Comment by chrbertsch** [comment]
> I think we can now close this ticket. @chrbertsch : do you agree? Can you please check if PR #1038 addresses the 5th point above?

Yes it does
