### ISSUE TITLE
Collect possible content for implementers guide

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1029]
Regularly an "FMI implementers guide" gets mentioned in discussions (and was there for FMI 1.0)
Let's collect "Boundary conditions" and possible content

Boundary conditions: 
- It could be living document (perhaps a Wiki?), that is regularly updated.
- non-normative 
...

Possible conent:
- as mentioned in https://github.com/modelica/fmi-standard/issues/1015#issue-623824305: 
Remark 1 in https://fmi-standard.org/docs/3.0-dev/#math-model-exchange "Calling sequences" should be mentioned or perhaps moved to the implementers guide
...

@pmai : could you please add your ideas to this?

(Once we have collected possible content, we can decide, if we really want to spend that effort to create and maintain an implementers guide)

**Comment by andreas-junghanns** [comment]
Much better: a version of the FMI Implementer´s Guide already exists.

What we need to define what should be in there and what should NOT be in there because it belongs into the standard document.

One extreme would be to say: all non-normative text should be in the FMI IG. But I think the standard document should be understandable on its own. The FMI IG should contain tips and tricks that explain how to implement well, not just correctly. Especially given certain known issues with compilers, OSs, often used libraries, commonly known programming errors etc.
Well, at least that is my opinion (let´s not call it humble).

Pierre might have a different opinion, I would love to hear how he would define the line between non-normative text in the standard and the FMI IG.

Over to you, Pierre!

**Comment by andreas-junghanns** [comment]
Ok, first attempt of the two lists, please edit here:

In IG:
 - tips and tricks how to implement robustly and well (beyond correctly), e.g. deal with known issues of
   - compilers/linkers
   - interactions of FMU/master algorithms with the OSs
   - commonly used libraries
 - warnings about commonly made programming errors

Not in IG:
 - standard text
 - non-normative hints/warnings about how to interpret the standard ("in other words...", or "in simpler words...")

**Comment by chrbertsch** [comment]
Ticket-viewing meeting: 

Pierre: We do not aim for the  v3.0 milestone

**Comment by andreas-junghanns** [comment]
Add a note about connecting clocked variables.

**Comment by andreas-junghanns** [comment]
_However, just like in FMI 2.0, it could in principle also be implemented by activating the model equations only at the first event iteration and returning always `newDiscreteStatesNeeded == fmi3False` from <<fmi3NewDiscreteStates>>._
_Furthermore, the discrete-time <<state,`states`>> are not updated by <<fmi3NewDiscreteStates>>, but as first action before the discrete-time equations are evaluated, in order that_ latexmath:[^{\bullet}\mathbf{x}_d] _(= value at the previous Lucid Synchrone/Modelica 3.3 clock tick) and_ latexmath:[\mathbf{x}_d] _(value at the latest Lucid Synchrone/Modelica 3.3 clock tick) have reasonable values between Lucid Synchrone/Modelica 3.3 clock ticks._

**Comment by andreas-junghanns** [comment]
- move some of the content of 3.1.3 "Model Evaluations, Dependencies, and Call Sequence"

**Comment by oliverkotte** [comment]
Possible topic for the implementer's guide:

To simulate externally scheduled virtual ECUs in virtual time, the FMI for Co-Simulation with Event Mode is a viable alternative to the FMI for Scheduled Execution. Using CS instead of SE for the virtual ECU has benefits when it comes to integration with the CS-FMUs of the remaining system.

Consider a virtual ECU as FMU for CS that is implemented such that
(1) No computation is done in StepMode, i.e. doStep() only advances internal simulation time.
(2) All computations are done in Event Mode by way of clocks activating model partitions.

Then, the effect of the call sequence
doStep(dt to activationTime), enterEventMode(), setClock (clock), updateDiscreteStates(), enterStepMode() of CS
becomes analogous to the call
activateModelPartition (clock, activationTime) of SE
and thus, for this use case, the FMIs for SE and CS become interchangeable in virtual time simulation.

**Comment by chrbertsch** [comment]
- discussion of the different interface types
- use cases (e.g. virtual ECUs)
- Licensing (comment on runtime licensing, legal considerations (e.g. open source licenses)
- how to deal with missing (non-optional) features (e.g., string inputs)
- interplay between FMUs of different FMI versions

Go through non-normative text of FMI standard and see which parts can be moved to implementers guide

**Comment by chrbertsch** [comment]
Requirement: Support "permanent" links in the created html, so that subsections or topics can be referenced from other documents persistently.

**Comment by chrbertsch** [comment]
Provide best practices how to generate multi-platform FMUs (e.g. by compiling source code FMUS on different targets with fmpy or other tools)

**Comment by chrbertsch** [comment]
Regular Design Meeting: 

- TorstenS: We could recycle a Reference FMU that calls other DLLs, or the other way round.
- The preliminary version is available to fmi-design members here: https://github.com/modelica/fmi-guides/
- perhaps we should select github actions also fmi fmi-standard build instead of circle-ci

**Comment by chrbertsch** [comment]
How to deal with "FMUs" to support FMI(1)2,3? Can SSP be used for that? See https://stackoverflow.com/questions/67435437/is-it-possible-to-create-one-fmu-which-supports-fmi-2-and-fmi-3?noredirect=1#comment119276676_67435437

**Comment by chrbertsch** [comment]
Provide information on the needed tool etc. in the documentation folder in case of needsExecutionTool=true, see #1470

**Comment by andreas-junghanns** [comment]
See also: https://github.com/modelica/fmi-guides/

**Comment by chrbertsch** [comment]
Web-meeting:
can be inspected now on https://github.com/modelica/fmi-guides/blob/main/fmi-guide/index.adoc 
Specific comments are welcome. Pierre will trigger people for review of specfic parts.
Let's discuss making this public in the next steering committee meeting on Oct 12th (not yet release).  The invitation to the Steering committee meeting has been forwareded to @pmai 
@TorstenBlochwitz  will check with the MA Board, also about use of logo)

**Comment by pmai** [comment]
>     * as mentioned in [Review 3.1 (ME mathematical description) #1015 (comment)](https://github.com/modelica/fmi-standard/issues/1015#issue-623824305):
>       Remark 1 in https://fmi-standard.org/docs/3.0-dev/#math-model-exchange "Calling sequences" should be mentioned or perhaps moved to the implementers guide

Now issue modelica/fmi-guides#2.

**Comment by pmai** [comment]
> _However, just like in FMI 2.0, it could in principle also be implemented by activating the model equations only at the first event iteration and returning always `newDiscreteStatesNeeded == fmi3False` from <>._ _Furthermore, the discrete-time <<state,`states`>> are not updated by <>, but as first action before the discrete-time equations are evaluated, in order that_ latexmath:[^{\bullet}\mathbf{x}_d] _(= value at the previous Lucid Synchrone/Modelica 3.3 clock tick) and_ latexmath:[\mathbf{x}_d] _(value at the latest Lucid Synchrone/Modelica 3.3 clock tick) have reasonable values between Lucid Synchrone/Modelica 3.3 clock ticks._

Now in issue modelica/fmi-guides#4.

**Comment by pmai** [comment]
> Add a note about connecting clocked variables of clocks with different properties.
> Maybe even how to connect any different kind of variables "correctly".

Now in issue modelica/fmi-guides#3.

**Comment by pmai** [comment]
> 
> 
> Possible topic for the implementer's guide:
> 
> To simulate externally scheduled virtual ECUs in virtual time, the FMI for Co-Simulation with Event Mode is a viable alternative to the FMI for Scheduled Execution. Using CS instead of SE for the virtual ECU has benefits when it comes to integration with the CS-FMUs of the remaining system.
...

Now tracked in modelica/fmi-guides#1.

**Comment by pmai** [comment]
>     * discussion of the different interface types

Already in Section 2 of IG; could be expanded a bit, but discussion from the point of view of the user is handled better in a user best-practice guide, like the publicly available SmartSE Recommendation, which already has much content here, and will be updated at the end of this year with 3.0 in mind.

>     * use cases (e.g. virtual ECUs)

Tracked in modelica/fmi-guides#1.

>     * Licensing (comment on runtime licensing, legal considerations (e.g. open source licenses)

Already in sections 2 and 3 of the IG, but more specific wording ofr OSS considerations to be added, tracked in modelica/fmi-guides#5.
 
>     * how to deal with missing (non-optional) features (e.g., string inputs)

Do you have something specific in mind? I mean if a feature is missing you have a problem, and the IG is addressed to implementers, not users...

>     * interplay between FMUs of different FMI versions

There is already wording in section 2 to call for this. Given that we do not know what implementations do to import FMUs into their system, we cannot state anything specific on interoperability, except mapping of types and arrays, the latter of which is also handled in more detail in section 3.

>     * descrbe remote execution

What should be described there, given that this is not a part of the standard, and there are various ways of doing remote execution (e.g. DCP, our RFMI protocol, the stuff that FMPy does, ...), and what to provide is really up to the implementation...

>     * Go through non-normative text of FMI standard and see which parts can be moved to implementers guide

Will be done once other content is integrated.

>     * move source-code usage from 2.2.1 example from standard to IG [and add a rationale as non-normative text to standard document]

I don't see any specific example in 2.2.1 that could usefully be removed from the standard as it stands. Has this been obsoleted, or is there something specific that you can point me to?

>     * Better explain recommended usage and limitations of SE, see #1440

Already tracked in modelica/fmi-guides#1.

**Comment by pmai** [comment]
> Provide best practices how to generate multi-platform FMUs (e.g. by compiling source code FMUS on different targets with fmpy or other tools)

The IG recommends to generate multi-platform FMUs. How this is done is surely up to the implementation, and one can hardly point to any best practice, since this really depends on the implementation strategy, i.e. does it support cross-compilers, does it ship with cross-compilers, does it even produce source FMUs, etc.

**Comment by andreas-junghanns** [comment]
Looks to me as if we can close this here - all comments should go into the IG repo.
Re-open if you do not agree.
