### ISSUE TITLE
Nested attributeGroups and lists in ModelDescription schema

### ISSUE THREAD

**Issue by IZacharias** [modelica/fmi-standard#1033]
The modelDescription schema contains constructs that are problematic for tools such as xsd2code and Windows SDK xsd.exe. This is inconvenient for FMU importers who uses these tools. 
For these parts, the code generators generate no code:

- lists defined in this way:

				<xs:attribute name="start">
					<xs:simpleType>
						<xs:list>
							<xs:simpleType>
								<xs:restriction base="xs:double"/>
							</xs:simpleType>
						</xs:list>
					</xs:simpleType>
				</xs:attribute>

- nested attributeGroups:
```
	<xs:attributeGroup name="fmi3Float64Attributes">
		<xs:attributeGroup ref="fmi3RealAttributes"/>
		<xs:attribute name="min" type="xs:double"/>
		<xs:attribute name="max" type="xs:double"/>
		<xs:attribute name="nominal" type="xs:double"/>
	</xs:attributeGroup>
```
Minor changes would solve the problems.
For lists use (as already used for binary variables):
```
<xs:attribute name="start">
    <xs:simpleType>
             <xs:list itemType="xs:double"/>
    </xs:simpleType>
</xs:attribute>
```

**Comment by pmai** [comment]
For the lists this might be an artefact of some past try at restrictions, or some other refactorings going on, I think we should change them as proposed.

For the nested attribute groups this seems more problematic, since not nesting these would mean duplications in definitions (and less obvious commonalities). Maybe a simple xslt-preprocessing prior to ingestion by xsd.exe/xsd2code would be sufficient?

**Comment by andreas-junghanns** [comment]
@IZacharias : can we close this with changes merged to master?

**Comment by IZacharias** [comment]
@pmai We could avoid duplication of attributes by referencing the attributeGroups directly from the variables, for example reference fmi3RealAttributes in fmi3Float64:

```
 	<xs:complexType name="fmi3Float64">
		<xs:complexContent>
                   <xs:extension base="fmi3VariableBase">
                           <xs:sequence>
                                  <xs:element name="Alias" type="fmi3FloatVariableAlias" minOccurs="0" maxOccurs="unbounded"/>
                           </xs:sequence>
                           <xs:attributeGroup ref="fmi3RealAttributes"/>
                           <xs:attributeGroup ref="fmi3Float64Attributes"/>
                           <xs:attribute name="start">
                                  <xs:simpleType>
                                        <xs:list itemType="xs:double"/>
                                  </xs:simpleType>
                           </xs:attribute>
                           <xs:attributeGroup ref="fmi3RealVariableAttributes"/>
                    </xs:extension>
```
```
	<xs:attributeGroup name="fmi3RealAttributes">
		<xs:attribute name="quantity" type="xs:normalizedString"/>
		<xs:attribute name="unit" type="xs:normalizedString"/>
		<xs:attribute name="displayUnit" type="xs:normalizedString"/>
		<xs:attribute name="relativeQuantity" type="xs:boolean" default="false"/>
		<xs:attribute name="unbounded" type="xs:boolean" default="false"/>
	</xs:attributeGroup>
	<xs:attributeGroup name="fmi3Float64Attributes">
		<xs:attribute name="min" type="xs:double"/>
		<xs:attribute name="max" type="xs:double"/>
		<xs:attribute name="nominal" type="xs:double"/>
	</xs:attributeGroup>
```
