### ISSUE TITLE
Missing Dimension and Annotations element for Enumerations in ModelDescription schema

### ISSUE THREAD

**Issue by IZacharias** [modelica/fmi-standard#1034]
In ModelDescription schema, Enumeration is the only variable without Dimension and without Annotations element:

![image](https://user-images.githubusercontent.com/33029000/83139518-ce2cf400-a0ec-11ea-8e3b-9f2f96ad2438.png)

Is that intentional or accidental?

**Comment by pmai** [comment]
That seems to be an accident in the way that enumeration has been defined, thus dropping the stuff that should have been inherited from fmi3VariableBase. Don't know the history of this definition...

**Comment by pmai** [comment]
Probably accidentally caused by 4fab32729ae350a1e8657342bc8680376a4898ac
