### ISSUE TITLE
Make argument "number of event indicators" consistent in API and document.

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#1041]
Currently, we're using the following variables to refer to the number of event indicators:
- `nEventIndicators`: Used in function `fmi3EnterEventMode`
- `ni`: Used in function `fmi2GetEventIndicators`
- `nz`: Used in function `fmi3GetNumberOfEventIndicators` and in the mathematical description.

I think these all refer to the same thing. 
If that's the case, I propose that we change the API and docs to have the same name for all of them.
`nz` makes the most sense to me, because it's compatible with the mathematical description (where z is used to denote an event indicator).

**Comment by andreas-junghanns** [comment]
I agree that we should use the same for all (There can only be ONE!).

I do not like short names, even with your argument that mathematicians would know that `z` and `nz` are roots. Computing Scientists are less likely to decode this.
If we adapt the names of arguments to the mathematical description, we would likely have to change a number of other parameter names as well.

Can we have the more expressive `nEventIndicators`, please?

In your code, you can have then the type-saving `nz` - we are quibbling here about what names we put into the header files (which only have decoration and description value).

I found only two more function parameter with 2 or less characters: `x` and `nx` for states and number of states. Could we maybe also agree to get this changed to states and `nStates`, while we are at it?

@klausschuch : which part did you like? All the same name? Or, using `nz`?

@clagms : Can you please create a PR?

**Comment by clagms** [comment]
@andreas-junghanns I can work on https://github.com/modelica/fmi-standard/pull/1046 once I understand the following:
1. We use nEventIndicators in functions `fmi3EnterEventMode`, `fmi2GetEventIndicators`, `fmi3GetNumberOfEventIndicators`, *and* mathematical description? Or do we keep the mathematical description out of these changes? 
2. Do we rename `nx` to `nStates` and `x` to `states`? Or, as @t-sommer suggested, `nx -> nContinuousStates` and `x -> continuousStates`?
3. Do affect the changes in item 2. only to the code? Or do we apply them as well to the mathematical descriptions?

I agree that longer names have more meaning.
Effecting those changes in the mathematical description might be more difficult, as some formulas might become too large (I'd have to try to see what the results looks like).

@klausschuch, @t-sommer, @chrbertsch, @pmai, and others, what do you think?

**Comment by chrbertsch** [comment]
> * We use nEventIndicators in functions `fmi3EnterEventMode`, `fmi2GetEventIndicators`, `fmi3GetNumberOfEventIndicators`, _and_ mathematical description? Or do we keep the mathematical description out of these changes?

This should be about the API only, not the mathemetical description, where x or x_C is perfectly fine and much better to read in formulae
 
> * Do we rename `nx` to `nStates` and `x` to `states`? Or, as @t-sommer suggested, `nx -> nContinuousStates` and `x -> continuousStates`?

I would use nContinuousStates` and `x -> continuousStates` to be more precise

> * Do affect the changes in item 2. only to the code? Or do we apply them as well to the mathematical descriptions?

only the API / code
