### ISSUE TITLE
Fix description of calculation of clocked variables in ME

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1045]
In 3.1 we state
"In FMI 2.0 there is no mechanism that the FMU can provide the information whether a discrete-time variable is active or is not active (is not computed) at an event instant. Therefore, the environment has to assume that at an event instant always all discrete-time variables are computed, although internally in the FMU only a subset might be newly computed."

PR #941 wants to remove the "2.0"

But for FMI3.0 this statement is no loger true, as we have clocked variables right?

**Comment by andreas-junghanns** [comment]
@chrbertsch : Sorry, I missed the second part of your comment in #941 - my change set (117a288) there should fix this. If you agree, please close this issue.

**Comment by chrbertsch** [comment]
Fixed with #941
