### ISSUE TITLE
res = model.simulate(final_time=10)   

### ISSUE THREAD

**Issue by xifanghnu** [modelica/fmi-standard#1048]
The following error occurred when I executed the command “res = model.simulate(final_time=10) ”
![image](https://user-images.githubusercontent.com/66315766/83526685-6249f180-a519-11ea-957e-b99a061b56a3.png)

**Comment by hyumo** [comment]
This repo is for fmi-standard development nor for answering library specific questions. Please read documentation in terms of how to use a library. If you still cannot find the answer, you can post your question on stackoverflow. I will close this issue.

**Comment by xifanghnu** [comment]
OK thank you！

 




| |
xfangwust
|
|
邮箱：xfangwust@163.com
|

Signature is customized by Netease Mail Master

On 06/03/2020 02:39, 于航 Hang Yu wrote:

This repo is for fmi-standard development not for answering library specific questions. Please read documentation in terms of how to use a library. If you still cannot find the answer, you can post your question on stackoverflow. I will close this issue.
