### ISSUE TITLE
Unify and possibly change the notation for communication time points and communication intervals

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1050]
In the mathematical decription sections of BCS we use a notation hc_i and tc_i for communication intervals and communication time points:
![image](https://user-images.githubusercontent.com/16363372/83945285-ff52a600-a809-11ea-97a0-fd71a382e7f0.png)

Using two letters for variables is very uncommon in mathematical litereature, as it can be confused with a product of t variables h and c_i for example.

It gets especially ugly in formulae with powers of such variables 
![image](https://user-images.githubusercontent.com/16363372/83945361-696b4b00-a80a-11ea-9d92-4d9b650e2053.png)

Probably the intention of using  hc_i and tc_i was to distinguish them between internal solver steps and time points h_i and t_i.

I propose to change the notation to hc_i --> H_i and tc_i to T_i

But how shall we then describe clock tick times and intervals in SCS?
Currently they are denoted as

![image](https://user-images.githubusercontent.com/16363372/83945482-2a89c500-a80b-11ea-9faf-bf02125aa526.png)
![image](https://user-images.githubusercontent.com/16363372/83945487-3bd2d180-a80b-11ea-943d-fb072d327a89.png)

**Comment by andreas-junghanns** [comment]
I agree with H_i and T_i.
I propose c_i clock tick time.
Clock interval is tougher - C_i seems odd, but I have no better suggestions.

**Comment by andreas-junghanns** [comment]
web design meeting:
it might be better to use t_c_{i+1} - this leaves us with more subscripts to indicate different kinds of time points.
