### ISSUE TITLE
Declaration of FMI Version Independence (Drafting)

### ISSUE THREAD

**Issue by pmai** [modelica/fmi-standard#1061]
This issue is intended as a starting point for a declaration of version independence for FMI, to aid the ongoing discussion of the exact semantics of versions and relevant compatibility issues. This is intended as a start, so please feel free to edit this issue text to add/rework/change/delete any stuff you find necessary, to come to a working set of definitions.

-----

We hold these truths to be self-evident:

Truth 1: "That all FMUs represent significant investment and longevity is desired by both producers and consumers."
Truth 2: "That to ease the handling of FMUs, we need to minimize the complexities of version compatibility for the users."

That to secure these goals, and reach as many current and future importers supporting maximum functionality and with minimum number of versions exported, the following technical challenges need addressing:
 1. **An old FMU running in a new importer:** This can trivially be achieved by simply implementing all FMI versions. However, to reduce implementation effort and thus help adoption of the standard, we strive to make new FMI minor versions strict supersets of previous minor versions.
 2. **A new FMU running in an old importer:** This requires new features in new FMI minor versions to be optional and ignorable by older importer implementations.

This means for the producers and users:
 1. An exporter can always export an FMU only once with the most advanced FMI minor version supported (per FMI major version). ("_produce once_")
 2. An importer can always import an FMU of previous and future FMI minor versions. ("_run all_")

-----------------------

Technically, this means for new FMI minor versions:

- All new functionality introduced in a minor version must be optional, and importers of earlier minor versions must be able to ignore the optional features, even if they are present in an FMU.

- C API functions:
   - New functions can be added, as long as they do not need to be called when operating in an importer with an older minor version. 
   - New arguments: No new arguments can be added to C API functions (nor existing ones dropped).
- XML/XSD:
   - The XML schema must be written in a way that allows new XML elements to be added to the schema in designated places.
   - New elements: 
   - New attributes:
- new state in state machine in existing interface type:
- New interface types: To discuss: These can be added, but only when support for an existing interface type is always present as well.

**Comment by andreas-junghanns** [comment]
Poll: Do you agree that we should follow the suggested definitions of above? Consequence: we will attempt to formulate features in 3.0 as optional features build on top of a hypothetical reduced 3.0 (and also try with expected new features for 3.X or 4.0):

Agree: Andreas, Pierre, Antoine, ChristianB, Klaus, Markus, Masoud, Otto, Robert
Disagree:
Abstain: TorstenS

**Comment by chrbertsch** [comment]
Shouldn't we update our development process https://github.com/modelica/fmi-design/blob/master/FMI_DevelopmentProcess/FMI_DevelopmentProcess_1.0.pdf according to this new understanding of "backwards compatibility" and prepare a vote on this in the Steering Committee?

**Comment by chrbertsch** [comment]
Ticket-viewing-meeting

AndreasJ: We do not yet know where this text shall go.
Pierre: Parts of it should go into the FMI3.0 standard.
Andreas: I could try to write this in an introduction section
Pierre: If we do not put this prominently, people will not be aware this
Andreas: I will create a PR.

**Comment by andreas-junghanns** [comment]
This requires a few hours of quiet time to do.
