### ISSUE TITLE
Clarify input events and intermediate input values

### ISSUE THREAD

**Issue by CSchulzeTLK** [modelica/fmi-standard#1068]
I see an important use case in providing smooth input functions for CoSimulation FMUs in a way, which does not reset the internal solver step size at communication points. Simulation times using BDF solvers strongly depend on the communication step size in CS mode using FMI 1.0 and 2.0.

Ideally it would be possible to provide smooth input values during one, and over several the doStep-intervals. No input event would be triggered at the communication point. So a BDF solver doesn't have to be reset. I think it would be good to clarify this.

I remember earlier discussions, where the callback function in the IOV could be used for that. If the input callback function is used during the interval, then inputs always have to be provided that way (=must not be provided at the communication point from "outside").

Is that use case covered by "normal" CS? Is it covered by Hybrid CS?

**Comment by CSchulzeTLK** [comment]
I'm missing some clarifications:
- The **master suddenly stops providing intermediate input** values after some point in (simulation) time
  - Since the u(t) function should be deterministic, at least old values should be accessible. I suggest **to "keep the old value"** (since we are doing this for basically all calls to set functions) **or forbid this**.
- Intermediate input values are provided, and additionally at the communication points the **fmi3Set{VariableType} is called with the different value provided as the intermediate input value**.
  - Examples (communication points are 2 and 3):
    - A: setInput(time=2) = 42, setIntermediateInput(time=2)=42, setIntermediateInput(time=2.5)=712, setIntermediateInput(time=3)=713, setInput(time=3)=1048
  - IMHO this **should reset the internal solver step size**
  - Inputs provided in the next doStep interval should provide the same input value at the starting communication point (because they should be deterministic)
- Intermediate input values are provided, and additionally at the communication points the **fmi3Set{VariableType} is called with the (numerically !) same value provided as the intermediate input value**.
  - Examples (communication points are 2 and 3):
    - A: setInput(time=2) = 42, setIntermediateInput(time=2)=42, setIntermediateInput(time=2.5)=712, setIntermediateInput(time=3)=713, setInput(time=3)=713
    - B: setIntermediateInput(time=2)=42, setIntermediateInput(time=2.5)=712, setIntermediateInput(time=3)=713
  - IMHO this **should NOT reset the internal solver step size**

**Comment by CSchulzeTLK** [comment]
Conclusions of the Working Group Meeting:

We discussed adding the sentence:
"If the master sets an intermediate input once for a variable in a communication interval it always has set it when requested by the fmu during this interval."
But decided that the keep the general rule (similar to ModelExchange) "If the master does not provide an input, has the same effect as if the master provides the same value as the last call."


- We should add to the definition of the set function, that if the set function is not called, then it has the same effect as if it was called with the same value as the last call. This is already the most common assumtion for ModelExchange implementation, so we should stick to that definition.
(section 2.1.7)
- Regarding caching: Setting an input with the same value is meant to be equivalent to not calling it!
- This has an influence tunable parameters, maybe we should exclude them?

- As implicitly already defined for ModelExchange we add:
If intermediateVariableSetAllowed is true, then this means the master defines the input values either implicitly or explicitly. If the master does not provide an input, has the same effect as if the master provides the same value as the last call.

- Rename "intermediateVariableSetAllowed" to "intermediateVariableSetRequested"?

- Open issues:
  - smoothness in Hybrid CS at communication points
  - tunable parameters


Some examples:
    - A: setInput(time=2) = 42, setIntermediateInput(time=2)=42, setIntermediateInput(time=2.5)=712, setIntermediateInput(time=3)=713, setInput(time=3)=713
=> the input is 713 at later communication points
    - B: setIntermediateInput(time=2)=42, setIntermediateInput(time=2.5)=712, setIntermediateInput(time=3)=713
=> the input is 713 at later communication points
    - C: setIntermediateInput(time=2)=42, setIntermediateInput(time=3)=713, setIntermediateInput(time=2.5)=712
=> the input is 712 at later communication points



backup:

**Comment by chrbertsch** [comment]
Changing milestone to v3.0, as the 3.0alpha4 parts have already been merged.

**Comment by andreas-junghanns** [comment]
"Open issue: smoothness in Hybrid CS at communication points": ChristianB wants to make a PR for this issue.

**Comment by chrbertsch** [comment]
> "Open issue: smoothness in Hybrid CS at communication points":

We alread have the text 

> Changes to continuous variables are only considered discrete during event handling. Changes to continuous variables during intermediateUpdate and normal communication points (communication points without event handling) are considered continuous.

in https://fmi-standard.org/docs/3.0-dev/#continuous

I propose changes to the mathematical description of CS in https://github.com/modelica/fmi-standard/pull/1094

**Comment by chrbertsch** [comment]
Viewing-all-ticket-meeting

Andreas: what is missing: If the importer is running without events, one should use a heuristics (just like FMI 2.0) to deals with discontinuitiy. FMI 3.0 offers now a new means to do better.
Torsten B: If there are events, continuous inputs are assumed to be continuous if there are no events.

@andreas-junghanns : I will create a PR to clarify this

**Comment by andreas-junghanns** [comment]
Point above: "clarify the general rule: "If the master does not provide an input, the input retains at the same value as the most recent (wall clock time) set function call"
(This is already the most common assumtion for ModelExchange implementation, so we should stick to that definition. Maybe this can be added to section 2.1.7.)"
If we add this sentence, would that not add confusion about other causalities, like parameters? Do parameters keep their values if not set again? I do not see why we need to add this. Please explain.

Point above: "non-normative text: This is not the same as calling the set function with the same value. E.g. calling the set function repeatedly with the same value might be less efficient."

This, I think, is already explained in caching and of course, calling a function several times is less efficient. What are we trying to explain?

Point above: "if intermediateVariableSetRequested is true and the "IntermediateInputList" is empty, then this can be considered an error."

Why? We never ask for non-empty arrays. As long as the nValues (or whatever) is 0, this should be allowed. It is a quality of implementation issue to not call useless functions, but not an error.

Note: if you are not reacting, this issue will close when we merge #1149.
