### ISSUE TITLE
Introduction to Synchronous Clocks and open questions

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#1073]
While trying to fix:
- https://github.com/modelica/fmi-standard/issues/1066
- https://github.com/modelica/fmi-standard/issues/1071
- https://github.com/modelica/fmi-standard/issues/916
- https://github.com/modelica/fmi-standard/issues/723
I realized that we need to define our clocks a lot better than what we currently have.
I'd like to start by producing an introduction to Synchronous clocks, since @IZacharias , @masoud-najafi , and @otronarp , yesterday kindly spent 2h explaining their interpretation of these. I had a look at the references provided by @MartinOtter as well.

Here's the text. Please play devil's advocate @andreas-junghanns, @masoud-najafi , @otronarp , @chrbertsch , and others.

___________

## Introduction to Synchronous Clocks

The main use case of the synchronous clocks is to represent sampled data systems.

The example adapted from the modelica specification, is a linear controller acting on a non linear plant. The controller samples the non linear plant at some rate, and the plant is continuously affected by the actuator values between samples.

In FMI 2.0, such system can be represented by two ME FMUs as follows:

![image-20200619053443952](https://user-images.githubusercontent.com/871103/85101177-1af27f00-b202-11ea-983d-3c29ed649727.png)

In the above architecture: 

- The controller equations are executed synchronously whenever there's a new sample yd. This is implicit in the equations.
- The timing of the sample induces an event indicator that forces the master to execute the controller and plant at the times at which the sensor wants to sample.
- Previous(xd) means the value of xd computed at the previous sample.
- y is a continuous variable, and u is piecewise constant.
- The master may execute both controller and plan fmus at times other than sample times as part of the time integration of the plant. In this case, the controller must produce the zero order hold value u.

One of the disadvantages of the traditional way is that we have a hard time deconstructing the controller FMU. 

To see one of the reasons why, suppose we want to represent sensors and actuators as separate FMUs (and therefore modularize the controller), as follows:

![image-20200619053529712](https://user-images.githubusercontent.com/871103/85101222-3067a900-b202-11ea-9beb-a69d36c3c688.png)

Since there's no guarantee that the equations in Ctrl, Actuator, and Sensor FMUs will be invoked exactly at the times that coincide with the sampling times of the Sensor FMU (recall that it is the ME master to pick the time advancement, based on the needs of the different FMUs), the Ctrl, Actuator, and Sensor FMUs need to be configured with the same sample rate. There are two problems associated with this approach:

1. This is error-prone for more complex controller architectures; and
2. Representing time and the sample rate as real numbers, there are numerical difficulties in guaranteeing that all three fmus will execute exactly at the same wallclock time. 

These are the problems that Synchronous Clocks solve.

The idea of clock comes naturally if we consider that the controller will sample the plant according to some frequency that depends on the frequency of the clock generator of the controller's microprocessor. It is easy then to describe the controller execution as happening every 100-th processor clock tick. We can even go further and define a new clock, that is based on the microprocessor clock, but abstracts away from the controller execution platform details. Such clock would say, e.g., that the there is a tick every 100 ms, to represent the capabilities of the controller execution platform.

Getting back to the example, the controller FMU may declare a clock that ticks every 100ms. In order to inform the master that the sensor and actuator FMUs are supposed to execute whenever the controller FMU executed, we need to connect that clock to those FMUs:

![image-20200619060354725](https://user-images.githubusercontent.com/871103/85101250-44aba600-b202-11ea-9046-14ba3a89301d.png)

The red lines above show the clock signal. The clock signal above forces the master to execute the controller, sensor, and actuator, equations at the same time (hence the name Synchronous for these clocks).

This motivates input and output clocks: 

- The ticking of an output clock is determined by the FMU that declares it. 
- The ticking of an input clock is determined by the master (which in turn will find the source that determines the ticking of such clock).

So in the above figure, FMU Ctrl declares an output clock, and the Sensor and Actuator FMUs both declare an input clock.

## Allowed and Forbidden Uses of Clocks

In the above example, yd is only defined when c ticks. It is not allowed to consult its value when c is not ticking. The signal of yd looks like the following:

![image-20200619062733999](https://user-images.githubusercontent.com/871103/85101284-57be7600-b202-11ea-9bc4-a169f52c8d81.png)

where $t_j$ is the time of the j-th tick of c.

For this reason, any algebraic equation that uses yd is also only defined when c ticks. So, in the above example, the variables xd and ud are only defined when yd is defined. However, the variable u is defined at any time, and can therefore be queried at any time. Since variables x, u, and y, do not depend on any clocked variable, they are also not associated to a clock and can be queried at any time.

Exploring these restrictions further, leads to the conclusions: 

1. a variable of an FMU must be associated to one clock and one clock only, of the same FMU. In the above example: the output variable yd is associated to the input clock c of Sensor FMU; the input variable yd of Ctrl is associated to the output clock c of Ctrl; and so on...
2. an assignment of the form `res := SomeFunction(clocked_var1, clocked_var2, ..., clocked_varN, var1, ..., varM)` must define `res` as an variable associated to a single clock, which means that: 
   1. `clocked_var1, clocked_var2, ..., clocked_varN` must all be associated to the same clock, or at least, must all be defined at the exact same time points (and this means that the different clocks must tick at the same time); and 
   2. `var1, ..., varM` must not be associated to any clock, and must be defined at all times.

## Interaction with other FMI Standard features and open questions

The following are the FMI features whose interaction with clocks I think we need to consider:

- event iteration: what happens when state events are detected...
  - at times different than clock ticks?
  - at times that coincide with clock ticks?
- super dense time: can clocks tick at super dense times? Or do they only tick at a newtonian time point (and that means that they are active throughout the superdense time iterations)?
- conversion between state events and clock ticks: an FMU may use an event indicator that depends on another FMU in order to trigger an event that is then mapped to an output clock tick... 
  - Does this violate the assumption that a clock must tick at a newtonian time point?
- multiple clocks firing at the same time: Andreas suggested that the FMU must be informed of all clocks that fired at that same time.
- can the size of an array of clocks depend on a tunable parameter? What happens when that parameter changes? What does this mean if the clock array is an input? and an output?
- Can an FMU have a output clock connected to its input clock... just for fun?

_________

**Comment by chrbertsch** [comment]
Ticket-viewing-meeting:

@clagms : I will create a PR draft
