### ISSUE TITLE
Merge BCS and HCS

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1077]
TorstenS: After a number of changes to the standard, the initial differences between BCS and HCS are disappearing - except for event handling. Is it to much to asked to have event handling even in BCS and if yes, what is the remaining difference?
Karl: To do nothing in event handling is problematic.
Pierre: If the master does not do the event handling, the FMU could do it internally at the beginning of the next doStep.
Pierre: Clocks are not allowed in BCS, but they are optional in HCS anyway. Clocks could be an optional feature.
TorstenS: Agreed - some master will just not support them.
Christian: BCS is similar to FMI 2.0 - how does that change? How does this work then?
Pierre: Event handling is not the issue, clocks are - are they optional?
TorstenS: If an environment does not support the new features, some will not.
Christian: Users will be confused about what FMU interface to use if this all turns to optional features, BCS was nice and simple and guaranteed what worked.
Pierre: The feature sets (profiles) is a better way to describe which use case an FMU supports.
TorstenS: Profiles are orthogonal to the interface types.
Christian: Currently clock support was not guaranteed, event handling is?
Karl: Yes.
TorstenB: We are plenty of application where event handling is not needed, e.g. HiL simulations, or FE-tools. That means we should keep BCS.
Pierre: This proposal would allow event handling to be optional.
TorstenB: This makes it harder for importers that do not deal with event handling: The implementers of importers (and exporters) have to read more and understand what to ignore.
Pierre: We should be able to write the standard such that we clarify what to ignore if you want to fall back to BCS.
TorstenB: It is harder to ignore a feature in a merged description than having the extra chapter.
Pierre: We have to address clearly at the start what to read when you start reading the standard.
TorstenB: What does optional event handling mean for an FMU? Is there a capability flag?
Karl: The FMU can notice the absence of the event-handling call and then internally do the "right thing".
Claudio: Will I understand can exchange events? Or if they have empty functions?
Karl: And the direct feedthrough will then be handled - the function must be optional.
TorstenS: But we are going through eventMode in HCS - so the functions must be present.
Pierre: we should decide today, if this is a worthwhile undertaking and not waste time with creating a proposal. The remaining differences are - as of today´s understanding -  clocks and event handling. I would agree that this is worthwhile trying.

Poll: Do you agree we should try to merge BCS into HCS?
In Favour: Andreas, Karl, Klaus, Pierre, TorstenS
Against: TorstenB
Abstain: Christian, Claudio

**Comment by chrbertsch** [comment]
Regular Design webmeeting: 
- open technical point: what shall importers and exporters do when event mode is not supported?
Pierre: importer ignores event
Torsten: In HCS one enters step mode through event mode. How shall the FMU react?
Pierre: for the impter it is simple. 
For the exporter: If one wants to export a "BCS" FMU: to not use event mode.
Torsten: one could use event mode to distinguish discontinuous jumps in inputs from large continuous changes
Pierre: "basic" co-simulation without guarantees of the master w.r.t.  continuity should be possible
Christian B: Christian S. wants to to avoid resetting the internal higher-order solver. 
Pierre: there are very conservative implementation of FMU exporters, that reset solver at every communication timestep.
Torsten: to we allow the setting of discrete variables in step mode?
Pierre: at communication points, setting of all values should be possible. In hybrid co-simulation one transports also the event mode
Torsten: one could add a flag, if the FMU supports discrete setting of continuous  in event mode
Jorge: in co-simulation I would see variables as continuous.
Pierre: for continuous variables one assumes continuously changing variables with intermediate values.
Pierre: Proposal: Variables can be changed at communication points (both discrete and continuous, as in FMI 2.0), variables can be also set in event mode (discontinuously)
Christian: Then we cannot rely in non-event mode on continuity. Then one might have to reset internal solvers
Markus: works in most cases, the solver reduces the stepsize 
Klaus: We should explain the meaning of continuous and discrete in co-simulation context.
Pierre: we should look at https://fmi-standard.org/docs/3.0-dev/#variability
Klaus: If the FMU internally resets for inputs on communication points, it should set this input as discrete.
Pierre: We must improve the definitions of continuous and discrete, independent of the merge. For the merge, it makes sense to consider the existence of the event mode (optionally) and what slave and master do with this.

**Comment by andreas-junghanns** [comment]
#1080 will take care of the clarification of variable changes.

**Comment by chrbertsch** [comment]
Fixed with https://github.com/modelica/fmi-standard/pull/1086, there is #1080 to clarify changes of continuous and discrete variables
