### ISSUE TITLE
Specify restrictions on independent variable

### ISSUE THREAD

**Issue by pmai** [modelica/fmi-standard#1078]
This is a continuation of issue #808, but independent from those clarifications: At least the following aspects of the independent variable need to be specified more precisely (there might be more, this is just a start from the top of my head):

- The independent variable cannot be an array
- The value of the independent variable that can be accessed via fmi3GetFloat64/fmi3GetFloat32 (depending on its type, both are currently allowed) must be identical (except for precision loss due to potential float64->float32 downconversion) under the rules of IEEE754 to the value of:
  - the `startTime` argument to the call to `fmi3EnterInitializationMode` upon entry into initialization mode 
  - the `time` argument of the last call to `fmi3SetTime` for ME
  - the returned value of the `lastSuccessfulTime` argument to `fmi3DoStep` for Basic/HybridCoSimulation
  - the value of the `intermediateUpdateTime` argument to `fmi3CallbackIntermediateUpdate` during calls to that callback
  - ??? for ScheduledCoSimulation
  - details for clocks to be added

**Comment by nickbattle** [comment]
From the rules that I have for FMI2 (which are probably the same for FMI3), I have:

- If you declare an independent variable, there can only be one
- It must be "continuous" with no "initial" and no "start"
- It must be Real (so a float in FMI3)
- The aliases of a variable cannot include both settable and "independent" variables

If you don't declare an independent variable explicitly:

- A variable is declared implicitly called "time", which is continuous
- Presumably you can't define a variable called "time" unless it is independent (this isn't checked currently)
- It is Real (I'm not sure of its units, but I suspect it's "s", which may imply creating a Units entry)
- It has a value reference created which is not equal to any other variable's value reference, but is otherwise arbitrary

Regarding a 32-bit/64-bit conversion, I thought that the latest idea was that a float32 has to be read/set with xxxFloat32 and ditto for Float64, rather than being converted implicitly? See #712

**Comment by pmai** [comment]
@nickbattle As you say, the variable itself has to be read by the right accessor, so a Float32 independent variable has to be read by fmi3GetFloat32, but the setting of the variable is not allowed via the accessor, but happens either via fmi3SetTime or fmi3DoStep (and other related functions actually, which I should add above), which always take a Float64, thus causing the down-conversion.

The rules for not explicitly declared independent variable will no longer apply, because the #808 decision was to always force a declared independent variable.

**Comment by chrbertsch** [comment]
For Scheduled Execution, a call to fmi3GetFloatXX for the independent variable does not make sense in the case of multiple activated model partitions with different activation times. Should we forbid such a call?
@MBlesken and @IZacharias : clould you please comment?

@pmai : which datails for clocks have to be added?

**Comment by MBlesken** [comment]
@chrbertsch @IZacharias it is not obvious to me why a call to fmi3GetFloatXX for the/a independent variable would not make sense in the case of multiple activated model partitions with different activation times. (... And I couldn't quiet get it from https://fmi-standard.org/docs/3.0-dev/#dependencies) If "independent variable" is always regarded as the one and only time variable I amuse that in real-time use cases this information would not be accessed via fmi3GetFloatXX. I'm not sure if those assumptions hold in general.

**Comment by chrbertsch** [comment]
>  If "independent variable" is always regarded as the one and only time variable I amuse that in real-time use cases this information would not be accessed via fmi3GetFloatXX. I'm not sure if those assumptions hold in general.

Indeed, as we have only one independent variable, it must be for the whole FMU. So it cannot have different values for different model partitions. Thus in my anderstanding a call of fmi3GetFloatXX for the independent variable does not make sense in SE.  If one want to get a time for a model partition, we would need somethink like fmi3GetTime(modelPartition), right?

**Comment by MBlesken** [comment]
> we would need somethink like fmi3GetTime(modelPartition), right?

I don't think that's even necessary. The master knows the time. It is the activationTime that he inserts when he calls ...ActivateModelPartition(...). I tried to point that out in the SE example given in #1087.

**Comment by andreas-junghanns** [comment]
Discussed at mini-design-meeting: SE models do not have a real-valued time internally. All activations are of model partitions move time forward discretely and it is unclear what time is between these calls. We should forbid calling fmi3GetTime() and fmi3GetFloat64(timeValueRef) for SE.
