### ISSUE TITLE
Clarify continous and discrete variables and changes

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1080]
During discussion w.r.t. #1077, we realized that we need to clarify definitions of discrete and continuous (for Co-Sim):
 - variables, and
 - changes, especially in the different simulation phases:
   * in intermediateUpdate
   * between doSteps() (normal communication time points)
   * during event handling.
We need to define what assumptions both importer and FMU can make. I think the variability section is the best to clarify this.

I am hoping that @KarlWernersson , @klausschuch , @TorstenBlochwitz can contribute here.

**Comment by chrbertsch** [comment]
We must consider the points in the discussion of the closed tickets #1077
