### ISSUE TITLE
Make event mode optional (to allow merging of BCS and HCS)

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1082]
If we make event handling optional in HCS, BCS can be treated as a special case of HCS (and we are closer to merging BCS and HCS, see #1077).

This would require:
 - making Event Mode optional and that requires fmi3ExitInitializationMode to land in Step Mode
 - adding a new capability flag in the XML canHandleEvents.

Is it this simple? What am I missing?

**Comment by andreas-junghanns** [comment]
This is a larger change and I would like some positive feedback before I start with a PR addressing this.

**Comment by t-sommer** [comment]
This would be the state diagram:

![state-machines-Page-1](https://user-images.githubusercontent.com/2453858/86528516-0f14e700-bea9-11ea-982e-ee488760949d.png)

**Comment by t-sommer** [comment]
IMHO, event updates should be triggered either by the master _or_ the FMU. The FMU could then signal via the XML, if it supports external event handling e.g.

```xml
<CoSimulation ... supportsExternalEventHandling="true"/>
```

and the master can signal to the FMU whether it actually intends to handle events, e.g.

```C
fmi3InstantiateCoSimulation(..., fmi3Boolean eventsHandledExternally)
```

**Comment by andreas-junghanns** [comment]
web design meeting:
All: accept the proposal to rename SCS to Scheduled Execution (SE)

**Comment by andreas-junghanns** [comment]
Klaus: Would we discuss ME renaming as well? It is often misunderstood as "model exchange" exchange of models...
Andreas: I would like to avoid this discussion and do not believe renaming will really help to clarify the issues.
Pierre: a measure of success of a technology is how many people discuss it without really understanding it.
Markus: renaming a term that has finally found some understanding, changing will cause issues.

**Comment by chrbertsch** [comment]
Fixed by https://github.com/modelica/fmi-standard/pull/1086
