### ISSUE TITLE
Order of get and set calls in intermediateUpdateMode

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1085]
If I remember well, we discussed that during Intermediate update mode, first the fmi3getXXX have to be called and then the fmi3setXXX, not in a mixed order
(just as in FMI 2.0CS there may be not get directly after a set without  an fmi2doStep inbetween). 
This is related to the direct feedthrough discussion.
But I do not find such a restriction of the calling sequence in the currenty specifiation. 
Or have I overseen it?
Or does such a restriction make no sense?

**Comment by andreas-junghanns** [comment]
Andreas: Are we assuming that computations are triggered?
Pierre: In Co-Sim we have to GetXXX first, and then call the SetXXX. We should follow the same mechanism.
All: agreed: this order should be required.
