### ISSUE TITLE
Add XCP support (Layered standard)

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1090]
In https://github.com/modelica/fmi-design/tree/master/Meetings/2020-05-07_FMI-Steering#111-prostep-fmi-feature-matrix the idea is contained  to suport XCP with a layered standard " ... Another thing is XCP …​ Now we can put the A2L in the extra directory."

**Comment by andreas-junghanns** [comment]
We need to define the location where to place the a2l in the /extra directory.
We should recommend to have the IF_DATA XCP element present to describe the XCP server settings internal to the FMU.
We should forbid include of other a2l files to avoid copy-to-target-dir issues.
All ASAP2 versions are allowed.

**Comment by fajansen** [comment]
Why is it required to start the XCP service at initialization mode? The real control unit only enables XCP access when the power supply is turned on. Requiring the XCP service to already work at simulation start causes a difference in the behaviour of a vECU compared to a real ECU.

**Comment by andreas-junghanns** [comment]
> Why is it required to start the XCP service at initialization mode? The real control unit only enables XCP access when the power supply is turned on. Requiring the XCP service to already work at simulation start causes a difference in the behaviour of a vECU compared to a real ECU.

Agreed, if your FMU allows power-up and power-down, this requirement is in the way.
I will turn this into a recommendation then to allow your use case and explain when to do what.
Thanks for the feedback!

**Comment by chrbertsch** [comment]
Ticket-viewing-meeting: 

Andreas: Reviews are welcome! I will work on this so this can be merged.

**Comment by andreas-junghanns** [comment]
PR pending final approval.
