### ISSUE TITLE
python support

### ISSUE THREAD

**Issue by lueth0014** [modelica/fmi-standard#1093]
Does FMI support cosimulation with codes written in python?  If not directly, is there a way around this or an alternateive?

**Comment by chrbertsch** [comment]
@lueth0014 : This is a platform for the development of the FMI standard. In the future please use other platforms like Stackoverflow for questions on the usage of FMI and tool/language support: https://stackoverflow.com/questions/tagged/fmi

Regarding python support: You could have a look at 
*  https://github.com/NTNU-IHB/PythonFMU
* https://github.com/LBNL-ETA/SimulatorToFMU
for wrapping python code as FMU (--> FMU export in Python)

Or you couple your code directly with a FMI simulation master written in python, e.g.
* https://github.com/CATIA-Systems/FMPy
* https://github.com/modelon-community/PyFMI (--> FMU import in Python)
You might have to modify the simulation loops to connect you Python code.
