### ISSUE TITLE
Change definition of fmi3Boolean from "int" to "char"

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1102]
since the arguments brought up in #48 don't hold any more for FMI 3 with the introduction of contiguous arrays and new data types.

**Comment by andreas-junghanns** [comment]
char or unsigned char?

**Comment by andreas-junghanns** [comment]
WEB design meeting: we should use int32, for packing int8 is the better choice. (and not flip-flop the definition)

Also, we should fix:
 - fmi3Clock, fmi3Boolean and fmi3Byte to use uint8_t

**Comment by andreas-junghanns** [comment]
Pierre: fmi3Boolean should change to _Bool.

**Comment by pmai** [comment]
See #1311, which should cover this; fmi3Clock is _Bool as well, since I could not for now find a good reason for it to be something else. If we move to ternary clocks, we would have to change in non-backward compatible ways anyways, so ...

**Comment by andreas-junghanns** [comment]
> 
> 
> See #1311, which should cover this; fmi3Clock is _Bool as well, since I could not for now find a good reason for it to be something else. If we move to ternary clocks, we would have to change in non-backward compatible ways anyways, so ...

Should we then remove the macro definitions
#define fmi3ClockActive   1
#define fmi3ClockInactive 0
?
Which would also mean that we have to change the text removing references and explaining that an "true" clock is an "active" clock...
