### ISSUE TITLE
Move 4.4. and 4.5 to separate files

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1105]
to be consistent, currently the content is in the 4_3_co-simulation_schema.adoc file

**Comment by andreas-junghanns** [comment]
Agreed, but let´s have the master/slave PR merged before we do this here.

**Comment by andreas-junghanns** [comment]
I looked and this was easier: the headings needed dropping one level to be the same as in ME and SE.
This fixed the issue of this ticke.
While at it: PR #1108 also addresses equalizing heading style.
