### ISSUE TITLE
Move dependency information from <ModelStructure> to variables

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1115]
With the removal of alias variables in FMI 3 the dependency information can be stored directly in the model variables by moving/adding the following attributes to the model variable elements:

- `dependency`
- `dependencyKind`
- `initialUnknown`

The `<ModelStructure>` element then becomes obsolete.

**Comment by TorstenBlochwitz** [comment]
Looks good to me. In this way, everything is on one place and you do not have to fiddle around with the lists in ModelStructure. We have to specify clearly to which variables which dependency is allowed to be defined. And we need to specify how unknown dependency is to be defined in contrast to "no dependency". But this is to be done anyway, independent from the way how the dependency information is stored.

**Comment by TorstenBlochwitz** [comment]
Looks good to me. In this way, everything is on one place and you do not have to fiddle around with the lists in ModelStructure. We have to specify clearly to which variables which dependency is allowed to be defined. And we need to specify how unknown dependency is to be defined in contrast to "no dependency". But this is to be done anyway, independent from the way how the dependency information is stored.

**Comment by t-sommer** [comment]
> We have to specify clearly to which variables which dependency is allowed to be defined. And we need to specify how unknown dependency is to be defined in contrast to "no dependency".

The way we specify the dependencies would stay the same:

- no attribute `dependencies`: variable depends on everything
- `dependencies=""`: variable depends on nothing
- `dependencies="2 3"`: variable depends on variables with VR 2 and 3

For Clocks we might to want to define a default of "no dependencies" if the attribute is missing.

**Comment by andreas-junghanns** [comment]
> For Clocks we might to want to define a default of "no dependencies" if the attribute is missing.

I do not like these exceptions, unless it is clear why clocks are different. Can someone explain that, please?

Until then, I would assume:
An output clock ticking depends, just like other variables, on who-knows-what, if not specified - so you have to assume on "everything".

**Comment by masoud-najafi** [comment]
Clocks are not really different. The only difference is that beside their dependencies on other KnownVariables such as regular-Inputs, we need also define their dependencies on input-Clocks. 
"everything" includes all "input clocks". That's make output clocks dependent, i.e. synchronous with input clocks.
Synchronous output clocks should remains exceptions for  few blocks, such as SubSample, SuperSample, and Conditional switchs.

**Comment by TorstenBlochwitz** [comment]
I agree to Masoud: Clocks are not different to other variable. I don't see why the exception is needed.

**Comment by t-sommer** [comment]
Closing (see https://github.com/modelica/fmi-standard/pull/1120#issuecomment-673327428)
