### ISSUE TITLE
Connection of variables with variability clock

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1126]
I wonder where in the FMU specification, it has been indicated that only output clocks of an FMU can be  connected to input clock of another FMU? I mean, we should underline somewhere that only output of variability Clock can be connected to input of variability Clock. It may be obvious, but should be mentioned somewhere.

**Comment by andreas-junghanns** [comment]
Can you create a small PR with a suggestion, please?

**Comment by t-sommer** [comment]
IMHO this is up to the co-simulation algorithm. As long as the calling sequence is correct it can connect whatever it wants.

**Comment by chrbertsch** [comment]
Can we close this due to #1130?

**Comment by masoud-najafi** [comment]
Yes.
