### ISSUE TITLE
Local clocks in Table-6

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1129]
In Table-6, the combination of Causality "Local" and Variability "Clock" is not allowed. Note that you may have local clocks that may not be exposed to outside. This happens especially when you export a model composed of FMUs with interconnected clock links.

**Comment by andreas-junghanns** [comment]
How would such an internal clock be different from an output clock?
Why would we differentiate?

**Comment by chrbertsch** [comment]
Ticket-viewing-meeting: 

Andreas: I do not understand the difference between a local clock and an output clock.
Masoud: a local clock is not exposed.
Torsten: ticking has to be treated internally. For local variables I understand the use case to get more internal information. What could one do with the information of an internal clock?
Andreas: Debugging.
Torsten: We should discourage connecting a local clock to another input clocked
Klaus: then we have local clocked variables
Pierre: Must they be local?
TorstenB: Yes
Klaus: For me the decision is too fast. What does it mean?
Torsten: I see debugging as a valid use case.
Klaus: no output variable may depend on a local clock.

@masoud-najafi I will create a PR, including the restrictions mentioned above.

**Comment by masoud-najafi** [comment]
>no output variable may depend on a local clock.

@klausschuch: By "output variable", do you mean "output clock variable"? Because a regular output variable may depend on local-clock ticks, i.e., at a lock clock ticks the output may change.
