### ISSUE TITLE
Periodic clock of type Float64

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1136]
In the spec document and the xsd files, "intervalCounter", "shiftCounter", and "resolution"  have been used to define the period and the start value of a periodic clock. These values are of type UnsignedLong. 
In APIs, we have fmi3GetIntervalDecimal  and fmi3GetIntervalFraction  pour specifying period of Real and Rational clocks.
Maybe I am missing something but
1) Don't we need to specify the period and offset for Float64 type (real type clocks) in the XML?
2) Don't we need API for setting/getting Shift (Offset) for Float64?
3) Don't we need API for setting/getting shiftCounter for UInt64?

**Comment by chrbertsch** [comment]
Ticket-viewing-meeting:

Masoud: we have an assymmetry between rational and real clocks
TorstenB: in Modelica we can specify a clock interval as real.
Andreas: the Master sets the clock. Why would you need to set?
Masoud: for the same reason as for the rational clocks.
Andreas: should we remove this also for the rational clocks? the master makes the clock tick 
TorstenB: there remains the first question.
Andreas: one cannot even represent pi as a float 64.
Pierre: we have 64bit in a unsigned long ...
Andreas: we have to state that the current rational clocks are sufficient. Why do we need real clocks?
TorstenB: It eases support for Modelica
Andreas: We need non-normative text 
Pierre: I can look into this

**Comment by pmai** [comment]
How and whether to refactor the clocks API depends to a certain extent on the actual clocks discussion results, since the actual API still left/newly introduced will have an impact on this as well.

**Comment by andreas-junghanns** [comment]
We added an additional attribute to variables in XML: `supportsFraction` to announce support of fractions for a given clock.
