### ISSUE TITLE
Entering Event mode due to a Clock tick 

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1137]
The signature of fmi3EnterEventMode is
fmi3Status fmi3EnterEventMode(fmi3Instance instance,
                                          fmi3Boolean stepEvent,
                                          const fmi3Int32 rootsFound[],
                                          size_t nEventIndicators,
                                          fmi3Boolean timeEvent);
Please note that it is possible that the FMU is pushed to EventMode due to a clock tick which is different from timeEvent. Would this API need an update?

**Comment by chrbertsch** [comment]
Ticket-viewing-meeting

Andreas, TorstenB: we need a new element.
Klaus: how would this look like?
Torsten: I would suggest just a boolean variable, indicating just that one clock ticked. Which clocked ticked can be found out by the importer
Torsten: at the next super dense time others clocks ticked.
Andreas: The master sends, which clocks ticked
Klaus: output clocks are coming from the FMU. The FMU knows which clocked ticked. 
Masoud: for an output clock, on may not call setClock 
Klaus: the FMU knows. Input clocks get transmitted by a special functions
Andreas: do we not to specify that the clocks are set before we set inputs?
Klaus: This would be like a hidden sub-state. But I think the order is not important
Andreas: I will add a comment for a clarification, why we do not need an indication for the event source

**Comment by andreas-junghanns** [comment]
Done in #1272.
Closing because the limit of 10 issues linked to #1272 was reached.
