### ISSUE TITLE
Clarification on dependency list of output clocks

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1139]
An output clock may depend on
1) Continuous-time states, e.g. state-event clock depending on states.
2) Regular inputs, e.g., an FMU that ticks a state-event clock when its regular input crosses zero.
3) Input clocks, e.g., an FMU that sub-samples its input clock.

Is this list complete?

**Comment by andreas-junghanns** [comment]
web design meeting:
Masoud: Discrete states?
Andreas: Do you want to have this added somewhere?
Karls: This should go to the model structure, or wherever where we describe what outputs can depend on.
