### ISSUE TITLE
Describe allowed functions in states

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1151]
(singled out from #1016 )

Currently in  https://fmi-standard.org/docs/3.0-dev/#_state_event_mode and https://fmi-standard.org/docs/3.0-dev/#_state_continuous_time_mode a lot of allowed function calls are missing (e.g. fmi3GetXXX, fmi3SetXXX) ...

Additionally, for some states like Reconfiguration mode, the description of allowed and forbidden function calls is missing completeley

**Comment by andreas-junghanns** [comment]
I have the feeling these are not the only modes, where we miss functions.

But: have you check the super states? I tried to make sure that functions callable in all sub-states of a super state are listed there.

**Comment by andreas-junghanns** [comment]
BTW: We agreed to no list forbidden functions anymore - I removed all such lists a while back.

I just checked: both Configuration Mode and Reconfiguration Mode list the only call allowed (that I can think of): 

fmi3ExitConfigurationMode
    With this function call, the FMU is returned to state Instantiated.
fmi3Set{VariableType}
    Only for variables with causality = structuralParameter and variability = fixed or variability = tunable.


fmi3ExitConfigurationMode
    Returns back to Event Mode (ME), Step Mode (CS) or Clock Activation Mode (SE).
fmi3Set{VariableType}
    Only for variables with causality = structuralParameter and variability = tunable.

**Comment by chrbertsch** [comment]
> BTW: We agreed to no list forbidden functions anymore - I removed all such lists a while back.

OK, you are right.

> I just checked: both Configuration Mode and Reconfiguration Mode list the only call allowed (that I can think of):

OK

But where I think the allowed functions for ContinuTimeMode and EventMode are incomplete
