### ISSUE TITLE
Clarification of clockReference attribute may be needed in 2_2_common_schema.adoc 

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1154]
At line 1343 of  docs/2_2_common_schema.adoc this sentence about "clockReference"  is not clear:

If < < causality > >  =  < < output > >  and  < < variability > >  =  < < clock > >  the  < < outputClock > > tick event can occur only in the model partition that is related to the referenced  < < inputClock > > , i.e. the < < outputClock ,`output clock` > > value (active/inactive) can only change in this model partition.

**Comment by andreas-junghanns** [comment]
In #1143 you state the problem as "In 2_2_common_schema.adoc I cannot understand the following phrase, is it related to SE or the TriggeredBy attribute?"

Why do we have to ways to define dependencies on clocks:
 - triggeredBy, and
 - clockReference

Can we drop triggeredBy?

Back to the sentence Masoud points out: I believe this is true for both clock types.
The mention of the "model partition" is unfortunate and we should clarify the use of this phrase, see #916.

**Comment by andreas-junghanns** [comment]
@IZacharias : What is different about triggeredBy compared to clockReference?

Suggest start of clarification: "The triggeredBy attribute is different to the clockReference attribute in the following way:..."

**Comment by IZacharias** [comment]
@andreas-junghanns 
The attribute clockReference of an output clock refers to an input clock. Only if this input clock has ticked, the output clock **may** also tick. But not every time the input clock is ticking, the output clock has to tick as well.

The attribute triggeredBy of an input clock refers to an output clock. Whenever the output clock is ticking, the input clock **must** also be ticking.
An explanation of triggeredBy is also contained in chapter 5.1.1.2 Clock Relationship.

We will introduce a clarification in chapter 2.

**Comment by masoud-najafi** [comment]
"The attribute clockReference of an output clock refers to an input clock."
In synchronous clock (not SE), this is called direct dependency of clocks, i.e., the output-clock is usually an independent clock, and no clockReference attribute is provided for it. If the output-clock depends on an input-clock, i.e., the output-clock ticks immediately after the input-clock tick in the same EventUpdate, its dependency is declared in the ModelStrcuture. We may need to converge this on both SE and non-SE and find a common solution.

I think we also need the attribute "triggeredBy", for synchronous clocks, we would need a direct clock-connection between an output-clock and ONE or SEVERAL of input-clocks of the same FMU. The use-case is #1140 .

**Comment by andreas-junghanns** [comment]
Both @IZacharias and @masoud-najafi seem to explain the same thing, for both SE and non-SE cases.

Summary:
- Output clocks and input clocks can depend on one another, in all interface types (ME, CS and SE).
- If an output clock depends on an input clock, the clockReference attribute is used and indicates that the output clock **may** tick **if and only if** the referenced input clock ticks.
- If an input clock depends on an output clock, the triggeredBy attribute is used to indicate that the importer has to forward clock ticks of the referenced output clock to that input clock. Several input clocks may refer to one output clock.

Do we all agree?

**Comment by masoud-najafi** [comment]
Yes, we cannot be more precise. The difference is just in implementation in the XML.
For me, these dependencies are something structural and may be declared in the ModelStructure, but any other solution would be good.

**Comment by IZacharias** [comment]
> Both @IZacharias and @masoud-najafi seem to explain the same thing, for both SE and non-SE cases.
> Summary:
> 
> Output clocks and input clocks can depend on one another, in all interface types (ME, CS and SE).
> If an output clock depends on an input clock, the clockReference attribute is used and indicates that the output clock may tick if and only if the referenced input clock ticks.
> If an input clock depends on an output clock, the triggeredBy attribute is used to indicate that the importer has to forward clock ticks of the referenced output clock to that input clock. Several input clocks may refer to one output clock.
> 
> Do we all agree?

@andreas-junghanns Yes, I agree. Thanks for this well explained summary!
