### ISSUE TITLE
Are discrete-time states in <ModelStructure>?

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1161]
In 2_1_common_api.adoc  there is statement:
"Discrete-time states are listed in the <ModelStructure>. They can have initial values defined by XML attributes [initial] and [start], or the initial values are computed internally as a function of the parameters."

This is not consistent with current ModelStructure. Do we need to add discrete-time states to the ModelStructure? Any use-case?

**Comment by andreas-junghanns** [comment]
This sentence was introduced by @pmai in d689e055cf2c76b50945fc9ca625dd8e7263186a.
@pmai : Do you remember what made you write this? I kind of agree with @masoud-najafi here: I cannot find any other place in the document that suggests that we expose any state (continuous or discrete) directly... Can we remove this sentence? Or clarify, which combination of causality/variability defines what you would call a discrete state? If we were to allow this, would we not need to declare that all discrete states must be exposed (or none)? I must admit, this is a bit confusing here...

**Comment by pmai** [comment]
I did not introduce this sentence, I only removed the previous attribute part of the sentence:

```
Discrete-time <<state,`states`>> are listed in the `<ModelStructure>` and have the variable xml-attribute <<previous>> referring to the variable holding the previous value of the <<state>>.
```

got shortened to

```
Discrete-time <<state,`states`>> are listed in the `<ModelStructure>`.
```

as part of removing the previous attribute. I think the original wording came from @KarlWernersson, maybe? I don´t know what the current status on the previous and discrete state stuff was (should it be reintroduced?), so probably @KarlWernersson knows best.

**Comment by friedrichatgc** [comment]
The ModelStructure is to expose the structure of the model to the importing tool. But the FMU should still be a black box for the importing tool. The importing tool only requires the structure of the interface (input, output, state derivatives, initial unknowns) of the FMU but should not need to know internals of the FMU structure.
So I don't see a need to list discrete states (being internal states, see #1171) in ModelStructure.

**Comment by andreas-junghanns** [comment]
See PR #1191 and issue #1172.

**Comment by KarlWernersson** [comment]
These was included in the original clocks proposal and some how got lost when the hybrid co-sim was merged and i was on parental leave.

There was a discussion to rename them to clocked states to avoid confusion.

These are optimal to add (similar as it it optional to expose the continous state derivatives for a co-simulatoin fmu)
They would list the discretized continuous states, or the discrete states (simple example a counter) asociated wiith a clock.
These variables will not be updated if a clock is ticking while subactive == true

**Comment by andreas-junghanns** [comment]
Done in #1272.
Closing because the limit of 10 issues linked to #1272 was reached.
