### ISSUE TITLE
triggered clocks and 

### ISSUE THREAD

**Issue by iscopa** [modelica/fmi-standard#1163]
Hello,

in 4.2.8.2 of fmi 3.0 spec there is a description of fmi3SetClock. There it is not clear the difference between "input" and "triggered clocks". Could you please clarify that concept?

////////////////////////////////////////////////////////
fmi3SetClock

    For input clocks, fmi3SetClock is called after entering Event Mode to set the activation status of clocks. For **both input and trigerred clocks**, this function can be called several times, only if recomputations of clock state are needed during Event Mode.
////////////////////////////////////////////////////////

"Clocks" description is wide spread over the standard. It would be helpful to have a dedicated chapter to clocks, illustrated with examples.

Thank you

**Comment by andreas-junghanns** [comment]
Agreed, this part needs attention - a number of other clocks-related tickets are already being discussed. We will address this as well - thanks for pointing it out!

**Comment by andreas-junghanns** [comment]
@iscopa : I cannot make you reviewer of my PR for this issue - please comment here anyhow - thank you!

**Comment by iscopa** [comment]
Hello Andreas, thank you for your feedback.
