### ISSUE TITLE
Which CC-license?

### ISSUE THREAD

**Issue by HansOlsson** [modelica/fmi-standard#1167]
I tried to look at the license text and found it to be contradictory, it says:

The FMI specification is released under the CC-BY-SA (Creative Common Attribution ShareAlike 4.0 International):

Attribution-NonCommercial-ShareAlike 4.0 International

This mentions both CC-BY-SA https://creativecommons.org/licenses/by-sa/4.0/ and CC-BY-NC-SA https://creativecommons.org/licenses/by-nc-sa/4.0/ which I find confusing, and I doubt the NC-part is intentional.

**Comment by chrbertsch** [comment]
FMI 2.0.1 was released under CC-BY-SA (Creative Commons Attribution-Sharealike 4.0 International), and I do not see a reason why we should change this. 
Also, https://github.com/modelica/fmi-standard/blob/master/docs/0___preamble.adoc  mentions `This document is licensed under the Attribution-ShareAlike 4.0 International license.`
So I suggest to change the license text to CC-BY-SA w/o NC.

**Comment by andreas-junghanns** [comment]
Such license changes should be approved by the FMI Steering Committee, unless what was written there was a mistake to simply be corrected to reflect what was previously decided.

**Comment by HansOlsson** [comment]
> Such license changes should be approved by the FMI Steering Committee, unless what was written there was a mistake to simply be corrected to reflect what was previously decided.

I _believe_ that it was just a mistake, since it's mentioning two different licenses.

**Comment by pmai** [comment]
I'm also not aware of any SC decision that would have moved to an NC license, which would have been needed. So it definitely seems like a mistake...

**Comment by andreas-junghanns** [comment]
> > Such license changes should be approved by the FMI Steering Committee, unless what was written there was a mistake to simply be corrected to reflect what was previously decided.
> 
> I _believe_ that it was just a mistake, since it's mentioning two different licenses.

Agreed. This needs fixing in 2.0.2 as well, right?
We will discuss this later today, and if all agree this to be a mistake, we can simply accept Christian´s PR.

**Comment by chrbertsch** [comment]
> Agreed. This needs fixing in 2.0.2 as well, right?
No, in 2.0.1 it is fine, no change needed.

**Comment by andreas-junghanns** [comment]
> > Agreed. This needs fixing in 2.0.2 as well, right?
> > No, in 2.0.1 it is fine, no change needed.

Ok, then this is a simple mistake and we should simply accept your PR.
