### ISSUE TITLE
Review attributes of <ScheduledExecution>

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1170]
Currently `<ScheduledExecution>` shares all attributes with `<fmi3CoSimulation>`:

```xml
        <xs:complexType name="fmi3CoSimulation">
		<xs:complexContent>
			<xs:extension base="fmi3InterfaceType">
				<xs:attribute name="canHandleVariableCommunicationStepSize" type="xs:boolean" default="false"/>
				<xs:attribute name="maxOutputDerivativeOrder" type="xs:unsignedInt" default="0"/>
				<xs:attribute name="providesIntermediateVariableAccess" type="xs:boolean" default="false"/>
				<xs:attribute name="recommendedIntermediateInputSmoothness" type="xs:int" default="0"/>
				<xs:attribute name="canReturnEarlyAfterIntermediateUpdate" type="xs:boolean" default="false"/>
				<xs:attribute name="fixedInternalStepSize" type="xs:double"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
```

Do `canHandleVariableCommunicationStepSize` and `fixedInternalStepSize` (and possibly others) make sense for Scheduled Execution?

**Comment by IZacharias** [comment]
@t-sommer Your are right, not all of the attributes make sense for SE.

**canHandleVariableCommunicationStepSize**: can be removed. All information on step size requirements can be taken from the clock variable elements
**canReturnEarlyAfterIntermediateUpdate**: can be removed. Early Return is not supported in SE
**fixedInternalStepSize**: can be removed
**hasEventMode**: can be removed. There is no Event Mode in SE.

The other attributes must remain.
