### ISSUE TITLE
Explain local variables

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1172]
During today web-design meeting, we discussed that local variables have no dependency information and that was one/the reason why you cannot connect them to other FMUs.

I just found in the text:
Local variable that is calculated from other variables or is a continuous-time state or an event indicator (see ModelStructure)....

For states we do not have dependency information?

**Comment by friedrichatgc** [comment]
I think a local variable is just a variable you can observe (e.g show it to the user during post processing the results). Nothing else should be done with a local variables (do not use it as output, ...).

**Comment by andreas-junghanns** [comment]
#1171 seems related

**Comment by andreas-junghanns** [comment]
web-desig meeting:
Clarify in glossary what a local variable is.

**Comment by andreas-junghanns** [comment]
Local variables are different from outputs in the following ways:
 - Local variables are not input, nor outputs, nor any kind of parameter (see causality definition).
 - Sometimes they are states, their derivatives, clocked states or event indicators.
 - Some local variables are listed in the ModelStructure (if they are Derivatives, EventIndicators or ClockedStates)
 - During initialization: you can ignore local variables only if they do not have start values and are not listed in InitialUnknowns.
 - After initialization: local variables are ignoreable if you do not want to use the structure of the model for connectivity or linearization of the FMU (or they are not listed in the <ModelStructure> at all). You can set them only if they are a state.

We might want to rename <ModelStructure><Derivate> to <ModelStructure><StateDerivative> to make sure we clarify the difference of general derivatives from state derivatives.

We need to specify (not just recommend) that the order of the (State)Derivate are listed is the same as one you call fmi3GetDerivatives(). Same for EventIndicators.
