### ISSUE TITLE
Add (*clockTicked) argument to fmi3NewDiscreteStates?

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1180]
Wouldn't it be "convenient" if a new argument (fmi3Boolean *ClockTicked) is added to fmi3NewDiscreteStates? Otherwise the importer should check all output-clocks after leaving fmi3NewDiscreteStates. This is very similar to the callback fmi3CallbackIntermediateUpdate where the clocksTicked indicates that GetClock should be called by the importer.
It both cases, it is a convenient flag, not a necessary flag. Because polling all output-clocks with GetClock must provide the same information.

**Comment by andreas-junghanns** [comment]
This is an output argument to inform the importer that the an FMU clock ticket.
This saves the importer a lot of GetClock() calls.

Klaus: The name should not use "tick".
Pierre: someClocksActive?

No opposition.

**Comment by masoud-najafi** [comment]
With the recent changes in the way clocks are handled in FMI-3.0, I think this ticket becomes obsolete and we can close it without doing anything. Except the for the name NewDiscreteState , where fmi3DoDiscreteStatesUpdate becomes more meaningful.
@clagms , What do you think about this ticket?

**Comment by clagms** [comment]
Agreed @masoud-najafi !

**Comment by andreas-junghanns** [comment]
IF we change this, I suggest to use fmi3UpdateDescreteStates().

**Comment by masoud-najafi** [comment]
OK, I will rename them to fmi3UpdateDiscreteStates.

**Comment by clagms** [comment]
> @clagms
> I am useless in doing PR, after my previous PRs, Torsten Sommer got mad on me :)
> So could I ask you for making a PR for renaming fmi3NewDiscreteState to fmi3DoDiscreteStatesUpdate, or learn me how to do it?

Sorry the delay @masoud-najafi ! I see that you've already done quite well 😄

**Comment by bernaloo** [comment]
@masoud-najafi I can do that :)
