### ISSUE TITLE
Add explanation and references to "synchronous clock theory"

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1184]
We mention "Synchononous Clock Theory" without explaining it. 

In 3.1.3 there is a reference to "Synchronous Systems", also with few references including the Modelica Language spec.

(from the discussion on  clocks in the clocks subgroup at the fmi design meeting)

"Synchononous Clock Theory" is listed in the glossary but not  written.

Do we have the same understanding of "Synchronous Clock Theory" as used in the Modelica Language?

But in Modelica clocks ticking at the same time refer to  synchronously evaluated equations. But in FMI with input and output clocks, there is a already an ordering of the evaluation order. 
So we should explain both the common concepts and differences (e.g. with Modelica Clocks).
And add references.

**Comment by chrbertsch** [comment]
@TorstenBlochwitz  : As this also relates to differences to Modelica Clocks: May I assign this ticket to you?

**Comment by andreas-junghanns** [comment]
There is no more reference to synchronuous clock theory in the entire text.
