### ISSUE TITLE
Clarify "time instant" if it means continuous time, or super-dense time

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1186]
Whenever we are describing issues in Event Mode in CS, we must be clearly defining which time we mean (continuous or super-dense).

**Comment by chrbertsch** [comment]
Both "time instant" and "time instance" occur in the text. I think it must all be "time instant", see https://english.stackexchange.com/questions/220028/instance-of-time-vs-instant-of-time

**Comment by andreas-junghanns** [comment]
This waits for clarification on clocks and events.

**Comment by andreas-junghanns** [comment]
Fixed in #1272, see https://github.com/modelica/fmi-standard/pull/1272/commits/19f7cdcb2e48ea4737d4ba6f690e563bed69c777
