### ISSUE TITLE
Clarify fmi3GetClock()

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1188]
We have to improve description of fmi3GetClock():
 - When are clocked variables valid (when to call fmi3GetXXX())
 - do we need a non-reset version?
 - should the reset-function be called fmi3GetClockAndReset()

**Comment by andreas-junghanns** [comment]
- Extend table for SE to allow GetClock for SE in Intermediate Update Mode.
 - IntermediateUpdateCallback must only be interpreted in SE.

**Comment by IZacharias** [comment]
It seems to be possible to do without an fmi3GetClockAndReset() function for SE. We must then force the FMU to reset the clock activation state of an output clock after calling intermediateUpdateCallback, i.e. during the time the variables of the output clock are accessed, the output clock is active.
Here is an example pseudo code that shows how it can work.
Assume the FMU has two input clocks and two output clocks. OutputClock1 is activated by InputClock1. OutputClock2 is activated by InputClock2. InputClock1 has higher priority than InputClock2.

```
// model partition for InputClock1
activateModelPartition1():
{
	...
	OutputClock1 = fmi3ClockActive;
	clocksTicked = fmi3True;
	intermediateUpdateCall(... clocksTicked ...);
	OutputClock1 = fmi3ClockInactive;
	...
}
 
// model partition for InputClock2
activateModelPartition2():
{
	...
	OutputClock2 = fmi3ClockActive;
	clocksTicked = fmi3True;
	intermediateUpdateCall(... clocksTicked ...);
	OutputClock2 = fmi3ClockInactive;
	...
}

fmi3GetClock()
{
	//return value of OutputClock1 and or OutputClock2
}


intermediateUpdateCall(..., clocksTicked, ...)
{
	...
	if clocksTicked == fmi3False
		return;
		
	// ActivationStateOfOutputClockX: global variable of the simulation environment. Used to ensure that the same output clock tick is not considered more than once
	if ActivationStateOfOutputClock1 == fmi3ClockInactive 
		fmi3GetClock(..., &ActivationStateOfOutputClock1 , ...)
		if ActivationStateOfOutputClock1 == fmi3ClockActive
			// get/set variables associated to output clock
			// and trigger connected input clock
			ActivationStateOfOutputClock1 = fmi3ClockInactive ;
			return;

	if ActivationStateOfOutputClock2 == fmi3ClockInactive 
		fmi3GetClock(..., &ActivationStateOfOutputClock2 , ...)
		if ActivationStateOfOutputClock2 == fmi3ClockActive
			// get/set variables associated to output clock
			// and trigger connected input clock
			ActivationStateOfOutputClock2 = fmi3ClockInactive ;
			return;
}
```

**Comment by andreas-junghanns** [comment]
#1199 contains the results of today´s discussion focused on ME and CS - to be continued...

**Comment by andreas-junghanns** [comment]
#1272 addresses all these issues.
I cannot link #1272 because we reached the limit of 10 issues linked to a PR  therefore closing, please reopen you disagree.
