### ISSUE TITLE
Multiple possible interpretations of clock API (and examples)

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#1199]
- Remove clocksAboutToTick from doStep because it's redundant with eventEncountered
- If you want to know if a clock is active, use getclock functions.
- A clock is active in a superdense time instant. call to newDiscreteStates makes it tick, and become inactive.
  - same applies to subactive. If we set a clock subactive, it remains subactive until the next fmi3NewDiscreteStates
- Function fmi3EnterEventModeTYPE has extra information that is important for model exchange but seems useless in co-simulation.

Types of clocks:
- Periodic: we know when they will tick.
- APeriodic:
  - Predictable: we know when they will tick.
  - Unpredictable: we don't know when they will tick.

Masoud: A model exchange scenario with unpredictable output clocks:
- The importer finds a zero crossing event
- To be continued...

Difference between model exchange and co-simulation with synchronous clocks: in co-simulation, the importer does not know when an unpredictable clock will tick. Only the FMU knows this.

A co-simulation scenario that allows inputs to be set before a clock ticks and while it is active:
- We have an FMU with an unpredictable output clock that ticks when a crank shaft inside that FMU is on top.
- The importer calls DoStep on the FMU.
- The FMU returns early (signals an early return through eventEncountered argument of doStep function) because (internally to the FMU) crank shaft 1 (modelled inside the FMU) is on top (and that will cause output clock 1 to tick).
- Importer sends the FMU into event mode.
- The Importer check which clock is active (by using GetCLock on every output clock of the FMU).
- The importer finds out that clock 1 is active.
- Importer gives new inputs that affect the clocked partition of clock 1 
    (before calling new discrete state).
- the clock 1 has not yet ticked.
- the importer calls fmi3NewDiscreteStates() and the clock 1 ticks inside the call.

Scenario to justify need for triggeredBy.
Masoud: Output clocks must not be associated to any variables (i.e., their clocked partition must be empty). 
Piere: if you want to have a non empty clocked partition, then you must use an input clock that is triggeredBy that output clock.
Christian: if an clock is signalled as being active, there's yet no calculation been done.
Pierre: Output clocks no longer seem to fit the definition in that they are no longer attached to a clocked partition.
Andreas: where is this requirement coming from? Example: if a plant model raises a "cylinder top" event, this is something that can onyl be computed if a lot of variables changes weith this event. This is just one FMU. 
Masoud: you can do everything isnide one FMU, but the good way to do it, is to generate an output clock and connect it to an input clock that will compute the variables that need to be activated by the output clock.

Example: fmu with radiactive decay. Each time there's decay, we have a energy variable in that output clock partition.
In order to model that, I need an input clock that is triggered by that output clock, so that the energy variable.

[Unpredictable aperiodic with clockedPartition on outputs] 
Scenario with two FMUs: an FMU (the Delcay FMU) with an output clock and an output variable, and another FMU (the calculation FMU) that has an input clock, input variable, and an output variable. 

Connections:
    Decay -output clock -- input clock --> Calculation
    Decay -output var -- input variable --> Calculation

- Decay.DoStep.
- The Decay signals early return (let's ignore the fact that the other FMU's state has run until the same time that the Decay integrated to).
- Decay.enterEventMode()
- Loop through clocks using the getClock function.
- The importer finds out output clock is active.
- Calculation.enterEventMode()
- Calculation.setClock(inputclock, active).
- Decay.newDiscreteStates() to make the output clock tick.
- [GetValues] Decay.getReal 
- [SetValues] CalculationFMU.setReal().
- [DecayNewDiscreteStates] CalculationFMU.newDiscreteStates() to make the input clock tick.
    During this call, Decay would update the internal state variables in the clocked partition.
- Decay.exitEventMode()
- Calculation.exitEventMode()

Remarks:
- Karl: [GetValues] must come after [DecayNewDiscreteStates] because The output variable is only computed when [DecayNewDiscreteStates] is executed.
- The clock being active means the output equations are active.

[Unpredictable aperiodic with clockedPartition on outputs by Pierre] 
Scenario with two FMUs: an FMU (the Delcay FMU) with an output clock and an output variable, and another FMU (the calculation FMU) that has an input clock, input variable, and an output variable. 

Connections:

    Decay -output clock -- input clock --> Calculation
    Decay -output var -- input variable --> Calculation

- Simulation time is T0

- Decay.DoStep(T0, H)
- The Decay signals early return (let's ignore the fact that the other FMU's state has run until the same time that the Decay integrated to).
- Decay.enterEventMode()
- Loop through clocks using the getInterval function and select those that return interval == 0.0.
- Decay.setClock(outputclock, active)
- Decay.newDiscreteStates().
  - This updates the output variable.
- Decay.getReal()
- Calculation.enterEventMode()
- Calculation.setClock(active) 
    || Calculation.setReal()
- Calculation.newDiscreteStates()
- Calculation.exitEventMode()
- Decay.exitEventMode()

[Partially predictable aperiodic with clockedPartition on outputs by Pierre] 
Scenario with two FMUs: an FMU (the Delcay FMU) with an output clock and an output variable, and another FMU (the calculation FMU) that has an input clock, input variable, and an output variable. 

Connections:

    Decay -output clock -- input clock --> Calculation
    Decay -output var -- input variable --> Calculation

- Simulation time is T0
- Decay.getInterval(outputclock) returns T1-T0
- Decay.DoStep(T0, T1-T0)
- The Decay signals early return (let's ignore the fact that the other FMU's state has run until the same time that the Decay integrated to).
- Decay.enterEventMode()
- Loop through clocks using the getInterval function and select those that return interval == 0.0.
- Decay.setClock(outputclock, active)
- Decay.newDiscreteStates().
  - This updates the output variable.
- Decay.getReal()
- Calculation.enterEventMode()
- Calculation.setClock(active) 
    || Calculation.setReal()
- Calculation.newDiscreteStates()
- Calculation.exitEventMode()
- Decay.exitEventMode()

[Unpredictable aperiodic without clockedPartition on outputs] 
Scenario with two FMUs: an FMU (the Decay FMU) with an input clock, an output clock and an output variable, and another FMU (the calculation FMU) that has an input clock, input variable, and an output variable. 
The output clock of the Decay FMU does not have any clocked partition. Instead the input clock partition contains the output variable.

Connections: 
    Decay.inputclock is triggered by Decay.outputclock
    Decay -output clock -- input clock --> Calculation
    Decay -output var -- input variable --> Calculation

- Simulation time is T0
- Decay.DoStep(T0, H)
- The Decay signals early return at time T1 (let's ignore the fact that the other FMU's state has run until the same time that the Decay integrated to).
- Loop through clocks using the getClock function to find out output clock is active.
- Decay.enterEventMode()
- Decay.setClock(inputclock, active)
- Decay.newDiscreteStates().
  - This updates the output variable.
- Decay.getReal()
- Calculation.enterEventMode()
- Calculation.setClock(active) 
    || Calculation.setReal()
- Calculation.newDiscreteStates()
- Calculation.exitEventMode()
- Decay.exitEventMode()

[Predictable aperiodic with clocked partition on output by Pierre]
Scenario with two FMUs: an FMU (the Decay FMU) with an output clock that predictable aperiodic, and an output variable, and another FMU (the calculation FMU) that has an input clock, input variable, and an output variable. 

Connections:

    Decay -output clock -- input clock --> Calculation
    Decay -output var -- input variable --> Calculation

- Simulation time is T0
- Decay.getInterval(outputclock) returns T1-T0
- Decay.DoStep(T0, T1-T0)
- Decay.enterEventMode()
- Decay.setClock(outputclock, active)
- Decay.newDiscreteStates().
  - This updates the output variable.
- Decay.getInterval(outputclock) returns T2-T1 
- Decay.getReal()
- Calculation.enterEventMode()
- Calculation.setClock(active) 
    || Calculation.setReal()
- Calculation.newDiscreteStates()
- Calculation.exitEventMode()
- Decay.exitEventMode()

[Predictable aperiodic without clocked partition on output by Masoud]
Scenario with two FMUs: an FMU (the Decay FMU) with an output clock that predictable aperiodic, and an output variable, and another FMU (the calculation FMU) that has an input clock, input variable, and an output variable. 

Connections:
    Decay.inputclock is triggered by Decay.outputclock
    Decay -output clock -- input clock --> Calculation
    Decay -output var -- input variable --> Calculation

- Simulation time is T0
- Decay.getInterval(outputclock) returns T1-T0
- Decay.DoStep(T0, T1-T0)
- Decay.enterEventMode()
- Decay.setClock(inputclock, active)
- Decay.newDiscreteStates().
  - This updates the output variable.
- Decay.getInterval(outputclock) returns T2-T1 
- Decay.getReal()
- Calculation.enterEventMode()
- Calculation.setClock(active) 
    || Calculation.setReal()
- Calculation.newDiscreteStates()
- Calculation.exitEventMode()
- Decay.exitEventMode()

=== Model Exchange Scenarios

[ME: Unpredictable aperiodic with clockedPartition on outputs by Pierre]
Scenario with two FMUs: an FMU (the Decay FMU) with an output clock and an output variable, and another FMU (the calculation FMU) that has an input clock, input variable, and an output variable. 

Connections:

    Decay -output clock -- input clock --> Calculation
    Decay -output var -- input variable --> Calculation

- Simulation time is T0
- Decay is in Continuous time mode, and is integrating until an event occurs
- The importer concludes that the FMU should go into event mode (see TODO below)
- Decay.enterEventMode()
- Loop through clocks using the getInterval function and select those that return interval == 0.0
- Decay.setClock(outputclock, active)
- Decay.newDiscreteStates()
  - This updates the output variable
- Decay.getReal()
- Calculation.enterEventMode()
- Calculation.setClock(active)
    || Calculation.setReal()
- Calculation.newDiscreteStates()
- Calculation.exitEventMode()
- Decay.exitEventMode()

[ME: Predictable aperiodic without clocked partition on output by Massoud]
Scenario with two FMUs: an FMU (the Decay FMU) with an output clock that predictable aperiodic, and an output variable, and another FMU (the calculation FMU) that has an input clock, input variable, and an output variable. 

Connections:
    Decay.inputclock is triggered by Decay.outputclock
    Decay -output clock -- input clock --> Calculation
    Decay -output var -- input variable --> Calculation

- Simulation time is T0
- Decay.getInterval(outputclock) returns T1-T0
- Decay is in Continuous time mode, and is integrating until T1
- Decay.enterEventMode()
~ Decay.getInterval(outputclock) should return 0.0
- Decay.setClock(inputclock, active)
- Decay.newDiscreteStates()
  - This updates the output variable
~ Decay.getClock(outputclock) -> False
- Decay.getInterval(outputclock) returns T2-T1
- Decay.getReal()
- Calculation.enterEventMode()
- Calculation.setClock(active)
    || Calculation.setReal()
- Calculation.newDiscreteStates()
- Calculation.exitEventMode()
- Decay.exitEventMode()

# Comparison of interpretations

Masoud:
- Has more moving parts (requires an aditional input and the triggeredby attribute).
- The input clock cannot be connected to any other output clock.

Pierre:
- Need funny return values from getInterval

# Agenda for next meeeting:

1. Explain both approaches
1. Work through an example that Masoud suggested using FMUs that have been reexported.
1. Compare both
1. Decide which is better

TODO: Make this into the standard: 
  - An unpredictable output clock must be tied to an event that must be exposed so that the importer will always enter event mode at the time that the output clock must be activated.
  - For a predictable output clock, the FMU has two possible mechanisms to inform the importer of the time at which the output clock should be activated: the nextTimeEvent and the getInterval. The FMU should use the getInterval only.

TODO: Consider more scenarios (described by Masoud)

**Comment by andreas-junghanns** [comment]
TODO for next Friday:
 - map out the orthogonal design issues in both approaches
 - check how to re-export both example FMUs in a single FMU
 - contrast to SE communication point clock requirements
 - decide on approach and victim to actually to write the stuff

**Comment by TorstenBlochwitz** [comment]
After a long discussion between Andreas and Torsten:

Pierre's approach requires that the following works:

> Loop through clocks using the getInterval function and select those that return interval == 0.0.

But this is not the case: The FMU would have to use the floating point time to make this decision. Depending on the time resolution of the importer the current event time might be shortly before or after the time, which was required by the FMU in Decay.getInterval(outputclock), but however might be the time instance at which the importer ticks the clock.

This would lead to the same inaccuracy as we currently have in FMI 1.0 and 2.0 using nextEventTime to specify time events.
One of the objectives to introduce the synchronous approach to FMI was to enable the importer to really be the "master of time": the master decides when a time based predictable clock ticks by explicitly calling fmi3SetClock() even if time resolution differs between the different simulation participants.
The paradigm is: The FMU must not use time to decide if a time-based predictable clock ticks or not. This decision is made by the importer.

**Comment by clagms** [comment]
>But this is not the case: The FMU would have to use the floating point time to make this decision. Depending on the time resolution of the importer the current event time might be shortly before or after the time, which was required by the FMU in Decay.getInterval(outputclock), but however might be the time instance at which the importer ticks the clock.

@TorstenBlochwitz I don't think this is an issue. I tried to see it from the Scenario [Partially predictable aperiodic with clockedPartition on outputs by Pierre] but could not see it.

Here's a reproduction of that scenario, with some more comments added and better notation for rigor.
It was good that you pointed this because I think there's another minor problem with the pseudo code (commented below).

@TorstenBlochwitz can you have a look at the annotated algorithm below and point out where is it that we will be making a wrong floating point comparison?


>One of the objectives to introduce the synchronous approach to FMI was to enable the importer to really be the "master of time"

I'm not sure this is correct. I agree that there should be a single source that decides when a clock should tick. But who said it has to be the importer? In the case of output clocks, it's the FMU, no?
The algorithm below mostly (check the different possible cases) ensures that the FMU is the one that decides when the clock should tick.


_____________________________________________
Legend and Notation for pseudo code below:
- This is a pseudo code step.
> This is a comment about the previous step
`This is a variable or code`
_____________________________________________

## Partially predictable aperiodic with clockedPartition on outputs by Pierre

Scenario with two FMUs: an FMU (the Delcay FMU) with an output clock and an output variable, and another FMU (the calculation FMU) that has an input clock, input variable, and an output variable. 

Connections:
```
Decay -- output clock -- input clock    --> Calculation
Decay -- output var   -- input variable --> Calculation
```

- Simulation time is `T0`
- And DecayFMU has internal time `Ť0` and is approx equal to `T0`: `Ť0≈T0`
- `Decay.getInterval(outputclock)` returns `ΔŤ = Ť1-Ť0`
- `Decay.DoStep(T0, ΔŤ)`
> There are multiple possible cases here:
1. Decay FMU uses its own internal time `Ť0` to increment the time: `Ť0 + ΔŤ == Ť1` and therefore concludes that the clock needs to tick but **it does not signal an early return** because the communication step ended at the right time `Ť1`.
2. Decay FMU uses its own internal time to increment the time: `Ť0 + ΔŤ == Ť1` and therefore concludes that the clock needs to tick and **it signals an early return** with last successfull time `Ť1` being very close, but not exacly equal to `T0 + ΔŤ`: `Ť1 ≈ T0 + ΔŤ`.
3. Decay FMU uses the importer time `T0` to increment the time: `T0 + ΔŤ == T1` and `T0 + ΔŤ > Ť1` **so it signals an early return**.
4. Decay FMU uses the importer time `T0` to increment the time: `T0 + ΔŤ == T1` and `T0 + ΔŤ < Ť1` so it **does not signal an early return**.
> In the cases where the Decay triggers an early return (cases 2, 3), it's easy to ensure that it will return exactly 0.0 when `Decay.getInterval()` is called.
> Case 4 does not worry me, because the next call to `Decay.DoStep` will make Decay signal an early return if the step size is large enough.
> Case 1 is worrying, because I'm not sure we cover this in the standard, and the exporter may think that the importer will be able to conclude that `Ť0 + ΔŤ == Ť1 == T0 + ΔŤ`, which is impossible, since `Ť0 ≈ T0`.
> Case 1 can also happen with time and state events whose trigger time happens to be very close to `T0 + ΔŤ`.
> Let's continue the algorithm assuming that the FMU always signals early return for case 1.
- The Decay signals early return.
> Let's ignore the fact that the other FMU's state has run until the same time that the Decay integrated to.
- `Decay.enterEventMode()`
- Loop through clocks using the `getInterval` function and select those that return `interval == 0.0`.
> In each of the above cases where an early return was triggered, the Decay FMU knows exaclty for whcih clock to return the exact value `0.0`.
- `Decay.setClock(outputclock, active)`
- `Decay.newDiscreteStates()`
  - This updates the output variable.
- `Decay.getReal()`
- `Calculation.enterEventMode()`
- `Calculation.setClock(active) `
    || `Calculation.setReal()`
- `Calculation.newDiscreteStates()`
- `Calculation.exitEventMode()`
- `Decay.exitEventMode()`

**Comment by clagms** [comment]
@andreas-junghanns , one more item for Friday's meeting:
- [ ] Work out an example with algebraic loops on the clocked partition.

I haven't had the time to work this out, but it seems that Pierre's approach works, even with different ways in whcih the algebraic loop can be solved:
Approach 1: the solution to the algebraic loop is done through fixed point iteration without incrementing the integer part of the superdense time (i.e., without calls to newDiscreteTimeState) in between.
Approach 2: If the solution to the algebraic loop is to done incrementing the integer part at each algebraic loop iteration (with calls to newDiscreteTimeState), then more trickery is needed as the clock will deactivate automatically when newDiscreteTimeState is called. Then we need to save the clocks state, activate it, call newDiscreteTimeState, then restore the state, set the new values to the clocked partition again, and repeat.

**Comment by clagms** [comment]
After having read through the original change proposal, and the paper in the modelica conference, here what I think the original intention of how to use the clocks was.
It does not seem to contradict any of the references I read, and does not require any major changes in what the fmi standard doc currently says.
I still have to double check the case of algebraic loops and the case that Massoud pointed out though (plus the TODOs in the pseudo code below).


_____________________________________________
Legend and Notation for pseudo code below:
- This is a pseudo code step.
  > This is a comment about the previous step

`This is a variable or code`
_____________________________________________


## Unpredictable aperiodic with clockedPartition on outputs by Original
Scenario with two FMUs: an FMU (the Delcay FMU) with an output clock and an output variable, and another FMU (the calculation FMU) that has an input clock, input variable, and an output variable. 

Connections:
```
Decay -- output clock -- input clock    --> Calculation
Decay -- output var   -- input variable --> Calculation
```

- Simulation time is `T0`
- `Decay.DoStep(T0, H)`
- The Decay signals early return (let's ignore the fact that the other FMU's state has run until the same time that the Decay integrated to).
  > Decay knows that the FMU will enter event mode at this stage, so it activates the clocked partition.
  > The clocked partition activation does not mean a computation is done right away. It just means that, if a clocked partition state variable `x` is queried (directly through `getReal(x)` or indirectly through `getReal(y)` of some other variable `y` that depends on `x`), then the FMU will do two things: 1. Copy the value of `x` to `previous_x` (this is a variable that's part of the Decay FMU state) (TODO: What happens to rollback?), and update the value of `x`. As with all the other equations, the importer must make sure that, by the time it asks for the value of `x`, then all the dependencies of `x` have been set (TODO: Check that interface exposes this information).
  > If some variables of the clocked partition have not been queried, then they are calculated when `newDiscreteStates` is called.
- `Decay.enterEventMode()`
- Loop through clocks of the Decay using the `getClock` function and select those that return `active == true`.
  > Calling `getInterval` on an active clock does not make sense, because one can only define the value of the next interval for the clock after all its clocked partition variables are evaluated, as this can only be ensured after `newDiscreteStates` is called.
- `Decay.getReal()` 
  > This updates the output variable.
- `Decay.newDiscreteStates()`
  > Any other variable belonging to the clocked partition will be evaluated at this point, and the output clock will become inactive.
  > Strictkly, a call to `Decay.getReal()` on output variable should return error because that variable is only defined when the clock is active. 
  > if one wanted to observe that variable again, we would have to turn the clock into subactive mode.
- Assume that `Decay.newDiscreteStates` indicates that no new event iteration is needed.
  > A call to `Decay.getInterval` at this point would make sense if this clock could be predicted. Since it can't, we must have a way to signal the importer that it should not call that function.
- `Calculation.enterEventMode()`
- `Calculation.setClock(active)`
- `Calculation.setReal()`
  > Assuming that setReal does not trigger any computation, then the above instruction can be executed before activating the clock. 
  I still feel that it's safer to first activate the clock, and then set the inputs to the clocked partition.
- `Calculation.newDiscreteStates()`
- `Calculation.exitEventMode()`
- `Decay.exitEventMode()`


## Partially predictable aperiodic with clockedPartition on outputs by Original

Scenario with two FMUs: an FMU (the Decay FMU) with an output clock and an output variable, and another FMU (the calculation FMU) that has an input clock, input variable, and an output variable. 

Connections:
```
Decay -- output clock -- input clock    --> Calculation
Decay -- output var   -- input variable --> Calculation
```

- Simulation time is `T0`
- And DecayFMU has internal time `Ť0` and is approx equal to `T0`: `Ť0≈T0`
- `Decay.getInterval(outputclock)` returns `ΔŤ = Ť1-Ť0`
- `Decay.DoStep(T0, ΔŤ)`
  > There are multiple possible cases here:
  1. Decay FMU uses its own internal time `Ť0` to increment the time: `Ť0 + ΔŤ == Ť1` and therefore concludes that the clock needs to tick but **it does not signal an early return** because the communication step ended at the right time `Ť1`.
  2. Decay FMU uses its own internal time to increment the time: `Ť0 + ΔŤ == Ť1` and therefore concludes that the clock needs to tick and **it signals an early return** with last successfull time `Ť1` being very close, but not exacly equal to `T0 + ΔŤ`: `Ť1 ≈ T0 + ΔŤ`.
  3. Decay FMU uses the importer time `T0` to increment the time: `T0 + ΔŤ == T1` and `T0 + ΔŤ > Ť1` **so it signals an early return**.
  4. Decay FMU uses the importer time `T0` to increment the time: `T0 + ΔŤ == T1` and `T0 + ΔŤ < Ť1` so it **does not signal an early return**.
  > In the cases where the Decay triggers an early return (cases 2, 3), it will activate the clock once entering event mode.
  > Case 4 does not worry me, because the next call to `Decay.DoStep` will make Decay signal an early return if the step size is large enough.
  > Case 1 is worrying, because I'm not sure we cover this in the standard, and the exporter may think that the importer will be able to conclude that `Ť0 + ΔŤ == Ť1 == T0 + ΔŤ`, which is impossible, since `Ť0 ≈ T0`.
  > Case 1 can also happen with time and state events whose trigger time happens to be very close to `T0 + ΔŤ`.
  > To solve this, we need to state in the standard that **if the end of a step size coincides exactly with the end of the co-simulation step, then `earlyReturn==False`, but `clocksAboutToTick==True`, and `lastSuccessfulTime==Ť0 + ΔŤ`**. 
  > If this is not the case, the importer may try to rollback other FMUs to a time that's very close to the end of doStep, which is pointless.
  > Let's continue the algorithm assuming that the FMU behaves correctly this manner for case 1.
- The Decay signals early return.
  > Let's assume the fact that the other FMU's state has run until the same time that the Decay integrated to.
- `Decay.enterEventMode()`
  > At this point the clock becomes active. 
  > The standard doc says, in the doStep description, that we need to call `Decay.newDiscreteStates()` before calling `getClock` but I think this is incorrect.
- Loop through clocks using the `getClock` function and select those that return `active==True`.
- `Decay.getReal()`
  > This updates the output variable.
  > Call to `Decay.getInterval()` is forbidden.
- `Decay.newDiscreteStates()`
  > This deactivates the output clock.
- `Decay.getInterval()`
  > Returns the next time for the clock tick.
  > Pierre's approach left this out.
- `Calculation.enterEventMode()`
  > The calculation input clock does not activate automatically, even if it knows the interval of the clock (which it should know).
- `Calculation.setClock(active) `
  > `Calculation.setReal()`
  > `Calculation.setInterval()` is forbidden while the clock is active? (TODO: What if the clocked partition depends on the interval of the clock itself?)
- `Calculation.newDiscreteStates()`
- `Calculation.setInterval()`
  > Inform the calculation FMU of what interval the next tick should be. This is important as there might be equations inside that depent on this interval (like a model predictive controller)
  > Pierre's approach left this one out.
- `Calculation.exitEventMode()`
- `Decay.exitEventMode()`

**Comment by clagms** [comment]
Here's an example with an algebraic loop (there's another approach to solve algebriac loops, which I want to explore).

## Clock with algebraic loops spanning output variables only - Method solve algebraic loop in same superdense time instant.

In this scenario, there's an algebraic loop spanning the output equations of the clocked partitions.
Clock `k` is unpredictable.

```
          x_{k+1} = f(x_k, u_k)
          y_k = g(x_k, u_k)

           +----------------+              +-----------------+
           |                |  clock k     |                 |
           |     Decay      +-------------->   Calculation   |
           |                |              |                 |
+----------> +----+         |              |        +------> +-----+
|          |      |         |    y_k       |        |        |     |
|          |      +-------> +--------------> +------+        |     |
|          |                |              |                 |     |
|          +----------------+              +-----------------+     |
|                                                                  |
|                                                                  |
|                               u_k                                |
+------------------------------------------------------------------+
```

- Simulation time is `T0`
- `Decay.DoStep(T0, H)`
- The Decay signals early return (let's ignore the fact that the other FMU's state has run until the same time that the Decay integrated to).
- `Decay.enterEventMode()`
- Loop through clocks of the Decay using the `getClock` function and select those that return `active == true`.
- `Calculation.enterEventMode()`
- `Calculation.setClock(active)`
  > Since there is an algebraic loop, we have to activate both clocks at the same superdense time instant, so we can solve the clocked partition equations.
- Start algebraic loop solution:
  - `Decay.getReal()` 
    > This updates the output variable from the old value of the input variable (some other guess values could have been used)
  - `Calculation.setReal()`
  - Check for convergence. If not, repeat.
- Converged.
- `Decay.newDiscreteStates()`
  > TODO: What if newDiscreteStates signals that we need a new event iteration?
  > Also note that this contradict the original RFC proposal, because there it says that the clock turns inactive the moment that all its variables have been computed. Following that proposal will mean that the importer will have to do a lot of bookeeping to know when exactly a clock turned inactive (so it can turn it active again). It's better to assume that the clock turns inactive when `newDiscreteStates` is called.
- `Calculation.newDiscreteStates()`
- `Calculation.exitEventMode()`
- `Decay.exitEventMode()`

**Comment by masoud-najafi** [comment]
If I understood correctly, after the meeting on 16 october 2020, @TorstenBlochwitz  indicated that the calling sequence detailed in the page 9 of this presentation
[Alatir_clock_handling.pdf](https://github.com/modelica/fmi-standard/files/5392536/Alatir_clock_handling.pdf)
would be included in the standard as the latest (more recent) interpretation of Clock APIs. This interpretation is subject to change if we find any use-case not compatible with this calling sequence.    
@TorstenBlochwitz , please let me know who should/would do this PR?
Thanks
Masoud

**Comment by clagms** [comment]
I can volunteer to write about this @TorstenBlochwitz , as I've already notes on the meaning of each function.
Just need to update those notes for @masoud-najafi 's interpretation (minor changes as I recall from our last meeting).
So, with some help from @masoud-najafi (to clarify here and there) I think I have enough material to write about this.

**Comment by andreas-junghanns** [comment]
> Is this ok with you @andreas-junghanns and @TorstenBlochwitz ?

Yes, of course, please go ahead (try to be brief in all explanations)!

**Comment by andreas-junghanns** [comment]
This should be clear now with #1272.
I would normally link #1272 to this to automatically close this issue when #1272 is merged, but this is somehow not possible now.
Closing this ticket instead.
