### ISSUE TITLE
eliminate clock union section, move concept to input clock section?

### ISSUE THREAD

**Issue by oliverkotte** [modelica/fmi-standard#1213]
Do clock unions really need to be introduced as a term warranting its own section? To reduce complexity of presentation, it may suffice to add one/few sentences to the input clocks section. They would state that an (aperiodic) input clock may depend on an output clock of the same FMU (so that the FMU can tell the importer to trigger the FMU's own event handling, with applications for SE)? I am not arguing against the concept, I was just confused by the term and once I understood the concept, I wondered why the term is needed at all.

**Comment by masoud-najafi** [comment]
IMHO, clock union is/should not be restricted to input clocks. In a complex model, even with the current specification, the clock union is possible, i.e., an output clock may "directly" depend on several input clocks. The TriggeredBy attribute is just a shortcut to a clock union between the output-clock and the input-clock to activate an internal partition. We can very well get rid of the TriggeredBy (even in SE) and use an external clock-union instead. So having a separate clock-union section would not related exclusively to input clock, and it is a general term.

**Comment by oliverkotte** [comment]
Tbh, I am still confused.
In the current FMI3 spec, the clock union section defines clock unions as input-clock(s) TriggeredBy an output-clock.
In your answer, you use the term clock union more loosely, stating it would also include “i.e.” an output-clock depending on input-clock(s).
For input-output-clock relationships within the same FMU, I gathered:

1. input-clock(s) TriggeredBy output-clock: mechanism to activate internal partition(s) without having to rely on the master (for SE)
2. output-clock TriggeredBy input-clock: avoid strange fmi3SetClock calls on output-clocks (for ME, CS)
3. output-clocks causally depending on input-clocks and being automatically activated during event iteration with or without TriggeredBy

To me, these are three different things. Which of these are clock unions?

**Comment by masoud-najafi** [comment]
1) Yes, this is the current interpretation mentioned in the Standard and it is for SE.
2)Having a loop from outputClock into an input-clock is a mechanism to activate a partition inside the FMU that programs an aperiodic clock. Using a TriggeredBy is doing the same in SE. Using TriggeredBy in ME to replace this external output-clock to inputClock has not yet introduced in the current standard.
3)This is the definition of an FMU operating as a Clock Union. Whenever one of input clocks of the FMU is activated, a  synchronous clock is triggered at the output clock of the FMU (i.e., in the very same super-dense time).

Hope this clarifies things.

**Comment by oliverkotte** [comment]
Yes, it does, thank you. It’s just that I still cannot fully shake the feeling that two different things are thrown together into one bucket that is labelled ‘clock union’.

1+2. are artificial mechanisms that use TriggeredBy to achieve a desirable feature (to be able to self-activate a partition; to be able to call set on input not output). These mechanisms operate on the level of the FMI interface.
3. This direct input clock->output clock dependency is a natural property of the model equations, not of FMI.

If 3. is the definition of an FMU operating as a clock union, I think it is debatable whether 1+2. are really clock unions or if they just appear to be. In other words, the mechanisms 1+2. could be introduced directly, focusing on their specific purpose. There might not be a need to introduce these under a clock union concept that seems to mix up model-internal properties with model-external mechanisms imposed on FMI-level. In yet other words, to me, the commonality of 1+2. with 3., direct I/O clock dependency, arises from the solution, it is not the thing that is being addressed, and thus maybe should not be emphasized so much to avoid confusion.

This is anyway just my two cents…

Mit freundlichen Grüßen / Best regards

Oliver Kotte
CR/AEE3

Tel. +49 711 811-26282 | Mobil +49 172 5679055
​

**Comment by masoud-najafi** [comment]
> If 3. is the definition of an FMU operating as a clock union, I think it is debatable whether 1+2. are really clock unions or if they just appear to be. In other words, the mechanisms 1+2. could be introduced directly, focusing on their specific purpose. There might not be a need to introduce these under a clock union concept that seems to mix up model-internal properties with model-external mechanisms imposed on FMI-level. In yet other words, to me, the commonality of 1+2. with 3., direct I/O clock dependency, arises from the solution, it is not the thing that is being addressed, and thus maybe should not be emphasized so much to avoid confusion.

Completely agree with you. Maybe having completely separate sections, for example "TriggeredBy", "Dlock-dependency" or "Clock-union" to separate these things would be better to avoid confusion. Just need to find good locations to explain them.
CC: @andreas-junghanns

**Comment by andreas-junghanns** [comment]
Clock unions are now completely gone.
Dependencies can be defined with normal ModelStructure dependencies.
TriggeredBy stays as concept as before and only applies to SE.
This issue closes automatically when #1272 is merged into the master.
