### ISSUE TITLE
Output-clocks may depend on several input clocks

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1214]
One of important assumption in the Clock support in FMI-3.0 in given in section 2.2.7, where it is mentioned that 
_"If the clock referenced by clockReference is a synchronous clock (clockType = synchronousTime), the variable is a clocked variable associated uniquely with this clock. It is not possible to associate more than one clock to a variable."_

We agree that this statement should be respected for all variables. But what about clock variables? Actually, an output clock may depend on several input clocks. Note that in many situation the UNION of clocks is needed. A kind of union of clocks is already supported through the TriggeredBy attribute, where a partition depends on an input clock and an output clock. 
Inside an FMU, the output clock may be triggered either by an internal event or due to one or several input clocks.
In re-exporting FMUs also, there are cases where an output clock needs to depend on several input clocks.
In the ModelStructure section, output variables can depends on several input clocks. 
So, I would suggest to provide an exception for clock variables and allow them to be assigned to several clocks. This also can be done by just remove the clockReference for Clock variables and make use of dependencies attribute in the modelStructure to avoid redundancy of information. Note that the information redundancy is already present.

**Comment by andreas-junghanns** [comment]
Output clocks are now normal output variables and this allows ModelStructure for Output elements to be applied and to relate output clocks to any number of inputs, including input clocks, even multiple input clocks.
This ticket closes when #1272 is merged into master.
