### ISSUE TITLE
 Is multi-dimentional clock variables really needed?

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1215]
Clock variables can be multi-demension, but there are a few clarification need to be done:
1) Can the dimension and sizes of a variable be different from that of its referenced-clock? For example, is it correct to assign a matrix clock variable to a scalar variable?
2) Suppose that the dimension and size of a variable V be identical to that of its reference clock C. Does clock C(i,j) affect only the element V(i,j) of variable V, or the entire V variable? 
3) Is there any real use-case for multi-dimensional clock variable?

**Comment by andreas-junghanns** [comment]
If this is too complicated, we could think of restricting clock variables to be scalar only in 3.0.

**Comment by andreas-junghanns** [comment]
We decided to leave clocks as normal variables, including the possiblity for them to be arrays.
Only allowing atomic clocks would make the standard more complex.
We are quite happy with the current solution as it unifies clocks into the general variable concept seemlessly.
Closing.
