### ISSUE TITLE
Allow inverse display units

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1220]
Example: `mpg` (miles per gallon) as display unit for `L/100km` (liters per 100 km)

```xml
<UnitDefinitions>
  <Unit name="L/100km">
    <BaseUnit m="2" factor="1e-8"/>
    <DisplayUnit name="mpg" invert="true" factor="235.214583"/>
  </Unit>
</UnitDefinitions>
```

The display value `v_display` would be converted from the base value `v_base` as

```
v_display = factor * (1/v_base)
```

if `invert == true`.

**Comment by andreas-junghanns** [comment]
Would the DisplayUnit not also need a Unit, like "mpg" as attribute?

**Comment by andreas-junghanns** [comment]
Should BaseUnit not have m="-1e5"?

**Comment by t-sommer** [comment]
> Would the DisplayUnit not also need a Unit, like "mpg" as attribute?
> Should BaseUnit not have m="-1e5"?

I've updated the example.

**Comment by chrbertsch** [comment]
I do not like this idea: the inverse is a different physical quanatity, and not just another  display unit. 
Addtionally, it complicates the definition of units, and we will run into problems like division by zero.
I think for an inverse quantity you need an explicit conversion either in you model to be exported as an FMU or in the postprocessing of the simulator.

**Comment by t-sommer** [comment]
> Addtionally, it complicates the definition of units, and we will run into problems like division by zero.

A separate variable only shifts the problem from the importer to the FMU.

**Comment by andreas-junghanns** [comment]
> 
> 
> > Addtionally, it complicates the definition of units, and we will run into problems like division by zero.
> 
> A separate variable only shifts the problem from the importer to the FMU.

... which would be a good shift. The FMU usually has more information about its variables and know when to expose inverse unit variables.

**Comment by t-sommer** [comment]
Consider the case of a parameter `fuel_consumption`:

With the separate variable, you would have something like this

```
fuel_consumption_metric = 5.4 [L/100km]
fuel_consumption_imperial = 43.5583 [mpg]
fule_comsumption_use_metric = true
```

as opposed to 

```
fuel_consumption_metric = 5.4 [L/100km]  # displayed as [mpg]
```

**Comment by chrbertsch** [comment]
Still to my opinion this goes beyond the idea of displayunits and will cause additional problems, see above. 
So I propose to close this. Shall be discussed at next regular FMI design webmeeting.

**Comment by chrbertsch** [comment]
Regular Design Meeting: 

Karl: What do do with the combination of inverse with an offset? Or prohibit it.
Pierre: I do not see the point for display unit at all
Torsten: in the  GUI
Pierre: but not the FMU
Karl:  Display units are quite practical
Karl: the importing tool has to deal with division
Pierre: If one wants this, there are use cases
Klaus: we ignore display units. No need for any extensions of display units. For now we would ignore it. 
Irina: no strong opinion.

Christian: I consider it complicated for the importer
Torsten, Klaus: It can be ignored
Klaus: Why not do it directly in the FMU?

Torsten: on can have multiple display units
Pierre: as long as we have display units, we should have the inverse

Torsten: I will provide a PR unitl tomorrow

**Comment by KarlWernersson** [comment]
The formula is wrong for inverse, it has to be either 

1. factor/(unit-offset) 

2. 1/(factor*unit -offset) 

(1) looks nicer but (2) has the benefit that factor and offset stay the same value as for the non inverse case. 

A third option would be to skip the combination of inverse and offset. I cant find a practical use case were is actually needed. Then we could keep the simple formula factor/unit, (follows the FMI principle keep it simple)

**Comment by chrbertsch** [comment]
> A third option would be to skip the combination of inverse and offset. I cant find a practical use case were is actually needed. Then we could keep the simple formula factor/unit, (follows the FMI principle keep it simple)

This would be my favorite as loing as we do not have a use case
