### ISSUE TITLE
What is the meaning of intermediate variable access in SE? are there continuity assumptions for output variables in  Intermediate update in CS and SE?

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1221]
Invermediate update mode is available in SE, see the overview https://fmi-standard.org/docs/3.0-dev/#table-overview-features and https://fmi-standard.org/docs/3.0-dev/#IntermediateUpdateModeSE .  There https://fmi-standard.org/docs/3.0-dev/#IntermediateUpdateMode from the the common concept section is referenced.

In the table in https://fmi-standard.org/docs/3.0-dev/#definition-of-model-variables, intermediateUpdate it is written: 
"This attribute is only used for Co-Simulation. The default value of this attribute is false."
So does this apply to SE or not?

For CS there are restrictions and assumptions for intermediate variables documented in the mathematical model.
E.g. we have clearly defined continuity or even smoothness requirements on intermediate inputs.
To my understanding, intermediate outputs should also be at least continuous (and thus only be allowed only for continuous variables?), but I do not find this clearly stated in the spec.

In SE, there are no such descriptions at all which would prevent communicating discrete changes at intermediate timepoints.

**Comment by chrbertsch** [comment]
Could some please comment, he or she shares my problems or if they go away? Thanks
@IZacharias , @MBlesken  and others

**Comment by IZacharias** [comment]
@chrbertsch @MBlesken In SE the intermediate update mode is used to inform the master about ticking output clocks. The access to intermediate variable values is not possible and therefore not mentioned in chapter 5. The intermediatUpdate attribute is ignored in SE.

**Comment by chrbertsch** [comment]
Regular Design Meeting: 

in the overview, add the information that intermediate update in SE is only possible to signal output clocks, not to exchange input and output values.

**Comment by chrbertsch** [comment]
Either Irina or I will create a PR in the next week
