### ISSUE TITLE
Drop setting of variables in Instantiated?

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1223]
Why do we allow setting of variables in Instantiated?
Can´t we restrict setting to Initialization Mode?
We currently have the same restrictions (except for inputs) on both modes.

We propose to keep Instantiated simple and focused on resource allocation.
Otherwise, a detaour via Configuration Mode can cause some trouble: what values survive when arrays need to be resized etc.

**Comment by KarlWernersson** [comment]
We don't have the same restrictions.

One type of variables that can only be set in instantiated but not in initialization mode. Is the start values with intial=aprox these are start values for variables  that are calculated though some internal nonlinear equation or other iteration. 
As other start values with initial=exact might affect the solution to this equation it can sometimes be necessary to change these start values.

**Comment by andreas-junghanns** [comment]
@KarlWernersson : Are you suggesting that we treat both modes the same? Or are you suggesting that we apply different restrictions on what variables can be set during which state of these two states (Instantiated and Initialization Mode)?

**Comment by andreas-junghanns** [comment]
@TorstenBlochwitz : Can you decode Karl´s answer and does that mean we can close this ticket?

**Comment by KarlWernersson** [comment]
I am saying that we currently have different restrictions and changing this would affect how start values with initial="aprox" is handled

**Comment by KarlWernersson** [comment]
So that would need a solution before we change it

**Comment by andreas-junghanns** [comment]
No, I think this is clear - thank you for the explanation. Closing ticket.
