### ISSUE TITLE
Merge <BaseUnit> into <Unit>

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1232]
as there is no benefit of having an empty `<BaseUnit>` vs. simply leaving the attributes at their defaults.

**Comment by andreas-junghanns** [comment]
Can you check #1187 and see if you can address this issue as well?

**Comment by chrbertsch** [comment]
> Can you check #1187 and see if you can address this issue as well?

@andreas-junghanns: Are you sure you linked the right ticket? I do not see the connection.

**Comment by andreas-junghanns** [comment]
> 
> 
> > Can you check #1165 and see if you can address this issue as well?
> 
> @andreas-junghanns: Are you sure you linked the right ticket? I do not see the connection.

Sorry, wrong. Fixed.

**Comment by KarlWernersson** [comment]
I would say that there is a theoretical difference by having an empty Base unit vs having no base unit, and that is that an empty base unit could be interpreted that the tool has done proper unit checking and knows that this unit it unitless in S.I, e.g. ppm in the example. By not specifying base unit it could be seen as that the tool hasnt bothered to do a unit check.

This is however quite implicit and **not defined.**

Also in practice does it do any big difference, for a human reader maybe, but for the importing tool, I would say probably no.

So for me go ahead and merge.

**Comment by chrbertsch** [comment]
@t-sommer : could you please provide a PR for this? Thanks!

**Comment by KarlWernersson** [comment]
Thinking some more i am not 100% sure it is a good idea.

It could be nice to clearly separate the base unit from the unit.
Technically it would be the same but it helps to more clearly define that the unit is not it's base unit, rather the base unit defines how the unit can be mapped to a set of SI units with the help of offset and factor.

So after a seccond thought i think it is better to leave it as is and don't change it.

**Comment by t-sommer** [comment]
I'm not proposing to get rid of the term "base unit", which will still be used (and defined) in the spec. It's only about cleaning up the XML. We've done the same for the types (inside `ScalarVariable`) etc.

**Comment by chrbertsch** [comment]
> I'm not proposing to get rid of the term "base unit", which will still be used (and defined) in the spec. It's only about cleaning up the XML. We've done the same for the types (inside ScalarVariable) etc.

@t-sommer :  perhaps this can be most easily shown an discussed by providing an a draft PR :-)

**Comment by t-sommer** [comment]
It's quite an effort to rewrite the chapter, so I just want to make sure everybody is on board.

**Comment by pmai** [comment]
I agree somewhat with @KarlWernersson that not providing a BaseUnit states that the relationship to SI units is unknown (if you just wanted to provide a unit-less variable, you would not have provided a Unit in the first place), whereas a BaseUnit with default values states explicitly that the Unit is dimensionless, i.e. it is just a count. Those are different things, so merging of BaseUnit into Unit would require an additional flag to distinguish those, and that seems overly complex.

Consider the use case where a modeling tool has unit information (like FMI 1.0), but no SI mappings for them. In FMI 2.0 it would create Units of the proper names, but without a BaseUnit, clearly indicating that there are no relations to a BaseUnit, and hence an importer would be wrong to assume that it can convert one unit into the other.

If however it provides a BaseUnit (or in FMI 3.0 by just defining the Unit) with default values for the attribute, this indicates that all of the Units are just counts, and can hence be converted (through identity) to one another. This is a very different thing.

So I would propose not to do this merge.

**Comment by andreas-junghanns** [comment]
If you do not agreeing with @pmai ´s proposal to not change the XSD, reopen this ticket.
