### ISSUE TITLE
Add defintion of the term "signal"

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1233]
that is used throughout the document, but not defined in the glossary

**Comment by andreas-junghanns** [comment]
Would it not be better to change "signal" to "variable" and not use "signal" at all?
(not where we use "to signal" as verb, we have to be careful)

@t-sommer : if you agree, I will create a PR.

**Comment by t-sommer** [comment]
Not sure if "variable" is always the intended meaning...

**Comment by andreas-junghanns** [comment]
> Not sure if "variable" is always the intended meaning...

Let me try and we will see what is left and if we need "signal" as extra concept.

**Comment by andreas-junghanns** [comment]
@t-sommer : Can you have a look? I think this is ok now and there is only one "signal" left in the Reference-FMU repo.
