### ISSUE TITLE
Auto-reset clock for ME/CS

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1238]
in Section 2.2.7.9 there is this statement:

"It is required for an FMU to directly internally set back the activation state of an output clock[i] to fmi3ClockInactive, if the function fmi3GetClock is called for a clock[i] and the interface is Scheduled Execution. [This is required to allow preemption.]
[TODO: WHAT? Separate issue to discuss needs of preemption. Link to example. This is necessary but nor sufficient requirement for preemption. Pick better name for the Getting to show that the clock is auto-reset. ]"

If this auto-reset is really required, is it possible to do it once the FMU leaves the current super-dense time, i.e., inside UpdateDiscreteStates() in ME/CS? This simplifies things for the importer in ME/CS, in particular when several dependent clocks are present in the model.

**Comment by andreas-junghanns** [comment]
Resetting clocks during UpdateDiscreteStates() is in line with considering the clock activation state to be part of the discrete state.
Spinning this thought further would also mean that a clock can only turn active during UpdateDiscreteStates().

**Comment by masoud-najafi** [comment]
I would say, a clock life cycle would be from SetClock to the end of UpdateDiscreteStates().

**Comment by andreas-junghanns** [comment]
> I would say, a clock life cycle would be from SetClock to the end of UpdateDiscreteStates().

Yes, agreed. Now, how would a clock get activated within one super-dense time instant? It must be prior to EnterEventMode() or during UpdateDiscreteStates(). Only then will the importer know to call SetClock().

If this is the case, then I suggest that the semantic is clear: the clock activation state is part of the discrete state.

If we can agree on this, explaining the semantics and mechanisms would be much simpler.

**Comment by masoud-najafi** [comment]
Suppose that there are two independent clocks clk1 and clk2 have been both scheduled at time Te. When the simulation time reaches Te, the importer should call:

EnterEventMode() //here the discrete mode starts
SetClock(**clk1**) // here the super-dense time for **clk1** starts
getXXX // do all necessary iterations such as solving algebraic loops
setXXX
UpdateDiscreteStates() // here the super-dense time for **clk1** ends
SetClock(**clk2**) // here the super-dense time for clk2 starts
getXXX
setXXX
UpdateDiscreteStates() // here the superdense time for clk2 ends
EnterContinousTimeMode() // here the discreteMode ends

The point is that in a single discreteMode, we may have several independent supper-dense times (each for an independent clock).

**Comment by masoud-najafi** [comment]
Also, suppose there is a dependent clock **clkd** that depends on another independent clock **clk**.
When the execution time of **clk** arrives:

EnterEventMode() //here the discrete mode starts
SetClock(**clk**) // here the super-dense time for **clk** starts
getXXX // do all necessary iterations such as solving algebraic loops
setClock(**clkd**) // if it happens that the dependent clock **clkd** gets activated
setXXX
UpdateDiscreteStates() // here the super-dense time for **clk** and **clkd** ends
EnterContinousTimeMode()

**Comment by andreas-junghanns** [comment]
> EnterEventMode() //here the discrete mode starts
> SetClock(**clk**) // here the super-dense time for **clk** starts
> getXXX // do all necessary iterations such as solving algebraic loops
> setClock(**clkd**) // if it happens that the dependent clock **clkd** gets activated
> setXXX
> UpdateDiscreteStates() // here the super-dense time for **clk** and **clkd** ends
> EnterContinousTimeMode()

Why do we call setClock(clkd) after the other get/set calls? Either the dependent clock was already active when entering event mode, or we will find out about it´s activation only when calling UpdateDiscreteStates(), right?
My understanding: Any setClock must happen directly after EnterEventMode or after UpdateDiscreteStates.
Otherwise, clocks cannot be considered part of the discrete state because they change even without calls to UpdateDiscreteState...

**Comment by andreas-junghanns** [comment]
@pmai / @TorstenBlochwitz : Please comment

**Comment by masoud-najafi** [comment]
> My understanding: Any setClock must happen directly after EnterEventMode or after UpdateDiscreteStates.
> Otherwise, clocks cannot be considered part of the discrete state because they change even without calls to UpdateDiscreteState...

What you are saying is right for "independent" clocks. The dependent clocks are a bit different. Consider, for example, an FMU that subsamples its input clock and ticks out one out of N ticks at its output clock.
How should the output ticks of this FMU be handled? The answer would be clearer if you consider the case N=1. If N=1, the FMU should look like a simple connection.
A dependent clock is actually a "child" of an independent clock. All children of an independent clocks that have been activated during a super-dense time are part of one clock family and should be considered as the same clock. And should be turned off all at the same UpdateDiscreteStates().

**Comment by TorstenBlochwitz** [comment]
Hi Masoud, together with Pierre and Andreas, we discussed your calling sequence.
What we do not understand is: if clkd is a dependent clock, how can the importer call fmiSetClock for it? clkd depends on clk, the importer does not know, how it depends. For that reason it is an Output Clock, the importer can call fmiGetClock on it.

For that reason and from our point of view, the calling sequence should look like:
- fmiEnterEventMode() //here the discrete mode starts
- fmiSetClock(clk) // here the super-dense time for clk starts
- fmiGetClock(clkd) //clkd depends on clk and could be active
- fmiGetXXX, fmiSetXXX // do all necessary iterations such as solving algebraic loops
- fmiNewDiscreteStates() // here the super-dense time for clk and clkd ends, all clocks are deactivated
...do what ever is necessary for other clocks or the discrete part of the model
- fmiEnterContinousTimeMode()

You are quoting the current version of the specification. We restarted the discussion on clock types and calling sequence 3 weeks ago. We try to go step by step from clock types to calling sequence to new specification text. From my point of view your demand is covered by the calling sequence in my presentation which we will continue to discuss as soon as the clock type discussion is finished.

**Comment by masoud-najafi** [comment]
>clkd depends on clk, the importer does not know, how it depends. For that reason it is an Output Clock, the importer can call fmiGetClock on it.
The importer has the dependency information in the ModelStructure. The clkd which is an output-clock should declare clk (which is an input clock ) in its dependency list. If clkd is not in the dependency list it will be an independent clock.

**Wait wait**, I made a mistake in my calling sequence. You have fixed my calling sequence. I just add the a line to do it more precise.

    fmiEnterEventMode() //here the discrete mode starts
    fmiSetClock(clk) // here the super-dense time for clk starts
    fmiGetClock(clkd) //clkd depends on clk and could be active
**setClock(ALL input-clocks connected to clkd) // This is what I intended to do**
    fmiGetXXX, fmiSetXXX // do all necessary iterations such as solving algebraic loops
    fmiNewDiscreteStates() // here the super-dense time for clk and clkd ends, all clocks are deactivated
    ...do what ever is necessary for other clocks or the discrete part of the model
    fmiEnterContinousTimeMode()


If the life cycle of clocks is fine, then we are OK. and we can put in the spec.

**Comment by andreas-junghanns** [comment]
#1272 addresses this now, hopefully clearly. Please check.
This issue closes automatically when #1272 is merged into master.
