### ISSUE TITLE
Use variability attribute of a "clock" to indicate its periodicity type

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1239]
Currently the variability of a clock does not carry any useful information about the clock. The dataType of clock variables is sufficient to check the consistency of connections between input and output clocks. 
Wouldn't it better to use the variability attribute of clock variables to indicate the periodicity of the clock?
For example, the period of "periodic" input or output clocks can be CONSTANT, FIX or TUNABLE.
The variability of other clocks such as apriodic clocks would be DISCRETE.
In this way, we may get rid of the "periodic" and "strict" attributes of the clock variables too, isn't it?

**Comment by TorstenBlochwitz** [comment]
We discussed this topic last week. Pierre volunteered to come up with a proposal, which will be discussed tomorrow in our next meeting.

Please be a bit patient.

**Comment by masoud-najafi** [comment]
Very good. It would be good if @pmai  could share the document before the meeting to let the others read it beforehand.

**Comment by andreas-junghanns** [comment]
This is now addressed with #1272 - please check if you are happy with the changes.
This issue will close automatically when #1272 is merged into master.
