### ISSUE TITLE
Clarification on assigning partition to outputclock in SE

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1242]
In section 5.2.1.2. (State: Clock Activation Mode), there is this statement:
"The fmi3ActivateModelPartition function is not called for output clocks of an FMU."

But in section 5.1, there is this statement:
"Model partitions that are associated to output clocks will accordingly provide the result values of the model partition’s variables for the current outputClock tick time ti of the active outputClock. The activation of such an outputClock is not controlled by the simulation algorithm but internally by the FMU."

Please clarify which one is correct. Can a partition or a clocked-variable be assigned to an outputclock in SE?
CC: @IZacharias

**Comment by IZacharias** [comment]
@masoud-najafi Your are right, the section 5.1 is not correct or at least misleading. A model partition cannot be associated to an output clock. What is meant here is that a variable can be associated to an output clock, i.e. the variable can be accessed when the output clock ticks.
We will fix this in the specification.

**Comment by andreas-junghanns** [comment]
@IZacharias : Please comment here when you fixed this in your PR.

**Comment by andreas-junghanns** [comment]
I think PR #1309 will cover this.
