### ISSUE TITLE
Bad default value for variability in fmi3Variable.xsd

### ISSUE THREAD

**Issue by GHannesen** [modelica/fmi-standard#1243]
In line 330 of fmi3Variable.xsd there is a default value for variability:
		<xs:attribute name="variability" default="continuous">

As type: <xs:complexType name="fmi3VariableCore" ...
is used for all variable types, for example integer,
the default is wrong and should be removed.

**Comment by GHannesen** [comment]
Actually the behavior is defined in the specification:
"The default is continuous for variables of type <Float32> and <Float64>, and discrete for all other types."

This doesn't match the xsd

**Comment by GHannesen** [comment]
... of type <Float32> and <Float64>, ...

**Comment by t-sommer** [comment]
Can you propose a solution?

**Comment by pmai** [comment]
In XML Schema 1.0 the only solution is to remove the default value in the schema, i.e. the proper default must be handled by the application layer. PR posed.
