### ISSUE TITLE
Problem with mandatory attributes in variable and typeDefinition

### ISSUE THREAD

**Issue by GHannesen** [modelica/fmi-standard#1246]
In FMI2.0 there were no mandatory attributes for any variable type. So no problem then.
Now, for clock variables there is a problem:
If a clock variable refers to a declared type, this declared type must contain the mandatory attributes "clockType" and "priority".
But the variable itself must provide for these attributes as they are mandatory here as well.
This means, the attributes "clockType" and "priority" can never be taken from the declaredType.
In order to achieve that the had to be optional in both declared type and variable definition, but must be preset in at least one location.
I guess, that's impossible to describe in an XSD.
How shall we proceed here?

**Comment by GHannesen** [comment]
My proposal is to simply remove the mandatory attributes from the **typedefinition ClockType** in order to avoid confusion.
The attribute 'priority' doesn't make sense there anyway.
And it will not be so painful, if the user has to specify the attribute 'clockType' in every clock referring to the declaredType.
Opinions?

**Comment by andreas-junghanns** [comment]
`clockType` is removed, `priority` is now only in `fmi3ClockAttributes`.
Please check if this addresses the issue you raised.
This issue will be closed automatically when #1272 is merged.
