### ISSUE TITLE
event mode lists exit initialization mode as allowed function calls

### ISSUE THREAD

**Issue by KarlWernersson** [modelica/fmi-standard#1250]
In the current standard in envet mode it lists

Allowed Function Calls
Function fmi3ExitInitializationMode
When the Initialization Mode is terminated with fmi3ExitInitializationMode, then Event Mode is directly entered, and the continuous-time and discrete-time variables at the initial time are computed based on the initial continuous-time states determined in the Initialization Mode.

But this function can only be called to transition to this mode, it is not allowed to be called in event mode.

**Comment by andreas-junghanns** [comment]
We have started a PR that also fixes this (not even draft yet).
