### ISSUE TITLE
Malplaced co-simuation comment in event mode

### ISSUE THREAD

**Issue by KarlWernersson** [modelica/fmi-standard#1251]
In  2.3.2.1 https://fmi-standard.org/docs/3.0-dev/#EventMode
between allowed function call fmi3ExitInitializationMode (error covered in #1250 )
and  fmi3UpdateDiscreteStates

the following text is misplaced

The co-simulation algorithm and the FMU enter this state when the co-simulation algorithm calls fmi3EnterEventMode in state Step Mode, in order to handle discrete events and clock ticks. If the co-simulation algorithm signals eventModeUsed == fmi3False during instantiation, the co-simulation algorithm is not allowed to call fmi3EnterEventMode.

The placement is verry strange, and it only talks about co-simulation in a text about the unified (ME-CS) state

**Comment by andreas-junghanns** [comment]
I removed these sentences - they are not only misplaced, but redundant because this is described elsewhere better. See PR #1263.
