### ISSUE TITLE
Table 7. structural parameter with variability constant

### ISSUE THREAD

**Issue by KarlWernersson** [modelica/fmi-standard#1253]
Structural parameters with variability constant is  ~~allowed~~. (edit)
Example arrays with constant dimensions.

This is missing in table 7 and subsequent unnumbered table  (Discussion of the combinations that are allowed) is missing this combination

**Comment by KarlWernersson** [comment]
Also in table six
the commination is both (exact), and forbidden (--)

**Comment by andreas-junghanns** [comment]
What would be the use for such a constant structural parameter? Documentation?
Would you not want a structural parameter to be at least fixed such that it makes sense to have it?
I agree, a small non-normative text should be added as footnote.

**Comment by andreas-junghanns** [comment]
> 
> 
> Also in table six
> the commination is both (exact), and forbidden (--)

We have started a PR that also fixes this (not even draft yet).

**Comment by KarlWernersson** [comment]
Sorry my bad, I was thinking on the dimension of arrays with constant sizes, but they reference constant variables directly instead of a "structural constant". So no it should not be allowed, however the table still need to be fixed.

I.e add an (a) in table seven for constant structural parameter, and update (a) in the table Explanation why this combination is not allowed
