### ISSUE TITLE
fmi3Set{VariableType} in initialization mode is over specified

### ISSUE THREAD

**Issue by KarlWernersson** [modelica/fmi-standard#1255]
In 2.3.1.2 fmi3Set{VariableType}
We lisst the allowed combinations 

For variables with:

- variability ≠ constant that have initial = exact, or

- causality = input, or

- causality = parameter and variability = tunable.

However 

- causality = parameter and variability = tunable.

is already covered by the first one 

- variability ≠ constant that have initial = exact

and should therefore be removed

**Comment by andreas-junghanns** [comment]
If we make inpts initial=exact (see #1244), then we can remove the 2nd condition as well, see #1260.
