### ISSUE TITLE
Move 2.2.9 "Getting Number of Event Indicators" to chapter 3 (ME)

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1259]
... as this is specific to ME and not common concept

https://fmi-standard.org/docs/3.0-dev/#_getting_number_of_event_indicators

**Comment by KarlWernersson** [comment]
Also the subsequent  2.2.10 Getting Number of States
https://fmi-standard.org/docs/3.0-dev/#_getting_number_of_states
