### ISSUE TITLE
Error in 5.2.1.3 of current FMI 3 spec 

### ISSUE THREAD

**Issue by iscopa** [modelica/fmi-standard#1270]
Hello,

I think the following statement in 5.2.1.3 is not correct

[...] _If an output clock with an attribute triggeredBy ticked, the scheduling algorithm schedules the model partition associated with the corresponding input clock._ []

Reason: Only an input clock can be "triggeredBy", so that the statement above should be reformulated, e.g.: If an output clock ticks and there is an input clock associated to that output clock (i.e. by the attribute triggeredBy), then the scheduling algorithm schedules the model partition associated to the corresponding input clock.

**Comment by andreas-junghanns** [comment]
@iscopa : thank you for the feedback - we are in the process of overhauling the entire clocks concept and will soon rewrite all related sections in the document. Please help us again AFTER this rewrite to spot such inconsistencies - thanks you!

**Comment by andreas-junghanns** [comment]
Please check #1272 if this is clear enough now. If you do not object, this issue will be closed automatically when #1272 is merged.
