### ISSUE TITLE
Fix typo in FMI 2.0.2

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1275]
On page 104

> Differents input variables may have different interpolation order

should be

> Different input variables may have different interpolation order

**Comment by chrbertsch** [comment]
Fixed in adoc and Word with https://github.com/modelica/fmi-standard/commit/fe4bc7b6e34a7cf63895d265f9ef6aac2ef77549 and  https://github.com/modelica/fmi-design/commit/c82e30ae7851a5698f18d615faab65a0faa066b5
