### ISSUE TITLE
Exclude *Configuration Mode* and *Reconfiguration Mode* from *FMU State Setable*

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1276]
We must not allow GetXXX function inside the configuration modes - there the state and the values of the variables are not clear because we are changing their dimensions.

Therefore, we either need to exclude the GetXXX calls inside these modes, or we exclude them from the current super state.

Proposal: We move *Configuration Mode* and *Reconfiguration Mode* outside of *FMU State Setable* (much like *Intermediate Update Mode*).

**Comment by andreas-junghanns** [comment]
Reminder: check if certain function groups could be moved up to super state *FMU state setable* after that move.

**Comment by KarlWernersson** [comment]
would that include not allow calls to set/getMFUState ?

**Comment by andreas-junghanns** [comment]
> 
> 
> would that include not allow calls to set/getMFUState ?

That is exactly why we propose this change.
