### ISSUE TITLE
Fix use of fmi2GetEventIndicators for Initialization Mode

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1277]
fmi2GetEventIndicators can be called in Initialization Mode according to 3.2.3.

But it is missing in the mathematical description of Initialization Mode and in Table 1.

**Comment by andreas-junghanns** [comment]
Fix fmi2GetNominalsOfContinuousStates in Model Exchange table of allowed function calls for *Initialization Mode* (allow like in state machine).

**Comment by chrbertsch** [comment]
> fmi2GetEventIndicators can be called in Initialization Mode according to 3.2.3.
> But it is missing in the mathematical description of Initialization Mode and in Table 1.

@andreas-junghanns: Shall we change in Table 1  `fmi2getXXX, fmi2getContinuousStates`  to `fmi2GetINIT, fmi2GetDerivatives, fmi2GetEventIndicators`  (with a reference for INIT to the definition in the state machine)
![grafik](https://user-images.githubusercontent.com/16363372/104126949-adee3480-535f-11eb-9e2e-aa4b0e5012ac.png)

what is fmi2getXXX anyway? is it somewhere defined? Is XXX = {Real, Integer, Bool, String}? Or is XXX = X in the sense of the state machine 
![grafik](https://user-images.githubusercontent.com/16363372/104127210-1853a480-5361-11eb-8c58-41f93e0dec2d.png)

**Comment by andreas-junghanns** [comment]
@TorstenBlochwitz : Do you have any preference how this should be done?

**Comment by chrbertsch** [comment]
Closed with #1318
