### ISSUE TITLE
Allow fmi3GetXXX in super state FMU State Setable

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1278]
In FMI 2.0 fmi2GetXXX is not allowed in *Instantiated*, but allowed in all other states.
Exception: fmi2GetNominalsOfContinuousStates is allowed - seemingly inconcistently (see #1277).

We propose to simplify and imporve consistency, to allow all fmi3GetXXX functions also in super state *FMU State setable*, which includes *Instantiated*.

**Comment by chrbertsch** [comment]
OK for me.

What might have been a reason of forbidding  `fmi2GetXXX ` in _Instantiated_? That the values might change in _initialization_? But the importer knows the current statemchine state and can deal with this.

**Comment by KarlWernersson** [comment]
Are we doing computations in instantiated? 
With a get call I assume that any values set will be used to compute the new output/calcualtedparameters/locals.
This should preferably be done in initialization mode, so we don't get two initialization modes.
If we don't allow new computations in instantiated, what's the point?
It might also be difficult as an exporter might not store start values for for the computed varaibles and will need a computation to get them.

So I don't like this idea.

The case i would support is to call get on variables with initial=exact and intiial=aprox (i.e those variables that can be set)

**Comment by pavel-grozman** [comment]
Från: KarlWernersson <notifications@github.com>
Skickat: den 15 januari 2021 11:46
Till: modelica/fmi-standard <fmi-standard@noreply.github.com>
Kopia: Subscribed <subscribed@noreply.github.com>
Ämne: Re: [modelica/fmi-standard] Allow fmi3GetXXX in super state FMU State Setable (#1278)


Are we doing computations in instantiated?
With a get call I assume that any values set will be used to compute the new output/calcualtedparameters/locals.
This should preferably be done in initialization mode, so we don't get two initialization modes.
If we don't allow new computations in instantiated, what's the point?
It might also be difficult as an exporter might not store start values for for the computed varaibles and will need a computation to get them.

So I don't like this idea.

The case i would support is to call get on variables with initial=exact and intiial=aprox (i.e those variables that can be set)

**Comment by andreas-junghanns** [comment]
We agree with @KarlWernersson here and leave as is in FMI 2.0.
