### ISSUE TITLE
Should it be allowed to call fmi3GetOutputDerivatives in *Intermediate Update Mode*?

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1280]
@TorstenBlochwitz is supporting such a change.

**Comment by chrbertsch** [comment]
I think this makes sense. E.g., in order to create an extrapolation/interolation polynomial, the importer can make use of any information it can get from the FMUs, also output derivatives.

If the there are no objections (especially from @clagms , @klausschuch  or @friedrichatgc ), I will create a PR.

**Comment by andreas-junghanns** [comment]
> I think this makes sense. E.g., in order to create an extrapolation/interolation polynomial, the importer can make use of any information it can get from the FMUs, also output derivatives.
> 
> If the there are no objections (especially from @clagms , @klausschuch or @friedrichatgc ), I will create a PR.

Massive changes are pending in #1272. Maybe you want to wait until @TorstenBlochwitz and I are done to avoid merge conflicts?

**Comment by chrbertsch** [comment]
fmi3CallbackIntermediateUpdate has the argumment intermediateVariableGetAllowed.
So calling fmi3GetOutputDerivatives only should be allowd, if intermediateVariableGetAllowed==true.
But shall it then always be allowed to be called, or do we need a new argument of fmi3CallbackIntermediateUpdate or capability flag to allow it?

**Comment by TorstenBlochwitz** [comment]
I don't think, we need another capability flag. If derivatives can be provided after fmi3DoStep, they can be computed in IntermediateUpdateMode too.
