### ISSUE TITLE
Allow early return from fmi3DoStep for non-event-related reasons

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1283]
We propose to allow early return also for non-event-related reasons, such as requesting a communication point because of maxima reached that would be missed or to prevent model violations due to illegal extrapolated values to inputs.

If an importer does not support *Event Mode* but allows early return, this needs to be signaled.
Therefore we propose to add earlyReturnAllowed as argument to fmi3InstantiateCoSimulation.

**Comment by chrbertsch** [comment]
Already included with https://github.com/modelica/fmi-standard/pull/1272/commits/3925c80811ebb48c8444ef33277dba5791bf94f3  in PR https://github.com/modelica/fmi-standard/pull/1272
