### ISSUE TITLE
v_rest in partial derivatives unclear

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1285]
Please make sure the text and all restrictions to knowns and unknowns in the text are consistent.
Especially w.r.t. parameters.

Please wait until #1272 has been merged.

**Comment by andreas-junghanns** [comment]
v_{rest} is now explained well in #1272.
Closing since the 10 linked-issues limit is reached.

**Comment by chrbertsch** [comment]
As v_known are clearly defined in dependencies (https://fmi-standard.org/docs/3.0-dev/#dependencies), and the v_unknowns are defined for each state in https://fmi-standard.org/docs/3.0-dev/#partial-derivatives, isn't it possible to define the v_Rest as "all the other variables" and just provide few examples?

**Comment by KarlWernersson** [comment]
Hm the text is a bit messy and not completely correct.
If I understand it correctly
v_known here are (for continuous time mode) the continuous time input and the continuous time states, i.e the variables that you can use to get the partial derivatives. v_rest are the variables that cannot be used but is part of the dependencies as the affect the function when they are set, so for continuous time mode that would includes any discrete input that affect the function, i.e. discrete real, Boolean integer string etc.

The confusion in the text  is that v_known are stated to be defined in the dependencies but the dependencies includes both v_known and v_rest.

I'm not exactly sure how to write it.
But unless I am missing something.

for continuous time mode, v_rest are any discrete input.
for event mode and step mode, v_rest are any non real input

**Comment by andreas-junghanns** [comment]
WEB design meeting: @chrbertsch will make a proposal for the PR.
