### ISSUE TITLE
start value definition in XSD

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1289]
Why do we define the start values as follows:
				<xs:attribute name="min" type="xs:long"/>
				<xs:attribute name="max" type="xs:long"/>
				<xs:attribute name="start">
					<xs:simpleType>
						<xs:list itemType="xs:long"/>
					</xs:simpleType>
				</xs:attribute>
and not fold the type in as for min/max?
Currently, the images exported do not show the type for the start attribute.

**Comment by pmai** [comment]
The start value is not just a single value, it is/can be a list of values, to support arrays. Hence the types are different. Or am I missing something?

**Comment by andreas-junghanns** [comment]
Ah!!
