### ISSUE TITLE
Define allowed Variable Types for Structural Parameters

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1293]
or maybe just require it to be `UInt64`?

see also #843

**Comment by andreas-junghanns** [comment]
We should restrict the type of structural parameters only if they are referenced in a Dimension element and then we should restrict the types to any of the unsigned integer types (uint64 might not be supported in certain platforms).
There might be structural parameters used only internally to the FMU to compute dimensions (e.g. a frequency to define an internal buffer length).

@klausschuch : can you provide a PR for this?

**Comment by pmai** [comment]
> We should restrict the type of structural parameters only if they are referenced in a Dimension element and then we should restrict the types to any of the unsigned integer types (uint64 might not be supported in certain platforms).

They are already restricted to UInt64, see section 2.4.7:

> Variable elements representing array variables must contain at least one <Dimension> element. Each <Dimension> element specifies the size of one dimension of the array:
> 
> * If the start attribute of the <Dimension> element is present, it defines a constant unsigned 64-bit integer size for this dimension. The variability of the dimension size is constant in this case.
> 
> * If the valueReference attribute of the <Dimension> element is present, it defines the size of this dimension to be the value of the variable with the value reference given by the valueReference attribute. The referenced variable must be a variable of type **UInt64**, and must either be a constant (i.e. with variability = constant) or a structural parameter(i.e. with causality = structuralParameter). The variability of the dimension size is in this case the variability of the referenced variable.
> 
> These two options are mutually exclusive, i.e., for each <Dimension> element either a start attribute or a valueReference attribute can be supplied, but not both. However different dimension sizes can be specified using different mechanisms and can have differing variability attributes.

So I would close this issue as moot... (We also standardized on UInt64 for dimensions and enums, so I don't think we need to be more lenient for structural parameters).

**Comment by andreas-junghanns** [comment]
WEB Design Meeting: already restricted in the text - but hidden somewhat. We should reduce redundancy in definition and move all to a single place with references points to this.
