### ISSUE TITLE
Does {VariableType} include Clocks?

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1296]
In https://fmi-standard.org/docs/3.0-dev/#_how_to_read_this_document, it is not clear if {VariableType} e.g. in https://fmi-standard.org/docs/3.0-dev/#_how_to_read_this_document fmi3get{VariableTypes} includes clocks or not.
As clocks are variables, I would read it as "yes".
But, e.g., in https://fmi-standard.org/docs/3.0-dev/#EventMode we list fmi3Set{VariableType} and fmi3SetClock  as different allowed function calls.

**Comment by andreas-junghanns** [comment]
As described in "2.2.6.2. Getting and Setting Variable Values", we include Clocks into VariableTypes. See also "1.4. How to Read This Document".

We have included SetClock and GetClock in the table when they need specific explanations.
Not quite consistently, we sometimes also have both in the same cell. We will remove such duplications.

I will, however, add xrefs for all these mentions of {VariableType} to the 1.4 section mentionend above.

**Comment by andreas-junghanns** [comment]
... in addition to that, see Table 3 for definitions of d and k.

**Comment by chrbertsch** [comment]
In SE clockActivationMode: Is setClock/getClock allowed and does it make sense? Currently I read it, that clocks are activated via the fmi3ActivateModelPartitions call, and the fmi3getClock is called in IntermediateUpdateMode, not in ClockActivationMode

**Comment by andreas-junghanns** [comment]
> 
> 
> In SE clockActivationMode: Is setClock/getClock allowed and does it make sense? Currently I read it, that clocks are activated via the fmi3ActivateModelPartitions call, and the fmi3getClock is called in IntermediateUpdateMode, not in ClockActivationMode

@IZacharias and @MBlesken are still working on some of the details for clocks in SE.
Let´s give them a moment until they declare to be done with their edits.

**Comment by chrbertsch** [comment]
In SE in IntermediateUpdateMode, getClock calls are not just "get Clock variable" calls, but modify the clock variable: 

> For an output clock only the first call of fmi3GetClock for a specific activation of this clock signals fmi3ClockActive. The FMU sets the reported activation state immediately back to fmi3ClockInactive for following fmi3GetClock calls for that clock until this output clock is activated again.

I do not understand this, and for me this would be a reason not to include clocks in fmi3get{variableTypes} calls. 
@IZacharias and @MBlesken : will this special behavior of getClock remain?

**Comment by IZacharias** [comment]
> In SE clockActivationMode: Is setClock/getClock allowed and does it make sense? Currently I read it, that clocks are activated via the fmi3ActivateModelPartitions call, and the fmi3getClock is called in IntermediateUpdateMode, not in ClockActivationMode

In SE setClock is not used at all. 
getClock is not allowed in ClockActivationMode, and is used in IntermediateUpdateMode for Output Clocks only.

**Comment by IZacharias** [comment]
> In SE in IntermediateUpdateMode, getClock calls are not just "get Clock variable" calls, but modify the clock variable:
> 
> > For an output clock only the first call of fmi3GetClock for a specific activation of this clock signals fmi3ClockActive. The FMU sets the reported activation state immediately back to fmi3ClockInactive for following fmi3GetClock calls for that clock until this output clock is activated again.
> 
> I do not understand this, and for me this would be a reason not to include clocks in fmi3get{variableTypes} calls.
> @IZacharias and @MBlesken : will this special behavior of getClock remain?

Yes, we need this behavior, and we see no other suitable time at which the value could be reset. 
getClock is used for Output Clocks only. It must be ensured that the ticking is not accidentally signaled twice for the same clock tick, e.g. because the execution of the IntermediateUpdateFunction is interrupted by a different task that also calls the IntermediateUpdateFunction.

**Comment by chrbertsch** [comment]
Webmeeting: define a shorthand fmi3Get{VariableTypeWithoutClocks} and fmi3Set{VariableTypeWithoutClocks} for SE

**Comment by andreas-junghanns** [comment]
This was linked to an excepted PR - but more work needed...
