### ISSUE TITLE
if importer must call fmi3GetInterval, do so just before exiting Event Mode?

### ISSUE THREAD

**Issue by oliverkotte** [modelica/fmi-standard#1303]
In Event Mode, the FMU may know the next tick of a time-based (e.g. aperiodic changing) clock only after all event iterations and calls to fmi3UpdateDiscreteStates() have occurred. Should the standard explicitly state that if the importer must call fmi3getInterval(), it shall do so right before exiting Event Mode, i.e. between a call to fmi3UpdateDiscreteStates() that returned with discreteStatesNeedUpdate == fmi3False, and e.g. fmi3EnterStepMode()?

**Comment by andreas-junghanns** [comment]
This is no different to any other fmi3Get call: Only when leaving the Event Mode will the FMU have the final value for that time.
Why do you think this requires special mention for fmi3GetInterval?

**Comment by oliverkotte** [comment]
I was not aware that fmi3GetInterval is no different to any other fmi3Get call (it makes of course sense).
So the question becomes where exactly is this mentioned in the standard? Interval (and Shift) are not of {VariableType} thus getInterval (and getShift) are not covered by 2.2.6.2.

**Comment by chrbertsch** [comment]
The fmi3GetInterval functions are explicitely listed as "Allowed Function calls" in event mode (see https://fmi-standard.org/docs/3.0-dev/#EventMode) . So they are not assumed to part of fmi3Get{VariableType}. 
I understand your comment, @oliverkotte , that you want to prescribe a certain point in the calling sequence  (just before leaving event mode). when the fmi3GetIntervalXXX function muss be called. And you, @andreas-junghanns say that this is clear.
 
So should we have at least an explanation (non normative?) about this? Could you suggest wording?
And we urgently need examples for the calling sequence of for CS FMUs with clocks!

**Comment by TorstenBlochwitz** [comment]
fmi3GetInterval is not different to fmi3Get calls like fmi3GetDerivative, fmi3GetEventIndicators and others. The equation fEvent indicates the dependencies and indicates what needs to be done: As it is now, the return argument Tinterval of fmi3GetInterval depends on the right-hand (RHS) side of fEvent. Hence, the importer should set all elements of the RHS if it is interested in a consistent result of fmi3GetInterval. This is the same for all fmi3Get functions.

According to this and as it is now, we do not enforce to call call it after a fmi3UpdateDiscreteStates call, or just before leaving Event Mode.

We should discuss, if this is is necessary and if yes think about a clear way how to express it.

**Comment by oliverkotte** [comment]
we are currently exploring this motif/sequence:
```
FMU1                                FMU2
===================                 ==================
aperiodic changing input clock
triggered output clock         ->   triggered input clock
triggered input clock          <-   triggered output clock
```

- Importer activates aperiodic changing input clock of FMU1, pushes FMU1 in EventMode
- FMU1 does computations and activates at same time instant a triggered output clock connected to a triggered input clock of another FMU2
- Importer activates triggered input clock of FMU2 at that time instant, pushes FMU2 in EventMode
- FMU2 does computations and activates at same time instant a triggered output clock connected to a triggered input clock of FMU1
- Importer activates triggered input clock of FMU1
- FMU1 does computations and only after these, as it is ready to leave EventMode (signaled by discreteStatesNeedUpdate=false), knows the next Interval
- Importer calls getInterval() and EnterStepMode() on FMU1, and EnterStepMode() on FMU2

When trying to write down the corresponding sequence diagram of FMI calls, this issue surfaced.

**Comment by andreas-junghanns** [comment]
WEB design meeting: @TorstenBlochwitz and @andreas-junghanns will turn this into a PR to restrict computation of T_{interval} in fmi3UpdateDiscreteState.
