### ISSUE TITLE
Intermediate update time in SE = modelPartition Activation time?

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1308]
According to https://fmi-standard.org/docs/3.0-dev/#advancing-time, "time in SE has a more discrete form". 
To my understanding, the activation of a certain modelPartition corresponds to a discrete point of time. 
And at least for non-realtime simulation, during the evaluation of the model partition it stays at this simulation time.

Now what happens, if this model partition invokes fmi3CallbackIntermediateUpdate? Which time can the argument intermediateUpdateTime have? must it be the time of the modelPartition activation? Or can it be a later point of time?
If time is discrete for a modelPartitionActivation to my understanding the intermediateUpdateTime must be equal to the model activation time and cannot be a later point of time. Is this correct? Then we should explicitly state this

**Comment by andreas-junghanns** [comment]
The FMU has control over its internal time computation and for plant models using SE, the FMU might indeed advance time internally. For real-time applications, it might be wall-clock time.

I suggest to not restrict the values of intermediateUpdateTime other than it has to be equal or greater than activationTime of fmi3ActivateModelPartition.

**Comment by andreas-junghanns** [comment]
@IZacharias and @MBlesken : Please comment today if possible so we can discuss this in our meeting today.

**Comment by chrbertsch** [comment]
> The FMU has control over its internal time computation and for plant models using SE, the FMU might indeed advance time internally. 

I still did not understand the mathematical model of of SE
Clocks in ME and CS correspond to events and disrete times.
But do I understand the above comment correctly, that in SE, the modelPartitionActivation and the activationTime do not correspond to a discrete time point for this model partition, but only passes the discrete time point of the activation and then control and advancement of time is in the control of this model partition.
But then we must explain this  more clearly! And the clocks in SE have a completely different meaning than in CS ME (was this the idea of the "communication point clocks?" Perhaps we should call them "modelPartitionActivationClocks")

In 5.1 "Model partitions that are associated to output clocks will accordingly provide the result values of the model partition’s variables for the current output clock tick time ti of the active output clock. The activation of such an output clock is not controlled by the simulation algorithm but internally by the FMU."
we should not use the same t_i that is used to explain the input clock, but use a different symbol (t_o?) for the output clock (with t_0>=t_i)

**Comment by andreas-junghanns** [comment]
Please have a look at Figure 46, "Scheduled Execution Example ThreeInputClocks".
@MBlesken is contemplating to add an output clock as well, but for now, the clocks in the figure are an excellent example.

While the activation time is discrete and has no period (contrary to doStep), the run-time of the tasks is not 0 and clocks activating other tasks happen "later". You can see preemption there and delayed execution... very, very educational (thanks again to @MBlesken!). What intermediateUpdateTime to use the moment the OutClock ticks, is up to the FMU. If the FMU does not have a "sense of time" (most RTOS tasks only know about how often they where called and the cycle time), it could create a synthetic time guaranteed to always increment.

Output clocks and t_o: this would be confusing, I think. An output clock has no idea about the activation time of the task it got triggered from and therefore the relationship you suggest only exists in very simple examples and does not really help explain. Worse, it might suggest a restriction that does not exist. Please have a look into RTOS implementations, very nice open source implementations exist (multiple, easy to find) - these explain in more detail what Figure 46 illustrates.

Meaning of clocks: The break-through in Fall was that we do not attach specific semantics to the FMI clocks mechanisms. And that is why the current clock mechanisms should work for ME, CS and SE, even if they have different semantics.

**Comment by chrbertsch** [comment]
> Please have a look at Figure 46, "Scheduled Execution Example ThreeInputClocks".

This is very clear for a realtime system with preemption etc . But for a non-realtime system ;  I thought model-partition execution time for non-realtime system as being abstracted to "zero execution" time, which does not seem to be the intention necessarily

> Output clocks and t_o: this would be confusing

this _is_ already confusing, because we use t_i for the activation time of the model partition, so we must make it clear that the clock tick time of the output clock (currently also denoted t_i) does not have be the same.

**Comment by chrbertsch** [comment]
Webmeeting: in the definition of fmi3CallbackIntermediateUpdate we need and explanation of intermediateUpdateTime  for SE

**Comment by MBlesken** [comment]
> I suggest to not restrict the values of intermediateUpdateTime other than it has to be equal or greater than activationTime of fmi3ActivateModelPartition.

@chrbertsch I think @andreas-junghanns suggestion could be the solution here. @IZacharias do you agree? (I.e. We could include this in PR #1309.)

**Comment by chrbertsch** [comment]
>I suggest to not restrict the values of intermediateUpdateTime other than it has to be equal or greater than activationTime of fmi3ActivateModelPartition.

This is fine. 
However, I still do not understand the timing concept of SE for non-realtime applications.
What happens, if a model partition gets activated, then internally in this partition (simulation) time gets increased, and then a get{VariablesTyp} functions is called. What simulation time does the output belong to? that of the activation, or some unknown internal simulation time? 
And what if the intermediateUpdate Callback got called inbetween (providing a new intermediate update time to the master)

**Comment by MBlesken** [comment]
>> I suggest to not restrict the values of intermediateUpdateTime other than it has to be equal or greater than activationTime of fmi3ActivateModelPartition.

>This is fine.

Done: commit [40a09d4](https://github.com/modelica/fmi-standard/pull/1309/commits/40a09d4791b1077c241f7bace137e5ca8fdded6a) in #1309

**Comment by MBlesken** [comment]
> However, I still do not understand the timing concept of SE for non-realtime applications.
What happens, if a model partition gets activated, then internally in this partition (simulation) time gets increased, and then a get{VariablesTyp} functions is called. What simulation time does the output belong to? that of the activation, or some unknown internal simulation time?
And what if the intermediateUpdate Callback got called inbetween (providing a new intermediate update time to the master)

@chrbertsch the simulator has to define a concept on how to advance time which is consistent for all the parts that have to be simulated in a system. An FMU being part of this system has to be included. If the simulator is not a real time a simulator it makes sense to define the simulation time as not proceeding during the computation of a task but only discontinuously with each (periodic) task activation. If you like we can discuss this personally, maybe including @andreas-junghanns and @IZacharias.

**Comment by andreas-junghanns** [comment]
WEB meeting: we should clarify (better) what the role of intermediateUpdateTime argument of fmiCallback3IntermediateUpdate() is during SE, especially in non-real-time applications.
