### ISSUE TITLE
Mechanism for FMU in Event Mode to communicate output clock tick to importer

### ISSUE THREAD

**Issue by oliverkotte** [modelica/fmi-standard#1310]
Neither of the two mechanisms for an FMU to communicate to the importer that a triggered output clock is about to tick
- early return from a fmi3DoStep with clocksAboutToTick == fmi3True, and

- calling fmi3CallbackIntermediateUpdate with clocksTicked == fmi3True

applies in EventMode. How to communicate to the importer that a triggered output clock ticks in Event Mode, so that the importer calls getClocks() on the FMU and gets to know about the clock tick?

In the motif below, FMU2...
1. gets pushed in Event Mode by the importer
2. gets its triggered input clock activated by the importer
3. runs updateDiscreteStates
4. wants to activate its output clock and communicate this to the importer - but how?

```
FMU1                                FMU2
===================                 ==================
aperiodic changing input clock
triggered output clock         ->   triggered input clock
triggered input clock          <-   triggered output clock
```

**Comment by andreas-junghanns** [comment]
WEB design meeting: all outputs can change after fmi3UpdateDiscreteStates - so you have to call fmi3GetXXX, including clocks.

**Comment by andreas-junghanns** [comment]
WEB design meeting: @oliverkotte and @clagms will provide a PR to clarify this in 2.2.9.2

**Comment by oliverkotte** [comment]
After some thought, I propose to **move the boolean return argument clocksAboutToTick from the doStep() to the updateDiscreteStates() method**. Reasoning:

Currently, when an FMU wants to communicate to the importer that its output clocks tick, it can do so only outside of Event Mode. The importer would first push the FMU in Event Mode, then call getClocks(). For reference, Section 2.2.9.2 currently reads:

> **Triggered output clocks**
> 	are activated within the FMU and the importer must call fmi3GetClock in Event Mode. There are two mechanisms for an FMU to communicate to the importer that a triggered output clock is about to tick:
> 		○ early return from a fmi3DoStep with clocksAboutToTick == fmi3True, and
> 		○ calling fmi3CallbackIntermediateUpdate with clocksTicked == fmi3True

(by the way, is the restriction 'early return' in the first mechanism really correct?)

But we have a use case where an FMU is essentially an event filter: The FMU internally ignores most triggered input clock ticks, but some of those ticks cause a triggered output clock to tick in super-dense time. Because the FMU determines in Event Mode during updateDiscreteStates() if its output clock shall tick, a third mechanism is needed with precondition FMU in Event Mode. 

My first idea for such a mechanism was adding a third bullet point to the above,
 * fmi3UpdateDiscreteStates returns with nextEventTimeDefined == fmi3True and nextEventTime equal to the current time.
 
But this is dirty because not all events are clock ticks.

My second idea was to add the same clocksAboutToTick flag that doStep() has also to updateDiscreteStates(). This would make it explicit what shall be communicated.

But once clocksAboutToTick is a return argument of updateDiscreteStates(), doStep() does not need it anymore. The doStep() method has an eventEncountered flag, which the FMU can raise to have the importer push it in Event Mode. Once in Event Mode, getClocks() will be called after updateDiscreteStates(), so a clocksAboutToTick flag there would suffice. And there, it should probably be called clocksTicked to be in line with the flag for fmi3CallbackIntermediateUpdate().

To me, this makes sense: Because there are quite some calls in between doStep() and getClocks(), moving the point where the FMU tells the importer about its output clock ticks to just before the getClocks() call opportunity will additionally cover those use cases (such as ours) where the decision to activate clocks happens after doStep(). 
 
@clagms, @andreas-junghanns, @TorstenBlochwitz, @chrbertsch: What is your opinion, am I misunderstanding something?

**Comment by andreas-junghanns** [comment]
@oliverkotte : Agree, partially. But maybe I am missing things?

clocksAboutToTick is an optimization that helps reduce useless calls to getClock() by the importer in case no clock ticks in the FMU.
I agree it would also help as return argument in fmi3UpdateDiscreteStates() to reduce useless getClock() calls in subsequent instants of super-dense time.
But: getClock() must be called at the beginning of *each* super-dense time instant - also the first.
Therefore I think we should keep it for doStep() to have the optimization also work for the first instant of super-dense time.

**Comment by KarlWernersson** [comment]
We do have that functionality.

When updateDiscreteStates return discreteStatesNeedUpdate == true
In that case then FMU must do another event iteration that would include calling get clock on all clocks.

What we don't have is the possibility to separate clocks from other events at this subsequent call, as we do in doStep. Moving it from dostep to updateDiscreteStates will not fix that only move the problem over there.

So we should either remove the argument form doStep, or add one for updateDiscreteStates.

As you point out, the event eventEncountered / discreteStatesNeedUpdate booth signal that you need another call to updateDiscreteStates , as do clocks about to tick.
The only difference is that if the second is false the importer could safely ignore calling getClock.
However I don't se that that would make any significant performance update so it seems a bit over engineered to me. 

So I would propose remove clocksTicked argument in doStep, it is sufficient with eventEncountered / discreteStatesNeedUpdate and that the user should call getClocks on all output clocks in these situations.
If I remember correctly the separation was needed for scheduled execution but doesn't use do step function anymore. 

If we keep it we should add a similar flag for updateDiscreteState for symmetry and the reasons you described above.

**Comment by oliverkotte** [comment]
I suggest that I open a PR to remove clocksTicked from doStep(), as Karl proposed, and also adapt section 2.2.9.2. and section 2.3.3. To my understanding, clocksTicked shall remain an argument of CallbackIntermediateUpdate because it is needed for Scheduled Execution. Or does someone think performance gains warrant the other option of keeping clocksAboutToTick in doStep() and also adding it to UpdateDiscreteStates()?

To support Karl's proposal: I have another FMU with one aperiodic changing input clock and many triggered output clocks. Whenever the aperiodic clock ticks, at least one output clock ticks. The aperiodic clock is as a way for the FMU to 'guide' the importer to doStep exactly to the time instants where output clock ticks will occur.

First, this motif implies that the first mechanism in 2.2.9.2. for an FMU to communicate to the importer that a triggered output clock is about to tick would be too restrictive:
* early return from a fmi3DoStep with clocksAboutToTick == fmi3True

should be changed to
* return from a fmi3DoStep with clocksAboutToTick == fmi3True

because earlyReturn need not be True for clocksAboutToTick (in Co-Simulation).

Second, with this motif, the FMU returns from doStep() knowing that one of its clocks is aboutToTick, but it does not yet know which. The clocks that will tick are determined in UpdateDiscreteStates(). So the very first call to getClocks() returns all ClocksInactive, it is only the second call to getClocks() that returns the proper activations. In this case, should doStep() return with clocksAboutToTick set to True or False? To call getClocks() only when necessary, doStep() should return False, and UpdateDiscreteStates() should return True. But semantically this seems a bit odd to me: When returning from doStep() in Step Mode, the FMU knows some of its clocks are about to tick in Event Mode, but they tick later in super-dense time so it would be better not to say so.

Lastly, I was/am confused with the order of get/set/update in Event Mode. Where exactly is this defined in the standard?

**Comment by clagms** [comment]
@oliverkotte I sent you an email to try to arrange a meeting to discuss this.
It's hard to understand whether what you're pointing out is a true limitation, or just the need to optimize stuff.

There's also some misunderstanding on this:
>Second, with this motif, the FMU returns from doStep() knowing that one of its clocks is aboutToTick, but it does not yet know which. The clocks that will tick are determined in UpdateDiscreteStates(). So the very first call to getClocks() returns all ClocksInactive, 

When you enter event mode for the first time, the FMU should already know which clock will tick, so the following is incorrect: "So the very first call to getClocks() returns all ClocksInactive".

**Comment by clagms** [comment]
Summary from meeting with @oliverkotte :

The problem: In co-simulation, when an FMU returns  clocksAboutToTick == fmi3False, and eventEncountered==fmi3True, the importer will push the FMU into event mode, and eventually call fmi3UpdateDiscreteStates(). 
If discreteStatesNeedUpdate==fmi3True, then the importer will do a second event iteration, and so on.
In the first event iteration, because the flag clocksAboutToTick==false, the importer does not need to call getClock on any of the FMU output clocks.
But in the second iteration, the importer needs to call getClocks on all FMU output clocks.

@andreas-junghanns' take: I agree that clocksAboutToTick would also help as return argument in fmi3UpdateDiscreteStates() to reduce useless getClock() calls in subsequent instants of super-dense time. But we must not remove clocksAboutToTick from doStep, for performance reasons.

@KarlWernersson 's take: I would propose remove clocksTicked argument in doStep, it is sufficient with eventEncountered/discreteStatesNeedUpdate and that the user should call getClocks on all output clocks in these situations.
If I remember correctly the separation was needed for scheduled execution but doesn't use do step function anymore.
So, remove clocksAboutToTick from doStep.

@clagms  & @oliverkotte  take: We're with @KarlWernersson . 

Conclusion: 
- @oliverkotte  will create a PR implement @KarlWernersson 's take, just so that everyone understands in concrete what is proposed.
- we need to discuss which of the two alternatives should be implemented.

**Comment by andreas-junghanns** [comment]
Let´s be clear:
 - having `clocksAboutToTick` is only improving performance (if false, save a few calls, for clever implementations only one call!).
 - if we do not have `clocksAboutToTick`, you need to call getClock on all clocks, just like you must call fmi3Get{VariableType} for all other variables.

To be consistent, we should have `clocksAboutToTick` in both doStep() and updateDiscreteStates, or have it in neither of those functions.

Removing the return argument from doStep simplifies the API and the potential performance loss is minimal.
I agree with that simplification and look forward to your PR.
