### ISSUE TITLE
Mention intermediate alpha version in generated html docu

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1317]
Currently we have in the generatd html document that it is "alpha.5". However we have made many changes and people get confused. I suggest  that we mention, that this is an intermediate version "alpha.5 + changes" and print the generation date and/or latest git commit hash

**Comment by andreas-junghanns** [comment]
@t-sommer : can you explain how this is supposed to work without us changing the text mutliple times (alpha.x -> alpha.x´ ->alpha.x+y)?

**Comment by t-sommer** [comment]
The only clean solution would be to use a separate branch for development e.g. [GitFlow](https://nvie.com/posts/a-successful-git-branching-model/).

**Comment by t-sommer** [comment]
We could make that transition any time, e.g. when tag `v3.0-alpha.6`.

**Comment by andreas-junghanns** [comment]
but the result would be even more moving parts for the development people... to simply clarify when a release is finished.
Is the extra parts worth that? I vote no, simply because the machine already scares contributors off. Adding complexity will not help that more important issue of getting more people to get involved.

**Comment by chrbertsch** [comment]
Either we go for a very leightweight change, just changing 
![grafik](https://user-images.githubusercontent.com/16363372/108966038-fc406400-767d-11eb-9956-853dc3c9c6f8.png)
to "FMI 3.0alpha.5 + changes, generation date DD-MM--YYYY hh:mm:ss" or something like this (how could one include the generation date with an adoc command?)

Or we change to somthing like gitflow (which I would prefer): what would be the consequences?
E.g., do tickets automatically get closed when the are resolved by a merged PR to develop or only when later  merged from develop to master? @t-sommer : e.g. in the fmpy development tickets get closed when taken care of in develop, but there is no link to the commit

**Comment by chrbertsch** [comment]
Thinking about it, I agree with @t-sommer that we should follow the GitFlow approach: 
merge PRs into develop, prepare release branches and use master only for tagged (pre)releases (e.g., alpha.6)
Only few people create PRs and should be able to adopt the small change of merging into develop instead of master, and now that we go towards a release and get more stable, we get more consistent with the branches and can benefit from the Gitflow tooling implemented in git clients.

We could set the develop branch to be the Github default branch, so that we still could use the feature of automaticilly closing linked tickets when merging a PR into develop, see https://stackoverflow.com/questions/14858075/set-the-develop-branch-as-the-default-for-a-pull-request

**Comment by t-sommer** [comment]
@chrbertsch, can you add this to the agenda of the next Steering Committee Meeting?

**Comment by chrbertsch** [comment]
> @chrbertsch, can you add this to the agenda of the next Steering Committee Meeting?

It's already there :-) https://github.com/modelica/fmi-design/blob/master/Meetings/2021/2021-03-02-FMI-Steering.adoc#3-using-gitflow-branching-scheme

**Comment by beutlich** [comment]
You might want to reference https://trunkbaseddevelopment.com/ here.

**Comment by chrbertsch** [comment]
Decision by the Steering Committe today: We will follow the Gitflow branching scheme.
