### ISSUE TITLE
Unify granularity of headings and index

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1327]
While for some subsection we have very detailed  (numbered) headings and index entries (e.g. https://fmi-standard.org/docs/3.0-dev/#fmiTerminalsAndIcons: 
![grafik](https://user-images.githubusercontent.com/16363372/109610194-b62b4a80-7b2c-11eb-9624-7c96b3340ec3.png)
, for other (long and important) subsections like the definition of model variables we have almost none: 
![grafik](https://user-images.githubusercontent.com/16363372/109610389-f985b900-7b2c-11eb-964d-c414499ae2cb.png)

We should unify the granularity.

**Comment by andreas-junghanns** [comment]
Which way would you lean - rather too many TOC entries, or rather too few?

**Comment by chrbertsch** [comment]
> Which way would you lean - rather too many TOC entries, or rather too few?

I tend to more entries, as this helps me to navigate though the document.

Or the magician @t-sommer comes up with a concept of having two TOCs selectable:

- Pressing "t" overview TOC (up to third level)
- Pressing "f" full TOC (up to fifth level)

or something like this.

**Comment by andreas-junghanns** [comment]
WEB meeting: We should try to have 4 levels in the text, but show only three levels in the table of content.

We might have to tweak the TOC-generation script.

**Comment by chrbertsch** [comment]
Changing line https://github.com/modelica/fmi-standard/blob/deffed8fa807ae5020be46e44a761f712028657b/docs/docinfo.html#L76

to:             
`selectors: $( "#content" ).has( "h1" ).size() > 0 ? "h1,h2,h3,h4" : "h2,h3,h4,h5",`

reduces the TOC on the right side to 4 levels

**Comment by chrbertsch** [comment]
I started a draft PR #1332 

only headings up to level 3 get displayed, and some level 4 headings introduced for model variables.

Please review  and commit directly. 
Do we want to remove all level 5 headings?

**Comment by andreas-junghanns** [comment]
Let´s not remove level 5 headings - they do not hurt at all and we might decide to have a more flexible TOC in the future.

**Comment by chrbertsch** [comment]
As noted by @clagms ,  in #1332 I made a mistake in the heading level of the model variables 
![grafik](https://user-images.githubusercontent.com/16363372/110765085-19675c00-8254-11eb-9d37-7c8e51d8c059.png)

Proposal to to fix this: 
- make 2.4.8- 2.4.12 to level 4 headings  2.4.7.1 - 2.4.7.5

Should we then display in the TOC on the right side of the html display headings up to level 4 or leave it to level 3?

**Comment by clagms** [comment]
I've given a partial solution to this in https://github.com/modelica/fmi-standard/pull/1344
It currently applies the proposal by @chrbertsch:
> make 2.4.8- 2.4.12 to level 4 headings 2.4.7.1 - 2.4.7.5

On the following:
>Should we then display in the TOC on the right side of the html display headings up to level 4 or leave it to level 3?

I have no opinion. Feel free to edit the PR if a decision is made on this.

**Comment by chrbertsch** [comment]
I would leave the TOC level at 3 to be able to keep the overview, where there reader is in the document. 
#1344  can be merged from my side.
