### ISSUE TITLE
Unify capitalization of "Mock-up" vs. "Mock-Up"

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1337]
IMHO, it should be "Mock-up" (lowercase "u") since

- "mock-up" is one word
- the capitalization should correspond to the acronym "FMU"

Can the native speakers please give their opinion on this?

**Comment by andreas-junghanns** [comment]
(Warning, non-native speaker speaking)
For a long time, your reading was the consensus of the group.
However, the Logo uses -Up.
And eFMI also preferred the -Up version and after a quick check, we decided to go consistently with -Up.
I made those changes in the document for 3.0, I think.

Unless we want to open another round of (IMHO fruitless) discussion (read: both spellings are strange on their own ways), I suggest to make stick with the newly homogenised Functional Mock-Up Interface.

@TorstenBlochwitz : Please correct my historical memory, if you see fit.

**Comment by t-sommer** [comment]
Uppercase "Up" is also inconsistent with FMI 1.0 and FMI 2.0. Since FMI 3.0 has not been release yet, this is the right time to fix it.

**Comment by t-sommer** [comment]
> However, the Logo uses -Up.

No problem, I can fix that.

**Comment by andreas-junghanns** [comment]
> > However, the Logo uses -Up.
> 
> No problem, I can fix that.

This is the least of the problems: We agreed to use the same spelling with eFMI. We are not free to just do whatever anymore.
If we want to change that (again), then we have to find another agreement with the eFMI project.

And please: if we can´t even harmonise on something as simple as naming (note: not spelling), how hard would it be to harmonise on hard technical details. Can we please leave things as currently agreed on?

**Comment by chrbertsch** [comment]
Regular Design Webmeeting: 
Only "FMI" and the "FMI"-logo without text is trademarked (as descriptive names cannot be trademarked), so the trademark topic is not touched by this. 
not super-important to most of us, will be discussed and decide in the Steering Committee.
