### ISSUE TITLE
Move code examples to *.c files and compile in CI

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1340]
so the code gets validate (at least for syntactical correctness).

**Comment by andreas-junghanns** [comment]
@MBlesken : Can you try to extract your C-code examples to external files, please?

**Comment by t-sommer** [comment]
...or include them from the Reference FMUs.

**Comment by MBlesken** [comment]
> @MBlesken : Can you try to extract your C-code examples to external files, please?

> ...or include them from the Reference FMUs.

@t-sommer @andreas-junghanns ... but we are not having the pseudo code discussion again, are we? I think we settled this in #1116
