### ISSUE TITLE
Contradictory text on clocks and possible change in qualifier for partition

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#1348]
The following standard excerpts are in contradiction.

From 2.2.9.3. Model Partitions and Clocked Variables:
>The association between clocked variables and their clocks is defined by the model dependencies. Clocked variables can only depend on one clock.

From 2.4.8. Definition of the Model Structure:
>A clocked variable my depend on multiple clocks and may therefore be listed in multiple <Clock> elements.

I guess the actual intention is to relax the constraint, and let the importer decide whether it will support variables that are set by multiple clocks.
If that's the case, then we need to re-think the name "partition" for clocked/model partition, because it implies that:
1. Every variable belongs to one clock (this is not true in the standard, afaik;
2. A variable can only belong to one clock (this seems to not be true anymore).

I propose that we avoid using the term partition, and just call them "the variables set by clock C".

**Comment by chrbertsch** [comment]
> If that's the case, then we need to re-think the name "partition" for clocked/model partition, because it implies that:
> 
> 1. Every variable belongs to one clock (this is not true in the standard, afaik;
> 2.    A variable can only belong to one clock (this seems to not be true anymore).


I assiciate the name "model partition" to the equations of calculations of the model, not to the variables

**Comment by andreas-junghanns** [comment]
The onconsistency must be fixed - that is easy.
The reason to allow variables to belong to multiple clocks are global variables, e.g. states (like a counter incremented by multiple tasks in SE).

PR coming up.

Note: Current glossary entry of "model partitian" is consistent.
