### ISSUE TITLE
Clarify who is responsible for atomicity in SE

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#1359]
Current it is unclear who is responsible for ensuring atomicity in the get/set of clock and variables, in Scheduled Execution.

For instance, when a call is made to a GetReal, the standard specifies that the call must be atomic for a single variable. Is it the FMU that will lock/unlock preemption? Or the Importer?

Also, are we sure that the call must be atomic for a single variable? If a call to GetReal is part of computing some discrete time vector equation, e.g., `x = Ax`, where `x` is a vector and `A` a matrix, in task T1, it is probably a good idea that such read and write of multiple variables be atomic. Otherwise, half of the `x` may be updated by some other task, in the middle of reading `x` in T1.

**Comment by andreas-junghanns** [comment]
@MBlesken & @IZacharias : Could you please comment?
I think it would make sense to have the importer deal with concurrancy issues whenever possible, but maybe I am missing the point here and asking the FMU to use the callbacks to lock and unlock preemption is required to reduce locked code sections to a minimum?

**Comment by andreas-junghanns** [comment]
I looked at #1368 - atomicity is clearly not solved in the implementation of fmi3GetClock there.

@MBlesken & @IZacharias : Do you imply then that the importer must make sure that fmi3GetClock is not interrupted?

**Comment by IZacharias** [comment]
@andreas-junghanns @clagms @MBlesken Regarding the get and set of inputs, outputs, parameters,...: It is important that the FMU provides the information in which model partition a variable is used or calculated (see also my comments in #1375 regarding this need). This enables the importer to place the calls of set and get exactly in the right task. If for example an output variable is assigned to ClockA, the importer calls fmi3Get for this output after the call to fmi3ActivateModelPartition(**ClockA**) (and nowhere else). It cannot happen in this case that the importer receives inconsistent data.
If the FMU does not provide the information, or the same variable is assigned to more than one clock, the FMU must take care of the consistency problems itself. The master cannot do this in this case.

**Comment by IZacharias** [comment]
> I looked at #1368 - atomicity is clearly not solved in the implementation of fmi3GetClock there.
> 
> @MBlesken & @IZacharias : Do you imply then that the importer must make sure that fmi3GetClock is not interrupted?

@andreas-junghanns You are right, we have to adapt this. The FMU should handle this.
@MBlesken FYI

**Comment by andreas-junghanns** [comment]
@IZacharias : So you are suggesting that the FMU must use CAS operations or, if that is not possible, to lock/unlock preemption?
Please also make sure we define exactly which part of the operation must be atomic:
 a) per valueReference
 b) all valueReferences of this call (to get a consistent state across all values retrieved)
I think the second would make more sense and would add value to using an array of valueReferences and one call compared to calling fmi3Get multiple times with fewer or even a single valueReference.

However, if we pick b) - why would then the FMU have to call lock/unlock preemtion? Wouldn´t the importer then know to not preemt at this very moment while fmi3Get is running and we can save the lock/unlock calls?

**Comment by clagms** [comment]
@IZacharias thank you for the clarification!

I don't understand the following statement:
> If the same variable is assigned to more than one clock, the FMU must take care of the consistency problems itself. The master cannot do this in this case.

As long as the FMU still provides information about which variable is read/written by which partition, then the master can determine which variables are shared, and can lock preemption.
Also note that, as @andreas-junghanns said, locking preemption at the value reference level (option a above) does not necessarily ensure a consistent execution of a model partition, because the Importer may be copying over a vector that in the meantime could have been changed.

To me this means that the importer must be the one managing locks before and after executing a model partition (and the FMU would be the one managing the locks while executing the partition).
