### ISSUE TITLE
Code example of SE abuses clocksTicked flag

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#1360]
The code example provided in the SE section is a good one to clarify the use of the different functions.
However, I think it contains a small mistake, that would induce the reader to the wrong interpretation of what the flag `clocksTicked` does.

In the following listing, check the comments prefixed by "Claudio"
```
void activateModelPartition10ms(fmi3Instance *instance, ...)
{
   ...
   if (...)
   {
      CountdownClockQualifier = fmi3NewInterval;
      CountdownClockInterval = 0.0;
      // inform simulation algorithm that the countdown clock has ticked
      // Claudio: This is an incorrect use of the flag. No clock has ticked... It's the importer that decides when a clock really ticks for countdown clocks (input clocks in general). 
      // Claudio: So this flag should be false. The Importer will check for a new interval on the clock, and if that interval is zero, then it will tick the clock.
      fmi3Boolean clocksTicked = fmi3True;
      instance->fmi3CallbackIntermediateUpdate(..., clocksTicked, ...);
   }
    if (...)
   {
      // outputClock ticks
      //  Claudio: This is the correct use of the flag.
      fmi3SetClock({7});
      // inform simulation algorithm that output clock has ticked
      fmi3Boolean clocksTicked = fmi3True;
      instance->fmi3CallbackIntermediateUpdate(..., clocksTicked, ...);
   }
   ...
}
```

As a consequence, the following listing is incorrect, because the interval of countdown clocks should be checked always. Not just when a clock as ticked.
```
void CallbackIntermediateUpdate(...,fmi3Boolean clocksTicked, ...)
{
   //Claudio: The fmi3GetIntervalDecimal call (and block of code surrounding it) should be done outside this if statement 
   if (clocksTicked == fmi3True)
   {
      // ask FMU if countdown clock is about to tick
      fmi3ValueReference aperiodicClockReferences = {6};
      fmi3GetIntervalDecimal(... aperiodicClockReferences, ... &interval, &qualifier, ...);
      if (qualifier[0] == fmi3NewInterval)
      {
         // schedule task for AperiodicClock with a delay
         Scheduler->ScheduleTask(TaskAperiodic, interval[0]);
      }

      // ask FMU if output clock has ticked
      fmi3ValueReference outputClockReferences = {7};
      fmi3Boolean[] clocksActivationState = {fmi3ClockInactive};
      fmi3GetClocks(... outputClockReferences, &clocksActivationState, ...);
      if (clocksActivationState[0])
      {
         // schedule some external task
         Scheduler->ScheduleTask(SomeTask);
      }
   }
}
```

**Comment by t-sommer** [comment]
We're currently converting the snippets to C (see #1358). Maybe we can fix them there directly as most of them are broken anyways.

**Comment by IZacharias** [comment]
@clagms The FMU uses the argument clocksTicked here to signal the simulation algorithm for which reason the call of the function fmi3CallbackIntermediateUpdate was made. 

The first call is made for the sole reason that the FMU wants to signal the simulation algorithm that the countdown clock should tick. That is, as soon as the FMU knows the new interval, it calls the function. The name of the argument is indeed a bit misleading (better clocksAboutToTick?).

The second call is made for the reason that the FMU wants to signal that the output clock has ticked.

Possible solutions from my point of view would be to adjust the name of the argument, or to introduce an additional argument just for handling the countdown clock. It would not be consistent to use an argument for one case, but not for the other.

**Comment by andreas-junghanns** [comment]
@t-sommer is on a renaming rampage - maybe we can inlist him to include a fix here as well?
If renaming does the trick, we should only do that and not introduce another parameter.

**Comment by clagms** [comment]
@IZacharias thank you for the clarification.
However, I don't agree that this is a naming issue. In the first call, the clocksTicked flag should be false, but the Importer should still check if a newInterval is returned on every countdown clock.

**Comment by andreas-junghanns** [comment]
> @IZacharias thank you for the clarification.
> However, I don't agree that this is a naming issue. In the first call, the clocksTicked flag should be false, but the Importer should still check if a newInterval is returned on every countdown clock.

@clagms & @IZacharias : did you two make progress on this issue here? Any concrete proposals that we could link as PR?

**Comment by andreas-junghanns** [comment]
@clagms : is this issue solved?

**Comment by clagms** [comment]
@andreas-junghanns I haven't done anything here since I'm waiting for a clarification on the following.
However, I'll email @IZacharias and try to talk this out.

> @IZacharias thank you for the clarification.
> However, I don't agree that this is a naming issue. In the first call, the clocksTicked flag should be false, but the Importer should still check if a newInterval is returned on every countdown clock.

**Comment by clagms** [comment]
After looking at https://github.com/modelica/fmi-standard/pull/1368 , I still see the same issue in the new code snippets.
@MBlesken , @andreas-junghanns , is the above PR supposed to address this issue?
A review has been asked of me, but it's hard to give it when I fundamentally misunderstand the use of the clocksTicked flag 😄

**Comment by andreas-junghanns** [comment]
@clagms : I looked at the code and I think this is correct: the FMU must inform the scheduler that the countdown clock interval needs to be queried again (clocksTicked == fmi3True). Why not also use this flag for countdown clocks?

However, the explanation for clocksTicked (let´s ignore the name for a minute) needs clarification to address countdown clocks and getInterval calls. I will link a PR in a minute.

**Comment by clagms** [comment]
>@clagms : I looked at the code and I think this is correct: the FMU must inform the scheduler that the countdown clock interval needs to be queried again (clocksTicked == fmi3True). Why not also use this flag for countdown clocks?

@andreas-junghanns , if this is the case, why do we need `fmi3IntervalUnchanged` for the enum `fmi3IntervalQualifier` ?

**Comment by IZacharias** [comment]
> > @clagms : I looked at the code and I think this is correct: the FMU must inform the scheduler that the countdown clock interval needs to be queried again (clocksTicked == fmi3True). Why not also use this flag for countdown clocks?
> 
> @andreas-junghanns , if this is the case, why do we need `fmi3IntervalUnchanged` for the enum `fmi3IntervalQualifier` ?

@clagms @andreas-junghanns We do not know for which countdown clocks new intervals are available. Clocks for which fmi3IntervalUnchanged is returned have already been handled in a previous execution of intermediateUpdateFunction.

**Comment by clagms** [comment]
@IZacharias thank you for the feedback.

>We do not know for which countdown clocks new intervals are available.

We know, because we can call getInterval and get back fmi3IntervalUnchanged. Abusing the flag clocks ticked does not really solve this point anyhow.

>Clocks for which fmi3IntervalUnchanged is returned have already been handled in a previous execution of intermediateUpdateFunction.

Yes I understand this. Hence my main point: that the flag clocksTicked should be minimizing the number of calls to getClock, not minimizing the number of calls to getInterval...

If this is what we want, then we have to rename the flag.

**Comment by clagms** [comment]
Also note that there are multiple issues with the clarifications merged in https://github.com/modelica/fmi-standard/pull/1376
(thank you @andreas-junghanns for the enhancements though)

**Comment by andreas-junghanns** [comment]
Let´s ignore the name of the flag for now (the definition is more important).
The clocksTicked flag helps to call getClock (and getInterval) only when needed.
Depending on the definition, it is either only getClock, or both getClock and getInterval, right?
The FMU knows what calls it wants the importer to make (it knows which clocks information is updated) and we need to define which optimization the importer can make.

@clagms : Why do you think clocksTicked should refer only to getClock (output clocks ticking)? Because of a definition? Because only that makes sense?

**Comment by clagms** [comment]
> The FMU knows what calls it wants the importer to make (it knows which clocks information is updated) and we need to define which optimization the importer can make.

Yes this summarizes the problem!

@clagms : Why do you think clocksTicked should refer only to getClock (output clocks ticking)?

Because that's the way it is defined in the current version of the standard. 
I'm ok with changing the meaning of that flag to cover "getInterval" calls, but we'd have to change everything else in the standard to make it consistent. And we'd probably have to discuss a bit as well, to make sure we're not overlooking anything.

**Comment by andreas-junghanns** [comment]
@clagms : This is the current definition of clocksTicked:
_The clocksTicked parameter is only used in Scheduled Execution and is ignored in Co-Simulation. When clocksTicked == fmi3True, it means that fmi3GetClock function must be called for gathering all Clock related information about ticking output clocks, fmi3GetInterval must be called for all countdown Clocks and then activate the respective model partitions accordingly._

I suggest to close this ticket as this issue is now clarified in the standard clearly.
