### ISSUE TITLE
Multiple get and set iterations in one super dense time instant in event mode of a CS FMU possible? Can this be prevented?

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1378]
To my understanding of event mode, multiple fmi3setXX fmi3getXXX iterationas are possible at the same super dense time instant, so that the Importer can solve for the given super dense time instant the governing algebraic equations.
This is a property of the "synchronous  clocks", right?

But can this behaviour be prevented? E.g., when the clocked variables belonging to a clock represent control SW, one does not want to iterate (and repeat) the evaluation for a given point of time. How can the FMU prevent the importer from doing so? Or is this not possible with clocked variables in CS?

**Comment by andreas-junghanns** [comment]
The caching mechanism should be transparent: that is, get/set trigger computations only when needed to return the proper values. Once a value has been computed, a second call just returns it.
At least this is how I understood the contract.

**Comment by chrbertsch** [comment]
> The caching mechanism should be transparent: that is, get/set trigger computations only when needed to return the proper values. Once a value has been computed, a second call just returns it.
> At least this is how I understood the contract.

My question is not about caching. 

For SE it is stated: It is not allowed to call fmi3Get{VariableTypeExclClock} functions after fmi3Set{VariableTypeExclClock} functions without an fmi3ActivateModelPartition call in between.
But for CS (and ME) in event mode there might occur algebraic loops that might be solved iteratively by multiple calls of fmi3setXX and fmi3getXXX calls. (To my understanding w/o increasing super dense time. Is this correct?).

But this might not make sense, if the clocked variables represent a a controller task with internal discrete states.
Is there a way for a ME or CS FMU with clocks to signal that iterative fmi3SetXXX and and fmi3GetXXX calls are not supported - with or without increasing super dense time?

**I just saw, that for this we can use canHandleMultipleSetPerTimeInstant=false.**
**This basically solves my question.**

**Additional question: can the FMU prevent an event iteration to happen?**

**Comment by andreas-junghanns** [comment]
For SE, there is no Event Mode, hence no event iteration.
canHandleMultipleSetPerTimeInstant=false is, to my understanding, the clear message that algebraic loops cannot be solved with simple set/get calls.

**Comment by chrbertsch** [comment]
> For SE, there is no Event Mode, hence no event iteration.
> canHandleMultipleSetPerTimeInstant=false is, to my understanding, the clear message that algebraic loops cannot be solved with simple set/get calls.

yes "canHandleMultipleSetPerTimeInstant=false"  can prevent iterative set/get calls within one super-dense time instant. 
But for various super-dense time instants (fora the same real time) setting different inputs and getting different outputs till possible:

![grafik](https://user-images.githubusercontent.com/16363372/112975665-3953b680-9154-11eb-8b63-f37d7a506e3f.png)

Is there a way to prevent this?

**Comment by andreas-junghanns** [comment]
Why would you want that?
Are you saying you have FMUs that can handle only one super-dense time step?
Is it about control code running only once?
Then you should use SE (without Event Mode etc.).

I must be missing something here...

**Comment by chrbertsch** [comment]
> Is it about control code running only once?

Yes

> Then you should use SE (without Event Mode etc.).
> I must be missing something here...

I can imagine many use cases 

- the addressed importer might only support CS (with clocks), not SE
- you have a mixed model: controller + physical plant model 
- this might be even a Matryoshka FMU of a CS plant model FMU + a SE Controller FMU

**Comment by chrbertsch** [comment]
For me the concept of "canHandleMultipleSetPerTimeInstant=false" is still not clear and should be adapted due to the introduction of clocks:

- its description (assignment of discrete states directly at setting inputs) contradict the description of event mode https://fmi-standard.org/docs/3.0-dev/#EventMode, where calculation are triggered by the fmi3getXXX functions or fmi3UpdateDiscrete states
- the name is misleading, as it is referring to super dense time instant, not a "real" time instant. Should it be canHandleMultipleSetPer**SuperDense**TimeInstant (which is long)

I think, we should find a means to prevent event iteration for  clocked variables even in ME and CS - otherwise many "clocked" use cases in ME or CS will not be possible or safe (e.g. time based clock with a constant internval of 10ms  with a simple increment  of an internal counter that shall be incremented every 10ms. Implementing this currently is not possible w/o complicated checks in which event iteration one is) and people will continue "misusing" other concepts like putting discrete changes in the doStep instead of using the new clocks features ...

**Comment by chrbertsch** [comment]
Regular design meeting: 

Karl: the clock should be activated only once.  At UpdateDiscreteStates the clock is disabled.
Christian: this answers my  question. I will think about it and problably close it.

Pierre: we should write something about this.  (why is controller code not triggered twice). All of this depends on being able to compute the outputs without changing the internal state). 
Karl: Could we have an arguemnt to a clock that it cannot be iterated? that the updates can only be calculated in updateDiscreteStates?
Pierre: Can the FMU prevent going into event mode? If you go to event mode, you can have multiple set-calls.
Can one signal that one supports event mode only with one-time sets.
I think we need a design wall-through to check such things.
I thing this is an import use case for CS FMUs with events.
Karl: We have the capability flag "hasEvent" mode.
Pierre: But if we have clocks, this is not meaningful
Should we have a flag that a clock can only be activated only once in event mode?
Karl: the master should not do this anyway.

Pierre: we should write this conclusions down. (perhaps inplementers guide)
Create a new milestone. v3_implementers_guide?
