### ISSUE TITLE
Design Walkthrough of Variable/ModelStructure

### ISSUE THREAD

**Issue by pmai** [modelica/fmi-standard#1385]
As discussed today in the Design Meeting 2021-03-31, given the way we have incrementally added more information to variables (cf. event indicators, clocks) and the ModelStructure, we should do a complete design walkthrough of this whole area to ensure that all of the functionality we have now available is well designed and understood in its consequences and documented as such. The proposal is to collect questions for such a design walkthrough here, and then schedule a focused workshop where the design is gone over in a structured way and the collected questions (and others that arise during the walkthrough) are answered and necessary changes/enhancements to the design or documentation are collected.

Potential querstions might include:

- What does dependency information on event indicators mean, how should it be specified and how can it then be used reliably (e.g. to not query/calculate indicators that cannot have changed due to the dependencies not having changed)?

**Comment by chrbertsch** [comment]
FMI Design Meeting: Let's prepare and schedule this for the next regular design meeting on May 26

@ all: please comment questions and comments to this ticket

**Comment by pmai** [comment]
Further topics for design walk-through:

- Do all combinations of clock types make sense if combined via the clock attribute of a clock (i.e. can a time-based input clock have a clock attribute pointing to e.g. a triggered output clock, etc.)?
- Do all other attribute combinations on variables make sense?

**Comment by chrbertsch** [comment]
Web-meeting: 
Pierre: are we stable enough w.r.t clocks? Let's wait for the outcome of tomorrow's discussion. Then I could prepare the "walkthrough" for some of the next meetings.

**Comment by chrbertsch** [comment]
@pmai : could we start the walkthrought today? Will you join the meeting?

**Comment by andreas-junghanns** [comment]
Clocks design walk through (by @TorstenBlochwitz & I (@andreas-junghanns)):
 - Clock `causality` is already restricted to `input` and `output`.
 - Added a note to `clocks`attribute to explain why we do not introduce further restrictions on clocked variables. See PR #1600.
 - `variability` and `previous` attribute are already properly restricted.

**Comment by andreas-junghanns** [comment]
>     * What does dependency information on event indicators mean, how should it be specified and how can it then be used reliably (e.g. to not query/calculate indicators that cannot have changed due to the dependencies not having changed)?

This allows the importer to use the partial evaluation which seems to be supported by an FMU that publishes this dependency information: Before getting the event indicators only the variables they depend on have to be set. This may be a good point for the implementer´s guide.

**Comment by KarlWernersson** [comment]
> This allows the importer to use the partial evaluation which seems to be supported by an FMU that publishes this dependency information: Before getting the event indicators only the variables they depend on have to be set. This may be a good point for the implementer´s guide.

Although this is theoretically possible, as I remember the discussion we had. the main reason to expose them was debugging.
