### ISSUE TITLE
Tag beta.1 and collect text for pre-release announcement

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1390]
Collection of announcement text (please directly edit here or comment)

This is the first beta release of FMI3.0. 

API changes compared to FMI3.0alpha.7:

Schema changes: 

- Clock dependency of variables is now an attribute of Variables (#1375)
- Clock attribute "canBeDeactivated" added (#1403)
- EventIndicator inherits from fmi3Unknown (#1377)

**Comment by chrbertsch** [comment]
I updated the proposed release text in the issue text above. @t-sommer , @andreas-junghanns : please check.
Can we tag and release beta.1 now?

**Comment by andreas-junghanns** [comment]
> I updated the proposed release text in the issue text above. @t-sommer , @andreas-junghanns : please check.
> Can we tag and release beta.1 now?

Yes, I think so: in the FMI design meeting we had two tickets still open for beta.1 that are now closed.
