### ISSUE TITLE
May time-based clocks only be activated at first super-dense time point (t_I=0)?

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1393]
Currently in the "Alllowed Function Calls" for Event Model, it is stated: "Only Time-based clocks must not be active for more than one call of fmi3UpdateDiscreteStates per Event Mode."

Is there any reason, why this should not be the first super-dense time point, i.e. integer part of super-dense time t_I=0?
Then we should explicitly state this. 

And as get-calls  and not only fmi3UpdateDiscreteStates may trigger calculations, it must be clarified that time-based clocks may for a given real-part of super-dense time not be active _after_ the first call of fmi3UpdateDiscreteStates. 

So I would re-state the cited sentence, e.g. like this: 
 "Time-based clocks may only be active for super-dense time points (t_R, t_I), with t_I=0, i.e. they must not be active after the first call of fmi3UpdateDiscreteState per Event Mode."

**Comment by andreas-junghanns** [comment]
@TorstenBlochwitz: We changed that - do you remember why?

**Comment by clagms** [comment]
If I remember correctly, it's up to the importer to decide when to activate the time based clocks and how to prioritize among multiple activating clocks... So it's natural not to force the time based clocks to be activated on the first super-dense time instant.

**Comment by chrbertsch** [comment]
>... So it's natural not to force the time based clocks to be activated on the first super-dense time instant.

The integer-part of super-dense time corresponds to event iteration. Event iteration is necessary to determine a discrete variable's change due to another discrete change. But clocked variables do not participate in event iteration (they tick only once per real part of a super dense time intant), so it does not seem natural to me to allow an ambiguity here.  The concept of priority of model partition exists only in SE. To my understanding, in ME and CS clocks ticking at the same time instant should be activated "synchronously" at he first integer part of super dense time. 
Or could someone please describe, why it should be different?

Imagine we have a CS FMU with  two periodic time-based clocks (with a 5ms and 10ms interval), and each of them increments the same (global) counter. For events, where both clocks are active, shall the counter be incremented once or twice? If both clocks are active at the same (e.g. first) integer part of super-dense time, it will be incremented once. If the 5ms- and the 10ms-clocks are active at different integer parts of super dense-time, the counter will be activated twice.
Which behaviour do we want? 
Or do we explicitely want the importer to activate clocks at different integer parts of a super-dense time instant? But from where should the importer know in which order? (as we have no priorities)

**Comment by clagms** [comment]
> But clocked variables do not participate in event iteration (they tick only once per real part of a super dense time intant), so it does not seem natural to me to allow an ambiguity here.

This is an interesting point of view. Time based clocks do indeed tick only at a real-part of the super-dense time... But not triggered clocks. These can tick multiple at event iterations (e.g., one discrete variable changing and causing a tick).

@chrbertsch do you recall the examples provided by @masoud-najafi , where you had FMUs that acted as event based sub-samplers? These highlighted well the need to see clocks as being capable of activating at multiple super-dense time instants with the same real part.

> Imagine we have a CS FMU with two periodic time-based clocks (with a 5ms and 10ms interval), and each of them increments the same (global) counter. 

This is a good example of why the importer should not allow the same variable to belong to different clocks :p.
Ignore this side remark, I think you are assuming that the increment of the counter will be done when UpdateDiscreteStates is called, right? 
In that case, it's up to the FMU to account for the simultaneous activation of the clocks. They are both declared by the same FMU, and the same FMU is implemented with a variable that is written by two clocks... 

Also note that nothing forbids the computation from being done when a call to getReal is made on that global variable. The point is that clocks activate equations, and equations are solved when getReal is called... and not just when UpdateDiscreteStates is called.

> Or do we explicitely want the importer to activate clocks at different integer parts of a super-dense time instant?

I would follow @andreas-junghanns 's philosophy and leave it to the importer to decide.
I think that, in the example you gave, the FMU still has enough information to handle simultaneous activation of clocks.

> But from where should the importer know in which order?

The importer may build a dependency graph representing all variables whose clock is active. If the same variable is affected by two clocks, then it becomes murkier, but the FMU should be the one handling this. The Importer just knows which inputs it needs to set, and which outputs to obtain, before calling UpdateDiscreteStates

**Comment by andreas-junghanns** [comment]
@chrbertsch : I think there is no right or wrong answer to your counter example: it depends what the counter should count. And that must be handled by the code generated by the exporter, not the importer

And I am not getting why CS and controller code is occupying us so much: If you want to run controller-code in CS, you have to guard it properly to expose a clean Step Mode and Event Mode. The API is clear, make sure YOUR code does what YOU expect.

And I understand the clee @clagms feels when this confusion comes up. My conclusion is less "synchronous" (too much lock-step during my army times, sorry), and more pragmatic, see above.

**Comment by chrbertsch** [comment]
> @chrbertsch do you recall the examples provided by @masoud-najafi , where you had FMUs that acted as event based sub-samplers? These highlighted well the need to see clocks as being capable of activating at multiple super-dense time instants with the same real part.

But these are triggered clocks, right? For them activation at higher integer parts of super dense time is fine for me.

> @chrbertsch : I think there is no right or wrong answer to your counter example: it depends what the counter should count. And that must be handled by the code generated by the exporter, not the importer.

Yes, but the exporter must know what to expect form the importer. If, e.g. for the example above, the FMU can handle the simultaneous activation of the 5ms and the 10ms clock correctly by internally knowing about priorities (5ms being of higher priority than 10ms).
But what if the importer for some strange reason activates the 10ms clock at (t_R,0) and the 5ms clock at (t_R,1)? This would be against the internal priority logic of the FMU.

I still do not see the reason or a use-case, why _time-based_ clocks should not all be mandatorily be activated at (t_R, 0).  This would be a clear and simple contract.

**Comment by masoud-najafi** [comment]
Hi,
Please ignore my comment if it is off-topic.
Each "asynchronous" clock tick (triggered or timed based), should have its own set of super-dense time iteration. For example, if two "asynchronous" clocks are active at the same time TR, the importer should run the super-dense time iterations for clock1. Once finished and UpdateDiscreteStates(clock1) is called, then iterations for clock2 is started. The order of calling clock1 or clock2 is arbitrary.
On the other hand, if clock1 and clock2 are synchronous, (i.e., have the same origin), then the iteration should be done while two are enabled. It is up to the FMU to decide what should be done in this case. All importers should do in the same way, otherwise the result may not be predictable.
Please ignore my comment if it is off-topic.

**Comment by andreas-junghanns** [comment]
> I still do not see the reason or a use-case, why _time-based_ clocks should not all be mandatorily be activated at (t_R, 0). This would be a clear and simple contract.

@TorstenBlochwitz : we used to have it that way and if I remember correctly, we relaxed this on purpose. Which was that?

**Comment by clagms** [comment]
> But what if the importer for some strange reason activates the 10ms clock at (t_R,0) and the 5ms clock at (t_R,1)? This would be against the internal priority logic of the FMU.

This is a good point @chrbertsch , but note that if the FMU should not try to control exactly when a clock becomes active. That is the job of the Importer (the FMU provides the approximate timing, and therefore its implementation should not rely on exactness of those activations). 
If two clocks are meant to be simultaneously activated by the importer, then the two clocks are connected with a clock connections... So that they become the same conceptual clock...

@masoud-najafi your comment is a bit off topic, and I think it is up to the importer to decide what you suggest here:
Each "asynchronous" clock tick (triggered or timed based), should have its own set of super-dense time iteration. For example, if two "asynchronous" clocks are active at the same time TR, the importer should run the super-dense time iterations for clock1. Once finished and UpdateDiscreteStates(clock1) is called, then iterations for clock2 is started. The order of calling clock1 or clock2 is arbitrary.

**Comment by andreas-junghanns** [comment]
@clagms and @masoud-najafi : I think this is an interesting point and needs clarification.

And I agree with @clagms : the FMU implementation MUST NOT depend on the order of these clock activations to compute "correctly".

And more to the point that @chrbertsch raised: The correctness of the FMUs computation MUST NOT depend on in which super-dense time instant its clocks are active (at least at current definition).

If we restrict time-base clocks to activation at (t_R, 0), it could simplify implementations on both sides.
The question remains: would we exclude important use cases with such a restriction?

**Comment by KarlWernersson** [comment]
> If we restrict time-base clocks to activation at (t_R, 0), it could simplify implementations on both sides.
The question remains: would we exclude important use cases with such a restriction?

Would the opposite be of interest?
Lets say that you have an FMU a mixed with "normal events" and a time based clock.
Would it be of interest to converge the "normal events" and then activate the time based clock.

If the event changes the input to the time-based clock, this will give a different result. depending on if you solve the time based clock at the start or the end.

Do we want to allow this behavior?
We do allow similar things for co-simulation where how you connect and from which timepoint you pick your input will effect the FMU's output.

**Comment by oliverkotte** [comment]
@KarlWernersson @chrbertsch for both your use cases, the FMU implementation depends on a specific order of clock activations to simulate correctly. But @andreas-junghanns and @clagms say this is forbidden.
Isn't the uncertain order of time-based clock activations with respect to triggered clock activations the problem? If time-based clock activations at (t_R, 0) were the default but (t_R, end) an option, would that solve the problem at hand without restricting use cases?

**Comment by clagms** [comment]
> If the event changes the input to the time-based clock, this will give a different result. depending on if you solve the time based clock at the start or the end.

@KarlWernersson I think the dependency graph between all active clocks should contain the necessary information to infer the correct order of variable computations. So, the importer would activate all clocks that should be activated, and then compute the variables (from the dependency graph), and then activate more clocks if they have become active (still in the same super-dense time instant), and repeat, until the set of active clocks has converged. Then a final computation of the variables would be done, and the discrete states updated.
It's up to the importer to make sure this process terminates, right?

> But @andreas-junghanns and @clagms say this is forbidden.

I think what I wrote is a bit different @oliverkotte : the FMU should have enough information to know that two clocks are active simultaneously, and therefore take the appropriate action to address the ordering issue. The only way it can impose ordering in the clock activations is through the clock dependencies (an output clock can depend on an input clock), and variable dependencies (a variable can depend on a clock being active or not).

**Comment by masoud-najafi** [comment]
I noticed that the restriction for assigning variable to a single clock has been removed from the standard, i.e., "Clocked variables can depend on multiple Clocks.". If this restriction no longer exists, then the activation order matters.

**Comment by andreas-junghanns** [comment]
Even if we define that time-based clocks tick only at (t_R, 0), the ordering issue remains.
Worse, it would remove the option to enforce a certain clock activation order by the importer (activating clocks in different super-dense time instants).

I don´t see this as a fundamitenal issue though: Model Partitions belonging to different clocks should be separate enough for order to matter (e.g. they should not be part of the same algebraic loop).
Variables depending on multiple clocks may of course depend on execution order, but that is bad design if that is the case and the exporter would have to take care of computing this correctly (latest on get after the final UpdateDiscreteStates).

**Comment by chrbertsch** [comment]
> (@andreas-junghanns) : Even if we define that time-based clocks tick only at (t_R, 0), the ordering issue remains.

 I do not agree. In my point of view there is no ordering for clock activations at the same real part or super dense time! That is for me the expected behaviour of simultaneous clock activations of time-based clocks at an event. 
Still the importer can _internally_ have something like an ordering or prioritization. But unlike in SE it does not _expose_ this.

> Worse, it would remove the option to enforce a certain clock activation order by the importer (activating clocks in different super-dense time instants).

I see this as a benefit as we avoid different behaviour by different importers. If one wants a special order of clock activations one should use an SE FMU with priorities.


> I don´t see this as a fundamitenal issue though: Model Partitions belonging to different clocks should be separate enough for order to matter (e.g. they should not be part of the same algebraic loop).

I think we cannot prevent this, as the algebraic loops occur by external connections.

> Variables depending on multiple clocks may of course depend on execution order, but that is bad design if that is the case and the exporter would have to take care of computing this correctly (latest on get after the final UpdateDiscreteStates).

The FMU does not even know if a call of  UpdateDiscreteStates is the final one; another FMU could demand a further event iteration, right?

> (@KarlWernersson):  Would the opposite be of interest?
Lets say that you have an FMU a mixed with "normal events" and a time based clock.
Would it be of interest to converge the "normal events" and then activate the time based clock.

What would be the use case for that? IMHO it just introduces a further ambiguity

> If the event changes the input to the time-based clock, this will give a different result. depending on if you solve the time based clock at the start or the end.

Yes. For that reason I would activate time-based clocks all at (t_R, 0). 

> Do we want to allow this behaviour?
We do allow similar things for co-simulation where how you connect and from which timepoint you pick your input will effect the FMU's output.

But for CS we accept a numerical error that  should converge to zero if we make the communication timesteps smaller. But the behaviour that we currently discuss is discrete, and the difference in simulation results will not go away ...

**Comment by clagms** [comment]
> > If the event changes the input to the time-based clock, this will give a different result. depending on if you solve the time based clock at the start or the end.
> 
> Yes. For that reason I would activate time-based clocks all at (t_R, 0).

In the scenario that @KarlWernersson mentioned, wouldn't the importer know that the event clock can affect the time based clock? This information is obtained through the variable and clock dependencies.
The Importer would then activate both clocks, and follow the dependencies between variables, computing them accordingly.
This is the case, whether we force the importer to activate the time based clock at (t_R, 0) or not. 
I think this is what @andreas-junghanns meant when he said that the ordering issue remains: imagine that a triggered clock activates when a time based clock does. The Importer must, regardless of the super-dense time instant, always activate the triggered clock when the time based clock ticks.

> In my point of view there is no ordering for clock activations at the same real part or super dense time!
> Still the importer can internally have something like an ordering or prioritization.

The ordering is imposed by the dependencies among variables and clocks. And there is a causal ordering among clock activations in the same super-dense time instant. A triggered clock can tick as a result of another clock ticking, or as a result of some variable acquiring a certain value.
I agree that this will not guarantee well behaved event iterations, but this is not the same as there being no ordering among clock activations.

> The FMU does not even know if a call of UpdateDiscreteStates is the final one; another FMU could demand a further event iteration, right?

Yes indeed.

> I see this as a benefit as we avoid different behaviour by different importers.

I still don't see what ambiguity is being introduced by us not forcing time based clocks to be activated at (t_R, 0)...
@chrbertsch can you provide a more detailed example showing how two importers (having taken different interpretations of the standard) would produce different results? 
To me this would nail the issue that we have to address...

**Comment by andreas-junghanns** [comment]
To many back-and-forths, let me try to sort the issues:

 - We agree that time-based clock activations are different from triggered input clock activations:
   * time-based clocks tick only once per Event Mode, that is are activated by the importer in only one super-dense time instant per Event Mode
   * triggered input clocks might be active or inactive mutliple times even during one super-dense time instant in one Event Mode, because their trigger conditions might be part of an algebraic loop (and we reflect this in the standard by asking deactivating of triggered input clocks to return their clocked variable to their previous values)

 - if an FMU exposes multiple input clocks (time-based or triggered input), it must assume they can be activated independently and therefore clocked variables of different clocks cannot be part of the same algebraic loop (allowing for independent solution of each loop by the importer), unless:
   * clock sources are externally connected and only the importer can know this, and/or
   * a (global) clocked variable in one FMU depends on multiple clocks effectively merging these algebraic loops forcing combined solution of these loops (detectable via dependency analysis by the importer) in case their input clocks tick during this Event Mode

 - I see this as quite clear for purely input-clock-based event handling. It gets more tricky when we mix this with "normal events" (see @KarlWernersson comments above, and let´s call them mixed Event Modes):
   * "normal events" invoke the same solution mechanism as for clocked variables, only for (an arbitrary subset) of all non-clocked variables, right?
   * When additionally input clocks tick (mixed Event Mode), more equations are active - *at the same time*!
   * I think: This requires a combined solution of the "normal event" equations and the model partitions (as they influence one another, why would they otherwise be in the same FMU) - "solving" them in some order seems broken to me.

Back to the initial question by @chrbertsch : when time-based clocks should be activated:
 - I do not see why we need to enforce early input-clock activation at t_I=0 for correctness: in a mixed Event Mode, you would only later add more equations (by activating the input clocks) and then solve all loops again - maybe this is more or less efficient, I would not know right now
 - But I also do not see why requiring activation at t_I=0 would restrict the solution

**Comment by andreas-junghanns** [comment]
Web-Meeting Andreas und TorstenB: To finish a continuous part of the simulation (e.g. doStep) we first have to solve the "classic" event iteration for the continuous part of the FMU. As long as this event iteration of the contious part of the FMU is not finished, invalid intermediate states might occur. Only once this iteration is finished, Clocks should be activated and resulting algebraic loops solved.
To allow this, we cannot enforce time-based clocks to be actived during the first super-dense time instant.
