### ISSUE TITLE
ResourceLocation: lifetime?, read-only?, path or URI?, point to "resources" or root?

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1405]

**Comment by andreas-junghanns** [comment]
We should also clarify, why we restrict reading content in `resourceLocation`:
> The `resource` data must be read into the model at the latest during initialization (that is, before `fmi3ExitInitializationMode` is called).

This is likely not observed by many tools and especially the use case `needsExecutionTool == true` might break for many.

**Comment by andreas-junghanns** [comment]
This issue raises 4 different sub-issues:
 1. What is the life-time of the resourceLocation directory?
    --> Design Meeting decision: Until the end of life of the FMU run-time instance (that is the return of freeInstance)
    --> Design Meeting decision: No guarantee that multiple instances receive the same resourceLocation (non-normative)

 2. Should we allow writing into resourceLocation?
    --> Design Meeting decision: WRITING NOT ALLOWED

 3. URI related
    keep URI or just an absolute path to directory with trailing path separator
     --> Poll to change to path:
             pro: Klaus, Pierre, TorstenS, AndreasJ, Masoud, Christian
             contra: ...

 4. Make resourceLocation point to root of ZIP archive?
    If yes, then
    a. extract all or only partially?
    If we pass the the root of the ZIP file, we restrict extraction to the same location.
    Poll: introduce binaryLocation of the platform:
        pro: Christian, Pi(erre)
        contra: Andreas, Kl(aus), Masoud, TorstenS^2, 
    Poll: extract ZIP (completely or just binary and resources) in one place and pass the root:
        pro: Pierre^8, Masoud
        contra: Andreas^2, Klaus^3, TorstenS^2, Christian
    --> Design Meeting decision: Leave things as they are

Add at the beginning: Comment to add what non-normative text really means.

@IZacharias and @MBlesken : Can you please check sub-issue 3 here? Can we remove the URI requirement?

**Comment by KarlWernersson** [comment]
Issue 3.0

We change something not broken so old implementations breaks if they don't change this small detail (trailing slash)
When have done this at tons of places...
