### ISSUE TITLE
Initialization of clock partition.

### ISSUE THREAD

**Issue by KarlWernersson** [modelica/fmi-standard#1407]
1.
>  Model partitions are initialized at their first Clock activation, not in Initialization Mode
>...
> However, fmi3Get{VariableType} will return the value computed at the last Clock activation time. Before the first Clock tick, clocked variables have their initial value.

Variables of a clock partition can have inital = calculated. What do they have as an initial value? Can any arbitrary value be returned?

2. How is the relationship between a fixed start value of a clocked state and the start value of its previous value. 
Can they have different start values?
Can both have start values?
If not which one should have the start value?
Both would work, I would prefer to put it on the clocked state.

3. Other states with initial calculated are required to be listed in initialUnknowns.
As the clock partition is initialized during the first clock activation this would prevent clockedStates with initial = aprox or calculated to be listed there.

Currently all outputs with "initial" not equal "false"  must be listed in initialUnknonws. This would require a restriction for them.

By keeping this restriction we prevent proper combined initialization of model partitions from different FMU's belonging to the same master clock.

To solve 3.  we would either
 1. Need to have specific clock initialization mode for each clock with inialUnknwons being solved there.
 2. Let clocked variables be initialized in initialization mode in the same way as the rest of the FMU. (Atleast outputs and possibly states)
 3. Declarer it out of scope and list restrictions that clocked outputs are not part of initial unknowns

**Comment by andreas-junghanns** [comment]
I thought this was obvious until you raised this point:
1. Why would such a special mode be needed? The clocks do not tick in Initialization Mode, but neither is the rest of the model "advancing time" and still, it is initialized. Why would we separate the clock partitions from the rest during initialization?
2. (Only) that makes sense to me, especially as clock partitions might share/use the "global" part of the model.
3. This would mean all clocked outputs must have a defined value and cannot be influenced by the rest of the initialization - that sounds odd to me.

For 2. we do not need to do much - maybe we should add a clarificiation in Initialization Mode that the FMU must also initialize all (appropriate) clocked variables - as for the rest of the model.

**Comment by KarlWernersson** [comment]
We needt to change this line in 2.2.9.3

> Model partitions are initialized at their first Clock activation, not in Initialization Mode.

Maybe revrite this whole section

> Discrete-time variables computed in such a model partition are called clocked variables. Therefore, the value of a clocked variable changes only when its Clock is active. Model partitions are initialized at their first Clock activation, not in Initialization Mode.

To
Discrete-time variables computed in such a model partition are called clocked variables. The value of a clocked variable changes only when its Clock is active, after initialization has been done in initialziationMode.


Also in table 24. section 2.4.8
Add the following at initialUnknwons.
- all clocked states  (defined with elements <ClockedState>) with initial = approx or calculated.

**Comment by clagms** [comment]
FMI Design Meeting:
- The previous reference to a clocked state, during initialization, cannot have a defined start value.
- Clocked variables can be initialized during initialization mode.
- Add restrictions to the previous relation: previous variable should be of compatible type and also discrete.
