### ISSUE TITLE
Clarify allowed causalities for clockedstate/state variables and their previous values

### ISSUE THREAD

**Issue by pmai** [modelica/fmi-standard#1412]
Seperated from the discussion in #1407 we have to work out the allowed causalities for clocked/discrete states and for their previous value variables, and starting from this we need to look at the allowed and allowable initial and start value attributes for those.

**Comment by clagms** [comment]
I've placed a sentence in https://github.com/modelica/fmi-standard/pull/1413 that can act as a placeholder for the information that might be added in the current issue:
```
the variable referenced by the previous attribute must have a type that is compatible with this variable.
```

**Comment by andreas-junghanns** [comment]
> the variable referenced by the previous attribute must have a type that is compatible with this variable.

In that PR I already changed this to require "same type".
Compatible types would need definition and with signed/unsigned and min=0 we can get a lot of "smart-people" comments about what can be considered compatible... I just feel we are not asking too much to ask for "the same" as internally, previous values should be the same type anyway (in sane implementations, I know).

**Comment by andreas-junghanns** [comment]
@KarlWernersson : can you please propose what exactly we should clarify for this issue? Which combinations of attributes we should check?

**Comment by KarlWernersson** [comment]
It has to be discrete and  (only leaves local and output)
and it has to be of the same type (already specified)

Input is a bit tricky, it would be quite wrong to let previous variable (the variable referenced as in the previous attribute) be an input, however an input can have a previous attribute  (the FMU buffers it internally and want to expose it)

So maybe it is sufficient to change the current text 

> and the variable referenced by the previous attribute must have the same numeric type

to

> and the variable referenced by the previous attribute must have the same numeric type and cannot have causality == input

**Comment by chrbertsch** [comment]
@KarlWernersson or @pmai : could you please prepare a PR?

**Comment by chrbertsch** [comment]
Regular Design Meeting: 

Karl: they have to be discrete, stated elsewhere.
Pierre: Why not  parameters?
Karl: They are fixed or tunable.
Pierre: "discrete" means "variability=discrete"

@clagms : I will create a PR
