### ISSUE TITLE
Clock start values

### ISSUE THREAD

**Issue by KarlWernersson** [modelica/fmi-standard#1416]
In the standard we have

`If causality = input and variability = Clock, that is, the variable is an input Clock, it is required to provide a start value for describing the expected initial condition of the input Clock for that FMU. If an input Clock has fmi3True as a start value, the environment should activate the Clock the first time it enters Event Mode. The environment can nevertheless choose different start values if it is not possible to fulfill the conditions in a simulation setup.`

I don't understand what would be the point for a clock start value.
What information does it bring.

Either the master is using a clock and then it knows if it should be active at time tStart.
Or the master is not activating the clock then it should always be false.

What does it mean to have a start == true and ofset == "some value"

Or am I missing something?

**Comment by andreas-junghanns** [comment]
The use case is initial tasks. These are tasks in controller code that are activated once when the controller starts.
We need a way to tell the importer that a clock should be active right at the start of the simulation.
I believe, this text dates back to the time when we did not have the apriodic input clocks, specifically changing clocks.

For changing input clocks, the importer has to call fmi3GetInterval() in Initialization Mode.
The FMU can now return 0.0 to request immediate activation.
With the proper priorities, initialization tasks will be activated before any of the periodic tasks.
And the FMU can then set the next interval to infinity when called with fmi3GetInterval() after that changing initial clock

@IZacharias , @MBlesken , @APillekeit : Do you agree that this is the way to handle initial tasks? Can we drop the "old" start-value text, given that we now have changing input clocks?

**Comment by IZacharias** [comment]
@andreas-junghanns Yes, I agree. I also no longer see any need for the start value for clocks. Not only changing input clocks, but also countdown clocks provide the possibility to query the start value during initialization (fmi3GetInterval()). 

@MBlesken FYI
