### ISSUE TITLE
Add clarifictions to SE and clocks

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1417]
@IZacharias : could you please include the changes in the spec that you propsed in the planned fmi-paper as suggested by @APillekeit  https://github.com/chrbertsch/fmi3paper/pull/4#discussion_r615941193 ? Thanks!

**Comment by andreas-junghanns** [comment]
Deisgn Meeting: Asked @MBlesken and @IZacharias for PR.

**Comment by chrbertsch** [comment]
I have searched but have not found the corresponding text passages in the spec (corresponding to the problematic text passages of the fmi3 paper: 

> Model partitions that are associated to output Clocks will accordingly provide the result values of the model partition’s variables for the current output Clock tick time $t_i$ of the active output Clock. The activation of such an output Clock is not controlled by the simulation algorithm but internally by the FMU.

and

> the results of the model partition defined by a triggered input Clock for the current Clock tick time

)

Thus closing; @IZacharias  or @APillekeit : Please re-open or better create a PR if you can find problematic text in the spec
