### ISSUE TITLE
Remove completedIntegratorStepNotNeeded

### ISSUE THREAD

**Issue by KarlWernersson** [modelica/fmi-standard#1419]
From the standard table 35

> If true, function fmi3CompletedIntegratorStep need not be called. If it is called, it has no effect.
If false (the default), the function must be called after every completed integrator step, see fmi3CompletedIntegratorStep.

In practice is this important?
The master could decided not to call this function if true.
 But what do we gain?
One less empty function call per integration step cycle. It feels minimal to me.

Can't we remove this feature and require this call for all fmu's. Similar as we unified calling sequence for discrete fmu's in ME

The gain would be that we lose one optional feature. That I suspect no master needs anyway. This simplifies the standard

**Comment by TorstenBlochwitz** [comment]
We gain something here! For iterative predictor corrector integration methods, we spare one additional evaluation of the whole model. If the corrector is small enough to fulfill the convergence criteria, the step might be accepted by applying these values to the state variable, but without evaluating the model using these values. But this would be necessary if at least for one FMU fmi3CompletedIntegratorStep needs to be called.

I would heavily demand to keep this capability flag!

**Comment by andreas-junghanns** [comment]
@KarlWernersson : someone needs it, it costs you little (by your own words), closing.

**Comment by KarlWernersson** [comment]
Fine by me, just needed a good reason.

**Comment by t-sommer** [comment]
Should we maybe add some non-normative text to explain this feature?
