### ISSUE TITLE
[Question] Is it allowed for fmi2GetNominalsOfContinuousStates to return nominal=0

### ISSUE THREAD

**Issue by AnHeuermann** [modelica/fmi-standard#1420]
We got an [issue on OMSimulator (#1007)](https://github.com/OpenModelica/OMSimulator/issues/1007) with a FMU returning nominals with value `0` which breaks our computation of the absolute tolerance. We "fixed" it by just rejecting FMUs that return `x_nominals[i]=0.0`.
But we are not 100% sure that our interpretation of the standard is correct and all the other importing tools that can run the SSP model from the ticket are using nominals differently.

In the FMI specification (v2.0.2)  the description of `fmi2GetNominalsOfContinuousStates` states:

>Return the nominal values of the continuous states. This function should always be called after
calling function fmi2NewDiscreteStates if it returns with eventInfo->
nominalsOfContinuousStatesChanged = fmi2True, since then the nominal values of the
continuous states have changed [for example, because the association of the continuous states
to variables has changed due to internal dynamic state selection]. If the FMU does not have
information about the nominal value of a continuous state i, a nominal value x_nominal[i] =
1.0 should be returned. Note that it is required that x_nominal[i] > 0.0 [Typically, the
nominal values of the continuous states are used to compute the absolute tolerance required by
the integrator.
Example:
absoluteTolerance[i] = 0.01 * tolerance * x_nominal[i];]

So just to double check:
Is it correct that if an FMU doesn't have nominal values `fmi2GetNominalsOfContinuousStates` must return `x_nominal[i] = 1.0`?

----
By the way, I didn't ask this question on StackOverflow because I want to have a answer from a person of the FMI group.

**Comment by KarlWernersson** [comment]
Yes

` If the FMU does not have
information about the nominal value of a continuous state i, a nominal value x_nominal[i] =
1.0 should be returned. Note that it is required that x_nominal[i] > 0.0`

I am unsure how this can be made more clear.

The other tools might not use nominal or are using the nominal given in the xml but cannot change nominal during runtime, or can handle the non supported case of nominal[0] = 0.0, or any other reason. You have to ask them how and why.
