### ISSUE TITLE
State that activateModelPartition() does not activate input clock?

### ISSUE THREAD

**Issue by oliverkotte** [modelica/fmi-standard#1421]
Shall the spec clearly state that activateModelPartition() does not set the input clock to ClockActive, as setClock() does for ME/CS? Then it becomes also clearer that activating/deactivating the input clock is not needed when implementing activateModelPartition(). This was not immediately obvious to me when browsing the spec (although it is implicit at least in Table 5) but it became obvious when reading Claudio's sentence:
> Note the difference between the partition activation function and the clock set/get functions: the later inform the Importer that a task should be scheduled, while the former executes as part of the previously scheduled task.

**Comment by andreas-junghanns** [comment]
@oliverkotte : Sounds good: please create a PR.

**Comment by chrbertsch** [comment]
So we never call setClock or getClock in SE, right? Then we should state this also in "2.2.9.5. Clocks specific API"

**Comment by oliverkotte** [comment]
The importer calls getClock on output clocks in CallbackIntermediateUpdate in SE.
But it never calls setClock in SE, right?

**Comment by andreas-junghanns** [comment]
@IZacharias or @MBlesken : Please comment here.

**Comment by oliverkotte** [comment]
If setClock is never called in SE, input clocks in SE would tick but they would never be activated, only their associated model partition would be

**Comment by IZacharias** [comment]
@oliverkotte 
> The importer calls getClock on output clocks in CallbackIntermediateUpdate in SE.
> But it never calls setClock in SE, right?

Yes, that is correct.

> If setClock is never called in SE, input clocks in SE would tick but they would never be activated, only their associated model partitions would be by way of activateModelPartition

Maybe I don't understand the question correctly. The call to the fmi3ActivateModelPartition tells the FMU that the clock is activated. What exactly do you think we should adjust in the specification?

**Comment by andreas-junghanns** [comment]
> If this is so, I propose to clarify this in the text.

@oliverkotte : Could you please create a PR?
