### ISSUE TITLE
Change "FMI interface type" to "interface type"

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1425]
See also https://github.com/chrbertsch/fmi3paper/issues/19

**Comment by andreas-junghanns** [comment]
@TorstenBlochwitz : Please weigh in on this here - you care more about style than I do and unless someone speaks out more forcefully than I did (https://github.com/chrbertsch/fmi3paper/issues/19#issuecomment-829051055), we should merge this to get it done and get back to the bigger issues.
