### ISSUE TITLE
Remnants of variability=clock

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#1441]
At some point I think we allowed variability=clock. This has now been replaced by a type Clock, but there are still some remnants, as identified by @nickbattle while upgrading the [FMI check tool](https://github.com/INTO-CPS-Association/FMI-VDM-Model): 

- [ ] Table 19. Definition of initial -- contains a row that is under the variability category.
- [ ]  Text `Attribute <<dependencies>> for output clocks (variables with <<causality>> = <<output>> and <<variability>> = <<Clock>>)`

**Comment by andreas-junghanns** [comment]
This should just be a matter of deletion, right? Can you or @nickbattle provide a PR?
