### ISSUE TITLE
Clarify semantics of clocks attribute for Clocks

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#1442]
It seems possible that a variable `C` of type Clock can refer to another clock `D` through the `clocks` attribute.
If this allowed? 
If so, what would be the meaning? My guess is that it means that Clock C *should* tick when clock D ticks? 
The meaning of *should* depends on whether C is an input clock or output clock:
- input clock -- The importer is still responsibly for activating C when D is activated.
- output clock -- The fmu will activate C when D is activated.

I haven't found this information in the standard. I would expect it to be in the table in section `2.4.7. Definition of Model Variables`, with some words regarding the semantics in section `2.2.9. Clocks`.

PS - Issue identified by @nickbattle while upgrading the [FMI check tool](https://github.com/INTO-CPS-Association/FMI-VDM-Model)

**Comment by andreas-junghanns** [comment]
We discussed this when writing this paragraph and thought it to be obvious then... maybe not:
A Clock variable C that has a clocks attribute "D" is a clocked variable depending on clock D.
 * if C is an input clock, it *can* only be activated when D is active (e.g. every second time) - still only the importer must do the activation.
 * if C is an output clock, it *can* only be active if D is active, so sub-sampling clocks are possible in this way.

@clagms || @nickbattle : Can you provide a PR to clarify this issue? To me, it might just need a brief non-normative text to explain this.

**Comment by clagms** [comment]
@andreas-junghanns it seems we're abusing the `clocks` attribute to do what the `ModelStructure` should be doing.
What you describe is essentially the feedthrough mechanism of clocks, which has the same meaning as the feedthrough of variables, and sort of clashes with the `dependencies`

imho we should keep these two meanings separate:
- `clocks` is a relationship between a variable V and a clock C, and it means V is a clocked variable, that has a value when C is ticking. This relationship, together with `ClockedState` allows us to put together the inputs and outputs of the equations that are associated to a clock.
- `dependencies` (in the ModelStructure) of an output clock C, lists all variables that contribute to clock C ticking, which can include other clock D. In the current text, we have
    ```
     Attribute dependencies for output clocks (variables with causality = output and variability = Clock) lists all known variables (including input clocks) that contribute to trigger a clock tick for that output clock.
    ```

In order to keep the two meanings separate, I propose we forbid the use of the `clocks` attribute on `Clock`.
The downside is that you cannot have feedthrough between input clocks. In any case, triggered input clocks should not have these feedthrough relationships, and time based clocks specify intervals, which make the use of feedthrough dependencies a bit weird.

**Comment by clagms** [comment]
If we decide to keep the two meaning separate, then this will also solve https://github.com/modelica/fmi-standard/issues/1443 because it will make it clear that Clocks cannot have the "clocks" attribute and therefore fix https://github.com/modelica/fmi-standard/issues/1444 as well.

**Comment by clagms** [comment]
@KarlWernersson having your input on this would also be nice!

**Comment by KarlWernersson** [comment]
For output clocks we already have this solution in modelStructure, they are listed among the other outputs. 

`Attribute dependencies for output clocks (variables with causality = output and variability = Clock) lists all known variables (including input clocks) that contribute to trigger a clock tick for that output clock. `

But this is quite different from the clocks attribute.
The model structure tells what can causes the clock to tick. (including other clocks but it could also have hidden unknowns such as a random number generator if you are unlucky =) so no guarantee that it will not tick even if all these dependencies are unchanged).
e.g.
Stochastic output clock, with an additional clock input, enforceforce_tick. Would maybe only list the enforceforce_tick as a dependency as we might not have a good way to describe the stochastic logic. and it can still tick even if enforceforce_tick is false.

the clocks attribute for a clock  makes it into a sub clock that explicitly states that this can only be activated if at least one of the clocks it is a sub of is activated.

If the same stochastic clock is a sub clock to another clock it will only activate its stochastic logic when the master clock is active. And therefore cannot tick if its master is inactive.

So I think we need both.

**Comment by clagms** [comment]
Thanks for the input @KarlWernersson ! But now I'm more confused 😄 

> The model structure tells what can causes the clock to tick. (including other clocks but it could also have hidden unknowns such as a random number generator if you are unlucky =) so no guarantee that it will not tick even if all these dependencies are unchanged).

I see that you and I have different interpretations of what these dependencies mean:
- Interp. K:  a dependency from variable `V` to a set of variables `{V1, V2, V3}`, means that `V = F(V1, V2, V3, O)`, where `O` is a set of variables whose values can change during the current super-dense time. As a result, even if V1, V2, V3, are kept constant, `V` may change.
- Interp. C: same as `Interp. K`, except that `O` can only contain constants in the current super dense time (this means that they can change, e.g., when UpdateDiscreteStates is called, but not before).

Note that V, V1, V2, and V3, can be Clocks, and that O can contain clocks.

So your random number generator would have to produce values only when UpdateDiscreteStates is called (or when entering event mode). 
Otherwise, if we took `Interp. K` to be true, there's would be no way for the importer to actually know when to call `getReal(V)`. 
If an FMU is exported under `Interp. K`, it would probably cause many hard-to-debug problems.

Taking `Interp. C` to be true, I argue that we don't need the `clocks` attribute, because the same information can be placed in the model structure: if a Clock C1 is a subclock of clock C2 (in the sense, C1 may tick _only when_ C2 ticks), then C1 declares a dependency to C2.
If we need a "more informative" relationship between clocks, I propose that we use an attribute that's different than the "clocks" attribute, to make it clear what the types are. For example:
- clocks: attribute of a Variable (except Clock) that refers to a Clock
- dependencies: attribute of an output Variable (including Clock) that refers to another variable (including Clock)
- subsample: attribute of a Clock to another Clock

**Comment by andreas-junghanns** [comment]
Web Design Meeting:
We cannot express dependencies between input clocks.
If we want to an input clock SAMPLE to be a clocked variable of another input clock MASTER, then the SAMPLE clock must have an attribute 'clocks' listing the MASTER clock.

Unless we want to forbit this (rather unusual/artificial?) use case, we should allow it in addition to the 'dependencies' attribute.

**Comment by andreas-junghanns** [comment]
@clagms : I will close this issue given our observation above, please reopen with a reason/proposal why we should forbid this.

**Comment by masoud-najafi** [comment]
I have started to implement for import/export some basic FMUs for clocks, such as periodic clocks, etc. They will be shared before the PlugFest. But, I cannot find in the specification the way several FMUs can be synchronized, or even simpler, "the way a ClockUnion block  could be implemented (a clock that triggers synchronously when a time-based or a triggered clocks ticks). Another important basic FMUs are conditionalSampler and subsampler that would be very helpful for understanding of clocks in FMI-3.0. It would be helpful, if you could provide me a pointer.
