### ISSUE TITLE
Two variables cannot have the same previous attribute

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#1443]
I could not find information on the standard, but I think it should be explicit that two variables `V1` and `V2`, cannot have the previous attributed pointing to the same variable `PV`.

I would expect to find this information in the `previous` attribute description, near the text:
`If present, this variable is a ClockedState and this attribute is a value reference to the variable with the previous value. `

PS - Issue identified in discussion with @nickbattle while upgrading the [FMI check tool](https://github.com/INTO-CPS-Association/FMI-VDM-Model)

**Comment by andreas-junghanns** [comment]
Why do you think this is not possible? What about aliases?
Do you think it makes no sence or do you see a contradiction or inconsistency to allow this?

**Comment by clagms** [comment]
I should have been clearer indeed.
Scenario:
1. Assume `V1` and `V2` have the same previous variable `PV`.
2. Assume `V1` and `V2` point to the same clock `C`.
3. Assume `C` ticks and the importer does the usual.
4. When `UpdateDiscreteStates` is called, `PV` has to be updated by the FMU to the value of *either* `V1` or `V2`. This is the problem I think.

**Comment by KarlWernersson** [comment]
The only way this would work if if they are aliases,

However in fmi 3 aliases no longer has attributes of their own besides descriptions and display unit and they are as sub variable of their "master" variable. So this cannot happen any more but rather all aliases has the same previous by default.
