### ISSUE TITLE
Clarify fmi2GetContinuousStates with zero states

### ISSUE THREAD

**Issue by chria** [modelica/fmi-standard#1447]
Is it legal to call fmi2GetContinuousStates when there are zero continuous states in the model? For instance would it be legal to call:

`fmi2GetContinuousStates(<pointer to fmi struct>, NULL, 0)`

and would this return FMI OK?

**Comment by jschueller** [comment]
currently openmodelica returns an error code if the array (2nd argument) is NULL regardless of the number of continuous states and we'd like to know if this implementation is valid wrt the standard

**Comment by andreas-junghanns** [comment]
I looked into 2.0.2 and did not find it specified there - suboptimal, agreed.
If the standard is silent, one should assume it is legal to call with NULL and 0 and magnamoniously return fmi2OK.

Maybe one could log a message stating that the FMU finds it odd to be called that way with 0 states.

**Comment by andreas-junghanns** [comment]
See #1451: At least for 3.0 we should get this improved.
Can we close this issue?

**Comment by chria** [comment]
@andreas-junghanns  Thanks for the feedback! Yes, I believe we can close this.
