### ISSUE TITLE
Should clock variables have start value?

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#1448]
In the standard it says, for an input clock variable C:
- C must have variability=discrete
- If not provided, the initial of C is determined by Table 19, which leads to initial=exact
- For initial=exact, C's start value must be provided.

Is this intentional? If it is, what would be a start=active mean? That C is active during the entire initialization mode (presumably activated by the Importer), and becomes inactive as soon as exit initialization mode has been called?

PS - Issue identified by @nickbattle while upgrading the [FMI check tool](https://github.com/INTO-CPS-Association/FMI-VDM-Model)

**Comment by KarlWernersson** [comment]
https://github.com/modelica/fmi-standard/issues/1416

**Comment by clagms** [comment]
Thank you @KarlWernersson 

I guess then that a PR is needed to make this clearer. I can do that before end of next week.

**Comment by clagms** [comment]
I'm afraid the solution to this issue warrants some discussion, before I can make a PR.
There are multiple ways to address this:
1. Should we forbid the use of the `initial` attribute for clocks?
2. Should we restrict the value of `initial` to a default value, like we do for output variables, as in
    ```
    If causality = output the initial attribute value is set to calculated and no start value is provided.
    ```

Item 1 makes sense and would be my pick, since the `causality` and `interval` attributes alone determine how the initial interval of the clock is obtained.
But it requires changing the xsd schema I think, so I'd need some input from @pmai .

Item 2 can be done in the document, but for some clock types, it might seem counterintuitive. In particular, all clocks can be forced to have `initial=calculated` but this means an input clock with `interval=fixed` , that requires setInterval in initialization mode, would have that too.

@andreas-junghanns et al, which one of the above should be taken? Or are there better ways?

**Comment by andreas-junghanns** [comment]
I think 1) is the better way: the importer must have autonomy in setting the clock at the beginning as it sees fit.
If we allow an initial value to be given, it would mean the FMU can determine exactly when the first tick happens - that would be different to all the other clock ticks.

**Comment by KarlWernersson** [comment]
> If causality = output the initial attribute value is set to calculated and no start value is provided.

This is wrong and should be removed., see table 19 below.
I suppose it is a remnant form when clocks where merged with the standard. and previously only applied to output clocks, but as the text is written now complexly confusing. 

But since we don't use start values for clocks-> just call get clock on all your output clocks as you will do in all subsequent events. No need for special handling here.

**Comment by clagms** [comment]
Then applying solution in Item 1 will also fix https://github.com/modelica/fmi-standard/issues/1449

**Comment by clagms** [comment]
The good news is that someone has already fixed the XSD according to Item 1 so we just need to update the text.

**Comment by andreas-junghanns** [comment]
@KarlWernersson : Please check the PR #1457 - is this the cleanup you think should be done?
