### ISSUE TITLE
Clarify meaning of Clocks in InitialUnknowns

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#1449]
The standard states:
- Output clocks can have initial=calculated (Table 19)
- Therefore output clocks should be part of InitialUnknowns section (Table 24. ModelStructure elements).0

Is this allowed? If so, what would be meaning be? That the FMU may decide to activate the clock during initialization mode?

PS - Issue identified by @nickbattle while upgrading the [FMI check tool](https://github.com/INTO-CPS-Association/FMI-VDM-Model)

**Comment by KarlWernersson** [comment]
Clocks are not in intial unknwons. They can be activated in the event directly after intiialzation before advancing continuous time

clocked outptus and states can optinaly be part of initial unknowns and can then be solved during initialization mode.

https://github.com/modelica/fmi-standard/issues/1407

**Comment by clagms** [comment]
Thank you @KarlWernersson . Then a PR is needed.

**Comment by clagms** [comment]
Closed by solution to https://github.com/modelica/fmi-standard/issues/1448
