### ISSUE TITLE
Clarify callback function pointers may or may not be NULL

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1451]
I am sure we discussed if NULL is allowed for callbacks - it is not clearly spelled out in the standard (at least I did not find it quickly).

**Comment by andreas-junghanns** [comment]
While looking at how strict we are on the usage of NULL, we should clarify if pointers to arrays with 0 length may be 0.

**Comment by andreas-junghanns** [comment]
> 
> 
> I am sure we discussed if NULL is allowed for callbacks - it is not clearly spelled out in the standard (at least I did not find it quickly).

1. I found `The co-simulation algorithm signals the support for Intermediate Update Mode by providing a non-NULL callback-function pointer for intermediateUpdate.` - this suggests that NULL is allowed for a callback function.
2. I found `Even if the scheduler does not support preemption, at least an empty implementation of these callback functions must be provided to allow the reuse of code for different modes together with an efficient preemption. [This avoids checks for null function pointers. A function call to a void-void function with an immediate return is hardly any overhead.]`. This requires this callback to be non-NULL.

Can we find a better general rule?
If not, we should spell it out at least for each callback function explicitely.

**Comment by KarlWernersson** [comment]
In principle yes but what does it mean that it is allowed ?
That you expect the FMU to not crash? Or the FMU to be ok?

It is slight more complicated as you have some combinations that dont make sense.

> typedef fmi3Instance fmi3InstantiateCoSimulationTYPE(
    fmi3String                     instanceName,
    fmi3String                     instantiationToken,
    fmi3String                     resourcePath,
    fmi3Boolean                    visible,
    fmi3Boolean                    loggingOn,
    fmi3Boolean                    eventModeUsed,
    fmi3Boolean                    earlyReturnAllowed,
    const fmi3ValueReference       requiredIntermediateVariables[],
    size_t                         nRequiredIntermediateVariables,
    fmi3InstanceEnvironment        instanceEnvironment,
    fmi3CallbackLogMessage         logMessage,
    fmi3CallbackIntermediateUpdate intermediateUpdate);


Having logginON  == fmi3True AND logMessage == NULL
Having   earlyReturnAllowed == fmiTrue AND intermediateUpdate == NULL
having nRequiredIntermediateVariables > 0 AND intermediateUpdate == NULL

These combinations are not allowed and should return fmi3Error I suppose, but in the end it is kind of up to the implementer.

In addition-> that we have requiredIntermediateVariables[] and  nRequiredIntermediateVariables in instantiate, partially makes 
statemen 1, from @andreas-junghanns comment a bit weaker. 

Maybe it is sufficient to state that it is allowed to give Null fir the callback and that (obviously) disables any feature that uses them. 
Then a good implementation can check for the above contradicting combinations and give error with a clear  message (although hard if logMessage is NULL)

**Comment by andreas-junghanns** [comment]
@KarlWernersson : you are right `requiredIntermediateVariables` is another case: we allow `nRequiredIntermediateVariables` to be 0, but we never say if the pointer must then be NULL - which we should.
But again: Would it not be simpler to have a general rule saying "any pointer can be NULL" so long as that is consistent with the rest of all settings.
Then the cases above (loggingOn == fmi3True AND logMessage == NULL as example) can be handled properly as errors.

**Comment by KarlWernersson** [comment]
Fine with me =)

**Comment by jschueller** [comment]
seems the style of coding in openmodelica I've seen so far is more conservative: check every argument is non-null else return an error code

**Comment by pmai** [comment]
I definitely also remember that this issue was discussed at some point during either the 1.0 or 2.0 cleanups, so maybe we can find something there?

**Comment by andreas-junghanns** [comment]
> Fine with me =)

When I looked for a good place where to place that, I found this:
`In general, FMI function arguments are not allowed to be NULL, unless explicitly allowed by the standard document where NULL will be assigned a specific semantic.
[For an example of NULL being explicitly allowed see resourceLocation. Careful implementations should still guard against NULL pointers.]`

This contradicts my previous suggestion. 👎 
So, do we want to add or change this?
I would prefer:
`In general, FMI function arguments are allowed to be NULL, unless explicitly forbidden by the standard document where NULL cannot be handled.
Such a NULL must be consistent with all other setting, especially if a capability flag announces support for a feature that requires specific callback functions to exist.
If a pointer to an array is NULL, the respective number of elements must be 0.`

**Comment by andreas-junghanns** [comment]
@t-sommer made a different proposal: declare these values as undefined because it makes no sense to use a pointer if it points to 0 elements. If that is agreable, it should be stated clearly "at the proper place".
@t-sommer : Can you create a PR for that?
