### ISSUE TITLE
Inconsistency between XSD and Variable Attributes section in document

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#1454]
While trying to fix https://github.com/modelica/fmi-standard/issues/1448 , I noticed that section `2.4.7.4. Variable Attributes` is inconsistent wrt to the new XSD Schema:
- there is no `fmi3VariableBase` anymore, since it was renamed to `fmi3AbstractVariable`, and some of its attributes were split to distinguish Clocks from other variables (and probably other reasons).

Sol1: To fix this, I propose that `Figure 23. fmi3VariableBase element.` is split into different figures, each representing one of the subclasses of `fmi3AbstractVariable`, and that a table, or list, or column of `Table 18. fmi3VariableBase attribute details.` , be added, clarifying which kinds of variables correspond to which subclass. For example: `initial - every variable type except Clock`.

Sol2: Alternatively, since this information can be read from the Schema, which should be the source of truth, we could refer the reader to it, and avoid more inconsistencies. The problem with this solution is that the same argument can be used for many other aspects of the standard...

@andreas-junghanns I need to fix this one before I can fix https://github.com/modelica/fmi-standard/issues/1448 . Should we go for Sol1 above?

**Comment by t-sommer** [comment]
Sol1 sounds good.

**Comment by andreas-junghanns** [comment]
I would also prefer sol1.

**Comment by andreas-junghanns** [comment]
I have implemented Sol1, except I did not annotate the attribtues as to which type they belong to - that is easily gathered from the XSD or images.
