### ISSUE TITLE
Starting values for simple and multi-dimensional String variables

### ISSUE THREAD

**Issue by paulfilip** [modelica/fmi-standard#1463]
For String multi-dimensional variables, the starting values are given modelDescription.xml through the 'Start' elements and the 'value' attributes. This remark is in the standard:
For variables of type < String>, the start values are not given as a list in the start attribute but as a sequence of < Start> elements with a value attribute.
For me it is unclear if this rule also applies for a simple String variable. Does it need to have a < Start> child element to retrieve its start value or can it be done through the attribute start such as < String .... start ="startValueString" />?

**Comment by pmai** [comment]
For string variables there is no start attribute (see the schema definition), so the sub-element must always be used.

**Comment by andreas-junghanns** [comment]
I agree with closing this particular issue, but:
 - there is no schema in the standard for String (that would have clarified this with more ease for Paul)
 - the latest changes to the schema are not reflected in the generate_figures.ps1, e.g. the fmi3VariableBase does not exist anymore and the schema PNG generation fails

@t-sommer : new issue? Will you just fix that as a fallout of the previous changes?

**Comment by andreas-junghanns** [comment]
I agree with closing this particular issue, but:
 - there is no schema in the standard for String (that would have clarified this with more ease for Paul)
 - the latest changes to the schema are not reflected in the generate_figures.ps1, e.g. the fmi3VariableBase does not exist anymore and the schema PNG generation fails

@t-sommer : new issue? Will you just fix that as a fallout of the previous changes?

**Comment by t-sommer** [comment]
> new issue?

Yes, please. This issue is invalid (see @pmai 's comment).
