### ISSUE TITLE
start value of binary variables in the xml

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1467]
The "start" value of binary variables is written with string using HEX characters. The  length of each element of a multi-dimentional binary variable is not known. shouldn't the "start" value of binary variables be defined in the same way as a string variable in the XML, i.e., as a sequence of <Start> elements with a value attribute.

**Comment by chrbertsch** [comment]
@pmai : could you please comment? 
@masoud-najafi : could you make a concrete proposal in form of a PR?

**Comment by pmai** [comment]
There is no need for this, since whitespace can be unambiguously used to separate individual items for hex (space is not allowed inside hex). For strings we cannot do so since whitespace is allowed as content of the string, hence cannot be used for separation of the list items...

**Comment by chrbertsch** [comment]
@pmai , @masoud-najafi : Could you provide an example for this in the standard text?

**Comment by masoud-najafi** [comment]
Thank you both. I have no example, I am just developing the parser, and I saw the need for that. So we should use Spaces to separate chunk of binary data, similar to other types.
