### ISSUE TITLE
nValueReferences in GetXXX and SetXXX

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1468]
In section 2.2.6.2. Getting and Setting Variable Values: it is written:
[nValues and nValueReferences is, strictly speaking, redundant information, but is added to ensure memory safety and other sanity checks.]

I understand that nValues is redundant, but not sure about nValueReferences.  Please check if this is correct.

**Comment by chrbertsch** [comment]
I agree that nValueReferences is not redundant.
