### ISSUE TITLE
needsExecutionTool attribute

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1470]
In the standard i is mentioned that "The name of the tool can be taken from attribute generationTool in <fmiModelDescription>.
But the exporter tool and the importer tool may be different, or their version may be different.
needsExecutionTool is currently a boolean value,  shouldn't needsExecutionTool  be a string (with empty default value) indicating the name of the require is d tool?

**Comment by chrbertsch** [comment]
Regular Design meeting: 
Torsten: this flag just signals to the user that the FMU is not to simulated just as it is. It is not complete.
One could just add an error message
Christian: Best provide information on the needed tool etc. in the documentation folder.

I propose to add a sentence in the implementers guide.

**Comment by andreas-junghanns** [comment]
@chrbertsch : If this is a point for the implementer´s guide, can you add it to the list there and close this issue here?

**Comment by chrbertsch** [comment]
added to https://github.com/modelica/fmi-standard/issues/1029#issuecomment-876591291
