### ISSUE TITLE
Clarification for Table 19: clocks attribute

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1471]
In Table-19 for the "clocks" attribute, it is mentioned that 
"[More rigorous importers requiring a variable to be dependent on a single clock can reject FMUs violating this restriction.]"
I wonder what "More rigorous importers" exactly means. If assigning a variable to several clocks is allowed, it is then a correct FMU and the FMU may be simulated. It is also fine and normal that an importer that cannot simulate this FMU, reject it.

**Comment by chrbertsch** [comment]
Regular design meeting: 
Replace "rigorous" by "importers who do not support ... can check this from the XML and reject the simulation of such an FMU"
