### ISSUE TITLE
Relax requirements for including binary dependencies

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1477]
Currently the docs state that

> Dynamic link libraries must include all referenced resources that are not available on a standard target machine [for example, DLLs on Windows that are built with Visual Studio should be compiled with the /MT option to include the required symbols from the Visual C runtime in the DLL, and not use the option /MD where this is not the case]. When compiling a shared object on Linux, RPATH="$ORIGIN" has to be set when generating the shared object in order that shared objects used from it, can be dynamically loaded.

However this renders any FMU illegal that cannot link statically against the VS runtime or depends on DLLs that "are not available on a standard target machine" (whatever that means), e.g. commercial third party libraries or applications that cannot be shipped with the FMU.

I propose to relax to this to _should include_ and also backport this change to `2.0.x`.

See also https://github.com/modelica/fmi-cross-check/issues/57.

**Comment by lochel** [comment]
This makes testing unnecessary complicated. For the sake of the cross-check all FMUs should encapsulate everything needed.
