### ISSUE TITLE
Handling of hidden states (delay buffers, plug-flow buffers, ...)

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#148]
**Reported by otter on 14 Oct 2013 07:22 UTC**
If an FMU is used by a collocation optimization method it is essential that all internal states of the FMU are reported, and that there are no hidden states. 

Typically, there are cases where hidden internal buffers for continuous-time variables are used in a simulation model, for example, buffers to model time delays, or buffers to model transport delays (like plug flow). At a minimum, in the xml-file it should be stated that such hidden (continuous-time) states are present in order that a specialized tool can print a warning, in case it is known that this will not work. The question is, whether it would be also possible to report these buffers to the environment.

----

Migrated-From: https://trac.fmi-standard.org/ticket/148

**Comment by modelica-trac-importer** [comment]
**Comment by rfranke on 20 Mar 2014 15:39 UTC**
Would be great to get a flag in FMI 2.0 indicating if there are internal buffers.

The communication to the environment can be done through continuous or discrete states.

**Comment by modelica-trac-importer** [comment]
**Comment by karl&#46;wernersson on 19 Oct 2017 14:29 UTC**
Would there be any need for this flag when clocked systems are sported in a future fmi version and discrete states are exposed in modelDescription?

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 1 Jun 2018 12:48 UTC**
Is this covered by the Clocks FCP?

**Comment by chrbertsch** [comment]
Regular design webmeeting:
Karl: only part of this is supported by the clocks FCP
Otto: The proposal is to have a flag. Could be something like HasInternalStates DontKnowIfItHasInternalStates DoesNotHaveInternalState
Masoud: For CS FMUs this flag would be always true.

@MartinOtter and @rfranke: could you please provide more details and come up with a proposal?
Otherwise we shall close the issue


> The communication to the environment can be done through continuous or discrete states.

**Comment by chrbertsch** [comment]
Regular Design Webmeeting

Closing this ticket until some comes up with a concrete proposal.
