### ISSUE TITLE
Add pointer to fmi3InstanceEnvironment to fmi3Callback{Lock|Unlock}Preemption()

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1508]
so the importer knows the origin of the call.

**Comment by andreas-junghanns** [comment]
If I remember correctly, we discussed this and decided against it, because the importer knows which partition is currently active. @MBlesken : could you please confirm?

**Comment by t-sommer** [comment]
But how do you know which instance, if you have multiple (especially if they don't need to be synchronized globally)?

**Comment by MBlesken** [comment]
> If I remember correctly, we discussed this and decided against it, because the importer knows which partition is currently active. @MBlesken : could you please confirm?

@andreas-junghanns unfortunately I don't recall the discussion. It might have been before my time. I am also not sure why you are asking this in this context. But, the importer knows which model partition is active and it could also save information to retrace which FMU is providing this model partition. ...

>But how do you know which instance, if you have multiple (especially if they don't need to be synchronized globally)?

@andreas-junghanns @t-sommer ... note that the importer is providing the pointer to the callback when instantiating an FMU. If the importer would want to distinguish which FMU called the lock/unlock it could pass out dispatcher (i.e. different callbacks to different FMUs who are then still using the same locks), right? Nevertheless, I am not sure why it could be important to distinguish which FMU called. 

Also note that different FMUs must not (cannot) share common global variables. So there is no reason why they should protect variables against access of another FMU. Again, I have a feeling we should discuss this in person, but I hope this helps.

**Comment by andreas-junghanns** [comment]
FMI web design meeting (Pierre, Andreas and TorstenS): we leave things as they are.
