### ISSUE TITLE
 Clarification on specifying intervalDecimal  &  shiftDecimal in the XML

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1514]
It would be helpful if It is stated somewhere in the specification that for which type of clock(s) intervalDecimal  &  shiftDecimal  must (or must not) be specified in the XML.

**Comment by andreas-junghanns** [comment]
This seems pretty clear to me, please see explanation of `resolution` - this table explains the optional XML attributes and how they relate. It is also clear which clocks must support Get/SetInterval - see the clocks table.
What exactly is missing?

**Comment by masoud-najafi** [comment]
Sorry,  I cannot find where it has been explained that intervalDecimal and shiftDecimal **attributes** are forbidden for Aperiodic clocks, maybe I am not checking the right specification.
