### ISSUE TITLE
fmi3GetXXX and fmi3SetXXX for clocked variables

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1525]
in section 2.3.5. (State: Event Mode) where  "Allowed Function Calls" is explained, it is mentioned that

"
Function fmi3Set{VariableType}:
This function can be called for variables with causality == input and for variables with causality == parameter and variability == tunable.

Functions fmi3Get{VariableType}:
Getting variables might trigger computations.
"
I have two questions concerning these APIs for variables whose "clocks" attributes is not empty, i.e., clocked variables:

1) Can SetXXX be called for a clocked-Input  variable when the corresponding clock is NOT active? 
2) Can GetXXX be called for a clocked-Output variable when the corresponding clock is NOT active? 

For me the answer is negative for both. The first one is obvious, and for the second one, if the importer needs the output, the sample and hold value has been already read by the importer at the previous tick of that clock and the value of the clocked-variable is available for the importer.

I think it is important to clarify this, it if it not already explained elsewhere.

**Comment by andreas-junghanns** [comment]
I checked and I could find only one sentence in `2.2.9.3. Model Partitions and Clocked Variables`:
`A clocked variable vk can acquire a new value and can be queried only when its Clock k is active, except during Initialization Mode.`

I think we should add a similar explanation in `2.2.6.2. Getting and Setting Variable Values`. I will create a PR.
