### ISSUE TITLE
Remove attributes "intervalDecimal" and "shiftDecimal"

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1527]
One of irritating things that I have encountered in FMI3 with clock variables is the fact that for periodic clocks
the start" value is not used but instead there are two  other attributes "intervalDecimal" and "shiftDecimal" that may be changed by the user.
What if these attributes be defined by other variables Float64 or UInt64 and only their references by used by the Clock variable?
In this way, in the table 5:

a "Constant periodic"   clock is a clock whose "intervalDecimal" and "shiftDecimal" are variables with Constant   variability.
a "Fixed periodic"      clock is a clock whose "intervalDecimal" and "shiftDecimal" are variables with Fixed      variability.
a "Calculated periodic" clock is a clock whose "intervalDecimal" and "shiftDecimal" are variables with Calculated variability
a "Tunable periodic"    clock is a clock whose "intervalDecimal" and "shiftDecimal" are variables with Tunable    variability

or in brief:
The "interval" type of a "periodic" clock is defined by the variability of the variables that are referenced by the Clock variable. The referenced variable may be, for example, a vector if size [1,2] to define [intervalDecimal, shiftDecimal] and may be of Type Float64 or UInt64.

In this way the table 5 may be simplified, and we get ride of these attributes in a variable of type Clock.  If you agree, we can discuss to polish this proposal to make it adequate.

**Comment by masoud-najafi** [comment]
Also using a different variable would allow to get rid of four APIs:
fmi3SetIntervalXX, etc. and used standard fmi3SetXXX instead.

**Comment by andreas-junghanns** [comment]
I like the idea of simplifying the API.
Before we work out details, let´s consider a few issues that you are not mentioning, like the fraction mechanism with multiples of resolutions - how would that play into your proposal?

**Comment by andreas-junghanns** [comment]
Also: your proposal does not consider changing and countdown clocks, for those we would still need those APIs, right?
The interval attribute would also be needed to define the clock type for clocks other than time-based clocks.
So we would still have the interval attribute, with fewer values because for the time-based clocks the values would be derived from the valueReferences pointed to by the Clock?

Also, the number of attributes for Clock would not drop: we need defined the value references...

**Comment by andreas-junghanns** [comment]
Web design meeting (Andreas and TorstenB): the qualifier argument of GetInterval would still have to be coded in yet-another-valueReference to an enumeration variable... is that really simpler?
If the interval depends on more than one parameter (tunable and fixed clocks) a single valueReference is not sufficient.

Summary:
 - The API cannot be simplified because of changing and countdown clocks.
 - The interval attribute is still required to distinguish between triggered and countdown and changing clocks.
 - The mechanism does not work if the interval depends on more than one variable.

We do not see how your proposal would simplify the Clocks handling: it would splinter the different Clock types and would still require API and attributes as today.

Please re-open with new arguments.

**Comment by masoud-najafi** [comment]
@andreas-junghanns 

AJ) The API cannot be simplified because of changing and countdown clocks.

MN) SetIntervalXX is not used in changing and countdown clocks. So it can simply be removed and use SetXX instead for Periodic clocks.


AJ) The interval attribute is still required to distinguish between triggered and countdown and changing clocks.

MN) Of course we need it, but it takes only these values: ["periodic", "changing", "countdown","triggered"]. Isn't more clear?


AJ) The mechanism does not work if the interval depends on more than one variable.

MN) Currently the "tunable interval" behaves like a "calculatedParameter" with "tunable" variability.
If the interval depends on several tunable parameters, the variability is still "tunable", but the causality would be "calculatedParameter". So it is consistent with the current spec.


Now concerning handling Fractional type intervals.
The referenced variable  can be either  1x2 vector, i.e.  [intervalDecimal,  shiftDecimal] for decimal interval types.
Or a 1x3 vector for fractional interval types i.e.,  [resolution, intervalCounter, shiftCounter].

**Comment by masoud-najafi** [comment]
AJ) The API cannot be simplified because of changing and countdown clocks.

MN) SetIntervalXX is not used in changing and countdown clocks. So it can simply be removed and use SetXX instead for Periodic clocks.

AJ) The interval attribute is still required to distinguish between triggered and countdown and changing clocks.

MN) Of course we need it, but it takes only these values: ["periodic", "changing", "countdown","triggered"]. Isn't more clear?

AJ) The mechanism does not work if the interval depends on more than one variable.

MN) Currently the "tunable interval" behaves like a "calculatedParameter" with "tunable" variability.
If the interval depends on several tunable parameters, the variability is still "tunable", but the causality would be "calculatedParameter". So it is consistent with the current spec.

Now concerning handling Fractional type intervals.
If the data-type of the reference variable is Float64,  the start value of the referenced variable should be a 1x2 vector, i.e. [intervalDecimal, shiftDecimal] for decimal interval values.
If the data-type of the reference variable is Uint64,  the start value of the referenced variable should be a 1x3 vector, i.e., [resolution, intervalCounter, shiftCounter] for fractional interval values.

**Comment by masoud-najafi** [comment]
Here is the list of benefits of this proposal:

fmi3SetIntervalDecimal  ->To be removed and  be replaced by setFloat64
fmi3SetIntervalFraction ->To be removed and be replaced by setUInt64
fmi3GetIntervalFraction ->To be removed and be replaced by getUInt64
fmi3GetShiftFraction    ->To be removed and be replaced by getUInt64
fmi3GetShiftDecimal     ->To be removed and be replaced by getFloat64

fmi3GetIntervalDecimal ->used only by "changing" and "countdown" clocks. (may be renamed to fmi3GetInterval)

--The Clock variable attribute "supportsFraction" will be removed
--The Clock variable attribute "PeriodicIntervalReference" will be added

--I do not know if it is useful or not, but the "Interval" and "Shift" for periodic clocks may not be limited to Float64 and UInt64 data-types. They can be of any FloatX and IntX and UIntX data type.

--Unlike the current spec where tunable interval does not exist (it is a calculated value as a function of tunable parameters) , a real tunable interval can ALSO be defined.

I think @t-sommer will like these simplifications.

**Comment by TorstenBlochwitz** [comment]
I would still prefer the current solution! It is symmetric and very clear. We would have to formulate restrictions on these variables, we would require support of vectors and so on.

**Comment by andreas-junghanns** [comment]
Web Design Meeting: the changes would be massive and late in the process and we do not even know if it truely simplifies the usage. We decided to close this issue.
