### ISSUE TITLE
NULL pointer for logMessage and intermediateUpdate callbacks

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1529]
In the specification, it is mentioned that 
"If loggingOn == fmi3False, then any logging is disabled and the logMessage callback function is not called by the FMU."
Does this mean that he logMessage callback pointer can be NULL? If yes, it may worth to be clarify.

In section 238 is mentioned that
"The co-simulation algorithm signals the support for Intermediate Update Mode by providing a non-NULL callback-function pointer for intermediateUpdate."
Which means the intermediateUpdate  callback can be NULL. Then it would be good to mention somewhere that if this callback is not provided, the "eventModeUsed" and "hasEventMode" arguments of fmi3InstantiateCoSimulation() must be false and nRequiredIntermediateVariables be zero.

**Comment by andreas-junghanns** [comment]
I think if we go through and mark every little bit that makes no sense, we will create a lot of text and a lot of potential confusion.
I created a PR where I state that if NULL is send in and you still "do stuff" with what is clearly not supported, don´t expect things (undefined behavior).

@MBlesken : Note: I found an inconsistency for if NULL is allowed for lockPreemption and unlockPreemption. I now removed the part where non-NULL functions are required as this text predates the later addition to allow NULL. Please check and comment.

**Comment by MBlesken** [comment]
>  I found an inconsistency for if NULL is allowed for lockPreemption

@andreas-junghanns Where is this stated? I found text stating "In general, FMI function arguments are not allowed to be NULL, unless explicitly allowed by the standard document where NULL will be assigned a specific semantic." but I couldn't find a statement like "fmi3CallbackLockPreemption can be NULL". Is that still okay?

**Comment by andreas-junghanns** [comment]
@MBlesken : in 2.3.1. Super State: FMU State Setable: "The arguments logMessage, intermediateUpdate, lockPreemption, and unlockPreemption, are function pointers provided by the simulation environment to be used by the FMU. Each of these pointers can be NULL to indicate missing support for the respective functionality."
