### ISSUE TITLE
Clarification on providesEvaluateDiscreteStates & fmi3EvaluateDiscreteStates 

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1541]
I have built an FMU and implemented the simulator to work when the flag providesEvaluateDiscreteStates is FALSE. Now I need to build other FMUs that really need this flag to be TRUE and really need the fmi3EvaluateDiscreteStates function. That would help to understand why this flag and this API are needed, because by reading the specification, I could not understand it.

Also I have these questions:

1) The references of ClockedState variables are all available in ModelStructure. Therefore the importer can evaluate f_disc and trigger the calculation of f_dist using the GetXXX function when the clock is Active.
So is the fmi3EvaluateDiscreteStates function really a convenience function (or in other works a  redundant function)?

If it is a redundant function, how can we prevent the importer from calling fmi3EvaluateDiscreteStates 
using the providesEvaluateDiscreteStates flag while the importer can emulate this function using GetXXX?

If it is not redundant, what makes the fmi3EvaluateDiscreteStates function different from GetXXX?
-------------
2) The two equations defined in sections 2.2.9.3 and 2.3.5  are not consistent when providesEvaluateDiscreteStates is true. see the attached image.
![image](https://user-images.githubusercontent.com/33484393/131501798-615b6716-044c-4a60-b46f-3ab24a5ff2e7.png)

**Comment by TorstenBlochwitz** [comment]
In case of providesEvaluateDiscreteStates = true the importer might retrieve discrete outputs without updating discrete states. This allows for example the numeric computation of partial derivatives of discrete outputs w.r.t. discrete states by setting discrete states and retrieving discrete outputs. In case of providesEvaluateDiscreteStates = false, the formerly set discrete states are overwritten by fevent.

**Comment by andreas-junghanns** [comment]
Web Design Meeting: we will try to discuss this with Rüdiger. Masoud will contact him to discuss his issue.

**Comment by rfranke** [comment]
I agree with Torsten. Please see also the notes of the discussion on June 23 under #1450.
If you don't need the separate evaluation of discrete states, then your importer does not need to call this function even if it is provided. `fmi3UpdateDiscreteStates` will do this.

**Comment by masoud-najafi** [comment]
HI Rüdiger @rfranke 

I need to understand this flag and its usage to implement it correctly for at least for the  import.
Let’s consider the standard LTI discrete state-space case:

x(n+1)=a*x(n)+b*u(n)    
y(n)  =c*x(n)+d*u(n)      

which is represented as follows in the standard

xd(n)=a*xd(n-1)+b*u(n)    (Fd)
y(n)=c*xd(n-1)+d*u(n)     (Fy)

Now consider the two cases:
A) providesEvaluateDiscreteStates==FALSE, 
 --The function fmi3EvaluateDiscreteStates is not called (or not available).
 --If I understand correctly, the two equations (Fd and Fy) are mixed and they cannot be separated, i.e., we have a single function Fd_Fy to update xd and y
    
  xd(n), y(n)=[a*xd(n-1)+b*u(n), c*xd(n-1)+d*u(n)]  (Fd_Fy)

--In the super-dense time calling GetXX(y), updates Fd_Fy and y(n) and xd(n) are updated as a function of x(n-1) and u(n)

--Since  according to standard the valueRefenreces of xd are also available, what happens if GetXX(xd) is called? < - -- **TO BE CLARIFIED** 

--in fmi3UpdateDiscreteStates
   states are updated.    x(n-1)  <- x(n)  


B) providesEvaluateDiscreteStates==TRUE. 

 --The function fmi3EvaluateDiscreteStates is called.

--In the super-dense time:
    GetXX(y) calles Fy and y(n) is updated 
    calling fmi3EvaluateDiscreteStates updates xd(n)  

--Since  according to standard the valueRefenreces of xd are also available, 
  calling GetXX(xd), is it equivalent to calling fmi3EvaluateDiscreteStates ? < - -- **TO BE CLARIFIED**

--in fmi3UpdateDiscreteStates
   states are updated.    x(n-1)  <- x(n)  


If I understand correctly, your use-case is the case (B) and you need to update y without updating xd (calling only Fy).
Can you provide the very simple LTI discrete-state-space for it? Is your use-case equation something like (Fy2)?

xd(n)=a*xd(n-1)+b*u(n)                  (Fd)
y(n)=p*xd(n)+q*xd(n-1)+r*u(n)      (Fy2)

**You need to obtains p and q and r coefficients by using the Jacobian and perturbations of xd and xd(n-1)?**   
**Are p and q coefficient are non-zero?**

Before continuing the discussion, please let me know whether what I have written above is correct .
Thanks
Masoud

**Comment by masoud-najafi** [comment]
OK.
So let's first define how a simple standard LTI system is represent in the standard, remind the following form

x(n+1)=a*x(n)+b*u(n)
y(n) =c*x(n)+d*u(n)

is already used in other well-know simulation tools in the control field such as Simulink. 
This form, as you indicated, is different from the FMI spec.  So How FMI wants to define this LTI case????
----------------
Then if GetXX(xd) does not update Fd, is its behavior is undefined. What does it do? GetXX(xd)  MUST trigger the calculation of xd, unless we declare it somewhere that for this particular case it does differently.

What about other parts of my questions?
Thanks

**Comment by rfranke** [comment]
This is what the specification says:
<img width="926" alt="Screenshot 2021-09-02 at 12 53 18" src="https://user-images.githubusercontent.com/4224368/131831544-9340fb64-f0bb-453f-8441-f996bdbf2b66.png">

To me this means that `fmi3Get` only triggers the evaluation of discrete states if `providesEvaluateDiscreteStates` is false. If it is true and you want to obtain the new states with `fmi3Get`, then you need to call `fmi3EvaluateDiscreteStates` before `fmi3Get`.

> What about other parts of my questions?
Your other questions go very far, up to "So How FMI wants to define this LTI case?". This might be too much for single issue.

**Comment by masoud-najafi** [comment]
**To me this means that fmi3Get only triggers the evaluation of discrete states if providesEvaluateDiscreteStates is false. If it is true and you want to obtain the new states with fmi3Get, then you need to call fmi3EvaluateDiscreteStates before fmi3Get.**

I do not know how you could deduce this from the specification, but that's very interesting to know.
 @andreas-junghanns @TorstenBlochwitz  Do you get it in the same way, by reading the spec? Here you change the way GetXX works with a capability flag.

**Comment by masoud-najafi** [comment]
@rfranke 
My question is not about the LTI form in FMI, it looks like nobody cares. My question is about your models that required this changes. So I repeat my question asked above:

B) providesEvaluateDiscreteStates==TRUE.

--The function fmi3EvaluateDiscreteStates is called.

--In the super-dense time:
GetXX(y) calles Fy and y(n) is updated
calling fmi3EvaluateDiscreteStates updates xd(n)

--Since according to standard the valueRefenreces of xd are also available,
calling GetXX(xd), is it equivalent to calling fmi3EvaluateDiscreteStates ? < - -- TO BE CLARIFIED

--in fmi3UpdateDiscreteStates
states are updated. x(n-1) <- x(n)

If I understand correctly, your use-case is the case (B) and you need to update y without updating xd (calling only Fy).
Can you provide the very simple LTI discrete-state-space for it? Is your use-case equation something like (Fy2)?

xd(n)=axd(n-1)+bu(n) (Fd)
y(n)=pxd(n)+qxd(n-1)+r*u(n) (Fy2)

You need to obtains p and q and r coefficients by using the Jacobian and perturbations of xd and xd(n-1)?
Are p and q coefficient are non-zero?

**Comment by rfranke** [comment]
Mostly Yes. The open points:

> --Since according to standard the valueRefenreces of xd are also available,
> calling GetXX(xd), is it equivalent to calling fmi3EvaluateDiscreteStates ? < - -- TO BE CLARIFIED

In my mind this adds an unnecessary complication if GetXX(xd) calls fmi3EvaluateDiscreteStates and GetXX(yd) does this not. But of course you have a point here if you don't want to adapt your importer to the capability flag.

> Can you provide the very simple LTI discrete-state-space for it? Is your use-case equation something like (Fy2)?

As said earlier, everything would be fine with your "standard LTI discrete state-space case":
> x(n+1)=ax(n)+bu(n)
> y(n) =cx(n)+du(n)

Then GetXX(x) returned x(n) and GetXX(y) returned y(n), independently of an update of the discrete states x(n+1). But we would get a delay of one step from u(n) -> x(n+1) to y(n+1). This is what FMI wants to avoid. 

Nevertheless you can have it with FMI by introducing a delay into your model as:
x(n)=ax(n-1)+bu(**n-1**)
y(n) =cx(n)+du(n)

**Comment by masoud-najafi** [comment]
I have not a clear mind yet. FMI standard really needs to specify the LTI case for each situation. the LTI form I mentioned is not my invention, it is the classical form used in any control textbook.

**Comment by andreas-junghanns** [comment]
Can we close this issue?

**Comment by masoud-najafi** [comment]
I could not find a simple example to implement and test and show that this feature is needed. I think this feature may lead to implicit discrete systems. But if you think that everything is clear for you, yes, you may close it.
