### ISSUE TITLE
Conflicting statements about when usage of fmi2GetXXX functions is allowed.

### ISSUE THREAD

**Issue by Krid82** [modelica/fmi-standard#1554]
The 2.0.2. standard isn't very clear or is even giving conflicting information about when it is allowed to use the `fmi2GetXXX` functions.

In **2.1.7** it says:
`The actual values of the variables that are defined in the modelDescription.xml file can be inquired
after calling fmi2EnterInitializationMode with the following functions:`

It doesn't give any restrictions other than that `fmi2EnterInitializationMode` must have been called.

In **4.2.4** it says that `fmi2GetXXX` functions can only be called in certain states. Specifically when in _InitializationMode_ on page 107 :
`The variables that can be retrieved by fmi2GetXXX calls are (1) defined in the xml file under <ModelStructure><InitialUnknowns>, and (2) variables with causality = ″output″.`

Later in the chapter (page 109) it says that while in _InitializationMode_ the `fmi2GetXXX` functions can be called
`for a variable with causality = "output" or continuous-time states or state derivatives (if element <Derivatives> is present)`

My first concern is that 2.1.7 gives the impression that it always allowed to call the `fmi2GetXXX` functions (after initialization) while chapter 4.2.4 says it's only allowed in certain states. My interpretation is that, since 2.1.7 refers to the application programming interface, that the information given in 2.1.7 merely means that it is always (after initialization) possible to read the FMU-Internal value buffers for the variables. It doesn't give any guarantees that the returned values are meaningful, though. Is that interpretation correct?

My second concern is that conflicting information is given in 4.2.4: It's my understanding that `variables listed under <ModelStructure><InitalUnkowns>` and `continuous-time states or state derivatives` are not exactly the same thing and it's not clear which of these two (different) statements has the priority.

**Comment by andreas-junghanns** [comment]
@chrbertsch : I think we can try to be more clear here. Can you try to propose the changes?

**Comment by chrbertsch** [comment]
I think we could clarify the following things:
1)  2.1. is a general description of the API; there can be further restrictions to calling certain functions in the different states of an FMU depending on the FMU kind (ME/CS)
2) Yes, `variables listed under <ModelStructure><InitalUnkowns>`  and `continuous-time states or state derivative` are exactly the same; in 2.2.8 the initial unknowns are defined as 
![grafik](https://user-images.githubusercontent.com/16363372/139601019-ee185ac8-511c-4947-912a-f793acfd54fb.png), so e.g. the calculated parameters are missing.
So we should fix footnote 2 on page 109 of FMI2.0.2 to  `variables listed under <ModelStructure><InitalUnkowns>` 

However, for FMI2.0.3 this change is too late, as the Steering committee has already voted on its release, and I do not consider this clarification important enough to halt the voting process in the MA.
I propose to mark this clarification in FMI 2.0.4, and in the meantime tickets labelled with FMI 2.0.4 can be seen as a kind of errata-document to FMI2.0.3

**Comment by chrbertsch** [comment]
I am not deep into this, but in FMI 3 we allow calling the getXXX on every variable in initialization mode, see https://fmi-standard.org/docs/3.0-dev/#InitializationMode --> Allowed function calls

Why is this different than in FMI 2.0?

**Comment by andreas-junghanns** [comment]
@chrbertsch : can´t we close this issue?
