### ISSUE TITLE
fmi3GetInterval/fmi3SetInterval/fmi3GetShift need to be replaced by Decimal and Fraction functions

### ISSUE THREAD

**Issue by dchne** [modelica/fmi-standard#1555]
Issue a)
In FMI 3.0 specification, references to fmi3GetInterval/fmi3SetInterval/fmi3GetShift should be expanded to corresponding Decimal and Fraction functions instead to avoid confusion.

Issue b)
In Section "2.2.10. Dependencies of Variables":
> The attribute supportsFraction of a Clock declares, if the fmi3SetXXXFraction and/or fmi3GetXXXFraction functions are allowed to be called.

In Section "2.4.5. Definition of Log Categories":
> supportsFraction | This attribute defines, if the functions fmi3GetXXXFraction and fmi3SetXXXFraction are allowed to be called for all time-based Clocks.

fmi3SetXXXFraction can only be fmi3SetIntervalFraction because fmi3SetShift* functions don't exist. To avoid confusion, please consider replacing fmi3SetXXXFraction by fmi3SetIntervalFraction.

**Comment by andreas-junghanns** [comment]
@dchne : Can you please review #1556?

**Comment by dchne** [comment]
@andreas-junghanns Thanks, this fixed Issue b). The change looks good to me.
