### ISSUE TITLE
Unclear specification on Scheduled Execution mode in earlier sections in FMI 3.0

### ISSUE THREAD

**Issue by dchne** [modelica/fmi-standard#1557]
In FMI 3.0 specification, description of the following concepts does not always include Scheduled Execution mode:
* super-dense time/communication point
* fmi3UpdateDiscreteStates
* canHandleMultipleSetPerTimeInstant, etc.

which may cause confusion on whether they are applicable in SE mode, especially in Section 2. For example:

> 2.2.9.1. Motivation
> exactly at which time instant, independent from continuous time specified by the arguments of fmi3SetTime or fmi3DoStep.

Does fmi3ActivateModelPartition need to be included in the text?

> 2.2.6.2. Getting and Setting Variable Values
> Variables of type Clock must be deactivated during fmi3UpdateDiscreteStates by the FMU.

Does fmi3ActivateModelPartition need to be included in the text?

> 2.4.7. Definition of Model Variables
> canHandleMultipleSetPerTimeInstant
> The default value is true. If canHandleMultipleSetPerTimeInstant = false, then only one fmi3Set{VariableType} call is allowed for this variable per super-dense time instant in Event Mode.

Is this flag applicable, or ignored in SE mode and eventless CS mode?

> 3 Model Exchange
> In contrast to Co-Simulation, the FMU is evaluated only at a specific time instant and not from one communication point to the next.

In SE mode, the time instant for external data exchange is also called communication point. However, it seems to be evaluated at one specific time instant.

> 2.2.12. Getting Derivatives of Continuous Outputs
> In FMI for Co-Simulation, the n-th derivatives with respect to time of continuous outputs can be retrieved with fmi3GetOutputDerivatives to allow interpolation/extrapolation of connected input variables between communication points by the importer in Intermediate Update Mode.

fmi3GetOutputDerivatives is available in Intermediate Update Mode for CS, but unclear if it's applicable in Intermediate Update Mode for SE.

**Comment by andreas-junghanns** [comment]
There is no Event Mode in SE. This is clear throughout the text and state diagram for SE.
Therefore, there are no super-dense time instances in SE.
There is not doStep nor setTime in SE either.

@MBlesken : Similar to #1553: is fmi3GetOutputDerivatives allowed in SE?

**Comment by chrbertsch** [comment]
Webmeeting: 

Klaus: regarding output derivatives: Why not? We have a capability flag  maxOutputDerivativeOrder.  If the FMU does not support it, it can signal it by providing a value of zero.
Karl: but we forbid many of the CS features in SE

**Comment by andreas-junghanns** [comment]
@dchne : thank you again for your pointers!
I prepared PR #1576 to address the points you raise and we (I) agree with.
Note: I chose to ignore your requests for additions when the information is availble through reasoning by "one step", here: if we discuss a function available only in Event Mode (e.g. fmi3UpdateDiscreteStates), or about the Event Mode itself, the question if that applies to SE is clear: it does not, because SE does not have Event Mode.

Please check the PR and kindly approve or request further changes there (I can still not invite you as reviewer directly, sorry).

**Comment by dchne** [comment]
@andreas-junghanns I have reviewed the change and it looks good to me. Thanks for clarifying.
