### ISSUE TITLE
fmi3GetNominalsOfContinuousStates missing from Continuous-Time Mode in Model Exchange mode

### ISSUE THREAD

**Issue by dchne** [modelica/fmi-standard#1558]
(Bundling a list of ambiguity issues to reduce interruption to Issues backlog)

a) In FMI 3.0 specification section "3.2.1. State: Continuous-Time Mode", function fmi3GetNominalsOfContinuousStates is not listed in "Allowed Function Calls". However, in section "3.3. Code Example", calling fmi3GetNominalsOfContinuousStates after fmi3EnterContinuousTimeMode appears to be valid.

b) This is not ambiguous, but it seems more readable if function signatures of fmi3GetNominalsOfContinuousStates/fmi3GetContinuousStates can be moved from section 2.3.3 to section 3.2.1, to be consistent with fmi3GetContinuousStateDerivatives.

c)  In FMI 3.0 specification section "2.3.6. State: Configuration Mode":

> Function fmi3GetContinuousStateDerivatives
> Function fmi3GetEventIndicators
> Function fmi3GetNumberOfContinuousStates
> Function fmi3GetNumberOfEventIndicators
> Can only be called in Model Exchange.

It is unclear if ME-only restriction applies to fmi3GetNumberOfEventIndicators, or all functions listed above. In section "2.3.4. Super State: Initialized", fmi3GetEventIndicators is not restricted to ME mode only. In section "2.4.8. Definition of the Model Structure":

> For Co-Simulation, elements <EventIndicator> are ignored.
> [If an FMU supports both Model Exchange and Co-Simulation, then the <EventIndicator> elements might be present, since it is needed for Model Exchange.]

which means in CS mode, there will be no means to get the number of event indicators. Therefore, fmi3GetEventIndicators cannot be called during Configuration Mode in CS mode. Similar conclusion for SE mode. SE mode seems to be missing out from the definition of "EventIndicator" attribute.

d) In FMI 3.0 specification section "2.3.9. State: Terminated"
> Function fmi3GetContinuousStateDerivatives
> Function fmi3GetContinuousStates
> Function fmi3GetNominalsOfContinuousStates
> Function fmi3GetEventIndicators
> Function fmi3GetDirectionalDerivative
> Function fmi3GetAdjointDerivative
> No restrictions.
> Function fmi3GetOutputDerivatives
> Not allowed in Model Exchange.

Similar to c), whether "No restrictions" applies to all functions listed above is unclear. Some may not be applicable to SE mode either. Whether fmi3GetDirectionalDerivative/fmi3GetAdjointDerivative can be called in SE mode is determined by issue #1553.

e) In section "2.4.8. Definition of the Model Structure":
> start
> [...Instead it is recommended to use the SSP Standard (https://ssp-standard.org/) to handle modified parameters of FMUs or different parameter sets.]

SSP 1.0 specification does not have a set of data types that matches FMI 3.0-beta2.
> derivative

Is this attribute ignored in CS and SE mode?

> reinit
> Only for Model Exchange (if only a Co-Simulation FMU, this attribute must not be present. If both Model Exchange and a Co-Simulation FMU, this attribute is ignored for co-simulation)

Is this value ignored in SE mode?

**Comment by andreas-junghanns** [comment]
@TorstenBlochwitz : We should look into these issues together - I am sure most of them need at least clarification, some content changes.

**Comment by andreas-junghanns** [comment]
to a) fmi3GetNominalsOfContinuousStates  is listed in the super state "Initialized" - therefore this applies to all sub-states.

to b) We always have the signature at the first appearance of the function (at least we try to). Therefore we then only link back to the signature later in the text.

to c) addressed in PR.

to d) addressed in PR.

to e) SSP dropped from text (does not belong here). `derivative` may also be used for CS and SE because it is used to declare input/output derivatives: "This information might be especially used if an input or an output is the derivative of another input or output..." is given in the text. `reinit` fixed, see PR.

Please check the PR if it addresses your points (given our comments) correctly.

**Comment by andreas-junghanns** [comment]
@dchne : What is your afiliation? Did "it" sign the FMI CCLA? If yes, we would like to turn you into a full contributor, such that you can directly comment and approve PRs.

Until then, please drop comments here or approve (non-binding, unfortunately) the PR - I can not yet make you an official reviewer with your current status.

**Comment by dchne** [comment]
@andreas-junghanns I don't think so; that being said, I am able to raise questions for clarification. The new change clarifies the ambiguities. Thanks!

**Comment by andreas-junghanns** [comment]
Thank you Tao: Your contributions are welcome in any shape or form and we take them very seriously for sure.
