### ISSUE TITLE
tag FMI3.0beta3

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1563]
#1562  should be seen as an API change, right?

Have there more API or schema changes been done since beta.2?

**Comment by andreas-junghanns** [comment]
In #1560 @ptaeuber suggests to rename a parameter to fmi3CallbackIntermediateUpdate().
Not quite an API change, but close enough.

**Comment by chrbertsch** [comment]
Webmeeting: let's stay with beta.2 for the plugfest IV

**Comment by chrbertsch** [comment]
Rename INTERVAL to CLOCKTYPE #1566  has to be considered

**Comment by chrbertsch** [comment]
Splitting Clock Activation (#1584) changes the API

**Comment by chrbertsch** [comment]
Could we try to tag beta.3 this year, so that tool vendors have time to adapt the prototypes for the next plugfest?

**Comment by andreas-junghanns** [comment]
> Could we try to tag beta.3 this year, so that tool vendors have time to adapt the prototypes for the next plugfest?

Yes, I agree that we should. The only changes pending are #1592 and whatever we decide (today?) about #1589.

**Comment by andreas-junghanns** [comment]
> > Could we try to tag beta.3 this year, so that tool vendors have time to adapt the prototypes for the next plugfest?
> Yes, I agree that we should. The only changes pending are #1592 and whatever we decide (today?) about #1589.

Now both these PRs have been merged and I know of no other, pending changes to API nor XML.
@TorstenBlochwitz and I will be going over the text this week and at the end of December, but we will focus on the text, not the API nor the XML.
Therefore, I think tagging beta3 now is likely a good time.

@t-sommer : could you start the tagging process? I checked, the XML-derived images are current.

**Comment by TorstenBlochwitz** [comment]
I would propose to:
- wait until Christmas, when Andreas and I will be ready with our re-read-re-write sessions
- and then tag it as Release Candidate 1 to indicate that we do no longer intend to change the API and XSD

**Comment by chrbertsch** [comment]
> I would propose to:
> 
>     * wait until Christmas, when Andreas and I will be ready with our re-read-re-write sessions
> 
>     * and then tag it as Release Candidate 1 to indicate that we do no longer intend to change the API and XSD

Should we vote in the Steering commitee to leave beta phase and and enter RC phase? could be discussed in the Steering committee meeting on Jan 12.

We should also define, what RC means.  There are still some open points, such as https://fmi-standard.org/docs/3.0-dev/#code-example-clocked-co-simulation, so FMI3 could not be released as is.

Perhaps until then we should stick to the tag FMI3.0beta3.  (this is more a technical thing for the plugfest prepartion.)

**Comment by andreas-junghanns** [comment]
webdesign meeting: Should we tag beta3 now?
TorstenS: No reason not to.
Andreas: Then we can use Beta3 for the Jan25 PlugFest.
All: Agreed.

**Comment by t-sommer** [comment]
I've tagged `v3.0-beta.3` and auto-created a [release draft](https://github.com/modelica/fmi-standard/releases/edit/untagged-0e8864400299d0305187). Please feel free to edit the text.
