### ISSUE TITLE
Rename INTERVAL to CLOCKTYPE

### ISSUE THREAD

**Issue by MBlesken** [modelica/fmi-standard#1566]

**Comment by andreas-junghanns** [comment]
Reasoning for change: We have seen in the text places where the XML attribute `interval` causes issues with understanding.
For lack of better ideas, we propose to use `clockType` instead.
Please comment.
If this finds acceptance, we should likely make this part of beta3.
FYI: @TorstenBlochwitz , @t-sommer , @klausschuch , @KarlWernersson

**Comment by andreas-junghanns** [comment]
FYI: @chrbertsch

**Comment by chrbertsch** [comment]
I agree, fits to the current definition of `interval `(https://fmi-standard.org/docs/3.0-dev/#interval).

We will have to adapt the first line of Tabele 5 (https://fmi-standard.org/docs/3.0-dev/#table-overview-clocks) where Clock type is used slightly different.
