### ISSUE TITLE
Latest version of generated documentation not published

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1571]
The latest version of the generated documentation is not published to https://fmi-standard.org/docs/3.0-dev/

E.g., the changes from the  commit https://github.com/modelica/fmi-standard/pull/1570#partial-pull-merging are missing

**Comment by pmai** [comment]
One likely reason is that the current build_spec step fails (hence nothing to publish is created):

> - /documents/index.html
>  *  External link https://arxiv.org/abs/1502.05767 failed: 403 No error
> htmlproofer 3.8.0 | Error:  HTML-Proofer found 1 failure!
>
> Exited with code exit status 1 
> 
> CircleCI received exit code 1

This seems to be an intermittent failure, i.e. sometimes it works, and the link itself is also working; so maybe an anomaly in the CircleCI infrastructure?

In anycase the html validation step seems to take 20min to run, might also be something to look at...

**Comment by t-sommer** [comment]
Fixed with 22df4a53a4680bb8038ad452dbc5fee85e6f756c.
