### ISSUE TITLE
<stdbool.h>

### ISSUE THREAD

**Issue by KarlWernersson** [modelica/fmi-standard#1573]
stdbool is not supported in older compilers, for visual studio 2012 and earlier this is the case.

It is important that we give an expectation of the size of bool in those cases as we don't want to set/get boolean on a dll where the importer/fmu disagree of the size of bool.

Historically it boolen in C has often been defined as an int, but to my understanding most compilers now use char.
Do we have commonly used compilers on the same platform that has different size for _Bool?

I see two solutions
revert our desertion to stdbool.h and define fmi3Bool  as one of
```
typedef char fmi3Boolean: // fmi1
typedef int fmi3Boolean; // fmi2
```

or if we want to keep stdbool

expand fmi3functions.h

```
#if !defined(_MSC_VER) || (_MSC_VER > 1700)
#include <stdbool.h>
#else
#if !defined(__cplusplus) && !defined(__bool_true_false_are_defined)
typedef char _Bool;
#define bool _Bool
#define false (_Bool)0
#define true  (_Bool)1
#define __bool_true_false_are_defined
#endif 
#endif
```

PS.
I don't frequently use Linux so please expand if similar defs are necessary for gcc or clang

**Comment by t-sommer** [comment]
We should clarify that the FMI 3.0 headers are C99.

**Comment by KarlWernersson** [comment]
OK, but have we specifed that FMI 3 api should be C99 standard, I cant find it. (more than that the headers are given in C99)

If we don't specify C99 standard we shouldn't have c99 types the API

**Comment by t-sommer** [comment]
You can compile your sources any way you want, as long as the generated code is compatible to the API defined by the headers.

**Comment by andreas-junghanns** [comment]
@KarlWernersson : @t-sommer introduced the C99-hint into the standard (see #1575) - this was just making the standard state what was already a fact, so this was a simply clarification. If you agree that this is now clear, please close this issue.

**Comment by KarlWernersson** [comment]
Sure, I posted one posily way to work around the problem. 
Still not so convinced about that stdbool was a good idea, don't really gain us anything we didn't already solved in FMI 1/2 but instead add new possible problems with older compilers.
But we have already changed and are in Beta so lets close this if no one agrees with me
