### ISSUE TITLE
should canReturnEarlyAfterIntermediateUpdate be renamed to canReturnEarly

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1586]
Since it be possible to choose whether an FMU/CS can return or not after an internal event, based on this flag, wouldn't be better to rename this flag to avoid confusion?

**Comment by andreas-junghanns** [comment]
Indeed. However, `canReturnEarly` is also used as an argument to `fmi3CallbackIntermediateUpdate`.
I propose to use `canReturnEarlyFromDoStep`.
Do you agree?
@all: any better proposal?

**Comment by masoud-najafi** [comment]
Yes, canReturnEarlyFromDoStep is much better.

**Comment by andreas-junghanns** [comment]
Web design meeting:
Klaus suggested: add a new capability flag `mightReturnEarlyFromDoStep`.
TorstenB: This would signal an internal reason for a communication point - not requiring an Event Mode necessarily. If event mode is required, then `eventEncountered` must be set to true.
Andreas: Maybe we should change `eventEncountered` to `eventHandlingIsRequired` - forcing the importer to set the FMU into Event Mode.
