### ISSUE TITLE
Move Capability Flags from common to co-simulation

### ISSUE THREAD

**Issue by KarlWernersson** [modelica/fmi-standard#1587]
As intermediate update and output derivative are no longer used in scheduled execution, the capability flags:

 - maxOutputDerivativeOrder
 - providesIntermediateUpdate
 - recommendedIntermediateInputSmoothness
should be moved from section 2.4.2. Definition of Capability Flags
to  section 4.4. Description Schema

Is providesEvaluateDiscreteStates used in scheduled execution?
Otherwise it needs a comment about not being used there.

**Comment by andreas-junghanns** [comment]
providesEvaluateDiscreteStates is only for Event Mode.

**Comment by andreas-junghanns** [comment]
@pmai : I removed the three capability flags that @KarlWernersson mentioned from the .xsd in PR #1585. It looks odd the way <xs:complexType name="fmi3ScheduledExecution"> "inherits" from `fmi3InterfaceType` - maybe an XSD expert can do that more elegantly?
