### ISSUE TITLE
Check restrictions on calling functions in different FMU modes e.g. intialization mode

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1588]
As noted in https://github.com/modelica/fmi-standard/issues/1554 for 2.0.x there are in FMI 2.0 restrictions on calling of FMI functions in certain FMU modes that are currently not there in FMI 3.0.

Could some with knowledge on this please check?

E.g., in FMI 3 we allow calling the getXXX on every variable in initialization mode, see https://fmi-standard.org/docs/3.0-dev/#InitializationMode --> Allowed function calls. 

But in FMI 2.0.x we have restrictions, e.g. footnote 2
![grafik](https://user-images.githubusercontent.com/16363372/144034885-50af4855-2222-404d-8b88-203b753cfecf.png)

(Might be also part of the Design Walkthrough https://github.com/modelica/fmi-standard/issues/1385)

**Comment by andreas-junghanns** [comment]
@KarlWernersson ?

**Comment by andreas-junghanns** [comment]
web design meeting: group tends towards allowing get() on all variables in Initialization Mode. But we need to define somewhere what the expected values will be (start value or default start value).
