### ISSUE TITLE
Improve naming conventions for flags, functions and arguments

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1589]
`eventHandlingIsRequired` vs. `requiresEventHandling`.

Passive vs. active.
Participle vs. imperative.

`encountered` vs. `required`

Who is requesting (importer or FMU), or encode it into the name itself?

**Comment by andreas-junghanns** [comment]
`allows` vs. `has` vs. `provides` e.g. `hasEventMode`...

**Comment by andreas-junghanns** [comment]
List of attributes to check:
 - `canBeDeactivated`
 - `intervalVariability`
 - `intervalDecimal`
 - `shiftDecimal`
 - `supportsFraction`
 - `resolution`
 - `intervalCounter`
 - `shiftCounter`
 - `needsExecutionTool`
 - `canBeInstantiatedOnlyOncePerProcess`
 - `canGetAndSetFMUState`
 - `canSerializeFMUState`
 - `providesDirectionalDerivatives`
 - `providesAdjointDerivatives`
 - `providesPerElementDependencies`
 - `completedIntegratorStepNotNeeded`
 - `providesEvaluateDiscreteStates`
 - `canHandleVariableCommunicationStepSize`
 - `fixedInternalStepSize`
 - `maxOutputDerivativeOrder`
 - `recommendedIntermediateInputSmoothness`
 - `providesIntermediateUpdate`
 - `mightReturnEarlyFromDoStep`
 - `canReturnEarlyAfterIntermediateUpdate`
 - `hasEventMode`
 - `providesEvaluateDiscreteStates`
 - `maxOutputDerivativeOrder`
 - `providesIntermediateUpdate`
 - `recommendedIntermediateInputSmoothness`
 - `canHandleMultipleSetPerTimeInstant`
 - `intermediateUpdate`

List of arguments to check:
 - `intermediateUpdateTime`
 - `clockHandlingRequested`
 - `intermediateVariableSetRequested`
 - `intermediateVariableGetAllowed`
 - `intermediateStepFinished`
 - `canReturnEarly`
 - `earlyReturnRequested`
 - `earlyReturnTime`
 - `eventModeUsed`
 - `earlyReturnAllowed`
 - `requiredIntermediateVariables`
 - `nRequiredIntermediateVariables`
 - `instanceEnvironment`
 - `intermediateUpdate`
 - `lockPreemption`
 - `unlockPreemption`
 - `stepEvent`
 - `stateEvent`
 - `rootsFound`
 - `nEventIndicators`
 - `timeEvent`
 - `elementIndicesOfDependent`
 - `elementIndicesOfIndependents`
 - `dependencyKinds`
 - `discreteStatesNeedUpdate`
 - `terminateSimulation`
 - `nominalsOfContinuousStatesChanged`
 - `valuesOfContinuousStatesChanged`
 - `nextEventTimeDefined`
 - `nextEventTime`
 - `noSetFMUStatePriorToCurrentPoint`
 - `enterEventMode`
 - `terminateSimulation`
 - `currentCommunicationPoint`
 - `communicationStepSize`
 - `noSetFMUStatePriorToCurrentPoint`
 - `eventHandlingIsRequired`
 - `terminateSimulation`
 - `earlyReturn`
 - `lastSuccessfulTime`

**Comment by chrbertsch** [comment]
Do we aim for this for beta.3? https://github.com/modelica/fmi-standard/issues/1563

**Comment by andreas-junghanns** [comment]
Summary of changes agreed to by FMI Design Meeting:
 - `completedIntegratorStepNotNeeded` --> `needsCompletedIntegratorStep`
 - `elementIndicesOfDependent` --> `elementIndicesOfDependents`
 - `discreteStatesNeedUpdate` --> `needsDiscreteStatesUpdate`
 - `eventHandlingIsRequired` --> `needsEventHandling`
