### ISSUE TITLE
get rid of the "no" in noSetFMUStatePriorToCurrentPoint

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1594]
FMI Design Meeting: 

singled out from #1589

@TorstenBlochwitz , @KarlWernersson, @masoud-najafi 
Can we get rid of the "no" in noSetFMUStatePriorToCurrentPoint?
What does this mean?
This is present in ME and CS

**Comment by KarlWernersson** [comment]
noStetFMUStatePriorTocurrentPoint, means that you promise the FMU to not setFMUState to a state relived at a time point before current time.
Removing the no would reverse the logic.
So currently if you send in FMITrue, the FMU can possibly do some optimization as it knows no setFMUstate will come that put the time backwards. Changing the name would the require a fmiFalse as input to allow such optimizations.

i would prefer keep it as is to avoid unnecessary changes, but do as you want

**Comment by masoud-najafi** [comment]
I have never liked neither the name of this argument, nor the fact that it is negative (I have not used it either). But, since the functionality of argument will not change at all, I would vote for keeping it as it is to avoid confusion.

**Comment by pmai** [comment]
I'd also tend to leave as is; however if there is a great need to get rid of the no, then one could use something like `willNotSetFMUStatePriorToCurrentPoint` as the argument name, which would keep the logic but might be more clear...

**Comment by andreas-junghanns** [comment]
I agree to keep things as they are now - the potential gain is too small compared to the benefits.
Closing. Please reopen if you have a great idea for a new name and the logic for it.
