### ISSUE TITLE
Solver in SE?

### ISSUE THREAD

**Issue by MBlesken** [modelica/fmi-standard#1607]
"Solver Included" is "Not applicable" for SE (former Schedule Co-Simulation)? Why? Isn't it like in Co-Simulation included in the FMU?

The question relates to the table in [feature_overview_of_the_interface_types](https://fmi-standard.org/docs/3.0-dev/#_feature_overview_of_the_interface_types) as well as the Figure 3 above (compared to Figure 2).

**Comment by andreas-junghanns** [comment]
"Solver" is ment as a ODE/DEA solver, not as the scheduler - that is the line below.
But you are correct - lines 2 and 3 of Table 1 should be symetrical, right?

**Comment by MBlesken** [comment]
>"Solver" is meant as a ODE/DEA solver, not as the scheduler - that is the line below.

I know. I don't think I'm confusing solver with scheduler. I just think that if a CS FMU contains a solver then why not an SE FMU as well?

> But you are correct - lines 2 and 3 of Table 1 should be symmetrical, right?

No, last column of the second row ("Solver included") should be checked (or "Possibly" if you like), I think, . Line three "Scheduler included" is fine  to me.

**Comment by andreas-junghanns** [comment]
> I know. I don't think I'm confusing solver with scheduler. I just think that if a CS FMU contains a solver then why not an SE FMU as well?
Because there is no ODE inside a SE FMU - at least conceptually. If your model partition solves ODEs or DAEs, that would be hidden behind the model partition abstraction.

**Comment by MBlesken** [comment]
> Because there is no ODE inside a SE FMU - at least conceptually. If your model partition solves ODEs or DAEs, that would be hidden behind the model partition abstraction.

Then why is it differently noted for CS? To me it seems to be the same situation.

**Comment by andreas-junghanns** [comment]
> > Because there is no ODE inside a SE FMU - at least conceptually. If your model partition solves ODEs or DAEs, that would be hidden behind the model partition abstraction.
> 
> Then why is it differently noted for CS? To me it seems to be the same situation.

Yes, to be symmetrical, it should be "possibly",

**Comment by chrbertsch** [comment]
I do not think we should mark the solver as "possible" in the table, which shall only give a very rough overview.
Solver "possible" gives a wrong hint to not so experienced users of FMI.

(In German: "Klarheit vor Wahrheit")

**Comment by MBlesken** [comment]
> The question relates to the table in feature_overview_of_the_interface_types as well as the Figure 3 above (compared to Figure 2).

... and what about adding a "solver" in Figure 3? It's normative ...

**Comment by chrbertsch** [comment]
... and what about adding a "solver" in Figure 3? It's normative ...

I would not include the solver in figure 3 for SE, as the solver is not conceptually adressed by the SE interface.
The current  figure 3 shows model partitions, but does not talk about what kind of calculations they include (could be internally a solver or something else)

**Comment by MBlesken** [comment]
... Agreed. Still: The same situation as for CS, isn't it? And yet one figure shows the solver and the other one doesn't.

**Comment by pmai** [comment]
I would also agree with  @MBlesken: The SE interface does not allow for an external solver: Any ODE system is hidden behind the SE abstraction, the same as it is hidden behind the CS abstraction. So if there is any solver at all, it is in the FMU, not outside of it. We do not distinguish between CS FMUs that encapsulate an ODE and ones that do not (and hence have no solver at all), so the same should apply for SE.

**Comment by MBlesken** [comment]
Design meeting Dec 22nd 2021: The table in line "solver included" should be symmetric in CS and SE. We have not concluded how this should be represented in the two figures.
