### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1618]
We should start preparing https://github.com/modelica/fmi-standard/blob/master/CHANGELOG.adoc  for the RC1

**Comment by andreas-junghanns** [comment]
Next step is Beta3. The FMI Steering Committee might decide (and I certainly hope so) that Beta3 == RC1 next Wednesday (Jan 12, 2022).
It is important to tag Beta3 ASAP because we want the PlugFest Jan 25/26, 2022, to be based on Beta3.

**Comment by chrbertsch** [comment]
Do we really need to maintain the  changelog file?
Everything is transparent in Github and is summarized in https://github.com/modelica/fmi-standard/releases 
So I propose to delete this file.
