### ISSUE TITLE
Clarify and distinguish clocks attribute from model structure dependencies.

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#1620]
## The problem

Right now, the standard states, regarding the definition of the `clocks` attribute:
> Clocks may depend on input Clocks. This dependency is also defined by the `clocks` attribute.

And then in non-normative text, it states that the dependency means 
> if an output Clock depends on an input Clock, then Clock ticks of the input Clock in Event Mode or Clock Activation Mode may create output Clock ticks during this event handling.

This is wrong and leads to an inconsistent definition of the `clocks` attribute.

## Proposed Changes

1. Imho, clock dependencies should be declared in the model structure, and not in the `clocks` attribute:
   1. an output clock `C1` declares that it depends on a clock `C2` means that: `tick(C2) => maybe tick(C1)`
2. The definition of the dependency should be normative.

PS - Issued identified thanks to the work of @SimplisticCode

**Comment by clagms** [comment]
There's another bit in the standard that needs to be modified, if this issue is solved:
> For example, an input Clock could be a clocked variable of another (input or output) clock to indicate that it can only be activated when that Clock is active.

**Comment by andreas-junghanns** [comment]
There is a subtle difference between a dependency declared with the model structure and those with a clocks attribute.
This was discussed at length during a design meeting and we decided to leave things as they are.
I also fail to see why what you mention is inconsistent (beside: there can never be an inconsistency between normative and non-normative text - in that case the non-normative text must be considered wrong):
The normative text is about (all) Clocks, the non-normative text speaks about an example.
What am I missing?

**Comment by clagms** [comment]
I vaguely remember the discussion, but the difference is not so subtle, and I was hoping that time would make it less hard to accept.

Was there are major downside to keeping the two dependencies separate? I can't remember...

The clocks attribute is used to build the clocked partition, whereas the model structure dependencies are used to optimize the propagation of changes, and checking of algebraic loops.
It seems cleaner to not mix those two uses in the same mechanism.

**Comment by andreas-junghanns** [comment]
We *have* two mechanisms. What is the issue?

**Comment by clagms** [comment]
The issue is that the definition of each mechanism can be made simpler and thus:
- there is no redundancy (i.e., exporter A implementing dependencies between clocks using the clocks attribute, and exporter B implementing dependencies between clocks using the model structure attributes); and
- easier to understand and implement for everyone.

I would accept the status quo if I could find an answer to the following:
> Was there are major downside to keeping the two dependencies separate?

**Comment by KarlWernersson** [comment]
The clock attribute states that the variable is a clocked variable belong to the clock partition of the clocks it depends on. This variable is only active if one of the listed clocks is active. Such a variable can only be set when this clock is active, and get results are invalid if the dependent clock(s) is inactive.
The model structure for output clocks shows the dependencies on what can trigger an output clock, this could include variables that are clocked and variables that are non-clocked.
So an output clock can depend on an input clock in modleStructure without being restricted to it by the clock attribute in its variable attribute

**Comment by KarlWernersson** [comment]
Closing?

**Comment by clagms** [comment]
So what @KarlWernersson just said basically agrees with my suggested changes, therefore this issue should NOT be closed.

**Comment by clagms** [comment]
As stated when I opened the issue, the following is incorrectly stated in the standard. But we need a consensus first, and then a PR.
> Clocks may depend on input Clocks. This dependency is also defined by the clocks attribute.

So your sentence
> The clock attribute states that the variable is a clocked variable belong to the clock partition of the clocks it depends on. This variable is only active if one of the listed clocks is active. Such a variable can only be set when this clock is active, and get results are invalid if the dependent clock(s) is inactive.

is not consistent with what is stated in the standard, because the clock attribute may contain other clocks.

**Comment by KarlWernersson** [comment]
A yes you are right, sorry I was a bit hasty

**Comment by andreas-junghanns** [comment]
I am confused about what you are proposing and we have three issues here that seem very much related.
I think a concrete PR might be the best way to focus the discussion.
@clagms : could you please create a PR (maybe one for all three issues?) such that we can read exactly what changes you propose?

**Comment by clagms** [comment]
working on a PR @andreas-junghanns

**Comment by clagms** [comment]
After phone call with @andreas-junghanns it became clear what the difference between the two is:
- clocks attribute really restricts when getClocks can be called because the clock, being part of a clocked partition of another clock, cannot be observed outside the activation time of that clocked partition (see @andreas-junghanns [comment](https://github.com/modelica/fmi-standard/pull/1624#issuecomment-1010151552) for another way to put this
- The clocks attribute still carries dependency information, so the Importer should declare the dependency in the model structure, but this is not always possible, as an input clock can be part of the clocked partition of another input clock (though imho this seems very unlikely in practice).

I now made c48b6ef42d92bf104ee641d384594d08b687efd3 to make this clearer. I think the original example was throwing the reader into thinking that the clocks attribute was just about activation.
