### ISSUE TITLE
Make explicit requirements for propagation of clock deactivations

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#1622]
Right now, the standard does not talk much about propagation of clock de-activations.

Consider the following FMU:
![image](https://user-images.githubusercontent.com/871103/148739257-170e2d5e-06b6-4186-955b-9c641ce8f5d5.png)

If there is a de-activation of clock `c`, then the FMU must be responsible for de-activating clock `d` (in case clock `d` ticked as a result of `c`'s deactivation).
This complicates the implementation of the FMUs that support deactivation of clocks and should be made clear in the standard.

PS - Issued identified thanks to the work of @SimplisticCode

**Comment by andreas-junghanns** [comment]
Please read the mathematical model in Event Mode, specifically the entry for `fmi3SetClock` - I think this clarifies this issue.

PS - This issue was identified and clarified thanks to previous work of @masoud-najafi.

**Comment by clagms** [comment]
The bits of text I mentioned above are from the Mathematical model in Event Mode.

This is the vicinity of the excerpts provided:
````
When a Clock is deactivated, the FMU must reset all clocked states of this Clock to the values computed during the last fmi3UpdateDiscreteStates when this Clock was active (∙vk).
````

There's nothing about propagation of clock de-activations.

**Comment by KarlWernersson** [comment]
Should it not solve itself?

setClock(c==true) 
getClock(d) => true. //v is evaluated
setClock(c==false) 
getClock(d) => false  //as v is not a valid variable any more.

**Comment by clagms** [comment]
> Should it not solve itself?

What is "it"? The FMU? Or the Importer? I claim that it's the FMU, and that this should be clear in the standard. It's just a sentence that is needed.

**Comment by KarlWernersson** [comment]
As it is is defined I don't think it is needed for output clocks, if you do nothing the updateDiscretesState should fix it if you have disabled c and as this is computed internally in the FMU so it is for me clear who should fix this.. But it doesn't hurt to be more explicit with examples in the standard.

A more tricky case is

Say you have input clock A , and input clock A, where B is a sub clock of A (i.e. it has a clock attribute with reference only to A)
if you activate both A and B and then deactivate A, who should deactivate B, importer or FMU?

**Comment by clagms** [comment]
That's a good case, but is B also an input clock? 
- If it is, then if you have an input clock B that is a subclock of A, the importer will always know when to tick it. So it may not make sense for B to be a subclock of A.
- If B is not an input clock, then your case boils down to the core of this issue: should it be the FMU (who activated clock B) responsible for de-activating?

I would just state that the responsibility of propagating clock de-activations falls to the responsible for propagating clock activations. So if an input clock should become inactive (because some upstream clock became inactive), then it's the importer who should de-activated.
If an output clock should become inactive (because the conditions inside the FMU or some input clock of the same FMU became inactive), then it's the FMU's responsibility to de-activate the clock.

**Comment by andreas-junghanns** [comment]
@clagms : I fail to see why this is unclear: inputs (regardless of type) must be set by the importer. If B is an input clock that is also clocked on input clock A (as @KarlWernersson likely wanted to say, just missed the A to be a B), then the importer knows that disabeling A must require B to be disabled as well. This is a consistency requirement that stems from the semantic we are defining in the standard.
Why would the FMU change an input?
Why would this be unclear?

**Comment by clagms** [comment]
It seems we are in agreement.

The proposed change is simple: Add a sentence to stress the responsibility of the FMU in de-activating output clocks in case they depend on a clock that got de-activated.
The importance of imprinting this in the reader is that the implementation gets more complicated as a result of this requirement. So it should not be left implicit.
