### ISSUE TITLE
Model Exchange Pseudocode Example: Possible issue with comment about setting initial inputs

### ISSUE THREAD

**Issue by GarronFish** [modelica/fmi-standard#1629]
In the Model Exchange Psuedocode Example in Section 3.2.4 of the FMI-Specification-2.0.3 near the beginning are the comments:

// set all variable start values (of "ScalarVariable / <type> / start") and
// set the input values at time = Tstart

However in Figure 6. in Section 3.2.3 it has that fmi2SetSEA with the index information:
SEA is one of Real, Integer, Boolean, String
for a variable with variability != constant
that has initial = "exact" or "approx"

The issue is variables with causality="input" have no initial, this means that input values should not be set at the location mentioned in the psuedocode.

I suggest that the comment:
// set the input values at time = Tstart

be moved into between the lines:
M_fmi2EnterInitializationMode(m)
M_fmi2ExitInitializationMode(m)

**Comment by t-sommer** [comment]
@KarlWernersson, what's your opinion on this?

**Comment by pmai** [comment]
The question is whether the comment in Figure 6 is maybe just excluding inputs by accident, since they are treated the same as other causalities with initial "exact":

> If initial = exact or approx, or causality = ′′input′′, a start value must be provided.

So probably the comment should just say:

> SEA is one of Real, Integer, Boolean, String for a variable with variability != constant that has initial = "exact" or "approx" or causality = "input"
