### ISSUE TITLE
Table 5, header cell `intervalVariability` misses closing |

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1631]
@t-sommer : Do you know how to fix that? Could you please fix this in andreas.junghanns/tree/WriteFest_14?
Or: Tell me what is wrong?

**Comment by t-sommer** [comment]
This seems to be related to https://github.com/asciidoctor/asciidoctor/issues/3447.

**Comment by t-sommer** [comment]
Closing as this is just a cosmetic issue and caused by upstream tools.
