### ISSUE TITLE
ERROR: division leads to inf or nan at time X, (a=xx) / (b=yy), where divisor b is: firstOrder.T

### ISSUE THREAD

**Issue by Amuri44** [modelica/fmi-standard#1637]
I have a model designed in OpenModelica contains integrators and transfer functions and first orders. When I run this model in OMEdit, it works fine with some warnings:

```modelica
assert    | debug   | division leads to inf or nan at time 0.056, (a=7.2e+302) / (b=1e-15), where divisor b is: firstOrder.T   | division leads to inf or nan at time 0.056, (a=7.2e+302) / (b=1e-15), where divisor b is: firstOrder.T
assert    | debug   | division leads to inf or nan at time 0.056, (a=7.2e+302) / (b=1e-15), where divisor b is: firstOrder.T
....
assert    | debug   | division leads to inf or nan at time 0.056, (a=7.2e+302) / (b=1e-15), where divisor b is: firstOrder.T
```
It seems that something related to block `firstOrder` is being fixed automatically by OMEdit but not when running FMI in julia, correct? the problem is not issued when (dt >=0.03 s) Any idea how to solve this issue?

**Comment by chrbertsch** [comment]
This repository is for the development of the FMI standard, not a support forum for tools implementing this standard.
