### ISSUE TITLE
Improved wording for ClockedState

### ISSUE THREAD

**Issue by nickbattle** [modelica/fmi-standard#1639]
A suggested change to the section on ClockedState, from Claudio:

```
Clocked variables that don’t have a previous attribute are part of the clocked partition (as inputs or outputs) but not states.
But the standard language needs to be improved:

> Each ClockedState must have the attribute previous to represent the previous value of this ClockedState

Should be

> ClockedStates are identified by the fact that they declare a previous attribute, that points to the same clock.
```

**Comment by clagms** [comment]
After checking out what is said about the clocked states in the model structure, I think the previous wording was ok. It's just that the full meaning of this only becomes clear when those two bits of information are made clear, and Nick only sent me one bit of it :).
