### ISSUE TITLE
Clock in CS "We consider ..."

### ISSUE THREAD

**Issue by MBlesken** [modelica/fmi-standard#1645]
4.3.6 ... "We consider ...": Something seems to be missing here.

Also in 4.4.1.2. //include::examples/co_simulation_clocked_cosimulation.xml[] is not resolved.

**Comment by andreas-junghanns** [comment]
I removed both partial examples. If someone finally builds a complete example, they can start again.

**Comment by MBlesken** [comment]
@clagms would you provide a CS clocks example? There has been little feedback in today's design meeting but maybe you are interested in providing an example. At least I would really appreciate it.

**Comment by clagms** [comment]
@MBlesken  You mean a couple of model description files?
If it's a co-simulation scenario and code of an importer, then you can already find something here: https://github.com/modelica/Reference-FMUs/pull/193

**Comment by MBlesken** [comment]
@clagms ... I meant ModelDescription.xmls and source code (FMU maybe importer, to), yes. Sorry I can't find any xmls in https://github.com/modelica/Reference-FMUs/pull/193/files and I am confused by the second sentence in the conversation "It uses model exchange in FMI3.0", I wouldn't expect CS Clocks examples in that PR. Am I getting it wrong?

**Comment by clagms** [comment]
@MBlesken Ok so what we're missing is just the model description files, right? 
Because the source code of importer and FMUs is in https://github.com/modelica/Reference-FMUs/pull/193
Nevermind the sentence "It uses model exchange in FMI3.0".
