### ISSUE TITLE
logMessage examples need to be updated

### ISSUE THREAD

**Issue by Maplesoft-fmigroup** [modelica/fmi-standard#1652]
Section 2.3.1 defines the logging function without 'instanceName' argument but the code examples (section 2.5.4.1 and 2.5.4.2) still use it:
`static void cb_logMessage(fmi3InstanceEnvironment instanceEnvironment, fmi3String instanceName, fmi3Status status, fmi3String category, fmi3String message) {
    // log message...
}`

**Comment by andreas-junghanns** [comment]
This is caused by an outdated link to the Reference-FMU repo. I updated the link, but that revealed another issue in that repo... waiting for @t-sommer to approve PR fixing this and then we can link that which will hopefully fix this issue here.
