### ISSUE TITLE
Enumerations should be set and retrieved with int32

### ISSUE THREAD

**Issue by KarlWernersson** [modelica/fmi-standard#1656]
Hi

When Masoud testing the Dymola FMU's we discovered that our tools didn't agree on which function to use to get and set enumerations.

In the standard at section2.2.6.2 It is currently stated:

> To set or inquire variables of type Enumeration, fmi3SetInt64 and fmi3GetInt64 must be used. 

However we have had several discussion about this and always agreed that enumerations should use Int32
e.g.
#1288 

Has there been some new decision that I have missed or is this just a mistake in the standard?
@masoud-najafi also agrees that int32 would be preferable

**Comment by pmai** [comment]
For what it's worth, this change was introduced by @andreas-junghanns with commit 12e8378570f796044f48753d0718e5235501bd93 which contains the commit message (along with many many other changes):

>     * Turn Enumerations to long in XSD and prescribe proper Get/Set

So I think this was an intentional change, not sure which PR/discussion lead to that change.

From my PoV it makes sense to use 64bit enums BTW...

**Comment by KarlWernersson** [comment]
Well, it has worked well with 32 bit so far. Is there really a need for a different solution in fmi3
32 bit integers can be stored in a double, 
Modelica don't have native support for 64 bit
I have yet to se an enumeration using more than 4 billion different enumerations

And we had this discussion before several times and came to the conclusion of 32 bit so what has changed?

I can make a pull request but I rather wait for @andreas-junghanns comment next week

**Comment by andreas-junghanns** [comment]
@KarlWernersson : we discussed this and the final argument was that often enums are bit-encoded and then having 64 bits is better than 32 bits. I don't remember who was involved in that discussion... sorry.

**Comment by chrbertsch** [comment]
> @KarlWernersson : we discussed this and the final argument was that often enums are bit-encoded and then having 64 bits is better than 32 bits. I don't remember who was involved in that discussion... sorry.

I think it was here: https://github.com/modelica/fmi-standard/issues/1288

**Comment by KarlWernersson** [comment]
@chrbertsch but that discussion closes with 32 bit

**Comment by KarlWernersson** [comment]
A sorry i misread that issue

**Comment by andreas-junghanns** [comment]
@KarlWernersson : does that settle it? Can we close this issue here?

**Comment by KarlWernersson** [comment]
Can you give me a day, i am not happy with the decision.
The point of bit encoding is to give several different bits at the same time, however our enum interface don't support that as far as I understand it. Or am i missing something, shouldn't a normal int64 be used for this with some annotation, or new bit type be used instead.?

Or how would it work with our enumeration setup?

**Comment by KarlWernersson** [comment]
Lets say we have bit encoded int64 that uses all 64 fields
Unless we want to list all 2^64 version in the item, we need to limit to send 1 bit field at a time.
This can easily be transformed to numbers 1-64.
If we want to send multiple bits at the same time we need to list all combinations among the items which isn’t feasible.

So with our current solution I don’t see this as a relevant scenario.
We either need to expand the EnumType to show that we are dealing are bit fields and not enumerations or better have a proper bitfield type. 

Or am I missing something?

**Comment by andreas-junghanns** [comment]
Web design meeting: we should at least be using UInt getter and setter functions.

**Comment by andreas-junghanns** [comment]
PR should just state as non-normative text that signed is needed to have negative enum values...
