### ISSUE TITLE
EnterEventMode definition needs clarification

### ISSUE THREAD

**Issue by Maplesoft-fmigroup** [modelica/fmi-standard#1657]
The description for the argument nEventIndicators includes the statement:
`... 0 if the importer cannot provide this information.`
Under what circumstances is this valid?  We're assuming it's only when stateEvent=false.
Similarly, if stateEvent=false, we're assuming that rootsFound does not have to be defined.
Also, the statement "informs the FMU which event indicator has a root" should say "informs the FMU which event indicators have a root" as there could be multiple roots.

**Comment by andreas-junghanns** [comment]
@TorstenBlochwitz or @KarlWernersson : Can you comment here, please?

**Comment by KarlWernersson** [comment]
Yes dont understand it, is the idea that it is optional to provide the roots to the FMU? Then why not the other event types?
I don't see how the importer would be incapable of providing the number of event indicators.

Or is the idea that the importer could say that one if its roots has changed so we have a state event but I don't know which?
Also don't seem like a proper case.



Also
state Event = true implies that at least one of the roots has changes.
So the this flag could signal if its needed at all to proved the roots found, but it seems a bit unnecessary.
It should de sufficient to provide the roots found array and if any element has the value != 0 we have a state event.
