### ISSUE TITLE
= or ==

### ISSUE THREAD

**Issue by KarlWernersson** [modelica/fmi-standard#1668]
I remember that we long time ago discuses if we were to use singe = or double == or equal, is etc. 
I i am not sure about that outcome but i have a vage memory that we decided for == 
I did not find anything in https://github.com/modelica/fmi-standard/blob/master/CONTRIBUTING.adoc#formatting-rules

Personally I don't care that much but currently there is still a mix

Wiht 253 hits on ' = '
and 123 on ' == '

With examples like

> Input Clock
> is a variable of type Clock with causality == input

> Input variables. The values of these variables are defined outside of the model. Variables of this type are defined with attribute causality = input

**Comment by andreas-junghanns** [comment]
Agreed, the uses of ` = ` and ` == ` is inconsistent.
I wonder if we can establish usage rules here that I can then transform into a PR.

Proposal 1:
Change all ` == ` into ` = ` regardless of use (of course not so in code examples!). People reading the document will understand the difference between an assignment and a conditional statement.

Proposal 2:
Use ` == ` only when it happens to be in a sentence where it can be read as Boolean expression, e.g. 
> "If argument `nominalsOfContinuousStatesChanged == fmi3True`, then..."
Other examples are "When..."
Of course, there are more difficult spots, where the sentence would have to be issue is a bit more murky, e.g.
> "<<Clock,`Clocks`>> with the attribute <<canBeDeactivated,`canBeDeactivated == true`>> may be actively deactivated using <<fmi3SetClockEM>>."
which would likely have to be reformulated to
> Only if the attribute <<canBeDeactivated,`canBeDeactivated == true`>>, then the Clock may be actively deactivated using <<fmi3SetClockEM>>.

Proposal 2 is a lot of work with the danger of changing the meaning of such sentences.
Therefore, I suggest we go with Proposal 1.
