### ISSUE TITLE
Remove computed from clocks.

### ISSUE THREAD

**Issue by KarlWernersson** [modelica/fmi-standard#1685]
After resting over a weekend, I realize that the `computed `attribute for clocks in unnecessary as this is implicitly defined if the fixed or tunable clock has `intervalDecimal `or not. The non computed must have `IntevalDecminal`, the computed must not have `intervalDecmial`.
So we could remove `computed `attribute completely.

**Comment by andreas-junghanns** [comment]
I like dropping an attribute. Could you provide a PR?

**Comment by KarlWernersson** [comment]
Will do
