### ISSUE TITLE
FMI3_Export for SetShiftDecimal and SetShiftFraction is missing in beta 4

### ISSUE THREAD

**Issue by PenndorfT** [modelica/fmi-standard#1686]
The functions fmi3SetShiftDecimal and fmi3SetShiftFraction are defined well in fmi3FunctionTypes.h but are not exported by fmi3Functions.h.
This leads to non "c symbol names" when compiling with c++ in linux.
The attached patch solves the issue.
[setshifts.zip](https://github.com/modelica/fmi-standard/files/8110663/setshifts.zip)

**Comment by KarlWernersson** [comment]
Do we need a beta 4.2 or a beta 5 quickly?

**Comment by andreas-junghanns** [comment]
> Do we need a beta 4.2 or a beta 5 quickly?

No, I do not think so - we are too late for the next PlugFest already.
