### ISSUE TITLE
Make it clear that priority is an attribute for Scheduled Execution only

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#1693]
This might be nit picking, but currently the standard says:

> This attribute is only considered for Clocks in Scheduled Execution. In Scheduled Execution this attribute is *mandatory*.

Which still allows for Synchronous Clocks to have a priority attribute (leading to even more confusion because importers suddenly need to think about its meaning).

If you agree, I can provide a PR that adds simply:

> This attribute should not be specified for Co-simulation or Model Exchange.

PS - discussed with @nickbattle and Simon.

**Comment by andreas-junghanns** [comment]
Your proposal works if the FMU has only SE content. But we need to allow mixed interface FMUs (e.g. SE+ME or SE+CS) and then the attribute must be present for SE and ignored for the other interface type.
Just saying "For FMUs that only have CS or ME this attribute must not be present." - does not address the mixed interface case.
Therefore the better explanation is to "ignore" `priority` for CS and ME. Improved wording welcome!

**Comment by KarlWernersson** [comment]
Coud this work?

This attribute is only considered for Clocks in Scheduled Execution. In Scheduled Execution this attribute is mandatory.
For CS and ME the meaning of priority is undefined and should be ignored.

**Comment by nickbattle** [comment]
At the moment (build 220223), if you have SE in the mix VDMCheck3 requires priority to be set in Clocks. If you don't have SE in the mix, it considers it an error to have priority set on Clocks. That may be a little harsh, and could be downgraded to a warning.
