### ISSUE TITLE
Clarify dependencies and providesDirectionalDerivatives w.r.t. time

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1697]
@KarlWernersson & @klausschuch : We have just found the following sentence:

`For Co-Simulation, if the capability flag providesDirectionalDerivatives has a value of false, then dependencies does not list the dependency on continuous-time. In other words, the respective partial derivatives cannot be computed.`

Is that part of the issue we just discussed in the 9:00 sync meeting?

**Comment by KarlWernersson** [comment]
So i went over the text and i think it is much better than in fmi2 regarding this. 
If the independent variable is included in the dependencies then you can get directionalDerivatvies with respect to it just as any other continuous dependency.

The only remaining issue is to make sure that the partial derivative with respect to time only thake the explicit dependencey not the implicit or total derivaitve.

So given funciton f( **x** ,t)
the partial deriavivie with the respect to t is.  df/dt and not df/dt+df/d**x** * d**x**/dt
(sorry for the bad formatting)

Si this clear to everyone when we talk about partial derivatives or do we need to ad such a clarification. (This is not so explcit when i reed my old university text book on multivariable analysis)

**Comment by andreas-junghanns** [comment]
@KarlWernersson : We need to clarify this - at least so one can understand what textbook to look this up at.
Could you please propose a change? Here or as PR, I will fix and manage the rest gladly.
