### ISSUE TITLE
Clarify that output clocks don't need a priority, even in SE

### ISSUE THREAD

**Issue by nickbattle** [modelica/fmi-standard#1698]
The current docs/examples/scheduled_execution.xml example raises a problem with VDMCheck because it requires every clock to have a priority in SE mode. But @andreas-junghanns tells me this isn't necessary for output clocks.  I can update the VDM model, but the standard should clarify this.

**Comment by nickbattle** [comment]
The [VDMCheck](https://github.com/INTO-CPS-Association/FMI-VDM-Model/releases/tag/1.1.2-snapshot-beta.4) fix is available in build 220301.

**Comment by KarlWernersson** [comment]
Sorry
