### ISSUE TITLE
ModelStructure order clarification.

### ISSUE THREAD

**Issue by KarlWernersson** [modelica/fmi-standard#1707]
As we no longer group the different parts of the modelStructure together is it now free to order the elements as you like, i.e.
Would

```xml
 <Output valueReference="335544320"
      dependencies="33554433"
      dependenciesKind="fixed"/>
 <InitialUnknown valueReference="587202562"
      dependencies="33554433 905969776"
      dependenciesKind="dependent dependent"/>
<ContinuousStateDerivative valueReference="587202565"
      dependencies="4294967295 33554435 33554437 33554439 352321536"
      dependenciesKind="dependent dependent dependent dependent fixed"/>
<EventIndicator valueReference="4294967274"/>
 <ContinuousStateDerivative valueReference="587202562"
      dependencies="33554435"
      dependenciesKind="fixed"/>
<EventIndicator valueReference="4294967273"/>
<InitialUnknown valueReference="587202562"
      dependencies="33554433 905969776"
      dependenciesKind="dependent dependent"/>
<EventIndicator valueReference="4294967272"/>
 <Output valueReference="335544323"
      dependencies="33554433 33554435 33554437 33554439"
      dependenciesKind="fixed fixed fixed fixed"/>
```

 be a fully legit ordering of the modelStructure?

**Comment by andreas-junghanns** [comment]
This is the relevant snippet from the XSD:
`                <xs:element name="ModelStructure">`
`                    <xs:complexType>`
`                        <xs:sequence>`
`                            <xs:element name="Output" type="fmi3Unknown" minOccurs="0" maxOccurs="unbounded"/>`
`                            <xs:element name="ContinuousStateDerivative" type="fmi3Unknown" minOccurs="0" maxOccurs="unbounded"/>`
`                            <xs:element name="ClockedState" type="fmi3Unknown" minOccurs="0" maxOccurs="unbounded"/>`
`                            <xs:element name="InitialUnknown" type="fmi3Unknown" minOccurs="0" maxOccurs="unbounded"/>`
`                            <xs:element name="EventIndicator" type="fmi3Unknown" minOccurs="0" maxOccurs="unbounded"/>`
`                        </xs:sequence>`
`                    </xs:complexType>`
`                </xs:element>`
Does `sequence` mean "order"? @pmai or any other XSD expert?

**Comment by t-sommer** [comment]
The elements must be in the order defined by the `<sequence>`.
