### ISSUE TITLE
Mention implementer's guide in the FMI3.0 standard text

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1711]
We should not only mention the implementer's guide on the website, but also (non normatively) mention it in the FMI3 Standard text (as the link to the FMI standard might be shared, and people might not be aware of the existence of the implementer's guide)

**Comment by andreas-junghanns** [comment]
@pmai : I assigned this to you as you might have a strong opinion as to how to link to the latest (even future) release of the IG.

**Comment by andreas-junghanns** [comment]
@t-sommer : do you have any opinion on this? All I would try to optimize is low maintenance: a merged PR should go right into what someone following that link would see - no other filter steps that cause someone spending time.
Reason: any change can be undone, no need to be extra careful.

**Comment by chrbertsch** [comment]
We could link to https://modelica.github.io/fmi-guides/main/fmi-guide/ ?
