### ISSUE TITLE
Clarify input event handling in CS

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1713]
In 4.1.1. we found:
`Since the FMU itself can detect such changes, the co-simulation algorithm does not need to enter EventMode in such a case, but must do so, in case event iteration is required.`

This is inconsistent with explanation in 4.4.1 for `hasEventMode`:
`If eventModeUsed = fmi3True, the co-simulation algorithm will have to actively trigger event handling in the FMU using fmi3EnterEventMode.`

We (@TorstenBlochwitz & @andreas-junghanns ) suggest to remove the first sentence and keep the explicit event handling requirement of input events.

**Comment by KarlWernersson** [comment]
I think this stems from earlier versions where we did not have hasEventMode when instantiating a CS fmu.
Since we now use this hasEventMode to switch on or of eventMode, I completely agree with your proposal.

**Comment by masoud-najafi** [comment]
Yes, the first part is the reliquary of the early versions and may be removed.

**Comment by andreas-junghanns** [comment]
PR #1714 will remove this sentence.
