### ISSUE TITLE
References to fmi3(Get/Set)Real

### ISSUE THREAD

**Issue by Maplesoft-fmigroup** [modelica/fmi-standard#1719]
The code segment in section 4.3.5 (https://fmi-standard.org/docs/3.0-dev/#_connected_fmus) contains comments with references to fmi3(Get/Set)(Real/Integer).  It should probably be changed to fmi3(Get/Set){VariableType}.

**Comment by andreas-junghanns** [comment]
@Maplesoft-fmigroup : Could you provide a PR for those changes?

**Comment by Maplesoft-fmigroup** [comment]
@andreas-junghanns Done: https://github.com/modelica/Reference-FMUs/pull/223
