### ISSUE TITLE
dependency of clocks

### ISSUE THREAD

**Issue by MBlesken** [modelica/fmi-standard#1721]
In the Model Structure chapter for dependency it is stated: "_[This means that all dependencies must be listed, also the dependencies of clocked variables on their input clocks, even if redundant information.]_" **Is this what we want?**

**If yes**: In the SE example the variables 

- Float64 name="AOut" valueReference="2" causality="output" variability="discrete" clocks="5"
- Float64 name="BOut" valueReference="4" causality="output" variability="discrete" clocks="6"

should be listed redundantly in ModelStructure as well, **right?**

The dependency of 

- Clock name="OutputClock" valueReference="7" causality="output" intervalVariability="triggered" clocks="5"

is already listed in ModelStructure, as well: Why did we say that is necessary? **Did we note the reason for it in the specification?**

I think @masoud-najafi or @clagms can maybe help here, but any feedback is welcome. FYI: @andreas-junghanns @PTaeuberDS

**Comment by KarlWernersson** [comment]
Yes, I don't remember why we need the clock information for clocked variables in the dependencies as it is already in the clock reference. But we have decided this several times. And I don't think we should change it so late.
The text should be 

> on their clocks
and not
> on their input clocks

as they could also be triggered by an output clock.

We also don't list clocks among the known variables which is not correct. they are known in event mode.

**Comment by KarlWernersson** [comment]
I also think we should skip the 

> even if redundant information.

It just adds confusion and is kind of, a complaint of our decision.

Alternatively change it to something like

> this clock dependency should be the same as in the attribute clock of the variable

Is this always is true?
For clocked variables I think so, but it is not true for clocks

**Comment by masoud-najafi** [comment]
>Is this always is true?
>For clocked variables I think so, but it is not true for clocks.
For clock variables we must also define their dependency, and it is really important to have dependency of output clocks on input clocks.

**Comment by masoud-najafi** [comment]
I agree that "even if redundant information" is redundant itself. "must" in the statement . So we may skip it.

**Comment by masoud-najafi** [comment]
> I also think we should skip the
> 
> > even if redundant information.
> 
> It just adds confusion and is kind of, a complaint of our decision.
> 
> Alternatively change it to something like
> 
> > this clock dependency should be the same as in the attribute clock of the variable
> 
> Is this always is true? For clocked variables I think so, but it is not true for clocks

We have not mentioned to add dependency of output clocks on input clocks in the dependencies. I think we should (even if it is redundant). But, as you said, if we mention "input" clocks as Knowns, declaring the dependency on input clocks becomes mandatory implicitly.

**Comment by MBlesken** [comment]
@masoud-najafi @KarlWernersson  I created PR #1727 to make the SE xml consistent. The things you are discussiong above I did not address with this PR since to me it would be necessary to state more explicitly WHY we need this information at both spots I the first place. That's a question I cannot answer. FYI @andreas-junghanns

**Comment by masoud-najafi** [comment]
@MBlesken 
I would prefer to have all of these dependencies only at ModelStructure, but if I am not wrong, this has been discussed long long time ago and it was decided to put in the Clock attributes.  @andreas-junghanns  may remember the reason. 
If you decide to put it in ModelStructure, I am in favor, it is more clean and more consistent with regular output dependencies.

**Comment by andreas-junghanns** [comment]
I added a PR to fix the non-normative text.
I don´t remember the reason for the redundancy, but I like the simplicity of the model description as it is:
 - tools without need for dependency information can ignore it
 - the dependencies alone can now be used to analyse dependecy graphs

**Comment by clagms** [comment]
Aren't these dependencies in the clocked variables because the same clocked variable can belong to multiple clock partitions?
It's conceptually different than an output variable having a dependency to multiple inputs.

The former states that there are multiple dependencies that must be handled separately, depending on the clock that's active, whereas the later just states that "you need to update all these inputs, before you can query this output".

**Comment by andreas-junghanns** [comment]
Thank you, @clagms! I also found this in 2.2.9 in the text:
`Note, the dependencies between clocked variables and their Clocks are defined by the attribute clocks in <fmiModelDescription><ModelVariables>. Compared to dependencies, clocks declared dependencies also restrict when clocked variables can be accessed.`
I will merge #1728, closing this issue. If not sufficient for this issue, please reopen.
