### ISSUE TITLE
bool and hexBinary defs

### ISSUE THREAD

**Issue by MBlesken** [modelica/fmi-standard#1723]
@KarlWernersson @t-sommer can you please check if the definitions in table 10, chapter 2.4 and the defines in fmi3PlatformTypes.h match w.r.t. bool and hexBinary:

- typedef bool fmi3Boolean; - table 10 says int: Shouldn't it be bool?
- typedef const fmi3Byte* fmi3Binary; - table 10 says char*: Shouldn't it be uint8_t*?

Thanks.

**Comment by KarlWernersson** [comment]
Why do we have the mapping to C at all, is it not sufficient with the mapping to FMI?
Is the C mapping defined somewhere else? In that case we should be careful to change it.

**Comment by KarlWernersson** [comment]
@pmai you usually knows these things?

**Comment by andreas-junghanns** [comment]
> Why do we have the mapping to C at all, is it not sufficient with the mapping to FMI? Is the C mapping defined somewhere else? In that case we should be careful to change it.

Our `fmi3PlatformTypes.h` has exactly these (corrected) mappings. I will merge the PR - thank you @MBlesken !
