### ISSUE TITLE
fdisc and fevent got mixed up

### ISSUE THREAD

**Issue by PTaeuberDS** [modelica/fmi-standard#1725]
In Section 2.2.8.3. "Model Partitions and Clocked Variables" it seems that all "fdisc" identifier were accidentally replaced by "fevent".
Maybe other parts of the specification are affected as well.

**Comment by andreas-junghanns** [comment]
Indeed, that broke in the "unbold"-session (56c3140458ef48ab8b2903314db55b17b1d27e67). @KarlWernersson found some and I still do not understand how that happend and why I did not catch this when I checked each of the changes :(
I will start a PR. But how do we make sure to catch them all? Sorry for the mess...

**Comment by andreas-junghanns** [comment]
I think I messed up a change with a regular expression inserting `_{event}` - I checked those changes in the unbold-changeset.
Can you find other hints as to what I might have broken?

**Comment by PTaeuberDS** [comment]
I don't have an overview, just saw it in that passage.

**Comment by andreas-junghanns** [comment]
> I don't have an overview, just saw it in that passage.

well, then I will merge, if more issues show up, please let me know
