### ISSUE TITLE
Move layered Standards to a different Github repo

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1745]
Layered standards such as 
https://github.com/modelica/fmi-standard/blob/master/docs/X_layered_XCP.adoc or https://github.com/modelica/fmi-standard/pull/1177
should not be bundled with the main FMI Standard document.

Reason: they have other release cycles and  approval processes - and the FMI standard itself  do not depend on them

Currently, e.g. the "assets" zip file of a release contains also the XCP layered standard (see https://github.com/modelica/fmi-standard/releases)

**Comment by andreas-junghanns** [comment]
Should we have a single repo with all layered standards currently proposed?

**Comment by chrbertsch** [comment]
> Should we have a single repo with all layered standards currently proposed?

As we will have different releases, perhaps its better to have a separate repos?
@pmai , @t-sommer : your opinion?

**Comment by pmai** [comment]
I would also move to separate repos, i.e. one for each layered standard, e.g. fmi-ls-xcp fmi-ls-bus or whatever.

**Comment by t-sommer** [comment]
So can we just remove it for now and create the repo later?

**Comment by t-sommer** [comment]
Wouldn't this make sense for Ports & Icons, too?

**Comment by andreas-junghanns** [comment]
> So can we just remove it for now and create the repo later?

... sure, as long as the text does not get lost...

**Comment by t-sommer** [comment]
And maybe also the buildDescription.xml, so we can reuse it in FMI 2.0.

**Comment by andreas-junghanns** [comment]
> And maybe also the buildDescription.xml, so we can reuse it in FMI 2.0.

We can reuse the description without removing it from the 3.0 standard.
This was discussed at the time and we decided against it.
