### ISSUE TITLE
Add license.spdx to structure of ZIP file

### ISSUE THREAD

**Issue by GallLeo** [modelica/fmi-standard#1750]
Section 2.5.1.1.1. Directory licenses states
"If it is present, it must contain either a [license.spdx](https://spdx.dev/), license.txt or license.html file as entry point."

But, the overview in
https://fmi-standard.org/docs/3.0-dev/#structure-of-zip
only mentions txt and html:

`license.{txt|html}            // entry point for license information`

Should it be changed to `license.{txt|html|spdx} `?

**Comment by andreas-junghanns** [comment]
@GallLeo : ok?
