### ISSUE TITLE
Should we mention PlugFest tools

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1754]
We currently just list the companies that tool part in the plug fests.
@TorstenBlochwitz and I (@andreas-junghanns) think it would be fair to give those companies and their tools some more permanent exposure in the standard by actually listing all tools that have participated in the plug fests.

If we agree, we need your company and tool name like so (please add to the list here in this comment):
 - Altair: Activate
 - AVL: ModelConnect
 - Dassault Systèmes: Dymola, FMPy, FMIKit
 - dSPACE: TargetLink, SystemDesk, Veos
 - ESI Group: SimulationX
 - PMSF: FMI Bench
 - Synopsys: Silver
 - ...

This can be added very late, but we should discuss if we want to add such a list at all.

**Comment by pmai** [comment]
I could certainly agree with this idea...
