### ISSUE TITLE
Rename branches and use matching path on fmi-standard.org

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1771]
I propose to rename the current branches to

- `master` -> `main`
- `support/v2.0.x` -> `v2.0.x`
- `support/v3.0.x` -> `v3.0.x`

and to use matching paths on the website, so the generated HTML for 

- `main` will be available on `https://fmi-standard.org/docs/main/` and
- `v3.0.x` will be available on `https://fmi-standard.org/docs/v3.0.x/`.

Tags will get their own path, e.g. `https://fmi-standard.org/docs/3.0/` (currently without the `v` prefix, maybe we should change this).

**Comment by chrbertsch** [comment]
What are the consequences of renaming branches? 
Will there be problems for locally checked-out repos?
Is it recommended to clone the repo from scratch?

 https://fmi-standard.org/docs/main/ will replace https://fmi-standard.org/docs/3.0-dev/ or will there be some kind of alias?

**Comment by t-sommer** [comment]
Will there be problems for locally checked-out repos?

> No. This does not affect any local repos.

Is it recommended to clone the repo from scratch?

> No.

Most projects have already migrated from `master` to `main`. I think this is a good time to do it.

**Comment by chrbertsch** [comment]
@t-sommer  Only missing thing is making available the generated docu for https://fmi-standard.org/docs/v3.0.x/ and the tags, right?

**Comment by t-sommer** [comment]
Yes, `v3.0.x` is not deployed yet.
