### ISSUE TITLE
Correct "+INF" to "INF" in FMI 2.0.3  2.2

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1784]
in the sentence "The special values NAN, +INF, -INF for variables values are not allowed in the FMI xml files"
According to https://www.oreilly.com/library/view/xml-schema/0596002521/re63.html "+INF" is not correct XML.

The question came up, as there was an FMU with an "INF" value

**Comment by chrbertsch** [comment]
I do not find the restriction "The special values NAN, +INF, -INF for variables values are not allowed in the FMI xml files" in FMI 3.0. Have I overlooked it, or is there a reason not to have it in FMI 3.0?

**Comment by t-sommer** [comment]
I propose to back-port #1122 to FMI 2.0.4.

**Comment by chrbertsch** [comment]
ToDo Update word docuent accordingly
