### ISSUE TITLE
Different annotations in 2.0.4

### ISSUE THREAD

**Issue by nickbattle** [modelica/fmi-standard#1798]
I've updated VDMCheck in anticipation of the backport changes for 2.0.4. This was mostly straightforward, since the checks from the 3.0 schema for the new XML files could be re-used. But there was one small issue, caused by the fact that the Annotations element of ScalarVariables is a different type to the Annotations that appear throughout the FMI3 schema.

Happily, the tool is able to cope with this - there are other occurrences of the same element name being used for two purposes (eg. Real for a variable and a type of variable). But it might be something that tool vendors should be told about in the release notes?

This issue is just to record the observation. There is no problem as such, and it can probably be closed immediately.

**Comment by chrbertsch** [comment]
@nickbattle : I do not understand. Is there any change compared to FMI 2.0.3?
Could you please propose a concrete wording what you would like to mention in the release notes? Thanks.

**Comment by nickbattle** [comment]
This might not cause vendors much trouble, but I noticed it, so I thought I should raise it. The problem is that the "Annotations" element of a ScalarVariable is of type **fmi2Annotation**, but the "Annotations" element throughout the newly backported FMI3 schema files are of type **fmi3Annotation**. I think that's the only element in common between FMI2 and the backported FMI3 files. The problem didn't occur in 2.0.3 because there were no backported FMI3 types.

This caused a problem in VDMCheck, since the same software was trying to parse all of the XML files, but there was only one VDM type called "Annotations".

How about, "Note that the Annotations element in the BuildConfiguration.xml and TerminalsAndIcons.xml files is different to the Annotations element in ScalarVariables."?

Or if you think this won't cause any problems, by all means close the issue. Just trying to help :)

**Comment by t-sommer** [comment]
The `buildConfiguration.xml` and `terminalsAndIcons.xml` files have to be validated using the FMI 3.0 XSDs, so I think this works as designed.
