### ISSUE TITLE
Order is lost with alias variables (FMI 3).

### ISSUE THREAD

**Issue by HansOlsson** [modelica/fmi-standard#1815]
Model variables can be declared in an arbitrary order in `<fmiModelDescription><ModelVariables>` for FMI 3.
That allows them to match the structure of an existing (Modelica) model - including the declaration order.

However, in the original model the list of variables includes variables that will become aliases, whereas in 
`<fmiModelDescription><ModelVariables>` the aliases are not ordered together with other variables (they are listed under their "main"-variable).

That means it is not possible to recreate the original model structure - including order of declarations (if there are any alias-variables).

**Comment by chrbertsch** [comment]
@HansOlsson : Could you please motivate, for which use cases it would  be important to recreate the original model structure.

**Comment by HansOlsson** [comment]
Recreating the original model structure (including declaration order within them) is useful for:

- Convenience - people are used to seeing the variables, and components, in a certain logical order.
- Animations in Dymola

If the goal _weren't to recreate the original model structure_ the entire idea with ModelVariables mixing various types of variables wouldn't be needed, and I'm not sure if we would need alias-variables at all.

**Comment by HansOlsson** [comment]
As an example of convenience consider Modelica.Mechanics.Rotational.Examples.CoupledClutches from MSL.

Originally the order is as follows (corresponding to what the user wrote):

![VariablesOrig](https://user-images.githubusercontent.com/13217430/197742012-0062802e-752b-4e02-899d-8de204f40edc.png)

Assumedly the user has some reason for that ordering.

Exporting it as FMI 3 (seen below) and trying to re-create the order will not work well as phi and tau will be in different order in different structured components, and the torque cannot be placed as it is entirely an alias:
![Variables](https://user-images.githubusercontent.com/13217430/197742270-bcc129bb-eb16-455e-837a-e03b79635943.png)

The corresponding XML document:
[Coupled.zip](https://github.com/modelica/fmi-standard/files/9859177/Coupled.zip)

**Comment by HansOlsson** [comment]
A possible solution is (an annotation on the variable, or optional attribute) declarationOrder giving an order for the variable and each possible alias as part of a global order (mixing aliases and normal variables).
