### ISSUE TITLE
Use cases for structural parameters

### ISSUE THREAD

**Issue by TorstenBlochwitz** [modelica/fmi-standard#1821]
During the FMI Design Meeting (2022-10-26) we had a discussion on use-cases for structural parameters and Configuration Mode. Some of us thought that structural parameters are **only** intended for dimensions of variables of the FMU. But they can also be used to mark variables, which must be set **before** Initialization Mode.

I went through the FMI 3.0 Specification: we mention this fact only once: https://fmi-standard.org/docs/3.0/#ConfigurationMode. 
Most of the other occurances of structural parameters refer to changeable dimensions of variables.

We should mention at least this other use-case too. At least in the Glossary.

**Comment by klausschuch** [comment]
I agree the glossary entry for structural parameters is wrong. Can we easily extend this in a maintenance version 3.0.1, i.e., is the glossary non-normative text?

**Comment by pmai** [comment]
It should be considered non-normative, that is the common practice for appendices across standards (i.e. they are considered non-normative unless specifically noted otherwise)...

**Comment by chrbertsch** [comment]
But as we mention the other usage of structural parameters in https://fmi-standard.org/docs/3.0/#ConfigurationMode, I would consider mentioning this in the glossary a clarification that we could include in FMI 3.0.1

**Comment by chrbertsch** [comment]
@klausschuch : could you please provde a PR for the coming FMI 3.0.1?  Thanks!
