### ISSUE TITLE
Relax content description of /binaries folder

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1822]
Current 3.0 wording in 2.5.1. Structure of the ZIP file suggests that only binaries are allowed in /binaries - we should allow other runtime-relevant files inside their platform specific /binaries folder.

**Comment by chrbertsch** [comment]
The content of the a specific binaries/platform folder should be platform specific.

**Comment by chrbertsch** [comment]
Design Webmeeting: 

Irina: what is the difference between the /binaries folder and the /resources folder? Where does an exporter put what?
Andreas: certain DLLs cannot be in the resource folder. OS specific load routines have acess specific files during runtime.
Irina: for DLLs it is already clear.
Pierre: For DLLs it is clear. Everything that is needed during runtime and is under control of the FMU can be put in the resources 
Andreas: ... for A2L we have several copies
Pierre: no use case for using it during load time
Markus: Proposal: everything in /binaries must be available before your load the dll and first call to the FMU, in the resources folder only after instanciation. What is inside this directories is up to the FMU.
Timo: for binaries one makes assumption on OS "magic", for resources one can use the filepath.
Andreas: for binaries, one has to unpack only the specific subdirectory. For resources everything has to be unpacked.
Irina: This seems to be a workaround for not having platform specific resources folder.
Andreas: Layered standards could provide more information for platform-specific content of resources files.
Andreas: fix language at the two places 
Pierre: let's go with Markus' proposal, clarify processing expectations.
