### ISSUE TITLE
use the org.fmi-standard.* prefix rather than org.modelica

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1827]
If we release layered standards as FMI standard, should we use org.fmi-standard.fmi-ls-XXX instead of org.modelica.fmi-ls-XXX?

**Comment by chrbertsch** [comment]
> If we release layered standards as FMI standard, should we use org.fmi-standard.fmi-ls-XXX instead of org.modelica.fmi-ls-XXX?

I agree. 

This should be changed in https://github.com/modelica/fmi-ls-bus/blob/main/docs/index.adoc#21-network-description-files and https://github.com/modelica/fmi-ls-xcp/blob/main/docs/index.adoc#21-network-description-files.

**Comment by andreas-junghanns** [comment]
Done in both fmi-ls-xcp and fmi-ls-bus.
