### ISSUE TITLE
fmi3ModelDescription.xsd: Missing Dimension and Annotations elements for Enumerations

### ISSUE THREAD

**Issue by IZacharias** [modelica/fmi-standard#1837]
According to Figure 28 in FMI 3.0 specification, array variables of type enumeration should be possible:
![image](https://user-images.githubusercontent.com/33029000/204255996-2d0e97f6-cb44-4e70-bf76-bde2310a973e.png)
However, the fmi3ModelDescription schema does not allow this. The Enumeration element does not contain a Dimension element:
![image](https://user-images.githubusercontent.com/33029000/204255454-bed1b6a6-16e9-4204-af9d-6b5881c23a4b.png)
Furthermore, the Annotations element is also missing.

I don’t see any reason to forbid Enumeration arrays. Therefore, I assume that this is a bug in the schema and not in the specification document.

**Comment by pmai** [comment]
Hi Irina, the schema is actually correct, as far as I can see, in that `fmi3Enumeration` is an extension of `fmi3MandatorilyTypedInitializableVariable`, which is an extension of `fmi3MandatorilyTypedArrayableVariable`, which is an extension of `fmi3TypedArrayableVariable`, which is an extension of `fmi3ArrayableVariable` which has the `Dimension` elements, which is again an extension of `fmi3AbstractVariable`, which has the `Annotations` element.

I don't know where the second diagram is coming from, but it seems that that program does not show the inherited/extension base content, but only the added content, leading to the confusion?

**Comment by IZacharias** [comment]
Hi Pierre, I think there is a bug in `fmi3MandatorilyTypedArrayableVariable`. It is not an extension of `fmi3TypedArrayableVariable` but `fmi3TypedArrayableVariable `is specified as restriction:

```
<xs:complexType name="fmi3MandatorilyTypedArrayableVariable" abstract="true">
        <xs:complexContent>
            <xs:restriction base="fmi3TypedArrayableVariable">
                <xs:attribute name="declaredType" type="xs:normalizedString" use="required"/>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>
```
I guess that this would be correct:
```
<xs:complexType name="fmi3MandatorilyTypedArrayableVariable" abstract="true">
	<xs:complexContent>
		<xs:extension base="fmi3TypedArrayableVariable">
			<xs:attribute name="declaredType" type="xs:normalizedString" use="required"/>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>
```

But then the declaredType attribute must be treated in a different way.

**Comment by pmai** [comment]
Hi Irina,

there is indeed a bug in the definition, however it should be a restriction (otherwise the use required would not be allowed/make sense); the real bug is that somewhere along the line the non-attribute content was not/no longer repeated in the restriction, as it should have been... probably my bad...

the fix would look like this:

```XSD
    <xs:group name="fmi3Dimensions">
        <xs:sequence>
            <xs:element name="Dimension" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="start" type="xs:unsignedLong"/>
                    <xs:attribute name="valueReference" type="xs:unsignedInt"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>
    <xs:complexType name="fmi3ArrayableVariable" abstract="true">
        <xs:complexContent>
            <xs:extension base="fmi3AbstractVariable">
                <xs:group ref="fmi3Dimensions"/>
                <xs:attribute name="intermediateUpdate" type="xs:boolean"/>
                <xs:attribute name="previous" type="xs:unsignedInt"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    ...
    <xs:complexType name="fmi3MandatorilyTypedArrayableVariable" abstract="true">
        <xs:complexContent>
            <xs:restriction base="fmi3TypedArrayableVariable">
                <xs:sequence>
                    <xs:element ref="Annotations" minOccurs="0"/>
                    <xs:group ref="fmi3Dimensions"/>
                </xs:sequence>
                <xs:attribute name="declaredType" type="xs:normalizedString" use="required"/>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>
```

I'll create a PR...
