### ISSUE TITLE
Define acceptable tolerance of start values in XML vs. C code

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1865]
In [2.4.8](https://fmi-standard.org/docs/3.0/#start) the spec states that

> calling [fmi3Set{VariableType}](https://fmi-standard.org/docs/3.0/#get-and-set-variable-values) to set [start](https://fmi-standard.org/docs/3.0/#start) values is only necessary, if a different value as stored in the XML file is desired

However this can lead to problems if the importer relies on the start value in the XML and this value does not match the actual value in the C code.

**Comment by pmai** [comment]
This is not allowed to happen: The start value in the XML must be identical to the start value in the code. It is the responsibility of the exporter to ensure this. Algorithms do exist that ensure the printed representation of IEEE754 FP numbers Match exactly to the LSB both for printing (responsibility of the exporter) and for reading (responsibility of the importer). There was is no tolerance here, and the standard does IMHO not imply any.

**Comment by chrbertsch** [comment]
Steering Committee: 
Torsten: I came across FMUs where this did not match.
Andreas: The spec says: there non-normative-text that talks about consistency of values in the xml and the coded ones.  (form the table of start value: )"Initial or guess value of the variable. During instantiation, the FMU initializes its variables with their [start](https://fmi-standard.org/docs/3.0/#start) values.[Therefore, calling [fmi3Set{VariableType}](https://fmi-standard.org/docs/3.0/#get-and-set-variable-values) to set [start](https://fmi-standard.org/docs/3.0/#start) values is only necessary, if a different value as stored in the XML file is desired.It is not allowed to change the start values in the [modelDescription.xml](https://fmi-standard.org/docs/3.0/#modelDescription.xml) file of an FMU, as this would break the consistency with the hard-coded start values within the FMU.This could lead to unpredictable behavior of the FMU in different importers, as it is not mandatory to call [fmi3Set{VariableType}](https://fmi-standard.org/docs/3.0/#get-and-set-variable-values) to set [start](https://fmi-standard.org/docs/3.0/#start) values during initialization.]"
Pierre: I think that the Implementer's guide says something it is.
Antoine: what is the rationale for exact same value?
Pierre: I would be strict.
Christian, Andreas: As we discuss this, we should clarify this.
Andreas: We should explain how to do the printing right. Some ways to print remove precision.
Christian: this could be explained in the  IG
Pierre: The minimal requirement is, that the representation results in the same IEEE floating point representation. We should add an explanation and point to how to deal with floating point equality.
Decision: explain this in the IG 
@pmai : I could add this to the IG
