### ISSUE TITLE
Clarification for concatenation of arrays in get/set functions

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1877]
Some users outside the FMI design group seem to be confused how to concatenate arrays in the set-/get- functions in the cases of multiple variables, see e.g. https://github.com/CATIA-Systems/FMPy/issues/495#issuecomment-1549552070.

Do we need a clarifcation? Please critically review.

**Comment by binghe** [comment]
Hello,

I'm working on a monitor synthesis software [1] which is going to support FMI 2.0 and 3.0. After having throughly read the FMI 3.0 standard, I couldn't figure out how to set/get values of FMU arrays, until today I got the answer mentioned in the above issue by other users.  I believe this is not just my problem, my colleague who get touch with FMI much longer than me, also couldn't figure out this information.

Thus, for potential other users, I suggest this information on setting/getting arrays can be clearly described in next updates of the FMI 3.0 standard, better also with examples just those in the above issue comments.

Regards,

Chun Tian
Fondazione Bruno Kessler (FBK), Italy

[1] https://es-static.fbk.eu/tools/nurv/

**Comment by chrbertsch** [comment]
Closed by https://github.com/modelica/fmi-standard/pull/1888
