### ISSUE TITLE
Fmi 3.0 Correct Table 12. fmiModelDescription attribute details to list "variableNamingConvention" instead of "Convention"

### ISSUE THREAD

**Issue by adriantirea** [modelica/fmi-standard#1878]

**Comment by t-sommer** [comment]
@adriantirea, can you please describe the problem in more detail?

**Comment by adriantirea** [comment]
In Fmi 3.0 and 3.0 rc1 standard document there is the table 12 with title "fmiModelDescription attribute details" that is wrong. It needs to contain on the last line "variableNamingConvention" instead of "Convention"
