### ISSUE TITLE
Clarify restrictions on "intermediateUpdate"

### ISSUE THREAD

**Issue by PeterMeisrimelModelon** [modelica/fmi-standard#1884]
`Variables with [causality](https://fmi-standard.org/docs/3.0/#causality) = [parameter](https://fmi-standard.org/docs/3.0/#parameter) must not be marked with [intermediateUpdate = true](https://fmi-standard.org/docs/3.0/#intermediateUpdate).

This attribute is ignored in Model Exchange and Scheduled Execution. Variables of type [Clock](https://fmi-standard.org/docs/3.0/#Clock) must not have the [intermediateUpdate](https://fmi-standard.org/docs/3.0/#intermediateUpdate) attribute. The default value of this attribute is false.`

I'd assume not only parameters, but also structuralParameters & calculatedParameters should not be marked with intermediateUpdate.

Also, "Variables of type Clock must not have the intermediateUpdate attribute" would seem to indicate that even setting the default value (=false) would not be permissible.

**Comment by chrbertsch** [comment]
@PeterMeisrimelModelon : please provide more details

**Comment by PeterMeisrimelModelon** [comment]
Accidentally submitted new issue before adding description, edited now.

**Comment by chrbertsch** [comment]
"structuralParameters" & "calculatedParameters" should not be marked with [intermediateUpdate = true](https://fmi-standard.org/docs/3.0/#intermediateUpdate); to my understanding this is already clear (but could be made more explicit): in the definition of "requiredIntermediateVariables" (https://fmi-standard.org/docs/main/#requiredIntermediateVariables) it is already stated that "For Co-Simulation, these intermediate variables must be continuous-time variables.", and as listed in https://fmi-standard.org/docs/main/#table-allowed-variability-causality-combinations, this excludes structural and calculated parameters.
(btw. "For Co-Simulation ... " is misleading, as intermediateUpate is only used in CS.  Should we change this?)


Regarding Clock variables: As they must not have the [intermediateUpdate](https://fmi-standard.org/docs/main/#intermediateUpdate) attribute, they cannot be part of "requiredIntermediateVariables" and thus cannot be set. I do no know what to clarify here.

**Comment by PeterMeisrimelModelon** [comment]
Thanks for clarifying the more explicit restriction with the MR.

As for the Clock variables, this might be more of a language consistency concern. "...must not have [...] attribute ..." can be read as "The mere existence of this attribute is erroneous, irregardless of the value". This is particularly odd, since there is a default value.

Compare: 

1. "Type definitions without unit **must not** have a unit attribute."
2. "A [structural parameter](https://fmi-standard.org/docs/3.0/#structuralParameter) **must not** have a [<Dimension>](https://fmi-standard.org/docs/3.0/#Dimension) element"
3. For the variable with [causality](https://fmi-standard.org/docs/3.0/#causality) = [independent](https://fmi-standard.org/docs/3.0/#independent), the attribute [initial](https://fmi-standard.org/docs/3.0/#initial) **must not** be provided, because its start value is set with the [startTime](https://fmi-standard.org/docs/3.0/#startTime) parameter of [fmi3EnterInitializationMode](https://fmi-standard.org/docs/3.0/#fmi3EnterInitializationMode).

How about "Variables of type Clock must not be marked with intermediateUpdate = true"?
