### ISSUE TITLE
Interpretation of fmi3GetBinary with array variables

### ISSUE THREAD

**Issue by k-a-le13** [modelica/fmi-standard#1906]
Hi,

What should be expected in the return data for `fmi3GetBinary` if some of the variables are arrays? 
 
Say that (as the importer) I want to get the data for 2 variables: 
- Value Reference 1 is a binary **scalar**, and 
- Value Reference 2 is a binary **array with a dimension of 3**. 

Will `values[]` contain 2 pointers or 4? 
- That is, will there be one pointer to the start of VR 1 and one pointer to the start of VR 2 (Option 1 below)? 
- Or will there be one pointer to the start of VR 1 and 3 pointers to the start of each element of VR 2 (Option 2 below)?

|Param | Option 1 | Option 2
|-------|-----------|----------
| valueReferences | [1, 2] | [1, 2]
| nValueReferences | 2 | 2
| values | _[a1*, a2*]_ where <br/> a1 = [1,2,3,4,5]; <br/> a2 = [[1,2,3,4]; [5,6,7,8]; [9,10,11,12]] |  _[a1*, a2*, a3*, a4*]_ where <br/> a1 = [1,2,3,4,5]; <br/> a2 = [1,2,3,4]; <br/> a3 = [5,6,7,8]; <br/> a4 = [9,10,11,12]
| valueSizes | [5,4,4,4] | [5,4,4,4]
| nValues | 4 | 4

The interpretation of the following sections of the FMI standard seems to point towards **Option 2**, but it would be great to have confirmation or explanation if different.

- **2.2.7.1. Serialization of Array Variables**: 
  - If an API function takes multiple value references, the serialized variables are concatenated.
- **2.2.7.2 Getting and Setting Variable Values**: 
  - `values` is a vector consisting of the [serialized](https://fmi-standard.org/docs/3.0.1/#serialization-of-variables) values of these variables.
  - `valueSizes` is a vector with the actual sizes of the values for binary variables. 

Perhaps, it would be beneficial to illustrate the case above in [Reference-FMUs](https://github.com/modelica/Reference-FMUs). We looked for an example, but did not find one.

**Comment by t-sommer** [comment]
If I understand your example correctly, what you mean is not

> Value Reference 2 is a binary array with a dimension of 3.

but

> Value Reference 2 refers to a 1-dimensional array variable of type fmi3Binary with 3 elements.

Then `Option 2` is correct.

`Option 1` can't work, because `a2*` would be a pointer to an array of `fmi3Binary` rather than an array of `fmi3Binary` as required by `fmi3GetBinary`:

```C
typedef fmi3Status fmi3GetBinaryTYPE (fmi3Instance instance,
                                      const fmi3ValueReference valueReferences[],
                                      size_t nValueReferences,
                                      size_t valueSizes[],
                                      fmi3Binary values[],
                                      size_t nValues);
```

**Comment by k-a-le13** [comment]
@t-sommer: thank you for the quick reply! That makes sense and the definition for `fmi3GetBinary` put the final nail in the coffin.
