### ISSUE TITLE
Forbid or discourage nameclashes of terminal names with normal model variables

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1907]
... came up in the LS

**Comment by klausschuch** [comment]
meeting 7.11.2023:
decision: we will not forbid (or discourage) name clashes between terminals and model variables for the ls-struct and we suggest to not do it for the main standard either.
reasoning: it is allowed in fmi3.0 and for the ls-struct it doesn't really make sense to introduce it just for this ls.
