### ISSUE TITLE
Handling of time-based Clocks with interval=0

### ISSUE THREAD

**Issue by PTaeuberDS** [modelica/fmi-standard#1916]
In section [2.3.5. State: Event Mode](https://fmi-standard.org/docs/3.0.1/#EventMode) in the description of the fmi3SetClock function the following restriction is made for time-based clocks:

"Only [time-based Clocks](https://fmi-standard.org/docs/3.0.1/#time-based-clock) must not be active for more than one call of [fmi3UpdateDiscreteStates](https://fmi-standard.org/docs/3.0.1/#fmi3UpdateDiscreteStates) per [Event Mode](https://fmi-standard.org/docs/3.0.1/#EventMode)."

This restriction contradicts the possibility for aperiodic time-based clocks to return an interval=0, which is possible according to the interval definition for, e.g., changing clocks:
![image](https://github.com/modelica/fmi-standard/assets/92858933/d25abe4a-73ae-45f8-9e2c-07a582f6ee46)

The restriction should only be made for periodic clocks:
"Only ~[time-based Clocks](https://fmi-standard.org/docs/3.0.1/#time-based-clock)~ periodic Clocks must not be active for more ..."

**Comment by chrbertsch** [comment]
FMI Design Webmeeting: 

Klaus: is it possible to call fmi3getInterval in event mode? 
Patrick: yes
Klaus: This question sound familiar ... Implicitely we would make a time-based clock a triggered clock. This was perhaps the intention.
Patrick: But allowing an interval=0 is a contradiction. 

Does someone remember why we have it as it is defined currently?

**Comment by PTaeuberDS** [comment]
Any new insights here?

**Comment by masoud-najafi** [comment]
"Only time-based-clock must not be active for more than one call of [fmi3UpdateDiscreteStates] per [Event Mode]"
is very hard to understand, it would be good to reformulate this phrase to be easier to read.  
Yes, I agree that a changing clock (which is apriodic) can have a zero Time Interval. So it contradicts.

**Comment by PTaeuberDS** [comment]
How would you propose to fix that? I think it makes sense to allow interval=0 for aperiodic and triggered clocks and to disallow it for periodic clocks.

**Comment by masoud-najafi** [comment]
I agree with this change..
