### ISSUE TITLE
Define legal values for currentCommunicationPoint after t = startTime

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1924]
Proposal:

`currentCommunicationPoint`(t_i+1) = `currentCommunicationPoint`(t_i) + `communicationStepSize`(t_i) for `time` > `startTime`

up to numerical accuracy.

**Comment by chrbertsch** [comment]
Karl: The currentCommunicationPoint is a sanity check. It is better noch to define a tolerance.
Torsten S: I came across this when implementing checks in the reference FMUs
Kaska: we can have the early return
Andreas: Here we are talking about the FMU checking currentCommunicationPoints passed to the FMU
Karl, Andreas: it is up to the FMU hot to react. the FMU can expect a "reasonable close" next currentCommunicationPoint.

We have 
![image](https://github.com/modelica/fmi-standard/assets/16363372/402c92fd-0912-4d9e-b445-c77cf4560feb)
in the specification.
