### ISSUE TITLE
FMI 2.0.4 PDF displays version 2.0.3 in header

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1925]
Screenshot from Chrome:

![image](https://github.com/modelica/fmi-standard/assets/2453858/9defea01-d332-4f1a-a96a-8c7cde4d65a4)

**Comment by chrbertsch** [comment]
Ah, one has to adapt this in the Word document properties: 
![image](https://github.com/modelica/fmi-standard/assets/16363372/b49d50ac-643f-458c-bd2c-341999f14765)

**Comment by chrbertsch** [comment]
Already fixed in the Word document
![grafik](https://github.com/user-attachments/assets/be3f65eb-ae13-4f66-8e4b-b936ea099cac)
