### ISSUE TITLE
fmi2_import_get_variable_has_start(fmi2_import_variable_t*) API is returning zero (0) for Outputs and Global Block Outputs

### ISSUE THREAD

**Issue by Yaismin** [modelica/fmi-standard#1930]
Hi Team,

I have a requirement of passing start value for  Outputs and Global Block Outputs variables in FMI2.0.
As part of this , I am trying to utilize fmi2_import_get_variable_has_start(fmi2_import_variable_t*) API to check if the variable contains start. But unfortunately, above mentioned API is returning zero (0), so I could not proceed further for retrieving the start value.

My question is, is it expected behavior for fmi2_import_get_variable_has_start(fmi2_import_variable_t*) API not to read start value for Outputs and Global Block Outputs variables. Though I am getting 1 while trying to read from Parameters and Inputs variable.

Many Thanks,
Yaismin

**Comment by chrbertsch** [comment]
Hello, 
this repo and its issues are for the FMI Standard and not for user support for specific tools.
Your questions seems to related to a specific implementation (FMI-Library?). 
Please ask there (https://github.com/modelon-community/fmi-library) or on StackOverflow (https://stackoverflow.com/questions/tagged/fmi) providing more information on your setup (used tools for FMU export and import)
