### ISSUE TITLE
Proposal for standardizing `fmiModelDescription` interface

### ISSUE THREAD

**Issue by hyumo** [modelica/fmi-standard#1961]
## As a user

When I need to get FMU information, I usually rely on FMU importers (`fmpy`, `pyfmi`, `fmilibrary` etc) to parse the `modelDesciption.xml` file and generate the `fmiModelDescription` object. Some observations in this process:

- The interface that interacts with the `fmiModelDescription` struct differs based on importer selection.
   - Different tools generate the `fmiModelDescription` struct to their own taste, this has caused large inconsistencies when users' goal for `fmiModelDescription` object is actually quite consistent, which is: *I just want to get information from the FMU but I dont want to parse the modelDescription.xml myself*.
- Even within the same tool, the interface that interacts with `fmiModelDescription` varies from version to version. It is very common that a certain field is missing due to human errors of the developers.
- Users almost always need to rely on an importer even when their simulation task is simple.

## As an importer tool developer

-  An XML parser/parsing is always needed to be implemented. It takes a lot of unnecessary time and effort to implement something that's already done on the exporters' side (exporters serialize their `fmiModelDescription` struct into an xml, then the importer needs to deserialize the xml back to the `fmiModelDescription` struct, what a waste of time)
- `dll` or `so` loading is runtime-dependent, but XML parser is usually language-dependent. For example, it is much harder to create an fmi importer tool in `C` compared to `C++` or `Python`, but essentially the effort could be almost identical without XML parsing (or unzipping). 

## Observations from FMIlibrary
- Some FMI tools depend on `FMILibrary` largely because of the `fmiModelDescription` interface in `C`, in this way, their higher-level language implementations could share the same interface
- Recreating a new `FMILibrary` from scratch is hard, but if the `fmiModelDescription` interface is "standardized" at the standard level then I don't even see the need of using it. 
- If you ask me what is the ultimate goal of this proposal, it will look something like: *an fmilibrary-like interface in the fmi standard*

**Comment by t-sommer** [comment]
Maybe someting like https://github.com/modelica/Reference-FMUs/blob/main/fmusim/FMIModelDescription.h ?

**Comment by hyumo** [comment]
Yes, exactly, except maybe doing it without the following constructor/destructor functions and make it part of `fmi1/2/3Instance`?
```
FMIModelDescription* FMIReadModelDescription(const char* filename);
void FMIFreeModelDescription(FMIModelDescription* modelDescription);
```

**Comment by chrbertsch** [comment]
This request is about how to represent the modelDescription.xml content inside an importer.
That is not an FMI Standardization issue – rather it is a quality of implementation issue for (open-source) importers – maybe you can raise the issue with the tools you are using?

On the technical side: standardizing the model description representation (and make it the only option) would force loading the shared object while the current approach allows loading the xml content independently of loading the shared object – and would also force the same binary representation for all kinds of different platforms and languages – contrary to some of the guiding ideas of the FMI standard.
