### ISSUE TITLE
Array Dimensions are always local constants in the FMU

### ISSUE THREAD

**Issue by Ricfav** [modelica/fmi-standard#1962]
Hello,
I hereby describe an issue I'm confronting when dealing with arrays in my models. 
I kindly ask for your help to understand how the issue could be overcome.

**Expected/Desired Behaviour:**
I want to export an FMU with array dimensions as fixed parameters which I could modify before initializing the simulation.

**Observed Behaviour:**
When I export the model the array dimension has causality = local, variability=constant and is thus not modifiable.

**Test code:**
 
```
model ArrayDimExample

  parameter Integer N = 5 "array dimension";
  Real A[N] "my array";

equation 

  for i in 1:N loop
    A[i] = i;
  end for;

end ArrayDimExample;

```

**Software Version:**
`Dymola 2024x Refresh 1, 2024-04-12`

**FMU export settings:**
Type: `Model Exchange + Co-Simulation`
Version: `3.0 (I also tried 2.0 with same results)`
Active flags:
```
 - Include source Code
 - Export with string parameters
 - Copy resources to FMU
 - Show dialog when exporting
 - Evaluate False on Export Parameter (I also tried with this flag off, same results)
```
 
Thank You in advance for your kind support.

Kind regards,
RF

**Comment by t-sommer** [comment]
This repository is dedicated to the FMI Standard. For tool specific questions, please ask this question on [StackOverflow](https://stackoverflow.com/) or contact your tool vendor.
