### ISSUE TITLE
Optional elements of ModelDescription

### ISSUE THREAD

**Issue by stanislav-git84** [modelica/fmi-standard#1966]
The FMU 2.0 Spec defines three optional elements of **ModelDescription**:

- Outputs
- Derivatives and
- InitialUnknowns

They're depicted in "dashed" box, and also the description indicates these three are optional.
![ModelStructure_definition](https://github.com/user-attachments/assets/c528f714-b2b9-4502-ad74-4166eef4fdb2)

The FMPy validation functionality as well as the https://fmu-check.herokuapp.com/ website however report a failed validation:

> `ModelStructure/InitialUnknowns does not contain the expected set of variables. Expected {product} but was {}.`

when FMU defines only the Outputs element (see SimpleExample_default.fmu).

![FMPy_validation](https://github.com/user-attachments/assets/720ce430-3e89-4534-ba00-2604712f53f5)
![FMU_check_website_validation](https://github.com/user-attachments/assets/10f58f00-697f-4cf2-bcc2-b49c29074cab)

When the same FMU defines also the InitialUnknown element (see SimpleExample_InitialUnknowns.fmu), the validation succeeds.
![FMUs_diff](https://github.com/user-attachments/assets/dfe96635-d771-4536-874b-8fb6c9a424ec)

Do we interpret the Spec incorrectly, or is this an issue of the validation functionality?

**Comment by pmai** [comment]
The fact that the XML schema makes the XML elements optional, and the fact that the _dependencies_ of the variables are optional does not contradict or override the other requirements in the standard, namely quoting entries from the table in section _2.2.8 Definition of the Model Structure (ModelStructure)_:

> Outputs: Ordered list of all outputs, in other words a list of `ScalarVariable` indices where every corresponding `ScalarVariable` must have `causality = "output"` (and **every variable with `causality=”output”` must be listed here**).

> InitialUnknowns: Ordered list of all exposed Unknowns in Initialization Mode. This list consists of all variables with
> (1) `causality = "output"` and (`initial="approx"` or `"calculated"`), and
> (2) `causality = "calculatedParameter"` and
> (3) all continuous-time states and all state derivatives (defined with element `<Derivatives>` from `<ModelStructure>`) with `initial="approx"` or `"calculated"` [if a Co-Simulation FMU does not define the `<Derivatives>` element, (3) cannot be present.].

So as long as your variable `product` is an output with initial either `approx` or `calculated` (which is the default for outputs that are non-constant), it must be listed in both `Outputs` and `InitialUnknowns`, even if you do not want to provide dependency information.
