### ISSUE TITLE
Errors and inconsistencies in table 2

### ISSUE THREAD

**Issue by Tc-Fast** [modelica/fmi-standard#1982]
Row 1 and 2: The subscripts use numbers in italic font. In mathematical notation numbers should always use a "normal" font.
Row 1: The precedence of "or" and "and" is unclear. Using parenthesis helps.
Row 3 and 4: The use of "epsilon" and "varepsilon" is inconsistent. I would like to use only "varepsilon" for clarity and consistency.
Row 7: "v" is sometimes printed in italic font and sometimes in "normal" font.
Row 7: "I > 0" is wrong. This should be "t_I > 0"
Row 7: This sentence is unclear to me: "if v for clocked variable v of clock k". I suggest this: "if v is a clocked variable of clock k"

Furthermore all abbreviations are capitalized in the documentation. In chapter 1.1 is one instance of a lower case "html". I suggest to capitalize it.

**Comment by KarlWernersson** [comment]
Thanks for fixing
