### ISSUE TITLE
Define non-x86 platforms for FMI 2.0

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1996]
as proposed at the [Advisory Committee meeting](https://github.com/modelica/fmi-design/edit/master/Meetings/2024/2024-11-05-FMI-Advisory-Committee/README.md).

This is (indirectly) already solved by referring to the "platform tuples" introduced by FMI 3.0.

From the FMI Specification 2.0.4, 2.3 FMU Distribution (p. 70):

> The following names are standardized: for Windows: "win32", "win64"- for Linux: "linux32", "linux64", for Macintosh: "darwin32", "darwin64" where "32" stands for "32-bit x86" and "64" for "64-bit x86" respectively. For any other platforms the "platform tuples" defined in the FMI 3.0 Specification, 2.5.1.4.1. Platform Tuple Definition, or any updated "platform tuples" published by MAP FMI on fmi-standard.org, should be used.

Further we should also define which directory takes precedence if e.g. both `win64` and `x86_64-windows` exist.

**Comment by pmai** [comment]
Actually looking at the text this already seems to solve the problem, and the precedence is also clearly given, so maybe this just needs more publicity to make people aware that this has already been solved in 2.0.x?
