### ISSUE TITLE
Build Description , What is a the point of a optimal attribute with a default value?

### ISSUE THREAD

**Issue by KarlWernersson** [modelica/fmi-standard#2019]
My understanding of an optional values that it is only valid if it is printed in the xml,
A default value is what value the attribute has if its not printed.
So to combine default value and optional is a bit confusing for me.
Or have i misunderstood something? 

In buildConfiguration/SourceFileSet/PreprocessorDefinitions/optional
and buildConfiguration/Library/external

both are optional Boolean with a default value?
Shouldn't they either have a default value or be optional?

**Comment by PTaeuberDS** [comment]
An optional attribute without default value is considered as "not valid/defined" if it is missing. An optional attribute with a default value is assigned the default value.

In the case of buildConfiguration/Library/external the library can either be internal or external, so a default value is needed (which only makes sense if the attribute is optional).

**Comment by KarlWernersson** [comment]
so, i still don't follow.

if its optional its is not defined, so either it is written and then it has a value true or false, or it is not written and then it don't have a value.

if it has a default value its is ether written with a value true or false, or it is not written and it can be assumed to have the value false.

my point is that optional and default value contradict themselves is the attribute is not present in the xml, is it false or not defined?
if its false it is not an optional attribute but only  a attribute with a default value, if it undefined if not written it don't need a default value as it will have a value if it is written

**Comment by otronarp** [comment]
The alternative to optional is that it's a required attribute and it's forbidden to have a default value in that case, see [3.2.3](https://www.w3.org/TR/xmlschema-1/#d0e2403) in the XSD specification.

> If `default` and `use` are both present, `use` must have the actual value `optional`.

**Comment by PTaeuberDS** [comment]
I think the misunderstanding is in the meaning of the optional. If an attribute is defined as optional in the schema it is still a defined attribute of that element, but it must not be explicitly written in the XML document. If it is not written in the XML document it is still a defined characteristic of that element but either has no valid value or the default value if defined in the schema.

**Comment by KarlWernersson** [comment]
Ok thanks, it has clarified it for me.
