### ISSUE TITLE
fmiCallbackFunction structure should declare const function pointers

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#216]
**Reported by andreas&#x2e;junghanns on 3 Apr 2014 15:32 UTC**
We changed the way to pass fmiCallbackFunctions in FMI20 to be by reference:
```
   typedef fmiComponent fmiInstantiateTYPE (fmiString, fmiType, fmiString, fmiString, const fmiCallbackFunctions*, fmiBoolean, fmiBoolean);
```

We need to clarify, that the callback function pointer won't change after initializations (like switching the logging callback function in the middle of the simulation).

We might simply redefine as (note the added `const`'s):
```
typedef struct {
   const fmiCallbackLogger         logger;
   const fmiCallbackAllocateMemory allocateMemory;
   const fmiCallbackFreeMemory     freeMemory;
   const fmiStepFinished           stepFinished;
   const fmiComponentEnvironment   componentEnvironment;
} fmiCallbackFunctions;
```

To clarify, we might also add to:
```
The struct fmiCallbackFunctions is provided as a pointer to the struct when instantiating an FMU, and not as the struct itself. This simplifies the importing of an FMU into a Modelica environment.
```
something like
```
The callback functions pointers will not change during simulation.
```

If, however, we decide that these function may change during simulation, then this needs clarifications as well.

----

Migrated-From: https://trac.fmi-standard.org/ticket/216

**Comment by modelica-trac-importer** [comment]
**Comment by otter on 4 Apr 2014 10:31 UTC**
Fixed according to proposal in the fmiFunctionTypes.h file. In the specification the following sentence is added:
  It is not allowed to change these functions between fmiInstantiate(..) and fmiTerminate(..) calls.

**Comment by modelica-trac-importer** [comment]
**Comment by rfranke on 26 Jul 2014 19:08 UTC**
This change has quite some impact because it is not allowed anymore to assign values to the fields of fmi2CallbackFunctions. It only works nicely if static arguments are used at construction time. It becomes clumpsy if the _fmi2CallbackFunctions_ struct or members such as _componentEnvironment_ are allocated dynamically at runtime. 

One out of two things need to be changed: Either the documentation in FMI 2.0 spec:
   - section 2.1.5: add const qualifiers in typedef struct fmi2CallbackFunctions
   - section 4.2.5: change C code example because it is not allowed to assign values to const fields

or the implentation in fmi2FunctionTypes.h
   - remove const qualifiers from members of struct fmi2CallbackFunctions

**Comment by modelica-trac-importer** [comment]
**Comment by otter on 27 Jul 2014 09:22 UTC**
Replying to [comment:2 rfranke]:
> This change has quite some impact because it is not allowed anymore to assign values to the fields of fmi2CallbackFunctions. It only works nicely if static arguments are used at construction time. It becomes clumpsy if the _fmi2CallbackFunctions_ struct or members such as _componentEnvironment_ are allocated dynamically at runtime. 
> 
> One out of two things need to be changed: Either the documentation in FMI 2.0 spec:
>    - section 2.1.5: add const qualifiers in typedef struct fmi2CallbackFunctions
>    - section 4.2.5: change C code example because it is not allowed to assign values to const fields
> 
> or the implentation in fmi2FunctionTypes.h
>    - remove const qualifiers from members of struct fmi2CallbackFunctions

FMI 2.0 is released, so a change is not possible now (and the documentation should be improved in a later revision or release).

I did not check, but as I recall, you can cast everything in C. So you can just allocate the function pointers at run time and then make an appropriate cast where the "const" attribute is included in the assignment.

**Comment by modelica-trac-importer** [comment]
**Comment by rfranke on 27 Jul 2014 11:52 UTC**
One could also say that the specification without const qualifiers has been released and the implementation in fmi2FunctionTypes.h will be fixed in a later build. 

If the const qualifiers remain, then an initialization code as given in section 4.2.5
```
////////////////////////// 
//Initialization sub-phase 
 
//Set callback functions, 
fmi2CallbackFunctions cbf; 
cbf.logger = loggerFunction; //logger function 
cbf.allocateMemory = calloc; 
cbf.freeMemory = free; 
cbf.stepFinished = NULL; //synchronous execution 
cbf.componentEnvironment = NULL; 
```

must be changed. With C99 most likely to:
```
//Set callback functions 
fmi2CallbackFunctions cbf = { 
    .logger = loggerFunction, //logger function 
    .allocateMemory = calloc, 
    .freeMemory = free, 
    .stepFinished = NULL, //synchronous execution 
    .componentEnvironment = NULL 
};
```

This is fine if the the function `fmi2Instantiate`of the FMU copies the pointers to `logger`, `allocateMemory`, etc. to its local memory, so that the calling environment can release the `cbf`struct afterwards from its stack.

If however the FMU just holds a pointer to the `cbf` struct, then the calling environment must keep the corresponding memory until after fmi2Terminate. If the FMU is loaded dynamically at runtime, then this memory is typically placed on the heap. Then the values of the struct members must be set with some low-level `memcpy` function or a cast of the whole struct to some private re-definition without const qualifiers.

If the const qualifiers remain, then the specification should be further extended with a statement saying that the FMU must copy all pointers to its local memory, so that the calling environment can release the `cbf` struct immediately after having called `fmi2Instantiate`. This way the calling environment can place the struct on its stack using clean C99 syntax.

Is it really worth all the trouble with C99, memcpy, casts, changes/extensions to the specification?

Or shouldn't the const qualifiers just be removed in a later build from the definition of the struct in fmi2FunctionTypes.h, relying on the already existing statement in the specification that the pointers must not be changed between fmi2Instantiate and fmi2Terminate?

**Comment by modelica-trac-importer** [comment]
**Comment by andreas&#x2e;junghanns on 27 Jul 2014 20:16 UTC**
Aside from this being too late, C allows you to circumvent the const-restrictions in many different ways. Defining as const is a C-ish way to indicate the expected change behaviour. So I don't even see a need to change it for convenience sake.

**Comment by modelica-trac-importer** [comment]
**Comment by rfranke on 27 Jul 2014 20:54 UTC**
Please note that the released FMI 2.0 specification declares `fmi2CallbackFunctions` without const qualifiers in section 2.1.5. Also the C code example in section 4.2.5 would not be valid with const qualifiers. 

On the other hand side, the declaration in `fmi2FunctionTypes.h` uses const qualifiers. This means that there is a need to change something.

You appear to propose that the FMI 2.0 specification shall be changed to reflect the implementation in `fmi2FunctionTypes.h`. 

Note: the C99 initializers used in my code snippet above should not be used in the FMI 2.0 spec because Microsoft didn't support C99 until very recently; meaning that it would'nt work with relatively new Visual Studio's.

Can you please invest a minute and re-write the C code example in section 4.2.5 for a `fmi2CallbackFunctions` struct with const members? Which of the many different ways allowed by C would you propose for the FMI 2.0 spec?

**Comment by modelica-trac-importer** [comment]
**Comment by andreas&#46;junghanns on 27 Jul 2014 21:03 UTC**
We will have to wait with any change for the 2.0.1 revision because 2.0 was released.

**Comment by modelica-trac-importer** [comment]
**Comment by otter on 28 Jul 2014 07:51 UTC**
I did not check, but the example code in section 4.2.5 should be something like:
```
fmi2CallbackFunctions cbf;
cbf.logger         = (const fmi2CallbackLogger) loggerFunction;
cbf.allocateMemory = (const fmi2CallbackAllocateMemory) calloc;
cbf.freeMemory     = (const fmi2CallbackFreeMemory) free;
cbf.stepFinished   = (const fmi2StepFinished) NULL;
cbf.componentEnvironment = (const fmi2ComponentEnvironment) NULL;
```
Note, all the function pointers can be allocated at run time. This (tiny) correction can be included in the next revision

**Comment by modelica-trac-importer** [comment]
**Comment by rfranke on 28 Jul 2014 09:49 UTC**
This doesn't work because the l-values of the assignments are const, meaning that nothing can be assigned to them after the construction of cbf. I'm afraid that one has to bypass the type conventions with some low-level memory copy operations for the pointer values or with a cast of a pointer to the whole cbf struct, e.g. to a private re-definition of fmi2CallbackFunctions without const qualifiers. In mine such tricks should not be required for a regular use of the FMI interface.

Moreover, note once more the definition of fmi2CallbackFunctions in section 2.1.5 of the FMI 2.0 specification on page 19 without const qualifiers:
```
typedef struct {
    void (*logger)(fmi2ComponentEnvironment componentEnvironment,
                   fmi2String instanceName,
                   fmi2Status status,
                   fmi2String category,
                   fmi2String message, ...);
    void* (*allocateMemory)(size_t nobj, size_t size);
    void (*freeMemory) (void* obj);
    void (*stepFinished) (fmi2ComponentEnvironment componentEnvironment,
                          fmi2Status status);
    fmi2ComponentEnvironment componentEnvironment;
} fmi2CallbackFunctions;
```

Two different versions of the struct fmi2CallbackFunctions have been released: one in the specification document an another one in the include file.

I think I will pick the version from the specification document and remove the const qualifiers from my copy of the include file.

**Comment by modelica-trac-importer** [comment]
**Comment by iakovn on 28 Jul 2014 10:24 UTC**
I agree with the last comment. Explicit casting away of const qualifiers is always a bad practice indicating that something is wrong in the code. In this particular case having const fields cannot be handled consistently.

To enforce "fixed" callbacks I'd suggest that the spec in 2.1.5 explicitly requires FMUs to make internal copies of the function pointers so that the fmi2CallbackFunctions struct can be de-allocated in the environment directly after fmi2Instantiate returns.

**Comment by modelica-trac-importer** [comment]
**Comment by andreas&#46;junghanns on 5 Aug 2014 07:37 UTC**
This fix/clarification needs to go into 2.0.1.

**Comment by KarlWernersson** [comment]
Since we separate definitions in the standard and the header, we get an out and can choose the one we like for fmi 2.0.1.
I would propose to remove the const qualifier.

**Comment by KarlWernersson** [comment]
decision
write text pointing out inconsistencies for 2.0.1
fix in 3.0

**Comment by KarlWernersson** [comment]
When fixing this i saw the folowing lines in the specification

In the default fmi2FunctionTypes.h file, typedefs for the function definitions are present
to simplify the usage. **This is non-normative.** The functions have the following meaning:

Am i understanding correctly that the header files are non normative, then it is quite clear that the callback functions are defined in the standard document and the non const definition applies?

**Comment by chrbertsch** [comment]
Closing as fixed with https://github.com/modelica/fmi-standard/commit/cb417acfcb7f1e14a0bd1e4d4b5a6d1c76826326 (Remove const modifier from fields of fmi2CallbackFunctions)

**Comment by chrbertsch** [comment]
@pmai  checked that the RC4 docu is fine regarding this.
