### ISSUE TITLE
Lack of integer types

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#251]
**Reported by anonymous on 13 May 2014 12:39 UTC**
FMI standard should support more types of integer.
signed/unsigned 32/64bits integers should be support. In other words:
 * 32bits signed integer (already supported by FMI 1.0 and 2.0)
 * 32bits unsigned integer (not already supported)
 * 64bits signed integer (not already supported)
 * 64bits unsigned integer (not already supported)

----

Migrated-From: https://trac.fmi-standard.org/ticket/251

**Comment by modelica-trac-importer** [comment]
**Comment by resteve on 13 May 2014 14:02 UTC**
Sorry I've reported the ticket anonymously...

**Comment by modelica-trac-importer** [comment]
**Comment by otter on 30 May 2014 07:12 UTC**
Replying to [ticket:251 anonymous]:
> FMI standard should support more types of integer.
> signed/unsigned 32/64bits integers should be support. In other words:
>  \* 32bits signed integer (already supported by FMI 1.0 and 2.0)
>  \* 32bits unsigned integer (not already supported)
>  \* 64bits signed integer (not already supported)
>  \* 64bits unsigned integer (not already supported)

This change is too late for FMI 2.0. Should be included in FMI 2.1

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 1 Jun 2018 13:10 UTC**
Could be important in the future in the context of ACOSAR and EMPHYSIS.

**Comment by TorstenBlochwitz** [comment]
Discussion at the FMI Design Meeting in Roanne:

Poll options:
1. Do nothing, but clock resolution and interval counter would require 64 bit type (5)
2. Change platform type to fmi3Integer = int64 (4)
3. Add 8 new integer types (uint8, int8, uint16, int16, uint32, int32, uint64, int64) and keep platform types (7)
4. Add 8 new integer types (uint8_t, int8_t, uint16_t, int16_t, uint32_t, int32_t, uint64_t, int64_t) and remove platform types and remove existing Integer type (12)

**Comment by HansOlsson** [comment]
Note that C99 defines both `int16_t` (exactly 16 bits) and  `int_least16_t` (at least 16 bits), and `int16_t` may not exist on all platforms.

**Comment by HansOlsson** [comment]
It seems that platforms without `int16_t` are mostly embedded targets - i.e. something that we should consider for FMI, and it seems `int_least16_t` should work the same (since signed integer overflow is undefined). 

Using `uint_least16_t` instead of `uint16_t` seems possible, but requires a bit of otherwise redundant masking. 

As far as I understand if both `int16_t` and `int_least16_t` exist they are the same.

**Comment by TorstenBlochwitz** [comment]
Second poll on float32:
1. do not introduce float32 at all (3)
1. introduce float32 as discrete variable type only (0)
1. introduce float32 as continuous variable type and have special float32 functions for DirectionalDerviatives etc. (0)
1. introduce float32 as continuous variable type and always use float64 functions for DirectionalDerviatives etc. (9)

**Comment by t-sommer** [comment]
@pmai, @andreas-junghanns can we close this in favor of #481?

**Comment by andreas-junghanns** [comment]
In general it is better to have fewer, more powerful tickets to give casual visitors a chance to see through the forest of tickets. Without knowing the details: Yes, please merge these issues.
