### ISSUE TITLE
Wrong call sequence for fmi2SetTime in ME pseudo code example

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#296]
**Reported by ottot on 18 Sep 2014 12:26 UTC**
In the pseudo code example for model exchange fmi2SetTime is called directly after fmi2Instantiate. At that stage the fmu must be in the state instantiated. However, according to the table fmi2SetTime can only be called in the states Event Mode/Continuous-Time Mode .

----

Migrated-From: https://trac.fmi-standard.org/ticket/296

**Comment by modelica-trac-importer** [comment]
**Comment by adrian&#46;tirea on 1 Oct 2014 07:52 UTC**
This ticket is duplicated. See #294.

Also the fmuChecker 2.0 do call fmi2SetTime in the early state. This needs fixed as well.

**Comment by modelica-trac-importer** [comment]
**Modified by otter on 6 Nov 2014 08:24 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by aviel on 13 Feb 2017 09:01 UTC**
Changed to minor priority since only a fix in the pseudo-code seems necessary to have consistency.

**Comment by chrbertsch** [comment]
Isn't there als an `M_fmi2EnterEventMode(m)` missing in the pseudo code example for ME at the beginning of the first 
`
// event iteration 
`
?
So I would think it should look like this

```

// set the start time
Tnext = Tend
time  = Tstart

// set all variable start values (of "ScalarVariable / <type> / start") and
// set the input values at time = Tstart
M_fmi2SetReal/Integer/Boolean/String(m, ...)

// initialize
   // determine continuous and discrete states
   M_fmi2SetupExperiment(m,fmi2False,0.0, Tstart, fmi2True,Tend)
   M_fmi2EnterInitializationMode(m)
   M_fmi2ExitInitializationMode(m)

   // event iteration
   M_fmi2EnterEventMode(m)
   M_fmi2SetTime(m, time)
   eventInfo.newDiscreteStatesNeeded = true;
   while eventInfo.newDiscreteStatesNeeded loop
     // update discrete states
     M_fmi2NewDiscreteStates(m, &eventInfo)
     if eventInfo.terminateSimulation then goto TERMINATE_MODEL
   end while

// enter Continuous-Time Mode
M_fmi2EnterContinuousTimeMode(m)

...
```

**Comment by otronarp** [comment]
There is an implicit transition to event mode when you call exitInitializationMode. 

>  When the Initialization Mode is terminated with fmi2ExitInitializationMode, then Event Mode is directly entered, and the continuous-time and discrete-time variables at the initial time are computed based on the initial continuous-time states determined in the Initialization Mode

However, I guess it doesn't hurt for the example to be explicit about it and call the function. Or we could add a comment line that clarifies that there is an implicit transition.

**Comment by jbernalr** [comment]
Its also the only remaining API that does not tell "where it is going" but that "it is leaving". For the fcp007 we made sure all calls are like the former.

**Comment by otronarp** [comment]
> Its also the only remaining API that does not tell "where it is going" but that "it is leaving". For the fcp007 we made sure all calls are like the former.

Interesting point, should we remove it for 3.0 and replace it with a mandatory call to enterEventMode?

**Comment by chrbertsch** [comment]
Webmeeting: there are still errors in the pseudocode. @KarlWernersson  will fix all the pseudo-code tickets: 
#308, #333 .

**Comment by KarlWernersson** [comment]
@jbernalr @otronarp One major difference for exitInitializationMode is that once you leave you cannot go back (unless you reset with fmiReset). For the other modes you might return to an arbitrary amount of times. Having the exit function makes this more explicit. It could be quite different internal behavior for an FMU to finish initialization compared to enter event mode which would make it nicer for the importer to separate these functions.
However this is not the ticket to handle this question and if you want to pursue this, please open another ticket for changing the name of exitInitializationMode

**Comment by KarlWernersson** [comment]
Fixed in pullrequest
