### ISSUE TITLE
Inconsistent definitions of when fmi2GetDerivatives and fmi2GetNominalsOfContinuousStates may be called

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#301]
**Reported by henrikt on 14 Nov 2014 14:08 UTC**
Inconsistency in the FMI 2.0 specification (July 25, 2014):

  In _Figure 6: Calling sequence of Model Exchange C functions in form of an UML 2.0 state machine_, page 83, it looks as if `fmi2GetDerivatives` may not be called in the _initialization mode_ (although there is the confusion part saying _continuous-time states and state derivatives_).

versus

  In the table on page 85, there's an _x_ for `fmi2GetDerivatives` in the _Initialization Mode_ column.

As a side note, the QTronic FMUs follow the figure, not allowing `fmi2GetDerivatives` to be called in the _Initialization Mode_.

----

Migrated-From: https://trac.fmi-standard.org/ticket/301

**Comment by modelica-trac-importer** [comment]
**Modified by torstenblochwitz on 5 Feb 2015 10:44 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by henrikt on 25 Jun 2015 06:27 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by henrikt on 25 Jun 2015 06:35 UTC**
I don't seem to have permission to edit the description, but my intention was to also include this inconsistency in the ticket:
   In _Figure 6: Calling sequence of Model Exchange C functions in form of an UML 2.0 state machine_, page 83, it looks as if `fmi2GetNominalsOfContinuousStates` may be called in the initialization mode, since it is listed under the abbreviation _F_.
versus
   In the table on page 85, there's no x for `fmi2GetNominalsOfContinuousStates` in the _Initialization Mode_ column.

As a side note, the QTronic FMUs follow the table this time, not allowing `fmi2GetNominalsOfContinuousStates` to be called in the _Initialization Mode_.

**Comment by modelica-trac-importer** [comment]
**Comment by karl&#x2e;wernersson on 21 Jul 2015 11:55 UTC**
Hi

This issue is also applies to fmi2GetEventIndicators.

I do believe that the proper way is to allow fmi2GetDerivatives in initialization mode since, just as fmi2GetContinousStates, variables with start=fix are supposed to be set and start=approx or calculated are supposed to be retrieve there is no harm in allowing all to be retrieved with fmi2GetDerivatives and fmi2GetContinouosStates

However I see no reason why one would call fmi2GetEventIndicators during initialization mode it would be correct to remove it's support of initialization mode from page 85


/Karl Wernersson

**Comment by modelica-trac-importer** [comment]
**Comment by maplesoft on 4 Nov 2016 14:43 UTC**
Some tools may require the knowledge of the initial state of event indicators to fully initialize the system containing the FMU.

For example, in MapleSim, each event indicator is mapped to a discrete variable that indicates its current state. For example, if the initial value of a trigger was trig[1]=1.0, then we would also have trig_pos[1]=true.

If the ability to call fmi2GetEventIndicators was removed from init mode, then only part of the overall system could be initialized, and the initialization of the trigger indicators would have to be implemented in an ad-hoc manner, making the master implementation unnecessarily more complex.

In any event, I do not see the harm in allowing a call to fmi2GetEventIndicators from initialization mode. The FMU should have sufficient knowledge of it's internal data so that this computation can be performed, no?

**Comment by modelica-trac-importer** [comment]
**Modified by aviel on 27 Nov 2017 16:44 UTC**

**Comment by KarlWernersson** [comment]
Proposal:
update state chart to allow fmi2GetDerivatives in initializationMode
for fmi2GetEventIndicators, see #395

**Comment by chrbertsch** [comment]
(Urgent for release of FMI 2.0.1)

Is this fine
![image](https://user-images.githubusercontent.com/16363372/65393414-92cd6f00-dd80-11e9-965d-2d1cc4e10d0c.png)

with the uptated non-normative text
_[Bugfixes in FMI 2.0.1: Note that there was an inconsistency in FMI 2.0 in the state graph and the table regarding if fmi2GetEventIndicators is allowed to be called in initializationMode. The table (see further down) is correct and fmi2GetEventIndicators can be called in initializationMode.
Additionally the state grapyh has been updated so that now fmi2GetDerivatives may by called in initializationMode.]._


Please comment, if ok, or if something has to be changed. Thanks!

**Comment by andreas-junghanns** [comment]
Agreed

**Comment by chrbertsch** [comment]
Closing as agreed by Andreas.
