### ISSUE TITLE
Time unit and absolute time reference (sync between multiple FMUs)

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#307]
**Reported by andreas&#46;nicolai on 5 Dec 2014 09:35 UTC**
An FMU should publish its expectations on the time variable that it receives via fmi2SetTime().

# Problem Statement : Time Unit

When encapsulating a model inside an FMU the developer can select an interpretation of the time quantity. It is not standardized in the FMI document (most people will assume seconds).

When two FMU are controlled by a master and the FMUs choose different time quantities/units, e.g. FMU1 selects seconds "s" and FMU2 operates on days "d", the master must handle unit conversion before setting new time points in each FMU.

The master must thus know the time quantity definition in each FMU. This definition is not yet exported.

## Workaround
Currently, the time unit definition in each FMU must be passed alongside the FMU in the master specification document.

# Problem Statement : Null-Time Reference to Absolute Time
When dealing with measured data (climatic data, measurement logs) in different FMUS, the communicated time (simulation time) must be aligned with absolute time, thus the simulation time 0 must be assigned an absolute time point.

Example:
Simulation shall cover summer months for a HVAC equipment sizing application, simulation time: start=0, end=7776000  (that is 90 days).

FMU1 models the solar panel equipment and requires solar altitude/elevation/azimuth for each day. Thus, the FMU1 needs to be told that simulation time 0 corresponds to, for example, May 1st, midnight (UTC, when solar model works with UTC time).

FMU2 models the building, and requires ambient temperatures. In order to retrieve the correct climatic data, it also needs to be told that simulation time 0 corresponds to said May 1st, midnight (but local summer time, since climatic data was recorded using that time).

## Workaround
Currently all FMUs have to be implemented according to the same absolute time reference which developers have to agree upon.

**But**: This makes reusability of FMUs in different scenarios quite difficult, since it cannot be expected that all FMU developers will agree on the same time reference. Alternatively, the absolute time reference has to be a configuration property of each FMU, potentially increasing the effort for FMU developers.

# Suggestion for short-term solution

Clarify in standard (demonstration documents), that the time value provided by master to the FMUs is the same to all FMUs and is defined in the master configuration file. The unit and absolute time offset has to be configured in each FMU to match that common definition. Potential unit conversions have to be handled inside the FMU.

The time unit used by the FMUs and master **should not be fixed** to, for example "s", since environmental prediction models may operate on 10000 years and expressing these values in seconds may cause rounding problems in integrators (due to restrictions on datatype double).

# Proposal for an extension to the standard
Allow FMUs to report their expectations on time unit to the master, so that the master can do a minimum of error checking. This can be done by requiring a Time variable definition in addition to all other scalar variables in the xml specs.

Similarly, the time offset (absolute time reference) may be exported for consistency checking. In the simplest way, this could be the NullTime reference in some standardized time format.

----

Migrated-From: https://trac.fmi-standard.org/ticket/307

**Comment by modelica-trac-importer** [comment]
**Comment by rfranke on 20 Dec 2014 07:40 UTC**
The double data type is not as bad as you think. A 64-bit double according to IEEE 754 can represent `+-2^53` exact integers. This means that it can represent 285 million years in seconds without loss of accuracy. 10000 years can be represented in milliseconds, though not in microseconds anymore.

Double has well known accuracy problems with places after the decimal point. This is why I find it a great idea to declare the time type in the modelDescription.xml file, allowing units like millisecond, microsecond or picosecond, which then can be communicated to the FMU as exact integers using the existing fmi2Real time. Only fractions of the defined time unit would be inaccurate with fmi2Real.

Regarding the reference time point: we adopted the Posix standard using the convention once introduced by Unix and nowadays adopted by many (if not most) systems, including also Java and JavaScript: our null reference is 1970-01-01T00:00:00Z (UTC time formatted according to ISO 8601).

This could at least serve as default null reference, but possibly be redefined in the modelDescription.xml file.

**Comment by modelica-trac-importer** [comment]
**Modified by andreas&#46;junghanns on 6 Feb 2017 10:38 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by aviel on 13 Feb 2017 18:10 UTC**
As far as I understand it, it seems that the variable with _independent_ causality allows to define the unit of the time variable. If such a variable is missing, there is a rule that defines the second as the default unit (section 2.2.7, p. 46). So an FMU can explicitly define the unit for the time. No workaround is needed for the 2.0.1 maintenance release. At most, a proposal for a new definition of the time unit could be formulated in a future release.

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 1 Jun 2018 13:30 UTC**
It is possible to have different time units in different FMUs, but it is not that obvious. Perhaps an implementation hint is sufficient.

**Comment by modelica-trac-importer** [comment]
**Comment by Andreas Nicolai on 1 Jun 2018 15:32 UTC**
Do master simulators exist that can handle this situation? Not to my knowledge... and even with SSP supporting implementations, it seems that the underlying assumption is: "everyone the same time unit and reference".

**Comment by modelica-trac-importer** [comment]
**Comment by andreas&#46;junghanns on 1 Jun 2018 17:50 UTC**
Replying to [comment:5 Andreas Nicolai <andreas.nicolai@…>]:
> Do master simulators exist that can handle this situation? Not to my knowledge... and even with SSP supporting implementations, it seems that the underlying assumption is: "everyone the same time unit and reference".

This is a quality of implementation issue for masters. Not the standard - except that we should make Antoine's observation more explicit in the standard document: without unit definition time is in seconds.

However, I think another note is needed: If time is not 0-based, it is relative to 1970-01-01T00:00:00Z (UTC time formatted according to ISO 8601).

**Comment by modelica-trac-importer** [comment]
**Comment by Andreas Nicolai on 1 Jun 2018 21:34 UTC**
Replying to [comment:6 Andreas Junghanns (QTronic)]:
> ... we should make Antoine's observation more explicit in the standard document: without unit definition time is in seconds.

Such a statement would work for me.

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 11 Jun 2018 10:12 UTC**
(FCP Alignment Meeting)
Clarifying sentences to be added in FMI 2.0.1; bigger changes to be added in separat ticket if needed.

**Comment by modelica-trac-importer** [comment]
**Comment by pierre&#46;mai on 11 Jun 2018 14:27 UTC**
As discussed at todays FCP Alignment meeting, the status quo already supports the alignment of different time units across FMUs:

Each FMU has the ability to specify its time unit as the independent variable as stated on page 46 FMI 2.0:

> "independent": The independent variable (usually “time”). All variables are a function of this independent variable. variability must be "continuous". At most one ScalarVariable of an FMU can be defined as "independent". If no variable is defined as "independent", it is implicitely present with name = "time" and unit = "s".

So the (relative) time units of all FMUs are already well-defined, and can be defined as needed for FMUs needing a different time unit (e.g. years, aeons, as long as they can be mapped to SI units).

Specification of absolute time bases is a different proposition, since the choice of proper time-bases depends very much on the application domain: Where astronomical simulations might want to use some TAI-based time base, navigational simulations might want GPS-based time bases, other UTC-based time bases, etc. And that's ignoring larger scale time-bases and other issues.

Therefore this should be dealt with through domain-specific layered agreements, e.g. by defining a domain-specific standard of how FMUs should expose a configurable offset parameter so that multiple FMUs can be automatically aligned by a knowledgeable master.

As such this issue is either solved already (time units) or should be dealt with in layered standards or a later FMI version, but is currently out of scope for FMI 3.0.

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 18 Jun 2018 08:33 UTC**
The standard is quite clear but perhaps it is hard to find (perhaps add a link at fmi2doStep and fmi2SetTime description); could be part of an implementers guide.

**Comment by chrbertsch** [comment]
Can we close this? Regarding the unit of time the standard is clear.
Otherwise please create a concrete proposal in a pull request.

**Comment by andreas-junghanns** [comment]
This was imported from the Modelica trac - I doubt your question will get a response and I agree with your statement, closing.
