### ISSUE TITLE
Fix Pseudocode Example

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#308]
**Reported by rfranke on 8 Dec 2014 07:44 UTC**
The pseudocode example for model exchange given in section 2.3.4 of the specification document doesn't check for time events at model initialization. It is proposed to use the following modified pseudocode instead, which
•	fixes the treatment of time events after initialization
•	moves all event processing to one place in the simulation loop – according to the calling sequence in Figure 6,
•	removes the call to fmi2SetTime during initialization (see also #296 and #294),
•	defines the initialization of event indicators with zeros,
•	removes undefined eps from detection of time events – there finds other places that also do comparisons without eps, like “while time < Tend loop”,
•	unifies capitalization

I prepared a Word document with change marks, FunctionalMockupInterface_v2.0.1-MaplesoftEdits-Pseudocode.docx, that could be added to the SVN or requested by e-mail.

Two questions arise:
1. Is the initialization of event indicators with zeros correct?
2. Does the retrieval of states have to check for initialEventMode or would the FMU set `eventInfo.valuesOfContinuousStatesChanged` and `eventInfo.nominalsOfContinuousStatesChanged` anyway during initialization?

```
m = M_fmi2Instantiate("m", ...)  // "m" is the instance name
                                // "M_" is the MODEL_IDENTIFIER
nx     = ...   // number of states, from XML file
nz     = ...   // number of event indicators, from XML file
tStart = 0     // could also be retrieved from XML file
tEnd   = 10    // could also be retrieved from XML file
dt     = 0.01  // fixed step size of 10 milli-seconds

// set the start time
time  = tStart

// set all variable start values (of "ScalarVariable / <type> / start") and
// set the input values at time = tStart
M_fmi2SetReal/Integer/Boolean/String(m, ...)

// initialize
M_fmi2SetupExperiment(m,fmi2False,0.0, Tstart, fmi2True,Tend)
M_fmi2EnterInitializationMode(m)
M_fmi2ExitInitializationMode(m)

initialEventMode = fmi2True
enterEventMode = fmi2False
timeEvent = fmi2False
stateEvent = fmi2False
previous_z = zeros(nz)

do
  // handle events
  if initialEventMode or enterEventMode or timeEvent or stateEvent then
    if not initialEventMode then
      M_fmi2EnterEventMode(m)
    end if

    // event iteration
    eventInfo.newDiscreteStatesNeeded = fmi2True;
    while eventInfo.newDiscreteStatesNeeded loop
      // update discrete states
      M_fmi2NewDiscreteStates(m, &eventInfo)
      if eventInfo.terminateSimulation then goto TERMINATE_MODEL
    end while

    // enter Continuous-Time Mode
    M_fmi2EnterContinuousTimeMode(m)

    // retrieve solution at simulation (re)start
    M_fmi2GetReal/Integer/Boolean/String(m, ...)
    if initialEventMode or eventInfo.valuesOfContinuousStatesChanged then
      //the model signals a value change of states, retrieve them
      M_fmi2GetContinuousStates(m, x, nx)
    end if

    if initialEventMode or eventInfo.nominalsOfContinuousStatesChanged then
      //the meaning of states has changed; retrieve new nominal values
      M_fmi2GetNominalsOfContinuousStates(m, x_nominal, nx)
    end if

    if eventInfo.nextEventTimeDefined then
       tNext = min(eventInfo.nextEventTime, tEnd)
    else
       tNext = tEnd
    end if

    initialEventMode = fmi2False
  end if

  if time >= tEnd then
    goto TERMINATE_MODEL
  end if

  // compute derivatives
  M_fmi2GetDerivatives(m, der_x, nx)

  // advance time
  h    = min(dt, tNext-time)
  time = time + h
  M_fmi2SetTime(m, time)

  // set inputs at t = time
  M_fmi2SetReal/Integer/Boolean/String(m, ...)

  // set states at t = time and perform one step
  x = x + h*der_x  // forward Euler method
  M_fmi2SetContinuousStates(m, x, nx)

  // get event indicators at t = time
  M_fmi2GetEventIndicators(m, z, nz)

  // detect  events, if any
  timeEvent = time >= tNext
  stateEvent = sign(z) <> sign(previous_z)
  previous_z = z

  // inform the model about an accepted step
  M_fmi2CompletedIntegratorStep(m, fmi2True, &enterEventMode,
                                             &terminateSimulation)
until terminateSimulation

// terminate simulation and retrieve final values
TERMINATE_MODEL:
M_fmi2Terminate(m)
M_fmi2GetReal/Integer/Boolean/String(m, ...)

// cleanup
M_fmi2FreeInstance(m)
```

----

Migrated-From: https://trac.fmi-standard.org/ticket/308

**Comment by modelica-trac-importer** [comment]
**Comment by karl&#x2e;wernersson on 10 Apr 2015 12:50 UTC**
Hi nice cleanup

There is however still some issues with this code that needs to be fixed.

First of, discrete input is only allowed to be set in event mode so they need to be moved to that section.

Also to get  a right behavior when coupling multiple fmu's during events, I/O need to be updated between every call to newDiscreteStates, (see FMITest.PropagateEvents.PropagateReinit or FMITest.VirtualLoops.SRFlipFlop for good examples that will have problems if this is not done)

In addition eventInfo.valuesOfContinuousStatesChanged can change at any call to newDiscreteStates its value needs to be checked not only at the last call but during anny call

For that case I would propose to change the event loop to


```
eventInfo.newDiscreteStatesNeeded = fmi2True;
M_valuesOfContinuousStatesChanged = fmi2False;
while eventInfo.newDiscreteStatesNeeded loop
   //set inputs at super dense time point
   M_fmi2SetReal/Integer/Boolean/String(m, ...)
   // update discrete states
   M_fmi2NewDiscreteStates(m, &eventInfo)
   //getOutput at super dsne time point
   M_fmi2GetReal/Integer/Boolean/String(m, ...)
   M_valuesOfContinuousStatesChanged =
   M_valuesOfContinuousStatesChanged OR eventInfo.valuesOfContinuousStatesChanged;
   if eventInfo.terminateSimulation then goto TERMINATE_MODEL
end while
```


Later on it should be


```
if initialEventMode or M_valuesOfContinuousStatesChanged then
  //the model signals a value change of states, retrieve them
  M_fmi2GetContinuousStates(m, x, nx)
  end if
end if
```


and removal of the non continuous set input calls at continuous time mode
```
// set continuous time inputs at t = time
  M_fmi2SetReal(m,...)
```

Best Regards
Karl Wernersson

**Comment by modelica-trac-importer** [comment]
**Comment by aviel on 13 Feb 2017 14:20 UTC**
This ticket seems to be related to ticket #333. By the way, it is not clear if the Pseudo Code Example is meant to be exhaustive with respect to all possible cases implied by the specification. If this is the case, this ticket is actually filed with _major_ priority, and the Pseudo Code Example should also take into account the pure discrete time variant of FMI. If it is not the case, it should be filed with _minor_ priority and the only requirement for a 2.0.1 maintenance release is to fix what is wrong in the example with respect to the specification (like the call to `fmi2SetTime` after the instantiation, as it is already reported by ticket #296), and nothing more.

**Comment by KarlWernersson** [comment]
parialy duplicate #333

**Comment by KarlWernersson** [comment]
Fixed in pullrequest
