### ISSUE TITLE
fmi2GetDirectionalDerivative: Inconsistency in specification and pseudocode example

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#311]
**Reported by Christian&#x2e;Bertsch on 9 Dec 2014 20:02 UTC**
There is an inconsistency in one of the FMI 2.0 interface function “fmi2GetDirectionalDerivative()” arguments. As per the documentation (Pg: 25)  the prototype of this function is defined as given below,

  fmi2Status fmi2GetDirectionalDerivative(fmi2Component c,const fmi2ValueReference vUnknown_ref[], size_t nUnknown,const fmi2ValueReference vKnown_ref[]  , size_t nKnown,const fmi2Real **dvKnown[]**,fmi2Real dvUnknown[])

However on Pg: 27, an pseudo code for same function is mentioned as example and that goes like below,

M_fmi2GetDirectionalDerivative(m, x_ref[i], 1, xd_ref, nx, **1.0**, ci);

This means there is a inconsistency in data type of the argument “dvKnown”, i.e in prototype it is defined as vector and in the pseudo code it is a hard coded value…

Is there a reason for this or its simply a documentation error?

----

Migrated-From: https://trac.fmi-standard.org/ticket/311

**Comment by KarlWernersson** [comment]
The pseudo code leaves a lot out and is not valid c, so I would prefer to leave it as is for 2.0.1
However, it’s an easy fix if deemed necessary
Proposal: don’t fix

**Comment by KarlWernersson** [comment]
Fixed
