### ISSUE TITLE
Efficient mechanism for FMU specific output writing in ModelExchange

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#326]
**Reported by Andreas Nicolai on 26 Feb 2015 09:04 UTC**
Currently it is unclear how to handle FMU-specific outputs efficiently in a ModelExchange scenario. For example, in a building simulation FMU at certain time points (usually hourly, or every 15 minutes) a lot of output data shall be generated by the FMU and stored in output files (passing that amount of output data through the variable-getter functions of the FMI is not feasible).

The integrator of the FMU ModelExchange master may use a higher-order integration method with variable time stepping (e.g. CVODE or similar). That means that integration steps and output steps in the FMU generally do not match.

## Efficient method proposal
In this case the most efficient way to implement outputs would be:

* after a completed integrator step:
* process all output time points scheduled within the last integration step interval
* interpolate backwards the states and inputs of the FMU that wants to write outputs (possibly using higher-order interpolation)
* update the state of the model FMU to these interpolated values via setTime, setContinuousStates, and setXXX (input parameters)
* signal FMU to write outputs

There should be a rule that says that the calls to write outputs shall only be done with monotonically increasing time point states.

## Workaround with current standard functionality
The current FMI standard does not include functions:
* to signal the FMU to write outputs
* to tell the master about desired output time points

The FMU can cause the master to interrupt integration at desired points by signaling discrete events, however, this would usually lead to a restart of integration after the event and impact performance significantly (e.g. higher-order integrators restart with method order 1 again). To prevent that restart-overhead, the master must implement sophisticated state checking and essentially compare states and derivatives before and after such events and decide upon a restart based on differences or no-differences.

## Proposed Solution

Incorporate functions to output writing in future versions of the FMI for ModelExchange standard:
1. fmi tells a list of output time points to master
2. master gets a notification call to FMU to signal that it had just received the state for a requested output

----

Migrated-From: https://trac.fmi-standard.org/ticket/326

**Comment by modelica-trac-importer** [comment]
**Modified by andreas&#46;junghanns on 6 Feb 2017 10:40 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by aviel on 13 Feb 2017 17:12 UTC**
Changed the milestone to 2.1, since it seems to be a request for a new feature.

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 1 Jun 2018 13:50 UTC**
A workaround would be to define a parameter defining output sample time.
From a user point of view it is related to the IOV FCP (for CS FMUs).
Could be a small change.

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 11 Jun 2018 10:15 UTC**
(FMI Alignment meeting)
To be discussed in IOV Working Group

**Comment by modelica-trac-importer** [comment]
**Modified by cbertsch on 11 Jun 2018 10:16 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by cbertsch on 18 Jun 2018 10:15 UTC**

**Comment by KarlWernersson** [comment]
As i understand the ticket this is about when the FMU write directly to file an not about using the api.
This is curently not somehting that is handled by the fmi standard.

The model exchange interface allow a master to interpolate the output the same way as a normal solver.
If one want the fmu does this internaly and dump it to a file this is a quit large change and should be included with a general proposal for writing to a file directly form the fmu.

As long as we dont implement a general  file utility for fmi i think this has to be tool specific and more a quality of implementation of respective tool.

I propose to close this ticket
