### ISSUE TITLE
Description of fmi2GetContinuousStates is out of date

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#334]
**Reported by karl&#x2e;wernersson on 10 Apr 2015 13:05 UTC**
Hi

in the description of the function  fmi2GetContinuousStates is not entierly correct.

**fmi2Status fmi2GetContinuousStates(fmi2Component c, fmi2Real x[], size_t nx);**
_Return the new (continuous) state vector x. This function has to be called directly after calling
function fmi2EnterContinuousTimeMode if it returns with eventInfo->
valuesOfContinuousStatesChanged = fmi2True (indicating that the (continuous-time)
state vector has changed)._

First of the attribute reinit in scalarVariables specifics exactly which states that needs to be reinitialized. This makes calling this function unnecessary and only a call to GetReal on the specific states is needed.

Also I do not see the requirement to call it directly after calling fmi2EnterContinuousTimeMode, it is fully legal to call this during event mode so the only requirement is to update the required states no later then directly after a cll to fmi2EnterContinousTimeMode.The update can be done either whit this function or by calling fmi2GetReal on the states specified with reinit attributes.

Best Regards
Karl Wernersson

----

Migrated-From: https://trac.fmi-standard.org/ticket/334

**Comment by modelica-trac-importer** [comment]
**Comment by aviel on 25 Oct 2016 12:06 UTC**
Moreover, the fmi2EnterContinuousTimeMode function does not return an eventInfo structure. The calling condition for fmi2GetContinuousStates should be completely redefined.

**Comment by modelica-trac-importer** [comment]
**Modified by aviel on 27 Nov 2017 16:55 UTC**

**Comment by KarlWernersson** [comment]
Proposed change

_Return the new (continuous) state vector x. 
After calling function fmi2NewDiscreteStates and it returns with eventInfo>valuesOfContinuousStatesChanged = fmi2True all states with reinit=true must be updated. It can be done with this fuction to update all states, or by fmi2GetReal on the individual states that has reinit = true._

**Comment by KarlWernersson** [comment]
desicion
accept proposal
