### ISSUE TITLE
inconsistency between description and state machine

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#338]
**Reported by andreas&#x2e;junghanns on 28 May 2015 08:45 UTC**
Ticket created on behalf of Kenneth Lausdahl (lausdahl@eng.au.dk).
Department of Engineering, Finlandsgade 22, 8200  Aarhus N, Denmark

```
fmi2Status fmi2EnterInitializationMode(fmi2Component c);
Informs the FMU to enter Initialization Mode. Before calling this function, all variables with
attribute <ScalarVariable initial = "exact" or "approx"> can be set with the
“fmi2SetXXX” functions (the ScalarVariable attributes are defined in the Model
Description File, see section 2.2.7). Setting other variables is not allowed. Furthermore,
fmi2SetupExperiment must be called at least once before calling
fmi2EnterInitializationMode, in order that startTime is defined.
```

The state machine doesn’t reflect this, since it allows the following call sequence:

mi2Instantiate != null -> fmi2EnterInitializationMode -> fmi2ExitInitializationMode -> fmi2Terminate -> fmi2FreeInstance

note that setupExperiment is not called here, since it is optional. If it should require a call to setupExperiment at least once before enterInitializationMode then an additional state is required.

If the state machine should require that setupExperiment is called at least once before enterInitializaitonMode then it should have another state as illustrated below (state in [], <- is the functions on transitions):

[ instantiated ]  <-setINI, F
|
| <-fmi2SetupExperiment
|
[ setup ] <- fmi2SetupExperiment, setINI, F
|
| <-fmi2ExterinitializationMode
|
[ intialization mode] <- ...

The added state will require fmi2SetupExperiment to be called before enterInitializationMode but still allow it to be called multiple times as the current state machine allows. With this chance the above call sequence will change to:

fmi2Instantiate != null -> fmi2SetupExperiment -> fmi2EnterInitializationMode -> fmi2ExitInitializationMode -> fmi2Terminate -> fmi2FreeInstance

----

Migrated-From: https://trac.fmi-standard.org/ticket/338

**Comment by APillekeit** [comment]
For me it would be enough to change line 387 of 2_1_common_api.adoc:
from
This function can be called after `fmi3Instantiate` and before `fmi3EnterInitializationMode` is called.
to
This function must be called after `fmi3Instantiate` and before `fmi3EnterInitializationMode` is called.

Since line 412 requires this anyhow, as pointed out above in the issue.
A separate state is not required in my view.

**Comment by chrbertsch** [comment]
I agree with @APillekeit and have included this for further discussion in PR https://github.com/modelica/fmi-standard/pull/579
