### ISSUE TITLE
Datatype Restriction in XML Schema Files

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#342]
**Reported by mfriedrich on 7 Jul 2015 13:37 UTC**
The XML schema files defines the datatype of integers as xs:unsignedInt or xs:int which are defined as 32bit integers by XML schema.
However, the C-API explicitly defines no size for these (but it depends dynamically on fmi2TypesPlatform).
Since the XML schema file should be independent of fmi2TypesPlatform I propose the following change in all .xsd files:

xs:unsignedInt -> xs:nonNegativeInteger
xs:int -> xs:integer

xs:integer and xs:nonNegativeInteger are defined as integers of arbitrary size in XML schema.

----

Migrated-From: https://trac.fmi-standard.org/ticket/342

**Comment by KarlWernersson** [comment]
I would like to avoid updating the xsd for 2.0.1 as this would be problematic with forwards compatibility.
For FMI 3.0 this seems to be solved with #481 
@friedrichatgc  Can we close this one?

**Comment by KarlWernersson** [comment]
decision wontfix
