### ISSUE TITLE
Replace canInterpolateInputs with maxInputDerivativeOrder

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#345]
**Reported by Oliver Kotte on 3 Sep 2015 11:57 UTC**
While the maxOutputDerivativeOrder is known as an integer, the maximal derivative order up to which an FMU canInterpolateInputs is not. There is no way of knowing up to which order an FMU can make use of provided input derivatives.

Yes, the FMU may simply discard surplus derivatives. But a master algorithm that is capable of estimating derivatives based on past data points cannot determine the order up to which it should perform the estimation.

So I would suggest to replace the boolean canInterpolateInputs capability with the capability maxInputDerivativeOrder that expects an integer value.

----

Migrated-From: https://trac.fmi-standard.org/ticket/345

**Comment by modelica-trac-importer** [comment]
**Modified by andreas&#46;junghanns on 6 Feb 2017 10:40 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by aviel on 13 Feb 2017 16:14 UTC**
Changed the milestone to 2.1, since it seems to be a new feature, and not a clarification for the 2.0.1 maintenance release.

**Comment by modelica-trac-importer** [comment]
**Modified by cbertsch on 1 Jun 2018 13:53 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 11 Jun 2018 10:19 UTC**
(FCP Alignment Meeting)
Small helpful change in XML.

**Comment by modelica-trac-importer** [comment]
**Modified by cbertsch on 18 Jun 2018 09:23 UTC**

**Comment by chrbertsch** [comment]
superseded by #603 
Please comment there or reopen if you disagree.
