### ISSUE TITLE
Clarify BSD version in standard documents

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#347]
**Reported by andreas&#46;junghanns on 9 Sep 2015 19:43 UTC**
From veronica.arama@&hellip;:

>  I downloaded FMI 2.0 and I have an issue related to the license of some files. You mentioned in the provided pdf that the license is BSD 2 clause but still in the files itself you’ve listed BSD 3- clause. Which is the correct license BSd 2 clause or BSD 3 clause?
>
> Can you please clarify the issue?

----

Migrated-From: https://trac.fmi-standard.org/ticket/347

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 24 Nov 2016 07:28 UTC**
Duplicate of #351.
Clarification of BSD3 usage shall be part of FMI 2.0.1. 

BSD3 usage shall also be clarified by putting the correct link on https://www.fmi-standard.org/development (instead of link to BSD2)

**Comment by modelica-trac-importer** [comment]
**Modified by andreas&#46;junghanns on 6 Feb 2017 10:41 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 6 Sep 2017 06:59 UTC**

**Comment by beutlich** [comment]
Seems 44e7a9fbd2cab711e39051b73c0186da91ceff6c addresses this issue, but I could not figure out why there was not a decent pull request by @t-sommer.

**Comment by beutlich** [comment]
Note that README.adoc links to the [2-Clause BSD License](https://opensource.org/licenses/bsd-license.html).

**Comment by t-sommer** [comment]
This is already addressed in #462

**Comment by KarlWernersson** [comment]
@andreas-junghanns Can this one be closed?

**Comment by beutlich** [comment]
Just to summarize: In master branch, it is the 3-Clause BSD License in the README.adoc and the 3-Clause BSD License with the license extension (as discussed in #423) in the 3 header files. From my view, this clarifies the previous mix of 2-Clause BSD with 3 clauses. We still have #423 to clarify the unusual license extension.
