### ISSUE TITLE
Setting/getting FMU state must only be allowed after call to ExitInitializationMode

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#367]
**Reported by Andreas Nicolai on 21 Jan 2016 20:42 UTC**
The state-chart for CoSimulation FMUs (paragraph 4.2.4, page 103) currently lists the functions:

fmi2GetFMUState, fmi2SetFMUState, fmi2SerializeFMUstateSize, ... 

as functions of type F.

Inside the state chart functions F can be called at every stage. This is not meaningful for several reasons:

The actual purpose of setting/getting FMU states is to allow iterations and "redoing" some part of the simulation. For this functionality, it is not required that the state of the FMU may be restored while inside the initialization mode, i.e. while iterating over initial conditions. Also, restoring the state of the FMU to just after instantiation doesn't make sense, because then a formal fmi2Reset() call gives basically the same result. Also, setting the FMU-state when in "terminated" stage is probably never required. 

The FMUs internal memory layout/resource allocation may change significantly between calls to fmi2Instantiate() and fmi2EnterInitializationMode() and fmi2ExitInitializationMode(). Some FMUs may actually just initialize their internal solvers (and related linear equation system modules) when initialization is complete. That may prevent the FMU to report the required memory size in fmi2SerializedFMUstateSize() prior to a full solver initialization (which is in such a szenario guaranteed only **after** a call to fmi2ExitInitializationMode()). 

**Suggestion**: To clarify this, either:
a) change the state-machine image and introduce a new function abbreviation Z (for ztate :-) ) and restrict call location to the yellow box after fmi2ExitInitializationMode() and before terminated and error.
b) add a rule in the text that describes the setter/getter functions and clarify the stages where a call is allowed.

----

Migrated-From: https://trac.fmi-standard.org/ticket/367

**Comment by KarlWernersson** [comment]
This change may be good to do, I don't see it as an inconsistency or bug that needs to be clarified for 2.0.1
I propose to move this to 3.0

**Comment by KarlWernersson** [comment]
dessicion move to 3.0 since its cleraly defined in 2.0

**Comment by beutlich** [comment]
@ghorwin FYI

**Comment by chrbertsch** [comment]
The states where the FMU State may be set and get is clearly defined in FMI 3.0 in the super-state https://fmi-standard.org/docs/3.0-dev/#state-fmu-state-setable-co-simulation (this is possibly not as proposed above, but clearly defined as proposed in option b) in the ticket description above)

So I propose to close this. 
@ghorwin, @KarlWernersson and others : please comment

**Comment by andreas-junghanns** [comment]
Please reopen, if you think this still needs attention!
