### ISSUE TITLE
Improve ModelStructure description in FMI 2.0 specification

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#374]
**Reported by maplesoft on 14 Apr 2016 19:30 UTC**
Suggestion to improve ModelStructure description on page 30 of the FMI 2.0 specification document:

Change from:

"Especially, the ordered lists of outputs, continuous-time states and initial unknowns (the unknowns during Initialization Mode) are defined here."

To:

"Especially, the ordered lists of all outputs, continuous-time states and initial unknowns (the unknowns during Initialization Mode) must be defined here if any exist. For more details on ModelStructure, see Section 2.2.8 on pages 55-59."

----

Migrated-From: https://trac.fmi-standard.org/ticket/374

**Comment by modelica-trac-importer** [comment]
**Modified by andreas&#x2e;junghanns on 6 Feb 2017 10:48 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by aviel on 13 Feb 2017 17:19 UTC**
Changed the priority to _minor_ since it seems to require only a small clarification in the current specification.

**Comment by chrbertsch** [comment]
Closing as included in merged PR #579
