### ISSUE TITLE
Check validity of variable names in _ref.csv in cross check commit script

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#377]
**Reported by karl&#x2e;wernersson on 2 Jun 2016 14:45 UTC**
It is quite annoying when your scripted validation of fmu signals cannot be done because the variable names in the reference is not the same as in the xml file.

I usually try to contact the uploaded when i encounter this but new mistakes are uploaded from time to time.

Would it be easy to do a validity check on the names in _ref.csv file?
Perhaps make sure that they exist in the names of the _cc.csv file if its to hard to check against the xml directly?

/Karl Wernersson

----

Migrated-From: https://trac.fmi-standard.org/ticket/377

**Comment by modelica-trac-importer** [comment]
**Comment by mfriedrich on 2 Jun 2016 15:08 UTC**
Since issue #332 is implemented it should be easy to check the names in the _ref.csv file against the modelDescription.xml file because XML reading capability is already added to the script since than.
I will extent the commit hook script by this check.

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 1 Jun 2018 19:27 UTC**
Closing as the old XC tooling is no longer maintained.
Please craete a ticket at https://github.com/modelica/fmi-crosscheck-tools/issues if the problem persists with the new infrastructure.

**Comment by t-sommer** [comment]
This is implement in https://github.com/modelica/fmi-cross-check.
