### ISSUE TITLE
check in pre_commit-hook that tools.info files have no space

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#381]
**Reported by andreas&#x2e;junghanns on 24 Jun 2016 09:35 UTC**
It looks like I can still commit them.
It would be nice if the tool reminds us not to commit (pun intended) such a mistake.

----

Migrated-From: https://trac.fmi-standard.org/ticket/381

**Comment by modelica-trac-importer** [comment]
**Modified by andreas&#46;junghanns on 6 Feb 2017 10:57 UTC**

**Comment by t-sommer** [comment]
@andreas-junghanns can we close this issue?

**Comment by andreas-junghanns** [comment]
sure.
In general: close what you think can be closed, if someone disagrees, they can always reopen.
