### ISSUE TITLE
Relax restriction on fixed/tunable output

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#383]
**Reported by karl&#46;wernersson on 4 Jul 2016 12:02 UTC**
Hi 
Currently ScalarVariables with causality Output cannot have variability fixed or tunable with the current motivation

_A fixed or tunable “output” has exactly the same properties as a fixed or tunable
calculatedParameter. For simplicity, only fixed and tunable calculatedParameters shall be
defined._

Although it is true that the properties are the same, it doesn't account for keeping model structure between the original model and the compiled FMU. 

I assume that a normal user expects that all outputs defined in a model will be included as output in the FMU and not transformed to calculatedParameters.

This now forces a tool vendor who don't want to transform fixed output to calcualtedParameters, to remove the fixed attribute of the output.

So with the current rule I believe we end up having a lost the fixed/tunable information on those outputs, without much gained.

Karl Wernersson

----

Migrated-From: https://trac.fmi-standard.org/ticket/383

**Comment by modelica-trac-importer** [comment]
**Modified by karl&#x2e;wernersson on 5 Jul 2016 11:25 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 1 Jun 2018 15:10 UTC**
To be discussed as a minor change for FMI 3.0.

**Comment by modelica-trac-importer** [comment]
**Comment by karl&#x2e;wernersson on 26 Jun 2018 15:59 UTC**
Fix for 3.0
Fixed and tunable outputs would be defined in both InitialUnknowns and Outputs of ModelStructure but they would have zero dependencies in Outputs as they have no dependencies during continuous time.

**Comment by chrbertsch** [comment]
> Although it is true that the properties are the same, it doesn't account for keeping model structure between the original model and the compiled FMU.

I think with the re-definition of the meaning of alias  #807 we decided to not follow this goal anyway.

So I propose to close this issue. 
@KarlWernersson  and others: please comment.

**Comment by andreas-junghanns** [comment]
Please reopen, if you think this still needs attention!
