### ISSUE TITLE
Build 2.0.1 specification documents

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#384]
**Reported by andreas&#x2e;junghanns on 2 Aug 2016 13:03 UTC**
This is an errata document we need for 2.0.

----

Migrated-From: https://trac.fmi-standard.org/ticket/384

**Comment by modelica-trac-importer** [comment]
**Modified by andreas&#x2e;junghanns on 2 Aug 2016 13:05 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by andreas&#46;junghanns on 17 Jul 2017 15:53 UTC**
We need to check all clarifications and changes we made in 1.0.1 (#370) for 2.0.1 as well (e.g. clarify multiple occurrences to the same valeuRerence in a reference vector).

**Comment by modelica-trac-importer** [comment]
**Comment by aviel on 27 Nov 2017 16:56 UTC**

|=ticket=|=variant effected=|=description=|=severity, 1-low, 3-high=|=suggested fix=|=compatibility issues for the suggested fix=|=status=|
|-|-|-|-|-|-|-|
|#301|ME|Calling _fmi2GetXXX_ functions in Initialization Mode|2|Forbid _fmi2GetDerivatives_, _fmi2GetContinuousStates_ and allow _fmi2GetNominalsOfContinuousStates_|possible|included|
|#334|ME|Description of _fmi2GetContinousStates_ is out of date|1|Rewrite according to state machine|none|included|
|#391|ME|Aliased continuous-time state variables|3|extend the meaning of fmi2SetXXX to _fmi2GetContinuousStates_ to forbid such aliases|possible|included|
|#392|ME|Using _fmi2SetReal_ for changing the value of continuous-time state variables|1|only _fmi2SetContinuousStates_ allowed|possible|included|
|#394|ME|_fmi2SetTime_ in Event Mode|1|Remove the call from the table of allowed function calls|possible|partially included; needs fixing of math. model according to #409|
|#395|ME|_fmi2GetEventIndicators_ and Initialization mode|1|Forbid _fmi2GetEventIndicators_ in Initialization mode|none|included|
|#396|ME, CS|Clarify the definition of the number of continuous-time state variables|3|_derivative_ attribute uniquely defines the continuous-time state variables; the <ModelStructure>/<Derivatives> list defines the number of continuous-time  states|possible|
|#407|ME|Calling _fmi2SetContinuousStates_ in Event Mode|1|Forbid it|possible|included|
|#409|ME|Non-determinism regarding the pure discrete-time FMU variant|3|Clearly defines this variant as mandatory if the appropriate criteria are satisfied (no continuous-time states, no state events, ...)|high|_drafting in progress_|
|#411|ME, CS|Are all of the API functions mandatory?|2|Two alternatives to be discussed|high|tbd|

**Comment by chrbertsch** [comment]
In the table above, only #301 is still open

**Comment by KarlWernersson** [comment]
Updated word document can be found here
https://github.com/modelica/fmi-design/blob/master/FMI_2.0.1/FunctionalMockupInterface_v2.0.1-MaplesoftEdits%20%2B%20gihub%20fixes.docx

**Comment by t-sommer** [comment]
Thanks for merging the changes, @KarlWernersson!

Here my findings: 

p. 1: "OnThe downloads" should be "On the donwloads"
p. 2: Table "History Road Map": row for "2.0.1" should be added
p. 2: link to GitHub project should be added
p. 3: remove any extensions to BSD-2-clause license
p. 4: remove backticks from fmi2Functions.h (etc.) and use Word formatting
p. 4: "C-file" should be "C file"
p. 4: "define" should be either "#define" or "definition"
p. 41: replace backticks with Word formatting
p. 49: replace backticks with Word formatting
p. 53: "tunable >fixed" should be "tunable > fixed" (missing space)
p. 53: closing sqare bracket missing after non-normative text
p. 55: SSP Standard is referenced but not linked (add hyperlink?)
p. 67: "ordered arbitrary" should be either "ordered arbitrarily" or better "in arbitrary order"
p. 67: the second sentence of the "clarification" is just confusing (what does it mean?)
p. 68: "." missing before "Specifically" and excess "." after "not support"
p. 68: "zip" should be uppercase "ZIP"
p. 69 "it's" should be "it is".
p. 69 "... and run" (what?) -> object missing
p. 81: "Pure Discrete" should be lowercase
p. 81: "crossing functions" should be "event indicators"
p: 84: excess "." after "getReal"
p. 90: "Pure Discrete-Time FMU" should be lowercase
p. 100: figure is misaligned

**Comment by chrbertsch** [comment]
I updated the document with @t-sommer 's findings. (p4 must be p14) and uploaded the document, except for 

- p67: Can I delete the second sentence of the "clarification"
- New question: Must it not be "the scalarVariables of the xml **need not"" be ordered in depth first" instead of **must not**?

additional changes already performed:
-p69 indentation
-p68 " all items in that binary folder **are** recommended "
-p69 removed "and run"

**Comment by chrbertsch** [comment]
Changed p67: now using strikethrough and commenting that the original requirement has been relaxed (had discussed this with @t-sommer)

**Comment by t-sommer** [comment]
@chrbertsch, can we close this issue?
