### ISSUE TITLE
Only one child element within the Tool element of an fmi2Annotation possible

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#386]
**Reported by klausschuch on 7 Oct 2016 08:58 UTC**
The fmi2Annotations are unnecessarily restrictive about the number of elements within the "Tool" element.
The maxOccurs attribute is not specified explicitly and the default value is 1. It should be set to unbounded.

	
```
#!div style="font-size: 80%"
Code highlighting:
  ```xml
<xs:complexType name="fmi2Annotation">
  <xs:sequence maxOccurs="unbounded">
    <xs:element name="Tool">
      <xs:annotation>
        <xs:documentation>Tool specific annotation (ignored by other tools).</xs:documentation>
      </xs:annotation>
      <xs:complexType>
        <xs:sequence> <!-- default value of maxOccurs is 1 -->
        <!-- should be replaced by <xs:sequence maxOccurs="unbounded"> -->
          <xs:any namespace="##any" processContents="lax" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:normalizedString" use="required">
          <xs:annotation>
            <xs:documentation>Name of tool that can interpret the annotation. "name" must be unique with respect to all other elements of the VendorAnnotation list.</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:complexType>
    </xs:element>
  </xs:sequence>
</xs:complexType>
  ```
}}}
```

----

Migrated-From: https://trac.fmi-standard.org/ticket/386

**Comment by modelica-trac-importer** [comment]
**Modified by andreas&#x2e;junghanns on 6 Feb 2017 10:59 UTC**

**Comment by KarlWernersson** [comment]
Although I agree with you, I don’t see this as something that should be changed in 2.0.1, it can currently be circumvented since any child nodes to the any node are unbounded.
Chaning milestone to 3.0

**Comment by chrbertsch** [comment]
<xs:sequence maxOccurs="unbounded">

is already defined in https://github.com/modelica/fmi-standard/blob/master/schema/fmi3Annotation.xsd

**Comment by andreas-junghanns** [comment]
related to #945 and #937

**Comment by clagms** [comment]
2020-04-30-Regular-FMI-Design-Meeting

KW: This causes more levels of hierarchy without need.

Conclusion: allow any content. PMAI will create a PR.
