### ISSUE TITLE
Clarifications regarding FMI version string: forward/backwards compatibility; version string.

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#388]
**Reported by cbertsch on 15 Oct 2016 19:25 UTC**
The meaning of the digits of FMI versinos (e.g. 2.0, 2.0.1) has been clarified at the FMI Meeting in Oberpfaffenhofen 9.2.2015 ( https://svn.fmi-standard.org/fmi/trunk/Meetings/2015-02-09-FMI-Oberpfaffenhofen/ ), i.e. after the release of the FMI 2.0 standard.

Thus some clarifications are needed for the FMI 2.0.1 standard:
* The meaning of major, minor and bugfix releases shall be explained in the 2.0.1 standard and should be used consistently (e.g. on page 31 of the 2.0 standard, 2.0.1 is called a "minor" release, but should be a bugfix releases.
* What shall an FMU exported to a FMI 2.0.1 have as version string in the xml? According to the 2.0 standard, I would have expected "2.0.1". However, in the course of creating first reference FMUs, we created an FMU with version string "2.0.1" in the modeldescription.xml, but none out of five tested importing tools (FMI 2.0 supporting, released in 2016 after the clarification of the version digit meaning)  accepted this FMU. So de-facto, such an FMU will be incompatible with FMI 2.0 importing tools. We should consider leaving the version string in FMI 2.0.1 to "2.0" and giving the "2.0.1" information only as an annotation.
* What shall be the return value of fmi2GetVersion(void) for a 2.0.1 FMU be? "2.0" or "2.0.1"? This could both happen for a "2.0.1" source code FMU beeing compiled with  the fmi2Functions.h Header file from either an FMI 2.0  or 2.0.1 supporting target. Must the return value of fmi2GetVersion be exactly the same as the version string of the "modeldescription.xml"? Then we should leaver both to "2.0".

----

Migrated-From: https://trac.fmi-standard.org/ticket/388

**Comment by modelica-trac-importer** [comment]
**Comment by rerbacher on 10 Nov 2016 09:37 UTC**
I think that a bugfix (maintenance) release of the FMI standard (e.g. 2.0.1) affects only the specification text itself, not the actual functionality or capabilities of this Major.Minor version of the FMI standard. I.e., desription errors are fixed, clarity is enhanced, ambiguities removed etc. Therefore, FMU exporting tools should always write only the Major.Minor version into the FMU, and FMU importing tools should only check for the Major.Minor version in the FMU. 

Reasoning: Let's assume that an FMU exporting tool did its implementation based on FMI 2.0 specification. Because of some errors or ambiguities in this specifiction text the tool implemented something in a way it was not meant by the standard. This error is detected and results in a discussion about needed fixes in the specification text. We can assume that in many cases there will be agreement on the correct meaning/interpretation before the bugfix version of the FMI standard will be released (2.0.1 in this example). So it is likely that the FMU exporting tool will have its implementation fixed and a new tool version released _before_ the bugfix version of the standard is available. In this case the tool simply _cannot_ (must not) write 2.0.1 to its exported FMU file. It should be clear that using an FMI version ahead of its official release is not a good idea at all.

I think that a _uniform_ use of FMI version numbers within FMUs _across all tools_ can be achieved only with the rules I outlined above. 

The FMI specification text then should be extended to prescribe that only Major.Mior versions are to written to exported FMUs.

-- _Rafael Gilles, dSPACE_

**Comment by KarlWernersson** [comment]
decision, clarify that fmiVersion in 2.0.1 must be 2.0 by removing this sentence Future minor
revisions are denoted as “2.0.1”, “2.0.2”, …

mention, in changes summary
