### ISSUE TITLE
Continuous-time state variables and alias status

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#391]
**Reported by aviel on 23 Nov 2016 15:00 UTC**
The status of aliased continuous-time state variables is not clear in the current Model Exchange specification.
According to page 51 (section 2.2.7), "Variables a and b that can both be set with fmi2SetXXX (...) cannot be alias variables".
Does _fmi2SetXXX_ applies to the _fmi2SetContinuousStates_ function?
If this is not relevant, aliased continous-time state variables are to be allowed. In order to have consistent values for the environment, it should be required that the corresponding state derivatives are also aliased. Moreover, the case of a continous-time state variable that is an alias of an input variable should be forbidden.

----

Migrated-From: https://trac.fmi-standard.org/ticket/391

**Comment by modelica-trac-importer** [comment]
**Modified by aviel on 23 Nov 2016 15:07 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by aviel on 27 Nov 2017 16:44 UTC**

**Comment by KarlWernersson** [comment]
From the derivative definition in the standard
_The state derivatives of an FMU are listed under element ModelStructure/Derivatives. All ScalarVariables listed in this element must have attribute derivative (in order that the continuous-time states are **uniquely** defined)._

Is this enught to state that the states are uniqe.
Allowing states to be alias is a realy bad idea and should be forbidden.
If the proposed solution of #392 is accepted this is solved.
If rejected we should still forbid it, possible solution to add on p 51
_5. states defined through ModelStructure/Derivatives cannot be alias.

In addition reference to state alias in undbounded p40 must be removed
_if the corresponding variable **or an alias of it** is a continuous state variable_

**Comment by KarlWernersson** [comment]
Close due to fix of 392
