### ISSUE TITLE
Can fmi2SetReal be used for changing the value of continuous-time state variables?

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#392]
**Reported by aviel on 23 Nov 2016 15:52 UTC**
In the Model Exchange specification, the use of the _fmi2SetReal_ function for changing the value of the continuous-time state variables is unclear. According to the mathematical model (p. 75, section 3.1), _fmi2SetReal_ can be called during Event Mode and Continuous-Time Mode to set the value of the continuous-time states. According to the Model Exchange state machine (p. 83, section 3.2.3), only _fmi2SetContinuousStates_ is allowed, whereas _fmi2SetReal_ is restricted to the input variables.

This ticket is related to #391, since clarifying the role of the _fmi2SetReal_ function imply consequences regarding the legality of aliased continuous-time state variables. 

----

Migrated-From: https://trac.fmi-standard.org/ticket/392

**Comment by modelica-trac-importer** [comment]
**Modified by aviel on 27 Nov 2017 16:44 UTC**

**Comment by KarlWernersson** [comment]
I think the intention was that one should call setContinousStates and not setReal on individual states as the first is slightly more efficient (no Value reference decoding) and you normally set all states together in a numerical solver. However, I don't see a reason why it should be forbidden for modelExchange. If it's allowed it would help solve #407

**Comment by KarlWernersson** [comment]
Proposed solution: Allow and update the state diagram.

**Comment by KarlWernersson** [comment]
Poll

Allow:
Antoine, Kaska, Markus, Massoud, Otto, Pierre Thomas, Timo, Karl
Remove from mathematical description:

Abstain: Andreas, Irina, Christian, Torsten, Klaus

**Comment by KarlWernersson** [comment]
Taks we need to calrify in the standard

**Comment by masoud-najafi** [comment]
Note that both GetReal() and getContinuousStates() are available in the "ContinuousTimeMode". That means states can be retrieved one by one, so why not allowing setting states one by one.

**Comment by chrbertsch** [comment]
Closed by https://github.com/modelica/fmi-standard/commit/8597686fd340196886f7cab4c66465c72ab2a4a4 in webmeeting

**Comment by chrbertsch** [comment]
This does not seem to present in the generated docomnet https://fmi-standard.org/docs/2.0.1-develop/#_pseudo_code_example and not in the word docucument and generated PDF (RC4)

![image](https://user-images.githubusercontent.com/16363372/66019616-97162c80-e4e4-11e9-95bb-52955e65a4ea.png)

**Comment by chrbertsch** [comment]
Will be contained in RC5
