### ISSUE TITLE
Improve sentence using nextMode (2x)

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#393]
**Reported by andreas&#x2e;junghanns on 28 Nov 2016 08:10 UTC**
The current standard document contains 2 references to `nextMode` which is unclear. This needs fixing. Suggestion by Martin Otter:

From:
```
and the function returns with nextMode = fmi2ContinuousTimeMode
```

to:
```
and the function returns with "enterEventMode = fmi2False, and terminateSimulation = fmi2False
```

----

Migrated-From: https://trac.fmi-standard.org/ticket/393

**Comment by modelica-trac-importer** [comment]
**Comment by aviel on 10 Jan 2017 13:20 UTC**
For the first reference on p. 71:
```
nextMode=EventMode
```
has to be replaced by:
```
enterEventMode=fmi2True
```

**Comment by modelica-trac-importer** [comment]
**Comment by aviel on 13 Feb 2017 16:00 UTC**
Change to _minor_ priority since this seems to require only a little text change to be consistent.

**Comment by beutlich** [comment]
Updated milestone.
