### ISSUE TITLE
fmi2SetTime in Event Mode of Model Exchange

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#394]
**Reported by aviel on 5 Dec 2016 16:13 UTC**
According to the table of page 85, section 3.2.3 of the Model Exchange specification, the _fmi2SetTime_ function can be called in Event Mode. However, the mathematical model of pages 74-75, section 3.1, does not seem to allow this. This inconsistency has to be fixed.

----

Migrated-From: https://trac.fmi-standard.org/ticket/394

**Comment by modelica-trac-importer** [comment]
**Comment by aviel on 27 Nov 2017 17:34 UTC**
More precisely, there is a statement in the mathematical model of p. 75, at the end of the _Equations during Event Mode_ section, that tells:
  Set independent variable time t<sub>i</sub> := (T<sub>next</sub> , 0)
which translates into a call _fmi2SetTime_ **if  no continous-time equations**. This seems relevant to the pure-discrete time FMU variant (see also #394).

In order to clarify this issue, a new section called _Pure discrete-time variant_ should be introduced between _Equations during Event Mode_ and _Equations during Continuous-Time Mode_ to account for this call to _fmi2SetTime_ (after the call to _fmi2NewDiscreteStates_, and before the call to _fmi2EnterEventMode_).

**Comment by KarlWernersson** [comment]
The a simple solution could be to add an 8 instead of an x for fmi2SetTime EventModeCombo in the table with the definition:

**8 only for a Pure Discrete-Time FMU. This exits the current event mode and sets the time for the next event instant.**

**Comment by KarlWernersson** [comment]
Addition, new Discrete state must have been called with iterationConverged==fmi2True  attest once before this can be done:
(Cleanup)

**Comment by chrbertsch** [comment]
Included in the merged PR #579
