### ISSUE TITLE
Clearly define that the entry point to the documentation contained in an fmu should be "index.html"

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#399]
**Reported by cbertsch on 8 Jan 2017 07:11 UTC**
In the FMI 2.0 standard, on p. 66 it is suggested that the entry point to the documentation is “index.html” (in the Structure of zip file of an FMU).
However, it is not clear whether this is only an example name, or if this name is mandatory. (e.g. the FMU SDK uses _main.html instead of index.html in its examples). 
My suggestion for FMI 2.0.1 would be, that if the optional documentation folder is present in the FMU, an “index.html” file will be mandatory. This could then be checked by the Compliance Checker.

----

Migrated-From: https://trac.fmi-standard.org/ticket/399

**Comment by modelica-trac-importer** [comment]
**Comment by aviel on 10 Jan 2017 13:31 UTC**
As far as I can recall it, the entry point was changed from `_main.html` in FMI 1.0 to `index.html` in FMI 2.0.

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 10 Jan 2017 13:59 UTC**
My proposal would be to make the index.html folder mandatory if the documentation folder is present and not empty.

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 6 Jun 2017 13:43 UTC**
@tool vendors: please use "index.html" for FMI 2.x.
The compliance Checker should check this.

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 30 May 2018 14:47 UTC**
Regarding the compliance checker this is tracked in https://github.com/modelica-tools/FMUComplianceChecker/issues/22

**Comment by KarlWernersson** [comment]
Decision: It have to stay as recommendation due to forwards compatibility 
If some one comes with a good text proposal, use it, otherwise keep current text.

**Comment by t-sommer** [comment]
@KarlWernersson, what is the `task`? Can't we just close this?

**Comment by KarlWernersson** [comment]
@t-sommer yes, i do not know how to make it more clearer in a simple way without enforcing it
