### ISSUE TITLE
Location of additional DLLs undefined?

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#401]
**Reported by cbertsch on 9 Jan 2017 14:58 UTC**
The FMI 2.0 standard suggests on p.66, that additional DLLs might be present  in the binaries/<platform> folder.
However, the FMU can only inquire for the location of the "resources" folder. 

How is it possible to call functions from and additionally included DLL? Shall such DLLs be called from "<fmuResourceLocation>/../binaries/<platform>" folder? This does not look nice because it is platform dependent; on would have to inquire during instancition which <platform> is currently used (e.g. win32, and win64) and then create <platform>-dependent code to call the correct DLL.
Is it guaranteed that the the directories other than the "resources" folder (i.e., "binaries", ...) are present during instantiation? p.19 of the FMI 2.0 standard only talks about the "resources" folder.
Wouldn't it be better provide explicitly a path to the <platform>-dependent binaries folder, e.g.? 
Or should additional DLLs be put in the "resources" folder? But then one would have to mirror the <platform>-dependent structure of the "binaries" folder, which does not look nice.

Feedback for the clarification is very welcome.

----

Migrated-From: https://trac.fmi-standard.org/ticket/401

**Comment by modelica-trac-importer** [comment]
**Comment by andreas&#46;junghanns on 9 Jan 2017 15:04 UTC**
DLLs can ask which folder they were loaded from and can then add that path to the top of the DLL include list, or use that path to explicitly load a dependent DLL from there.

Placing platform dependent executable files into the resource folder would force multi-platform DLLs to have the platform folders there as well. This was discussed a long time ago but I guess the reasons did not make it into the standard (we might want to clarify this in the notes document though as this is more design rational than normative text).

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 12 Jan 2017 18:47 UTC**
OK, DLL location can be inquired by something like http://stackoverflow.com/questions/6924195/get-dll-path-at-runtime.
Perhaps one should give a hint to this in the FMI 2.0.1 standard or the accompanying "implementation hints" document https://trac.fmi-standard.org/export/2782/trunk/FMI_2.0.1/FunctionalMockupInterface-ImplementationHints.docx

We have seen problematic FMUs exported from a commercial tool, where DLL were inside the ressources folder. Is this explicitly forbidden by the standard (should this be clarified in FMI 2.0.1?)? Should this be checked by the compliance checker? (If this is not explicitly forbidden, at least the compliance checker could give a warning)

**Comment by modelica-trac-importer** [comment]
**Comment by andreas&#46;junghanns on 12 Jan 2017 19:52 UTC**
We might recommend a certain behaviour/location, but not as normative text.
The FMU exporting tool produces both DLLs, the one with the FMU-API inside and the one loaded from that. And it knows where things are stored inside the FMU. So all information is present to locate the 2nd DLL and load it from there.

But what should we recommend? The best solution will very likely depend on the platform. If we leave it unspecified and un-recommended, the FMU exporting tool implementers can use their preferred way.

**Comment by modelica-trac-importer** [comment]
**Comment by pierre&#46;mai on 15 Jan 2017 23:37 UTC**
While this (i.e. doing DLL-derived path calculations) is current practice (and will e.g. be mentioned as a fallback mechanism in the upcoming ProStep best practice guides), it relies on one thing that is not guaranteed by the current standards: The standard does not currently guarantee that the whole ZIP archive is unpacked, nor into one place.  It would be perfectly OK for an importing implementation to unpack only the model-identifier-derived DLL into place A (and nothing from the rest of the binaries directories), and unpack the resources folder into place B (totally unrelated to place A).  Quite a number of FMUs will not work if unpacked in this fashion (and this is not a theoretical problem, we have seen this problem in the wild).

Given the current mandate for FMI 2.0.1 I don't see how this can be fixed, but it should be fixed in a future version; otherwise specification and actual practice will drift even more apart, thus making implementation of useful FMI implementations even more dependent on these kind of actual, unspecified practices.

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 16 Jan 2017 19:19 UTC**
I think we can and should fix this in FMI 2.0.1.
Having additional binaries in the binaries folder is already allowed in FMI 2.0 (listed in the zip file structure on page 66: "<other DLLs> // The DLL can include other DLLs)." I agree with Pierre, that the storing location of these DLL is not clearly specified.
I see the necessity to clarify this ambiguity, which is one intention of a bugfix release.
My proposal would be, that the full content of the platform-specific folder of the binaries (e.g. binaries/win64/\*.* together with subfolders) must be present in the same folder as the <modelidentifier>.dll/so-File. 

Could such a FMI 2.0.1 FMU be simulated in a 2.0 FMI importing tool as required by forward compatibility of bugfix releases? Yes, if the importing tool has the same interpretation of the FMI 2.0 standard as the clarification. No, if the importing tool acts as described in Pierre's comment. However, this can also happen for FMI 2.0 FMUs, where the exporting tool interprets the standard in the same way as the clarification.

Would it be an alternative to put the binaries in the ressources folder, the location of which is specified? I think this is not what the ressources folder is intended for.

Question: Is it possible for inquiring for the file location of an .so file in Linux/OS X as for a windows DLL?

**Comment by modelica-trac-importer** [comment]
**Comment by pierre&#46;mai on 10 Feb 2017 12:06 UTC**
Replying to [comment:5 cbertsch]:
> I think we can and should fix this in FMI 2.0.1.

Personally I agree with this position, however I don't see support from others on this issue.

> Question: Is it possible for inquiring for the file location of an .so file in Linux/OS X as for a windows DLL?

Yes, this is usually possibly via dladdr() for Linux and OS X, at least for the FMU code itself (other code might have to work around PLT problems first).

**Comment by modelica-trac-importer** [comment]
**Comment by pierre&#x2e;mai on 10 Feb 2017 12:10 UTC**
Also given that this clarification is to be part of the FMI 1.0.1 release, and the fmuLocation has been clarified to be the path to the unpacked contents, this solves the problem for FMI 1.0.1 nicely, IMHO, since this more or less implicitly requires full unpacking of the FMU and allows this to work (more or less by accident ;).

A similar solution should hopefully be achievable for 2.0.1.

**Comment by chrbertsch** [comment]
For FMI 2.0.1 my proposal is to make it mandatory, that all the content of the the currently used ´binaries´ subfolder  (e.g. /binaries/win64) of the FMU ZIP-File must be present unzipped in a common folder on the target machine. Then they can be found using the mechanisms discussed above.

For FMI 3.0 I propose to have an `fmuRootLocation` instead of an `fmuResourceLocation` in the instanciation and make it mandatory, that either the complete FMU-Folder is present unzipped on the target or with some exceptions (e.g. on a windows target one would not need linux binaries, or one could have exceptions for realtime systems). Then one could access the resources folder by `fmuRootLocation/ressources` and could find the binaries on a windows platform in `fmuRootLocation/binaries/win84`. 

 (As and alternative for FMI 3.0 one could have an `fmuBinariesLocation `additional to the ´fmuRessourceLocation´ which I would  not prefer)

**Comment by KarlWernersson** [comment]
Proposal for 2.0.1

Add at page 66 before **resources**

_< If an FMU is run through one of its binaries all items in that binary folder **must** be unpacked at the same location as the binary < modelIdentifier >.* is unpacked >_

If this is deemed to intrusive for forwards compatibility we could write something like this.

_< If an FMU is run through one of its binaries all items in that binary folder is **recommended** to be unpacked at the same location as the binary < modelIdentifier >.* is unpacked. If not it’s likely that, if the FMU has dependencies on those items, it will not be able to find them and run >_

**Comment by KarlWernersson** [comment]
Decisions, recommended rout

**Comment by chrbertsch** [comment]
Included in the merged PR #579
