### ISSUE TITLE
Correct handling of dependencies seems not possible for continuous-time state variables

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#402]
**Reported by aviel on 11 Jan 2017 10:09 UTC**
In the Model Exchange specification, the continuous time-state variables can only be changed through a call to the `fmi2SetContinuousStates` function, as shown on the _Continuous Time Mode_ state of the _state machine of calling sequence_ (section 3.2.3, p. 83), since it is not allowed to use the `fmi2SetReal` function. If a continuous-time state derivative or an output variable depends on a subset of the continuous-time state vector (as described in the _ModelStructure_ element of the _fmiModelDescription_), it is not possible to benefit from the caching mechanism proposed by the FMI specification, because all of the continuous-time state variables must be reseted at once. Since some numerical integration schema do not rely on synchronuous assignment of the state variables, there seems to be an inconsistency with the Mathematical Description (section 3.1), that states that the dependencies, if they are declared by the FMU, must be taken into account for each variable (the remarks on p. 73 and 76 forget to deal with the continous time-state dependencies and only exhibit examples related to direct feedthroughs).

----

Migrated-From: https://trac.fmi-standard.org/ticket/402

**Comment by modelica-trac-importer** [comment]
**Comment by otter on 11 Jan 2017 10:44 UTC**
Replying to [ticket:402 aviel]:
> In the Model Exchange specification, the continuous time-state variables can only be changed through a call to the `fmi2SetContinuousStates` function, as shown on the _Continuous Time Mode_ state of the _state machine of calling sequence_ (section 3.2.3, p. 83), since it is not allowed to use the `fmi2SetReal` function. If a continuous-time state derivative or an output variable depends on a subset of the continuous-time state vector (as described in the _ModelStructure_ element of the _fmiModelDescription_), it is not possible to benefit from the caching mechanism proposed by the FMI specification, because all of the continuous-time state variables must be reseted at once. Since some numerical integration schema do not rely on synchronuous assignment of the state variables, there seems to be an inconsistency with the Mathematical Description (section 3.1), that states that the dependencies, if they are declared by the FMU, must be taken into account for each variable (the remarks on p. 73 and 76 forget to deal with the continous time-state dependencies and only exhibit examples related to direct feedthroughs).

FMI for ModelExchange was designed under the assumption that the "states" are known and are inputs from the integrator to the model at the same time instant. Integration schemes that update the states not all at the same time instant cannot use FMI for ModelExchange. This restriction is implicit in the mathematical description and function calls (as you also found out). It might be useful to state this restriction explicitly in the specification.

The dependency on the states in the dependency list is NOT given for input/output connections, but to define the sparseness structure of the Jacobian with respect to the states.

**Comment by KarlWernersson** [comment]
Can we close this, or alteast move to 3.0?

**Comment by KarlWernersson** [comment]
fixed by ticket #392
