### ISSUE TITLE
Pure discrete-time FMU with state events

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#405]
**Reported by aviel on 26 Jan 2017 08:45 UTC**
In the model exchange 2.0 specification, a variant called "pure discrete-time FMU" is defined (see remark 4, p. 78 of section 3.1). It seems also that such an FMU can still define event indicators since there is no restriction on the _numberOfEventIndicators_ attribute of the _fmiModelDescription_ element (Such FMUs actually exist in the cross-check repository). Moreover, the _fmi2GetEventIndicators_ function can be called in Event Mode (according to the mathematical model description of section 3.1, and the State Machine of Calling Sequence of section 3.2.3). However, this seems contradictory since _fmi2GetEventIndicators_ is used to locate the state events during the Continuous-Time Mode, which is not relevant to pure-discrete time FMUs. So, the specification must clarify how to deal with state events in that case. Another possibility is to restrict state events to "standard" FMU that rely on the Continuous-Time Mode to be evaluated.

----

Migrated-From: https://trac.fmi-standard.org/ticket/405

**Comment by modelica-trac-importer** [comment]
**Comment by karl&#46;wernersson on 19 Jun 2017 10:28 UTC**
Hi Antoine

There is no requirement to find the exact time point just a recommendation for a good implementation, a simple fixed step solvers used for model exchange import would likely not have this possibility and just check for state events at end of step, (which gives worse accuracy and the possibility to even miss state events).

Similar this option for skipping continuous time mode was at the request of vendors/users which specializes on discreet models which normally uses a fixed sample time to update the simulation time.
There is also no restriction on entering continuous time mode for a discrete FMU to find a more accurate time point for when the event indicators changes, it’s just not required.

**Comment by modelica-trac-importer** [comment]
**Comment by najafi on 20 Jul 2017 11:55 UTC**
Hi,
As Antoine said, an FMU without continous state can have zero-crossing and to get a precise event-detection going into continous-time mode is required. Hence, for a block without continuous-time state and with zero-crossing, going though different path, changes the result. If We do not clarify the definition of "pure continuou-time" FMU, we SHOULD indicate that selecting this branch is just a "recommendation".

**Comment by KarlWernersson** [comment]
For 2.0.1 i think a recommendation to use the continuous time interface if you want to find the exact time point of state events. If we go with the proposed solution for issue #409 this is easy.

An addition to remark 4 could be (or a new remark 5)
**If a Pure Discrete-Time FMU has state events and the precise time points for them are required 
the FMU needs to call fmi2EnterContinousTimeMode to go into continous time mode to pinpoint the time point with event indicators and fmi2SetTime**

**Comment by KarlWernersson** [comment]
An alternative is to Redefine Pure Discrete Time FMU's as not having crossing function, however this might be too liberal with the forward compatible rules.

**Comment by KarlWernersson** [comment]
Decision, Force enterContinousTime mode if fmu has crossing functions

**Comment by chrbertsch** [comment]
Included in the merged PR #579
