### ISSUE TITLE
Inconsistent definition of the calling conditions for fmi2SetContinuousStates

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#407]
**Reported by aviel on 27 Jan 2017 09:04 UTC**
In the model exchange 2.0 specification, the definition of the allowed states for calling the `fmi2SetContinuousStates` function seems inconsistent. In the Mathematical Description (section 3.1, p. 75), the function can be called in _Event Mode_, whereas in the State Machine of Calling Sequence (section 3.2.3), the call is not allowed in _Event Mode_. **This restriction is repeated by the table of p. 85**.
This is really annoying for executing an FMU in an importing environment since it is not possible to know in advance to which convention the FMU adheres to.

----

Migrated-From: https://trac.fmi-standard.org/ticket/407

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 30 Jan 2017 19:05 UTC**
Do you agree that fmi2setContinuousStates should be allowed in continuous time mode _and_ in event mode? So the state machine and and the table on p.85 should be modified?

**Comment by modelica-trac-importer** [comment]
**Modified by aviel on 27 Nov 2017 17:14 UTC**

**Comment by KarlWernersson** [comment]
There is one problem and that is the reinit tag for states, if this is true, then that specific state can work as an output during event mode and might be updated by FMU. Any call to setContinousStates would be invalid for those variables.
With this in mind i would say its not allowed to call setContinousStates during event mode. 
The alternative would be to allow the FMU to always ignore the values of the individual states with reinit=true during event mode, this is possible but would complicate the standard.

Then taking a look at 
https://github.com/modelica/fmi-standard/issues/392
If one allows this, i don't see a problem allowing setReal on those states that are not covered by reinit.

**Comment by KarlWernersson** [comment]
Poll,

Allow setContinousStates in eventMode

Disallow setContinousStates in eventMode
Antoine, Kaska, Markus, Masoud, Pierre, Thomas, Timo, Karl
Allow SetReal on states without reinit in event mode
Karl
abstain: Andreas, Irina, Christian, Kalus, Otto, Torsten

**Comment by KarlWernersson** [comment]
Invest age for 3.0

Clarify mathematical description

**Comment by chrbertsch** [comment]
Included in the merged PR #579
