### ISSUE TITLE
Clarification that variable names must be unique

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#415]
**Reported by ottot on 20 Apr 2017 06:57 UTC**
In _2.2.7 Definition of Model Variables (ModelVariables)_ there is a table where the description of the name attribute is "The full, unique name of the variable.", so there it looks well established that the name should be unique.

In _2.2.9 Variable Naming Conventions (variableNamingConvention)_ we have the sentence _The names must be unique, non-empty strings._ However it looks to be under the heading _variableNamingConvention = "flat"_. It should either be repeated under _variableNamingConvention = "structured"_ or moved to the top-level in _2.2.9_ so that it is clear that the uniqueness requirement applies regardless of _variableNamingConvention_.

----

Migrated-From: https://trac.fmi-standard.org/ticket/415

**Comment by modelica-trac-importer** [comment]
**Modified by aviel on 4 May 2017 06:29 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by pierre&#x2e;mai on 12 Jun 2018 21:19 UTC**
FWIW, the full entry in section 2.2.7 reads:

_The full, unique name of the variable. Every variable is uniquely identified within an FMU instance by this name or by its ScalarVariable index (the element position in the ModelVariables list; the first list element has index=1)._

This seems to be fairly clear that variables must always be uniquely identified by their name, regardless of naming convention used. Might still be a good idea to clarify some more, though.

**Comment by chrbertsch** [comment]
Included in the merged PR #579
