### ISSUE TITLE
Strange license extension in FMI ME 1.0.1

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#423]
**Reported by beutlich on 14 Sep 2017 09:32 UTC**
The header files of [FMI ME 1.0.1](https://svn.modelica.org/fmi/branches/public/specifications/v1.0/FMI_for_ModelExchange_v1.0.1.zip) contain a new (w.r.t. FMI ME 1.0) license extension:

```
   with the extension:

   You may distribute or publicly perform any modification only under the
   terms of this license.
```

To me it seems the intention was to forbid sublicensing, however

* This extension now changes the license from a standard BSD license to a custom BSD-style license.
* BSD (all three flavours) already forbid sublicensing (which is the main difference to MIT license actually).
* This extension was only added to FMI ME, but not FMI CE, thus it rather seems an incomplete extension.

Proposal: Remove that extension again and get the license correctly sorted out to use the 3-Clause BSD license (probably). See also #347.

----

Migrated-From: https://trac.fmi-standard.org/ticket/423

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 14 Sep 2017 09:39 UTC**
Just have seen, that this license extension is already there in FMI ME 1.0, thus it is not a newly introduced issue.

**Comment by modelica-trac-importer** [comment]
**Comment by andreas&#46;junghanns on 14 Sep 2017 11:09 UTC**
CAn we close this ticket?

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 14 Sep 2017 11:18 UTC**
You mean closing in favor of #347? Probably.

**Comment by modelica-trac-importer** [comment]
**Comment by otter on 14 Sep 2017 12:06 UTC**
The license for FMI 1.0 was defined in a contract between the MODELISAR partners (Project Cooperation Agreement):

 Article 7.1:
 a) During the term of this agreement, and except if the Parties agree otherwise during a PCC, such license shall be granted by Parties as follows: For the FMI specification document: CC-BY-SA (http://creativecommons.org/licenses/by-sa/3.0/legalcode, http://creativecommons.org/about/licenses) For the FMI source code files: BSD license (http://www.opensource.org/licenses/bsd-license.html) incorporating the following paragraph: “You may distribute or publicly perform any modification only under the terms of this license”.

Therefore, it is not possible to just change the license without a new legal agreement.

As I recall, the reason to add this sentence was that some partners feared that FMI \*.h files are extended by FMI tool vendors and that they put the extensions under their own copyright and license. If the FMI group then adds later similar or identical extensions, this might give unnecessary conflicts.

Note, the license text refers only to the respective \*.h file. Therefore, if an organization would like to add extensions under a different license, they can just do it, but have to store these extensions in a different header file.

**Comment by modelica-trac-importer** [comment]
**Comment by otter on 14 Sep 2017 12:07 UTC**
To be precise: The link in the contract refers to the BSD2 license text (not BSD3)

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 14 Sep 2017 12:11 UTC**
Martin: Thanks for pointing to the Project Cooperation Agreement.

> The link in the contract refers to the BSD2 license text (not BSD3)

That is what #347 was reported.

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 14 Sep 2017 12:20 UTC**
If this license extension is by design actually, then it seems incomplete since it is missing in FMI CE files. Still, I'd prefer to have the standard 3-Clause BSD license here, since this license extension is superfluos when it comes to sublicensing.

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 14 Sep 2017 12:35 UTC**
In my point of view, FMI 1.0.1 and later are new releases and are not bound by MODELISAR agreements intended for FMI 1.0.

I strongly recommend to use "standard" open source licenses (like BSD-3clause) without amendments. 
Companies have "black/whitelists" for these standard licenses, while a license with an amendment is a new license which has to be re-evaluated by legal departments.

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 7 Sep 2018 21:20 UTC**
This was not touched for v1.0.1.

**Comment by andreas-junghanns** [comment]
I am still not sure if this "addition" changes anything. It looks to me like a harmless reference to say "do what you are told". I suggest to leave things as is. If you don't agree, please re-open this ticket.

**Comment by pmai** [comment]
Any addition makes the license a non-catalog license, which means the necessary involvement of IP-lawyers before most larger companies will touch this. And given the completely ambiguous text that was added, there are legitimately multiple interpretations of the clause (ranging from it just restates you must obey the BSD license, to you must release any modifications under BSD terms to others, which could then in extremis even apply to non-header code).

I think this needs fixing. Preferably by selecting a standard license, but if a custom license is needed it needs to be drafted by well-versed IP lawyers, the current license is just an accident waiting to happen.

**Comment by andreas-junghanns** [comment]
Mmmh. I totally agree about the lawyers. But if it was like this in 1.0, can we simply change it for 1.0.1_mod?
Or do we have to release 1.0.2?

**Comment by pmai** [comment]
I think it can be rereleased as 1.0.1, since nothing content wise changes. But I think the license is written into the project charter, so this will have to be changed first, I think, and that’s relevant for 2.0.1 and 3.0 releases, which I think are more important...

**Comment by andreas-junghanns** [comment]
I cannot find the sentence `You may distribute or publicly perform any modification only under the terms of this license.` in the 1.0.1 documents. The project rules state:
`FMI specifications are published under the CC-BY-SA (Creative Common Attribution ShareAlike 4.0
International) license (or a follow-up version of this license), a human-readable summary of the license
text as well as a link to the license text itself is available from https://creativecommons.org/licenses/by-
sa/4.0/
Source code or other data, such as C-header and XML-schema files, that accompany the specification
documents are provided under the BSD 2-Clause license (or a follow-up version of this license). A human-
readable summary of the license text is available from http://www.opensource.org/licenses/bsd-
license.html`

Why can't I find what Thomas complains about? Which page did I (and the text search) miss?

**Comment by pmai** [comment]
That sentence is contained in the header files themselves.

If the project rules have been modified as you state, then the sentence should be removed from all to be released or re-released standards, and the BSD license should be switched to the 2-clause one.

The version of the project rules on the modelica.org page still contains the original wording:

> The FMI specifications are published under the CC-BY-SA (Creative Common Attribution ShareAlike 3.0 Unported) license, i.e., the license used by Wikipedia. A human-readable summary of the license text is available from http://creativecommons.org/licenses/by-sa/3.0/ Source code, such as C-header and XML-schema files, that accompany the specification documents are provided under the BSD license (http://www.opensource.org/licenses/bsd-license.html) with the extension that modifications must be also provided under the BSD license. 


So maybe that should also be updated at some time.

**Comment by pmai** [comment]
In the case that the project rules now name the 2-clause BSD license, then change  44e7a9f should be reverted and the text changed to 2-clause across the board, too.

**Comment by pmai** [comment]
Oh, and the license stuff is also on page 2 of 1.0.1, again with the extension sentence.

**Comment by andreas-junghanns** [comment]
Now I am thoroughly lost. But if you think the extension restricts the license somehow, removing it will not be an issue because it grands the users more rights, not less. And then changing even 1.0.1 should be no problem.

**Comment by t-sommer** [comment]
> In the case that the project rules now name the 2-clause BSD license, then change [44e7a9f](https://github.com/modelica/fmi-standard/commit/44e7a9fbd2cab711e39051b73c0186da91ceff6c) should be reverted and the text changed to 2-clause across the board, too.

I want to point out that this change just fixes the name and the link. The license text itself has not been touched.

IMHO the link can be removed since the complete license is contained in the respective files. The [linked document ](https://opensource.org/licenses/BSD-3-Clause)contains only a template (with placeholders):

> Copyright &lt;YEAR&gt; &lt;COPYRIGHT HOLDER&gt; [...]

**Comment by chrbertsch** [comment]
We should remove the extension to the BSD license in the header files in all future releases of the FMI standard (2.0.1, 3.0 and if it will exist 1.0.2) according to the up-to-date FMI Proejct rules: https://fmi-standard.org/assets/FMI_ProjectRules_v2.0_2016_06_21.pdf
We should also add a link to the up-to-date project rules to https://www.modelica.org/projects to replace or extend the original project application PDF. @andreas-junghanns : Could you please trigger this?
Could someone also add a target milestone for 2.0.1 to this ticket?

**Comment by beutlich** [comment]
> Could someone also add a target milestone for 2.0.1 to this ticket?

Done.

**Comment by chrbertsch** [comment]
@t-sommer: can we close this due to commit https://github.com/modelica/fmi-standard/commit/3fa34ed9e787453ab667369c6913b05db546e699 ?

**Comment by t-sommer** [comment]
The title refers to FMI 1.0.1 so I'm not sure if we can handle this here since we don't maintain the 1.0.x source on GitHub.

**Comment by chrbertsch** [comment]
@t-sommer : I was referring to "We should remove the extension to the BSD license in the header files in all future releases of the FMI standard (_**2.0.1,**_ 3.0 and if it will exist 1.0.2)".
So I will remove the the 2.0.1 target milestone

**Comment by chrbertsch** [comment]
> The title refers to FMI 1.0.1 so I'm not sure if we can handle this here since we don't maintain the 1.0.x source on GitHub.

Currently this is our only issue tracker for the standard. So I propose to create a milestone v1.0.2 and assign this ticket to it. If the steering decides not to release a version 1.0.2, we can close all this tickets as wontfix.

**Comment by chrbertsch** [comment]
fixing with https://github.com/modelica/fmi-design/commit/2e9da61f03718bc0c1cf2b8f015fb4a21bce85eb ... just to tidy up the issue tracker
