### ISSUE TITLE
Clarify "behavior" of restored FMU as part of the state

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#425]
**Reported by Andreas Nicolai on 10 Nov 2017 11:10 UTC**
FMI Co-Simulation standard defines the state of an FMU (to be stored/restored as) (I believe in section 2.1.8):

"The FMU has an internal state consisting of all values that are needed to continue a simulation. This
internal state consists especially of the values of the continuous-time states, iteration variables,
parameter values, input values, delay buffers, file identifiers and FMU internal status information." 

However, the requirement is fairly weak since it only requires that the FMU can be \*continued\*. It does not explicitly require, that the FMU \*behaves\* exactly in the same manner, when the simulation is continued with the same inputs/control from the simulation master.

Assume, for example, an FMU implements a higher-order integrator such as CVODE: the FMU could continue the simulation solely by getting the time point and solution vector at this time. However, without integration history and other heusteristic variables, the integrator would have to restart the integration (through re-init in case of CVODE) with method order 1 and some initial time step.

Obviously, the results would be different than those of the FMU continuing the integration without re-init. Though, the results would be within the requested tolerances. Such an FMU would formally fulfil the requirements of the standards,i.e. could be continued (within requested accuracy).

Problem: when a co-simulation master algorithm is employed that builds up a Jacobian matrix of coupling variables using finite-difference-quotient approximations, it relies on FMUs returning \*exactly\* the same results for any non-correlated input values. Therefore, the requirement on FMUs being reset is, that when integrated again over the same integration step with same inputs, the results must be \*exactly\* the same, always.

The FMI standard should be enhanced to enforce such a behavior, or at least discuss implications on FMUs that fulful only the weak criterion (just continue and provide results with tolerance band).

----

Migrated-From: https://trac.fmi-standard.org/ticket/425

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 1 Jun 2018 15:23 UTC**
Clarification should be in 2.0.1.
Should be discussed for FMI 3.0; perhaps could be implemented with a capability flag.
As only a few tools support getting/setting states, it should not be made more complicated.

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 18 Jun 2018 10:30 UTC**
"The FMU has an internal state consisting of all values that are needed to continue a simulation **producing exactly the same result**

For a possible clarification in 2.0.1 see #441

**Comment by modelica-trac-importer** [comment]
**Comment by anonymous on 10 Jul 2018 14:34 UTC**
EDF use FMI-CS in larger and larger co-simulations with variable stepping and rollbacks so we would prefer/appreciate stability in FMU behavior especially the same results after restarting a FMU and redoing the same steps under the same conditions.

We understand the difficulty is related to the numerical solver used inside each FMU but the standard should not take this implementation difficulty in account and define more strict restarting conditions.

**Comment by modelica-trac-importer** [comment]
**Comment by anonymous on 25 Jul 2018 14:11 UTC**
For EDF it should be non-compliant to have a different behaviour when a state is recovered from the time in which the state was saved.
But the interface cannot impose this, as it's a methodological concern to be added to the FMI document.

**Comment by beutlich** [comment]
@ghorwin FYI

**Comment by chrbertsch** [comment]
FMI regular design webmeeting: 
Karl: it is a big effort to support the same solver behaviour. A flag could be useful. But one could also write it in the documentation
Pierre: it will be difficult to find a name for this capability.
Karl: also the definition of the behivour is difficult
Pierre: Gets difficult when user code is inside
Masoud: one could raise a warning message
Karl: this must be tool issue. If we have an internal solver in Modelica, it is well defined, with user C-Code it is a mess.
Karl: one could add a Flag: NumericalSolverStateIIncluded in stored state
Pierre: when we can formulate how this shall behave, we can define the capability flag
Torsten S: shouldn't it be something like "deterministic"?
Pierre: What does this cover? All cases? then in most cases one cannot guarantee it (e.g. with user code).

Shall we go on with something like "NumericalSolverStateIncluded"?

Masoud: if the Solver state is not included, is it useful at all?
Karl: it still gives the same result within a given tolerance. It is still useful.

Karl: such a flag is not completely well defined.
Torsten: might be interesting in hybrid co-simulation, but perhaps not to the end-user

Kaska: CS are more like a blackbox

Klaus: Which tool vendors would set this flag?
Karl: For some solvers (DASSL), CVODE: could change with updates
Otto: this is the problem, not in the hand of the tool vendor
Christian: this flag would give me more information
Otto: but only up to a tolerance. As an end user you should not bother


Poll: Shall we have a flag: 
Pro: Christian B., Karl
Contra: Masoud
Abstain: Kaska, Klaus, Torsten S., Otto, Hela, Andreas Aigner, Andreas P.

For now we will not have a flag, tools can write if they save the solver state in the documentatoin.
If someone wants a flag, please re-open the ticket and come up with a concrete proposal.
