### ISSUE TITLE
fmi2CancelStep clarification

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#426]
**Reported by masoud on 4 Dec 2017 12:54 UTC**
When a fmi2DoStep() command is cancelled using fmi2CanCelStep(), according to the statechart diagram in FMI2.0/CoSimulation standard in page 103, and also  the table  in page 105, the state of FMU can be changed using fmi2SetFMUstate(). But in the description of the fmi2CancelStep() (page 101) the function fmi2SetFMUstate() has not been mentionned as a legal function to be called in the "step Cancelled" state to change the state. This has caused confusion.

----

Migrated-From: https://trac.fmi-standard.org/ticket/426

**Comment by KarlWernersson** [comment]
@pmai Did you fix this for 2.0.1?
When i investigate the text has been updated to
Afterwards only calls to `fmi2Reset`, `fmi2FreeInstance`, or `fmi2SetFMUstate` are valid to exit the *step Canceled* state.

From
Afterwards it is only allowed to call fmi2Reset or
fmi2FreeInstance.

Or was this changed in the conversion from word to adoc?

**Comment by KarlWernersson** [comment]
Fixed by pmai 29 oct 2018 16.19
