### ISSUE TITLE
FCP_015: Callback functions for numerical stability

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#430]
**Reported by adeas31 on 20 Apr 2018 13:08 UTC**
FCP Callback functions for numerical stability

----

Migrated-From: https://trac.fmi-standard.org/ticket/430

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 1 Jun 2018 15:29 UTC**
Can this be aligned with IOV?

**Comment by chrbertsch** [comment]
FMI-Design Meeting Regensburg: it was decided to enable similar functionality by  adapting the FCP007 allowing for setting intermediate inputs. --> Intermediate variable access

**Comment by chrbertsch** [comment]
@robbr48, @meek1 : can we close this?
Could you please check the current proposal on the master branch, if it fullfills you your requirements or please create a pull request.

**Comment by robbr48** [comment]
This is covered by #546. All requirements are fulfilled in the current proposal.

**Comment by andreas-junghanns** [comment]
@robbr48 : Can you close the ticket then?
