### ISSUE TITLE
Update text under state chart in FMI 2

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#431]
**Reported by karl&#x2e;wernersson on 26 Apr 2018 14:13 UTC**
The text describing the what can be set at different states in section 4.2.4 is more relaxed than what is specified in the state graph and other locations of the standard. It needs to be updated to avoid different interpretations

----

Migrated-From: https://trac.fmi-standard.org/ticket/431

**Comment by t-sommer** [comment]
I've already prepared editable SVG versions of the state diagrams with [draw.io](https://www.draw.io/)

**Comment by chrbertsch** [comment]
The text has been updated in https://github.com/KarlWernersson/fmi-standard/commit/63cda9c3ac7bf225d7b7beac98d27086d252151c and been included in the merged PR #579
