### ISSUE TITLE
Unclear combination of canHandleVariableCommunicationStepSize and stepSize in DefaultExperiment

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#437]
**Modified by klausschuch on 26 Jun 2018 14:26 UTC**
The meaning of the stepSize attribute of the DefaultExperiment element is not clear if the capability-flag canHandleVariableCommunicationStepSize is set to false.
Is the given stepSize the only possible step-size or can the fmi-master chose any other stepSize?
How can the FMU express that it can handle only one specific stepSize?

An FMU may require one of the following three cases:
1) communicationStepSize is variable (may be different for each DoStep call)
2) communicationStepSize is not variable, but defined by the master ("fixed")
3) communicationStepSize is not variable, but defined by the FMU ("constant") in the modelDescription.xml

Additionally, an FMU may want to restrict the actual sizes of communicationStepSize (min, max) in the modelDescription.xml.
(maybe this is topic is covered in the Hybrid-FCP)

This ticket is related to ticket #434.

----

**Reported by klausschuch on 11 Jun 2018 07:45 UTC**
The meaning of the stepSize attribute of the DefaultExperiment element is not clear if the capability-flag canHandleVariableCommunicationStepSize is set to false.
Is the given stepSize the only possible step-size or can the fmi-master chose any other stepSize?
How can the FMU express that it can handle only one specific stepSize?

An FMU may require one of the following three cases:
1) communicationStepSize is variable (may be different for each DoStep call)
2) communicationStepSize is not variable, but defined by the master ("fixed")
3) communicationStepSize is not variable, but defined by the FMU ("constant") in the modelDescription.xml

Additionally, an FMU may want to restrict the actual sizes of communicationStepSize (min, max) in the modelDescription.xml.
(maybe this is topic is covered in the Hybrid-FCP)

This ticket is related to ticket 434.

----

Migrated-From: https://trac.fmi-standard.org/ticket/437

**Comment by modelica-trac-importer** [comment]
**Modified by klausschuch on 26 Jun 2018 14:26 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by karl&#46;wernersson on 26 Jun 2018 15:00 UTC**
Fixed step size rate for fixstep solvers can be clearly defined with a clock in the Hybrid Co-sim proposal.
For normal co-simulation you should not mixup communication step size (the size of dostep) with internal solver step size. If solver uses fixed step size it will have to call mu tipple internal steps until the communication step size is reached. 

In regards to these changed and introduction of multi rate the canNotHandleVariableStepSize flag should be removed

**Comment by modelica-trac-importer** [comment]
**Modified by karl&#46;wernersson on 26 Jun 2018 15:01 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by karl&#46;wernersson on 26 Jun 2018 15:02 UTC**
Look into clearify for 2.0.1

**Comment by chrbertsch** [comment]
As we now have a defined `fixedInternalStepsize` https://github.com/modelica/fmi-standard/pull/857 , I propose to close this.

@KarlWernersson , @klausschuch  and others: please comment

**Comment by andreas-junghanns** [comment]
Please reopen, if you think this still needs attention!
