### ISSUE TITLE
Clarify static linking

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#438]
**Reported by cbertsch on 18 Jun 2018 09:01 UTC**
Clarification regarding static linking for 2.0.1 bugfix release.
See #313 for changes in FMI 3.0
To be clarified:
"self contained" is not clearly defined. 

Define "self contained" that FMUs may not dependend on something external of the FMU (all DLLs and other resources must be contained in the FMU, exception: CS FMUs with needsTool-XML-Tag. As this will not work generally for runtime systems, it is recommended to always link runtimes statically (for Windows Visual Studia use option /MT)

----

Migrated-From: https://trac.fmi-standard.org/ticket/438

**Comment by andreas-junghanns** [comment]
FMI Design Meeting (Roanne, Siemens PLM, Oct, 2018): We called a poll on the question:
"Should we allow external dependencies for static (compile time) and dynamic (runtime) linking of FMUs (even if we strongly discourage such practices) and if yes, proper dependency documentation must be available in the modelDescription.xml (see source-code FCP for 3.0)?"
Agree:  (11)
Disagree:  (6)
Abstain: (2)

**Comment by KarlWernersson** [comment]
Can we get a good solution here for 2.0.1 or should we leave it for 3.0?

**Comment by KarlWernersson** [comment]
decision, move to 3.0

**Comment by chrbertsch** [comment]
FMI Design Meeting: 

is solved by proposal of Source code WG regarding external dependencies.
We still stronlgy recommend static linking.

Task: update text.

**Comment by chrbertsch** [comment]
Can we close this?

The libraries for static linking are defined in https://fmi-standard.org/docs/3.0-dev/#_library

Is there anything elso to clarify?

**Comment by andreas-junghanns** [comment]
Agreed, this is much improved already.
