### ISSUE TITLE
Redefine scope of maintenance/bugfix and minor releases

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#439]
**Reported by cbertsch on 18 Jun 2018 09:54 UTC**
Currently, it is not possible that a 2.0.1 FMUs has higher demands than a 2.0.0 FMU.
It is not even possible for an importer to know, that an FMU is exported according to the 2.0.1 standard, as this information is not contained in the version string.
This has the consequence that from the point of view of an FMI importer, it has to treat all FMUs as 2.0.0 FMUs, i.e. any fixes or clarifications in 2.0.1 cannot be made use of. So even obvious bugs in the specification cannot be fixed. 
For the 3.x release, it should be changed so that FMUs contain the complete version string 3.x.y.
The development process shall clarify, that the requirements on 3.x.y+1 releases can have higher demands on the FMU than a 3.x.y version.
The consequences for the cross check must be discussed.

An alternative would be to make such changes in minor releases (see e.g., #369).

Otherwise the release of maintenance/bugfix releases do not make much sense but could be handled in an implementers guide (e.g. in a wike without large release process)

----

Migrated-From: https://trac.fmi-standard.org/ticket/439

**Comment by modelica-trac-importer** [comment]
**Modified by karl&#46;wernersson on 26 Jun 2018 15:23 UTC**

**Comment by t-sommer** [comment]
Closed in favor of #433
