### ISSUE TITLE
Clarify "behavior" of restored FMU as part of the state (clarification in 2.0.1)

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#441]
**Reported by cbertsch on 18 Jun 2018 10:30 UTC**
Regarding #425: check if a clarification in 2.01 is possible.

----

Migrated-From: https://trac.fmi-standard.org/ticket/441

**Comment by KarlWernersson** [comment]
The specification is quite clear on what is needed, it does not require (but also do not forbid) the full solver information be included.

Changing this would be an enhancement request and does not fall into 2.0.1 release

**Comment by KarlWernersson** [comment]
Agreed in meeting 2018-11-16

**Comment by beutlich** [comment]
@ghorwin FYI
