### ISSUE TITLE
Expand and check documentation for new array functions

### ISSUE THREAD

**Issue by pmai** [modelica/fmi-standard#458]
The current version of the joint FCP-006 Arrays and FCP-003 Binary Types that landed on master should contain all header and schema changes as well as an initial stab on the specification parts. However the whole specification will have to be gone over to ensure that the changes due to the new array variables have been properly reflected, and some of the new C-API definitely needs further elaboration in its documentation.

**Comment by chrbertsch** [comment]
@pmai , @klausschuch , @andreas-junghanns , @t-sommer 

Could you please write down in this ticket which specific steps have to be taken?
If it is jsut about general proofreading, I propose to close this ticket

**Comment by chrbertsch** [comment]
This seems to be a general proofreading issue, see comment above. Merging of the array and binary FCPs took place more than 1,5 years ago, so I expect the main problems to be fixed already with other commits.
Please re-open, if there are special findings.
