### ISSUE TITLE
Include code from headers instead of copying

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#464]
AsciiDoc allows the inclusion of certain lines of arbitrary text files:

```
[source, C]
----
include::headers/fmi3FunctionTypes.h[lines=64..72]
----
```

If we use this for the API sections we can avoid ambiguities and don't have to copy the sources.
Since `headers` is not a sub-directory of `docs` we would have to run asciidoctor with `-B <parent_of_docs>` and adjust the existing includes.

The line numbers would also have to be updated when the headers change (search and replace). An alternative to line numbers are [tags](http://mrhaki.blogspot.com/2014/04/awesome-asciidoc-include-partial-parts.html) but this requires changes to the header files.

**Comment by pmai** [comment]
Implemented via tags by @t-sommer in PR #469.

**Comment by t-sommer** [comment]
There are still (illegal) hard-coded C and XML examples in the documentation:

`docs/2_1_common_api.adoc`:

```
typedef double fmi3Real;
```

`docs/2_2_common_schema.adoc`:

```
_[
Example:
<Variable name="spD" valueReference="126" causality="structuralParameter"
  variability="fixed">
  <Integer start="3"/>
</Variable>
]_ 
```

**Comment by chrbertsch** [comment]
@t-sommer : for the hard-coded C-Code: where shall the .c file be located? In \examples? Or is this reserved for xml files?

for the xml-occurance: I checked, this was the only one, I created PR #960

**Comment by t-sommer** [comment]
Any C code should go into the Reference-FMUs repo, so it get built and validated during CI.
