### ISSUE TITLE
fmi3GetNumberOfContinousStates is missing in fmi3FunctionTypes.h

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#470]
The function`fmi3GetNumberOfContinousStates` is mentioned in [2_1_common_api.adoc](https://github.com/modelica/fmi-standard/blob/master/docs/2_1_common_api.adoc#getting-number-of-states) but doesn't exist in [fmi3FunctionTypes.h](https://github.com/modelica/fmi-standard/blob/master/headers/fmi3FunctionTypes.h)

**Comment by pmai** [comment]
This seems a typo, because the function is called `fmi3GetNumberOfContinuousStates`, and is present in fmi3FunctionTypes.h and fmi3Functions.h as expected?

I've fixed the reference in my fixup commit to #469 ...
