### ISSUE TITLE
Clarification on fmi2SetupExperiment startTime and stopTime

### ISSUE THREAD

**Issue by hyumo** [modelica/fmi-standard#474]
It is unclear if `stopTime` should be greater than `startTime` in `fmi2SetupExperiment` when `stopTimeDefined` is true. 

It might be good to 
- Clarify that `stopTime` must be greater than `startTime` explicitly in the spec.
- Clarify the return value of `fmi2SetupExperiment` when `startTime == stopTime` and `startTime > stopTime`. 

BTW: It seems that integrating backwards is not considered in FMI standard, but should this be considered in the FMI standard as well? i.e. StopTime < StartTime and communicationTimeStep < 0

**Comment by KarlWernersson** [comment]
Do we need to do this?

curently this is stated

**The arguments startTime and stopTime can be used to check whether the model is valid
within the given boundaries or to allocate memory which is necessary for storing results.
Argument startTime is the fixed initial value of the independent variable5 [if the
independent variable is “time”, startTime is the starting time of initializaton]. If
stopTimeDefined = fmi2True, then stopTime is the defined final value of the
independent variable [if the independent variable is “time”, stopTime is the stop time of
the simulation] and if the environment tries to compute past stopTime the FMU has to
return fmi2Status = fmi2Error. If stopTimeDefined = fmi2False, then no final value
of the independent variable is defined and argument stopTime is meaningless.**

If one sets stopTime = start time, computation can still be done, solving initialization etc. but trying to increase the time past the given stop time requires the fmu to return error, if stopTimDefined = True
So giving stopTime = startTime is valid and the behavir is clear, and functions can normaly be called, but any increas in time with setTime/doStep should result in an error being returned.

Setting startTime > stopTime would be invallid in most Fmu's and masters and could easily be checked on both levels. If the FMU returns a warning or an error is curently up to the implementer as return values of functioncalls with illegal arguments is not defined.
However in the rare case that one would develop an FMU that would be able to simulate backwards in time, and one has a master that can simulate such an fmu. Do we want to explicitly forbid it?

**Comment by masoud-najafi** [comment]
Many numerical solvers support backward integration, and it costs nothing to allow backward integration for ModelExchnage. But for CoSimulation, in FMI2.0 it is mentionned that communicationStepSize MUST be >0.0 .

**Comment by chrbertsch** [comment]
@masoud-najafi  could you please provide "real world examples" where backwards in time integration is important?

**Comment by masoud-najafi** [comment]
I do not know much about real world examples. But consider, for example, finding the initial value of a system based on known final values. Another example would be calculating a trajectory passing through a given point x0 which requires a forward integration from x0 and a backward integration from x0 in reverse time. Backward integartion is a standard method to find stability boundaries, unstable manifolds, and unstable equilibrium. If  solvers like Sundials CVODES or LSODA support  the backward integration, it means there are some needs for that. But I have never seen any demand for backward integration with FMU.

**Comment by hyumo** [comment]
One use case would be to roll back to a certain state, like get/set_fmu_state. 

It seems that most tool vendors would *NOT* like to implement get/set_fmu_state(), i.e. due to threading issues etc. However, they are important for reliable co-sim masters. 

Integrating backwards could achieve the same result but without using get/set_fmu_state(). Or instead, users could implement state roll back on their own. 

It's like get_directional_derivatives(), if FMU export tool does not like to implement it, then a user could use implement this function on their own by setting continuous state and getting derivatives.

**Comment by chrbertsch** [comment]
As we cannot demand an FMU exporting tool to support this feature, a new capability flag would be necessary (something like canIntegrateBackwardsInTime) which makes the standard more complicated.

**Comment by hyumo** [comment]
ok, never mind. I will close this issue.
