### ISSUE TITLE
Add numeric variable types (FCP-017)

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#481]
As requested in the [FMI Steering Committee Meeting on Nov 5, 2018](https://github.com/modelica/fmi-design/blob/master/Meetings/2018-11-05-FMI-Steering/minutes.adoc#21-proposal-for-new-numeric-value-types) I've created [a draft for the FCP]( https://github.com/modelica/fmi-design/blob/master/FMI_ChangeProposals/FCP_017_Numeric_Variable_Types/FCP_Numeric_Variable_Types.adoc).

**Comment by pmai** [comment]
Shall I create a corresponding feature branch in fmi-standard with the commits from [fmi3-numeric-variable-types](/pmai/fmi-standard/tree/feature/fmi3-numeric-variable-types)?

**Comment by t-sommer** [comment]
I've created the branch [feature/numeric-variable-types](/modelica/fmi-standard/tree/feature/numeric-variable-types) (without the prefix since all new features go into the next version anyways). I'll make a PR with an updated version of my proposal.

**Comment by chrbertsch** [comment]
I had created a dummy FCP-16  for this topic https://github.com/modelica/fmi-design/tree/master/FMI_ChangeProposals/FCP_016_Data_Types
Now a new FCP-017 has been created: 
https://github.com/modelica/fmi-design/tree/master/FMI_ChangeProposals/FCP_017_Numeric_Variable_Types 
Now we should merge them and delete one of them.

**Comment by t-sommer** [comment]
@chrbertsch I will go through the document and merge it with FCP-017. Thanks for the hint!
