### ISSUE TITLE
Move FCPs to feature branches and use issues

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#487]
The FCP documents contain a lot of valuable information that is closely related to the development that happens on the `feature/*` branches.

Can we move them to the respective feature branches once the working group agrees that they're mature enough?

See also #304.

**Comment by andreas-junghanns** [comment]
I see no real alternative. Do you?

**Comment by t-sommer** [comment]
We should also use issues (with the label `FCP`) to track the FCPs. That way we can easily reference them in other issues. The current `FCP-XXX` numbering (with all the stale FCPs) in the fmi-design repo is confusing.

**Comment by t-sommer** [comment]
Closing this as all FCPs for v3.0 have been merged.
