### ISSUE TITLE
Clean up labels

### ISSUE THREAD

**Issue by KarlWernersson** [modelica/fmi-standard#491]
Hi I was asked to clean up the labels for the issues, the current ones can be viewed here
https://github.com/modelica/fmi-standard/issues/labels

My proposal is to

**bug**: remove, its as standard document not code. What as bug is not rely clear. And bug is not the right word
**CI**: keep (for issues with CI)
**co-simulation**: keep
**discussion**: keep
**documents**: remove, or someone please specify
**duplicate**: keep
**enhancement**: keep
**FCP**: either split into specific fcp numbers or remove
**good first issue**: remove
**help wanted**: remove -> use discussion
**invalid**: remove
**model-exchange**: keep
**needs poll**: remove -> use discussion or vice versa
**remove all priorities**: tickets should be resolved or decided to be moved out of a milestone before the milestone is finished. Priorities is somewhat subjective.
**question**: remove
**reference-fmus**: keep
**specification**: remove since most things are sorted here, and the risk is high for issues missing this label that should have it
**task**:keep
**tbd**:keep
**wontfix**: keep or change to invalid

What are your thought on this?

**Comment by t-sommer** [comment]
Isn't `needs poll` and `tbd` more or less the same (= to be decided at the next meeting)?

**Comment by t-sommer** [comment]
`enhancement` could be renamed to `feature` to be consistent with the branch names (`feature/*`)

**Comment by KarlWernersson** [comment]
Poll (at least how its used in FMI meetings) is a guide to show the general view so for me it more goes into discussion, while tbd is something that shall be decided.
I use tbd as a tag for issues that _I think_ are ready for but needs a decision.

**Comment by beutlich** [comment]
I am in strong favour to keep the GitHub default labels: bug, invalid, enhancement, question, discussion, duplicate

**Comment by t-sommer** [comment]
Since we don't have any code (except for the header files), what is a `bug`?

**Comment by beutlich** [comment]
Fine for me with the following additional comments
* Not sure if tbd and question mean the same thing. I'll let it to you.
* I thought FCP is on issue targeting the FCP process itself, not on concrete FMI change proposals. Since it is currently not used this way, remove it.

**Comment by t-sommer** [comment]
Regarding the FCPs see also #487

**Comment by beutlich** [comment]
> 
> 
> Regarding the FCPs see also #487

Right. But w/o any label to filter.

**Comment by KarlWernersson** [comment]
My intention with the tbd label was to mark them ready for a decision during a meeting. Once the decision is made change the label from tbd to task. 
Tbd is probably not the best name, but the best I could think of at the moment that was short.
If you think question covers that we could use it instead but as I understand it, it is more open.

**Comment by KarlWernersson** [comment]
My English is probably not good enough to give a 100% accurate answer to that question.
Not to be done. that’s more what I have marked as task.
What I mean is ready for decision however that’s not a nice label. The idea is to easily sort things that will be resolved soon one can easily sort those issues and examined to prepare for a meeting, if a 2.0.1 meeting cannot come to a decision maybe the label will be pushed back to discussion?
Work flow Discussion->tbd->task

**Comment by beutlich** [comment]
OK, we need to be more specific then:
* question for unclear topic
* tbd for any undecided topic. I'd rename it to the more familia `needs input` though.

**Comment by pmai** [comment]
On the label discussion itself: I think we should have something like the tbd flag, but call it explicitly Needs Decision (or something like this, that's why I had needs poll) for issues which do not need any kind of general discussions or input anymore but are ripe for a final face to face (phone 2 phone) discussion and decision in the FMI technical meeting (with maybe then escalation to steering comittee, where needed). All issues flagged like this are candidates for the agenda of the next FMI technical meeting.

All in all, with a renaming of tbd to make it more clear, I like @KarlWernersson 's proposal.

**Comment by chrbertsch** [comment]
According to the Regensburg design meeting (see minutes: https://github.com/modelica/fmi-design/tree/master/Meetings/2019-03-06-FMI-Design-Meeting-Regensburg), Torsten will tidy up the labels.

Shall we have  special label for issues like this itself called "infrastructure"?

**Comment by t-sommer** [comment]
I think we can use `CI` for all infrastructure related issues

**Comment by t-sommer** [comment]
Since we moved to polls instead of SC votes, can't we just merge all `tbd` into `needs poll` and use the workflow `discussion` -> `needs poll` (if necessary) -> `task`?

**Comment by chrbertsch** [comment]
The workflow is fine for me.  But we should sort the  `tbd`-labeled issues, if they really need a poll or can be moved to   `discussion` or `tbd`.
`CI` is fine for me (though it would be more intuitive to move the CI-related topics to an `infrastructure` topic. The important thing is that we can differentiate via filters about open issues of the standard and other stuff)

**Comment by t-sommer** [comment]
Okay with me, but I would rather rename `CI` to `infrastructure` instead of having two.

**Comment by chrbertsch** [comment]
OK.
I would keep the `help wanted`, as it especially can be used for large tasks.

**Comment by chrbertsch** [comment]
Regular design meeting: 
Move tbd to discussion.
Move specification to documents

**Comment by chrbertsch** [comment]
Rename CI to infrastructure

**Comment by chrbertsch** [comment]
Proposal to remove the labels for old Design meeting (e.g. Lund2019).

**Comment by chrbertsch** [comment]
Proposing to delete the following labels:

- Lund 2019
- DesignMeetingRenningen2019
- co-simulation (as we otherwise would also need many similar labels)
- specification (as we have documents)

And keeping the rest.

Any objections?

**Comment by andreas-junghanns** [comment]
> Proposing to delete the following labels:
...
> Any objections?

Agreed.

**Comment by chrbertsch** [comment]
Done
