### ISSUE TITLE
Clarification on setting variables with causality 'output'

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#493]
In the fmi2.0 standrad, is it allowed to change the value of variables with causality "output" using fmi2SetXXX APIs. This has been authorized in tables at page 105 and the state-machine in page 103. inside "instantiated" and "initialization" modes.  This is kind of weired to allow setting directly variables that are normally get computed as a function of input variables and other parameters.
I would like to know if it is a bug or a feature?

**Comment by KarlWernersson** [comment]
This is a feature.
Note that it also requires the output to have a start value with fixed = exact, (or approx before initialization)
Outputs without start value cannot be set.

**Comment by chrbertsch** [comment]
Closing due to no protest to Karl's answer.. If someone disagrees or sees need for clarification please re-open.
