### ISSUE TITLE
Deprecated capability flag canSignalEvents of FMU CS 1.0.1

### ISSUE THREAD

**Issue by beutlich** [modelica/fmi-standard#520]
The image on [page 34](https://svn.modelica.org/fmi/branches/public/specifications/v1.0/FMI_for_CoSimulation_v1.0.1.pdf#page34) of the FMI CS 1.0.1 specification still displays the canSignalEvents capability flag though it has been removed from the subsequent table.

**Comment by chrbertsch** [comment]
@t-sommer : should we create a milestone v1.0.2 for this? (not believing that we will ever release it; but people could filter the issues and thus find out about bugs in v1.0.1

**Comment by andreas-junghanns** [comment]
Why not create such a milestone? I like the idea to collect these issues in this way.

**Comment by chrbertsch** [comment]
fixing with https://github.com/modelica/fmi-design/commit/5a2c112f20f40007deb70e2488b3d94ac7efbcc2 - not expecting ever a release of 1.0.2 ...
