### ISSUE TITLE
Simplify dependenciesKind

### ISSUE THREAD

**Issue by klausschuch** [modelica/fmi-standard#521]
The dependency kinds "constant", "fixed", "tunable" and "discrete" are not necessary.
This information can be taken from the referenced variable.
There should only be two kinds: "dependent" and "linear"

**Comment by chrbertsch** [comment]
Discussion in Meeting 11.1.2019
Klaus: Can this information anyway be taken from the referenced variable?
Karl: Have to think about it
Klaus: I am mainly referring to section 2.2; 
Karl: we would remove information; one cannot find it from the variables
Klaus: In DCP this was discussed, there we only have dependent and linear. I think I was wrong with this issue. I will discuss this in the DCP group

**Comment by klausschuch** [comment]
The simplification would induce a loss of information. The information cannot be taken from the referenced variable. The dependency kinds  "constant", "fixed", "tunable" and "discrete" specifies the variability of the factor $p$ of the linear equation $y = p * v$ where $y$ is the unknown and $v$ is the known.

The topic has been discussed in the DCP group: For DCP, the initial dependencies are more important than the run-time dependencies. DCP will only define "dependent" and "linear", and not provide further details about the factor p. This is in line with the InitialUnknowns for FMI. The name "linear" instead of constant will be used.

**Comment by KarlWernersson** [comment]
Just a question regarding dcp.
would not linear cover all three of constant, fixed and tunable? And dependent would discrete and dependent?

**Comment by klausschuch** [comment]
@KarlWernersson 
Yes, we did not change anything in the dcp specification because linear and dependent should sufficient for a typical dcp use case.
There the dependency information is basically necessary during initialization. Hence, it is irrelevant if the variability of the linear factor is constant, fixed, or tunable.
