### ISSUE TITLE
Clarify wording on unique value references

### ISSUE THREAD

**Issue by pmai** [modelica/fmi-standard#522]
As discussed in WebMeeting on 2019-01-11, the current wording on uniqueness of value references can be misunderstood to disallow aliases. Also there is still wording in the document that states that the combination of type and vr are unique.

**Comment by nickbattle** [comment]
I couldn't find the notes of the WebMeeting in fmi-design, but could you clarify the point above about uniqueness - is the intention now that an fmi3ValueReference is unique across all variables?

I note that the logger #ref# format has dropped the type qualifier, which is consistent with such unique references, but as it says above, there are still multiple places in the document where uniqueness is stated to be VR+type.

**Comment by chrbertsch** [comment]
@nickbattle : this issue _are_ the notes of this discussion on this issue in the FMI design webmeeting :-)

Yes, the intention is that value references are unique across all variables (this was discussed and decided at several FMI meetings, and is related with dropping the variable _index_.)

The "wording in the document that states that the combination of type and vr are unique" is wrong and must be corrected.

**Comment by nickbattle** [comment]
@chrbertsch Ah, now I understand :-)

OK, thank you for the clarification. That will considerably simplify the formal modelling - this aspect was quite complicated in the FMI2 model.

**Comment by chrbertsch** [comment]
superseded by #807
