### ISSUE TITLE
change links to documents still to "old" svn to point to github (or copy resources to here)

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#524]
E.g. https://svn.fmi-standard.org/fmi/branches/public/FMI_CCLA_v1.0_2016_06_21.pdf is one such link.

**Comment by chrbertsch** [comment]
@andreas-junghanns Is this w.r.t. to the standard documemnt or the website? Then we should move the ticket there

**Comment by andreas-junghanns** [comment]
The web-site is what I had in mind.

**Comment by t-sommer** [comment]
@andreas-junghanns, can we close this in favor of [fmi-standard.org #137](https://github.com/modelica/fmi-standard.org/issues/137)?
