### ISSUE TITLE
Use (unique) variable reference instead of index

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#527]
It was decided to get rid of the index and use a unique value reference instead.
(Could someone provide a link to when this was decided? In the Roanne design meeting?)

In the current draft version of the the 3.0 standard, still the index is used in many places, e.g.
* Variable definition: https://fmi-standard.org/docs/3.0-dev/#_definition_of_model_variables_modelvariables
* Model structure: https://fmi-standard.org/docs/3.0-dev/#_definition_of_the_model_structure_modelstructure

**Comment by klausschuch** [comment]
The current draft still describes the indices because #528 is not fixed yet.
It was discussed in the Munich Meeting at ITK Nov 2017. Unfortunately, it is only briefly mentioned in the minutes of the meeting.

**Comment by chrbertsch** [comment]
#528 is fixed already.
@klausschuch and @t-sommer:  Can we close this ticket now?
