### ISSUE TITLE
Add rationale information for array FCP design to standard

### ISSUE THREAD

**Issue by pmai** [modelica/fmi-standard#529]
As discussed in #512 more rationale information on the design of the new array API needs to be added as non-normative text to the standard.

**Comment by chrbertsch** [comment]
@pmai , @klausschuch and others: is this still valid? 
Please list, what is missing

Otherwise, I propose to close this

**Comment by chrbertsch** [comment]
Regular design webmeeting: 

add rationale for nvalues (--> ensure memory safety, other things still can get wrong)

[This information can be used to prevent access violations]

**Comment by chrbertsch** [comment]
Ticket-viewing-meeting

@klausschuch : I will look into this

**Comment by chrbertsch** [comment]
FMI Design meeting: @klausschuch I will create a PR today.

**Comment by andreas-junghanns** [comment]
Fixed in https://github.com/modelica/fmi-standard/pull/1272/commits/2fbb798015828cbe5e7e734f48bcde343f76d2fb in #1272.
Closing here because the 10 issues that can be linked to a PR has been reached.
