### ISSUE TITLE
Rework fmi3Discard mechanism for DoStep

### ISSUE THREAD

**Issue by pmai** [modelica/fmi-standard#535]
As discussed in the design meeting on 2019-02-13:

The current definition of fmi3Discard only allows restarting of the calculation if full-fledged fmi3Get/SetFMUState support is present. Since fmi3SetFMUState can already be called in terminated/error state, fmi3Discard does not provide more of a potential mechanism for resuming than fmi3Error (except for the indication of the actual reason for the error).

However it is rather more likely that implementations can more easily support reseting the FMU state to the state when entering the fmi3DoStep on a failed step, than having full fledged fmi3SetFMUState support.

Therefore the definitions should be changed, so that:

- fmi3DoStep returning fmi3Discard means the FMU has ensured that the state is unchanged from entering the fmi3DoStep call, so the FMU remains in step state, and a new fmi3DoStep call starting from the original time can be called.
- FMUs that cannot support this must return fmi3Error, which auto-transitions to terminated state, but still allows fmi3SetFMUState to restart the FMU.

To be decided: Add a new fmi3-Return Value to indicate that the failed fmi3DoStep is due to not being able to complete the step, and not some other error (e.g. fmi3StepFailed).

**Comment by APillekeit** [comment]
FMI Design Meeting in Regensburg:
Discussion points:
- fmi3Discard gets a new meaning: last communication step is rolled back internally by the FMU. The master can call doStep() again from last communication point time.
- add fmi3StepFailed for the case that the FMU can not roll back internally. The internal time is undefined. 

The side effects have to be discussed in more detail.

**Comment by chrbertsch** [comment]
@KarlWernersson :  will write down a solution discussed in Regensburg

**Comment by KarlWernersson** [comment]
Disregarding asynchronous doStep, the concept of fmiDsicard after a doStep  in Fmi2 is actually an earlyReturn where you cannot continue the simulation from. When doStep returns discard you end up in stepFaild that we accidentally removed from the new statemachine in fmi3. In fmi2 two cases can get you into this state. Either an internal Termination is called. E.g.  the modelica function terminate, or anything else is causing the simulation to fail. The second case doesn’t in practical differ much from an fmiError except that you can retrieve the last successful time. And you are at least implicitly supposed to be able to retrieve the values at that time instance, while error also allows you to return values it does not give any of those implicit guarantees. But that diference is not realy cleary defined.

During the meeting in Regensburg, I @TorstenBlochwitz and @andreas-junghanns  had a short meeting and came up with the following solution,
A Third state in addition to stepMode and eventMode, earlyReturnMode. So when an doStep returns fmiDiscard, you have ended up in early returnMode. From this mode and fmu can go to stepMode, eventMode or terminate,  An fmi3 Fmu that has the same features as an fmi2 Fmu would only be able to go to terminate from this state. You would only need an additional Boolean that says if it can continue to simulate form this early return you have to terminate.
With this the Fmu could signal that a full restart is possible by giving the last successful time to the start of the doStep and signaling that it can continue. But this solution would be more flexible as it could give the current time and let you continue from there, e.g. when you extrapolated your input derivatives they have now moved in to area where they are undefined and you need to set new ones. 

This should easily be combined with the hybridCosim, so you basically only have one type and then different level of feature support. Where only supporting the minimum set of features would be functional similar to a fmi2 co-simulation. 
And the getStatusFunctions can be removed and entered in intermediateStepInfo

One thing to clear out is how is then fmiDiscard interacting with the intermediateStepInfo.willDoEarlyReturn. Is there a use for both? Or should one be scraped for the other?

Pleas correct me if I missed something @andreas-junghanns @TorstenBlochwitz

**Comment by KarlWernersson** [comment]
---------------                                    --------------- 
     |              |  <--- EnterStepMode-------------- |              |
     |  StepMode    | -------------EnterEventMode-->    |  EventMode   |
     |              | <----                  -------->  | 
     ---------------       |                |          ---------------
           |  EnterStepMode|                |  EnterEventMode   |           
           |fmiDiscard     |                |                   |  fmiDiscard       
           |               --------------- --                   |           
            ------------>  |                |   <----------------      
                           |    EarlyReturn |                             
                   ------  |       Mode     |                             
      fmiTerminate |          ------------------                             
                   V

**Comment by masoud-najafi** [comment]
What does Discard mean for Event mode and event iterations? If a Discard is allowed in EventMode, the same should hold for ModelExchnage too.

**Comment by KarlWernersson** [comment]
You are correct there should probably not be a discard from the eventMode, i was a bit quick when making the ascii art, i will update the "state graph"

**Comment by KarlWernersson** [comment]
Note that event mode also have the option of forced termination from the fmu with the eventInfo.terminateSimulation. While stepMode only has voluntarily paths to terminate.

**Comment by masoud-najafi** [comment]
I wonder, if it has been decided if fmi3IntermediateStepFinished() callback is optional or mandatory?
If it is optional, we need a getStatus-like function to retrieve 1)EventTime in case of earlyReturn 2) LastSuccessfulTime in case of return from StepMode by a fmi3Discard.

**Comment by chrbertsch** [comment]
Regular Design Meeting: 
The Callback function is mandatory. 
(The FMU can call it, when it wants to transport information. Masoud will give an example what to clarify)

**Comment by masoud-najafi** [comment]
In FMI-2.0 , the main arguments of fmi3DoStep() are `currentCommunicationPoint` and `communicationStepSize`. They indicate the communication points between the master and the FMU/CS.
It is quit common that mesh-points (or definitive points or finished points or intermediate completed steps or whatever) of the internal FMU solver do not coincide with the communication points. I.e., if `cp(i)=currentCommunicationPoint` and `cp(i+1)=cp(i)+communicationStepSize`, then in FMI-2.0,  it may happen that the internal solver of the FMU exceeds `cp(i+1)` and computes and returns the FMU outputs at `cp(i+1)` by interpolation. The only exception is when fmi2DoStep returns with fmi2Discard.

In FMI-3.0, several features including, early return, events, clocks and in particular IOV have been introduced that require invoking the `fmi3IntermediateStepFinished()` callback. The callback is called at event times, at solver mesh-points as well as at intermediate try points. 

Now my question is to clarify if the same independence between internal FMU solver mesh-points and the  communication points can be kept in FMI-3.0? 
 
![communication_syncho](https://user-images.githubusercontent.com/33484393/56901374-4d8a6700-6a98-11e9-9002-d73c3f57efdc.png)

If yes, then when fmi3DoStep is called for the interval [cp(i), cp(i+1)], should the callback be invoked at C2 and C3, and/or at cp(i+1)? Note that cp(i+1) may be neither a meshpoint nor a try (temporary intermediate) point.

If No, then in FMI-3.0, the master needs to force the FMU internal solver to synchronize its internal steps with communication points.

**Comment by jph-tavella** [comment]
As explained by Masoud, in FMI-3.0, the fmi3IntermediateStepFinished() callback is used by the FMU at internal solver mesh-points or intermediate try points.
According to the given example, when fmi3DoStep() is called for the interval [cp(i), cp(i+1)], it is quite sure that cp(i+1) will not coincide with internal solver points but the FMU knows by advance (I mean from time i) that cp(i+1) will be a new intermediate point to be taken in account by its solver so i+1 becomes a new internal event time and this should suggest that the callback is to be invoked at C2 and cp(i+1).

**Comment by masoud-najafi** [comment]
So in this situation the callback should be called at cp(i+1) with this fmi3IntermediateStepInfo values:
intermediateStepTime->cp(I+1)
eventOccurred->False (unless there is really an event)
clocksTicked->False (unless there is really a clock tick)
intermediateVariableSetAllowed->FALSE
intermediateVariableGetAllowed->TRUE
internalStepFinished->FALSE (unless cp(i+1) coincides C3)
canDoEarlyReturn->False
willDoEarlyReturn->TRUE

**Comment by APillekeit** [comment]
I have to admit that I currently may not see the details of the described supposedly problematic situation. Nevertheless I'm not sure if the described combination is possible for
internalStepFinished->FALSE 
canDoEarlyReturn->False
willDoEarlyReturn->TRUE

My understanding is that an early return is only conducted if "internalStepFinished" equals True because if not, the solver of the FMU is in an internal intermediate state that only allows to provide variable values for certain outputs or inputs. But an early return would require the handling of all variables for this intermediateStepTime time instant after returning from doStep() which is then the communicationpoint time instant.

Also, if an FMU signals "willDoEarlyReturn" it also "CanDoEarlyReturn". The only meaningful compibations in my view are:
a) canDoEarlyReturn->True and willDoEarlyReturn->False (Master could command the FMU to early return at this intermediateStepTime instant)
b) canDoEarlyReturn->False and willDoEarlyReturn->False
c) canDoEarlyReturn->True and willDoEarlyReturn->True (FMU tells the Master that it is about to do an early return at this intermediateStepTime)

**Comment by masoud-najafi** [comment]
I think this is not the right ticket to discuss about it. Let's move it to another IOV related ticket.

**Comment by jbernalr** [comment]
If this issue covers finalization of cs and me state machines, could you please consider this question/open-point as well?: https://github.com/APillekeit/fmi-standard/issues/4

**Comment by chrbertsch** [comment]
Regular design webmeeting

Already included in merged Hybrid CS State machine PR
