### ISSUE TITLE
Clarification of AsciiDoc formating

### ISSUE THREAD

**Issue by APillekeit** [modelica/fmi-standard#544]
first issue:

In the standard documentation it is in many cases required to describe "is equal to" relationships in case of XML attributes or general values e.g. return values of functions.

The proposal made at the FMI design meeting in Regensburg (March 2019) was to use natural language as much as possible.

examples: 
...if `variablity` equals `constant`, then...
...if `variablity` equals `constant` or `fixed`, then...
...if the return value of `fmi3Instantiate()` equals `NULL`, then...

This should be added to the contributer guidlines

**Comment by chrbertsch** [comment]
I am sceptical if we really should implement this.

Almost all occurances of the  such "equalities" are not like

...if `variablity ` =`constant,` then...

but like

...with `variablity` = `constant`. 

What would be a compact natural language description be for that?

...with `variablity` equaling `constant`.   (This sounds wrong. How would a native speaker express this?)

So I propose not to do this and close this ticket.

**Comment by APillekeit** [comment]
> What would be a compact natural language description be for that?
> ...with variablity equaling constant.   (This sounds wrong. How would a native speaker express this?)

I would suggest in this case: 
... with variability is constant. 
... with variability is set to constant. 
or something similar.

This is not important for me at all. 

Nevertheless, I would have saved time by ignoring the design meeting decision. I have made changes to the documentation based on this decision in the past. These changes may be reverted where applicable. 

I do not invest additional time.
