### ISSUE TITLE
Consistency between Modelica language external functions, and source code FMUs

### ISSUE THREAD

**Issue by hubertus65** [modelica/fmi-standard#545]
For all Modelica tools, it should be possible to generate a source code FMU from Modelica. Therefore, source code FMUs should allow at least the same languages as the Modelica external function interface. 

This will also have consequences for Modelica Libraries, where sources for external dependencies are not always included. This is handled separately in the Modelica specification repo.

**Comment by hubertus65** [comment]
For reference, here is the text from the Modelica external function interface. Unfortunately, in latex source, but probably still readable. 
\section{External Function Interface}\doublelabel{external-function-interface}

Here, the word function is used to refer to an arbitrary external
routine, whether or not the routine has a return value or returns its
result via output parameters (or both). The Modelica external function
call interface provides the following:

\begin{itemize}
\item
  Support for external functions written in C (specifically C89) and
  FORTRAN 77. Other languages, e.g. C++ and Fortran 90, may be supported
  in the future, and provided the function is link-compatible with C89
  or FORTRAN 77 it can be written in any language.
\item
  Mapping of argument types from Modelica to the target language and
  back.
\item
  Natural type conversion rules in the sense that there is a mapping
  from Modelica to standard libraries of the target language.
\item
  Handling arbitrary parameter order for the external function.
\item
  Passing arrays to and from external functions where the dimension
  sizes are passed as explicit integer parameters.
\item
  Handling of external function parameters which are used both for input
  and output, by passing an output that has a declaration assignment to
  the external function. {[}\emph{Declaration assignments are executed
  prior to calling the external function.}{]}
\end{itemize}

The format of an external function declaration is as follows.

\begin{lstlisting}[language=grammar]
function IDENT string-comment
  { component-clause ";" }
  [ protected { component-clause ";" } ]
  external [ language-specification ] [
  external-function-call ] [annotation ] ";"
  [ annotation ";" ]
end IDENT;
\end{lstlisting}
Components in the public part of an external function declaration shall
be declared either as input or output. {[}\emph{This is just as for any
other function. The components in the protected part allow local
variables for temporary storage to be declared.}{]}

The language-specification must currently be one of "builtin", "C",
"C\ldots{}" (for one of the specific C-standards like C89, C99, and C11
-- which specifies that it relies on the C standard library of that
version) or "FORTRAN 77". Unless the external language is specified, it
is assumed to be "C". \emph{{[}The intended use of e.g. "C99" is to
detect if the user tries to link with a C99-function using a C89
compiler.{]} }

The "builtin" specification is only used for functions that are defined
to be built-in in Modelica. The external-function call mechanism for
"builtin" functions is implementation-defined. {[}\emph{Typically, for
functions from the standard C-library, the prototype of the function is
provided but no library annotation. Currently, there are no other
builtin functions defined in Modelica.}{]}

{[}\emph{Example}:

\begin{lstlisting}[language=modelica]
package Modelica
  package Math
    function sin
      input Real x;
      output Real y;
      external "builtin" y=sin(x);
    end sin;
  end Math;
end Modelica;

model UserModel
  parameter Real p=Modelica.Math.sin(2);
end UserModel;
\end{lstlisting}
{]}

The external-function-call specification allows functions whose
prototypes do not match the default assumptions as defined below to be
called. It also gives the name used to call the external function. If
the external call is not given explicitly, this name is assumed to be
the same as the Modelica name.

The only permissible kinds of expressions in the argument list are
component references, scalar constants, and the function size applied to
an array and a constant dimension number. The annotations are used to
pass additional information to the compiler when necessary.

A component reference to a component that is part of an input or output
is treated the same way as a top-level input or output in the external
call.

**Comment by chrbertsch** [comment]
Would this really mean support Fotran 77 source code, or should C source code be able to reference (compiled) libraries that have been implemented in Fortran (e.g., LAPACK)?

**Comment by chrbertsch** [comment]
Regular design webmeeting:
Karl: do not think that all Modelica tools can deal with Fortran code. It is  good to have the same as Modelica.
Pierre: One needs to be able to compile it. Do not think the Fortran77 issue is a problem at all, as it is compiled via C anyway today. 
Could be interesting for newer Fortran or C++
No need for FMI 3.0.
@APillekeit .: I think we allow C++ and mark this with a language attribute. I do not know if there are toolchains that support Fortrain. I do currently not see the need. I will ask @IZacharias again.
@hubertus65 : is this a real need for you or nice to have?

**Comment by chrbertsch** [comment]
Regular design webmeeting: 
Andreas P. : Inrina told me there will be an attribute language and language version. (C, C++, Fortran and a version.) Irina is aware of the Modelica specification demands.
Christian: in the future a source code FMU might not only contain C-Code
Andreas P.:do we really need Fortran support?
Klaus: Why Fortran? Why C++? And why not other languages?
Karl: Those two are supported in the Modelica Specification
Andreas. P.: We need a discussion in the larger group which languages to support. Also what the users would like to have.
Karl: If we allow something, some users will use it.

**Comment by chrbertsch** [comment]
@IZacharias  and @hubertus65 : Could you please discuss this and come up with a proposal for the Design meeting next week? Thanks!

**Comment by IZacharias** [comment]
FMI design meeting in Renningen:
Andreas: Who cares about Fortran source code FMUs?
Nobody raised his hand.

Pierre: We would raise expections if we allow this, which might be hard to solve.
Andreas: We should recommend, to use f2c for Fortran. I propose to decide to not include Fortran and to to concentrate on the more important questions: which version of C do we support.

Poll: Should Fortran be mentioned as one of the supported languages for source code FMUs?
In favor: 0
Against: 16
Abstain: 3

Decision: Fortran will not be mentioned as one of the supported languages for source code FMUs

**Comment by chrbertsch** [comment]
As we decided not to mention Fortran: Is there anything left after https://github.com/modelica/fmi-standard/pull/582 or can we close this?

**Comment by chrbertsch** [comment]
closing in regular design meeting
