### ISSUE TITLE
ME connected Test-FMUs: Move from SVN to Github?

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#548]
As we already have moved most of the FMI material from the SVN to github repos, and plan to get away with the SVN  at the last FMI Design meeting we discussed what to do with the FMI 2.0 ME Test FMU https://svn.modelica.org/fmi/branches/public/Test_FMUs/FMIModelicaTest/ . 

I consider it imporatant that they stay available to the public.

Will the SVN be deactivated in the (near) future?

There are different options: 
* One idea was to zip them and provide them “as is” for download somewhere. (In case they will not change any more, they are 216 Mbyte)
* Another was to put them in a (separate?) github repository. Would you,  @MartinOtter be the maintainer in that cases?
* One could also included them in the XC repository (in a new subdirectory,  as it not intended to run them in the XC, which currently only runs for single FMUs), perhaps https://github.com/modelica/fmi-cross-check/

As the test FMUs have been created with Dymola, they should be uploaded to the new location by someone from Dassault systems ( @KarlWernersson : could you assist in this?) or with written consent of Dassault Systems to comply with Dassault's license conditions regarding distribution of FMUs.

**Comment by chrbertsch** [comment]
If the SVN is not disabled soon, we could also just re-add a link to the location on SVN, see https://github.com/modelica/fmi-standard.org/pull/138

**Comment by KarlWernersson** [comment]
I can generate a new batch of FMU's  based on the modelica files once we decide where to put them =)

**Comment by chrbertsch** [comment]
As an intermediate soluation, the link to the SVN location of the files has once again been added to the website, https://github.com/modelica/fmi-standard.org/commit/d70b0b8df745c4e7be175b74df5cb2d2cd403575

**Comment by chrbertsch** [comment]
Closing for now, can be re-opened when there are plans to shut down the SVN.
