### ISSUE TITLE
List internal solver information for FMU-CS in FMI3.0

### ISSUE THREAD

**Issue by meek1** [modelica/fmi-standard#557]
Provide solver information in xml for co-simulation FMUs, i.e. solver name, tolerance, step size, etc.

**Comment by chrbertsch** [comment]
@meek1: could please be more specific what you would propose?
Tolerance and preferred communication stepsize are already present.
Solver name: Would this be a string (could already be done in a vendor annotation) or would you like to define names? Then I would not see it in FMI, but perhaps in a layered , as the names of solvers will differ massively from tool to tool (exception perhaps CVODE). 
How would you make use of this information?

**Comment by meek1** [comment]
When a FMI composite model including one or more co-simulation FMUs doesn't work as expected it might be of interest to know what internal solvers are used, and what are the default tolerences and (if applicable) the internal fixed step size.

This could already be done in vendor annotation, Dymola seem to somtimes include solver info in the generationTool tag. However not for all solvers, for example not for Cvode. If a separate solver info tag would be available, then the users' chances of getting solver info increases. Solver name should be a (human readable) string, but the FMI standard should not specify which solver names are allowed etc. The FMI compliance checker or cross checker should validate that there is actually a string for FMU-CS.

**Comment by chrbertsch** [comment]
Regular design meeting: in SSP there was a proposal to have solver names, but it got removed.

Could we include this in the default experiment? https://fmi-standard.org/docs/3.0-dev/#DefaultExperiment ?

Other information in the default experiment is used for the master to set values. 
Default experiment is also used for ME. 

Could this be an attribute in the CoSimulation Tag?

Solver names could already be included in the description string.

Solver parameters could be changed as parameters.

It cannot be mandatory:  some CS do not have a solver

**Proposal: an optional attribute solverInformation  in the  CoSimulation Tag (a human readable string)**

It could also be a VendorAnnotation

Kaska: it might be useful to set up a co-simulation

(Masoud: might be useful in ME, if the model needs a specific solver)

Pierre: It would be helpful to have a structure (should be coordinated with SSP)

Klaus: for SSP, especially for ME FMUs, one would need more structured information.

Pierre: if from SSP there comes a proposal we shall revisit this.

Karl: one could have variable FMUs inside the FMU with different solver

Pierre: we could create a call between FMI and SSP group.  --> Pierre

**Comment by chrbertsch** [comment]
Could be extended to ME.

**Comment by chrbertsch** [comment]
Regular design meeting: Wait for SSP proposal

**Comment by andreas-junghanns** [comment]
We have since introduced fixedInternalStepSize in the modelDescription.xml and that is likely as much as we should expose to importers. The beauty of FMI is that we can hide such information and expose only what is required for the importer to run efficiently.
Please reopen, if you have a clear use case and PR for additional information required.
