### ISSUE TITLE
FMI 3.0: SimpleType -> Type

### ISSUE THREAD

**Issue by MartinOtter** [modelica/fmi-standard#560]
The fmi3ModelicaDescription.xsd file contains the element "TypeDefinitions / SimpleType". Please, change to "TypeDefinitions / **Type**". The reason is that in the future non-simple types might be added, such as fixed-size arrays (e.g. vector with 3 elements used by a multi-body model) or records. It might be even meaningful to already add for FMI 3.0 fixed-size array types.

**Comment by chrbertsch** [comment]
see #561  --> the SimpleType tag will disappear

**Comment by chrbertsch** [comment]
@MartinOtter , @pmai , @andreas-junghanns  or others:  
Could someone with more xsd-knowledge than I please check:

In FMI 3.0 I do no longer see "TypeDefinitions / SimpleType", but the definition in https://github.com/modelica/fmi-standard/blob/master/schema/fmi3ModelDescription.xsd references https://github.com/modelica/fmi-standard/blob/master/schema/fmi3Type.xsd.

So is this issue still there?
Shall we change something for FMI 3.0?`Then please create a PR.

**Comment by andreas-junghanns** [comment]
"TypeDefinitions / SimpleType" are gone from the .xsd files.
We still have a few obsolete mentions that will be removed once we have the new schemas linked here Issue #569 deals with this update effort (including the images of the schema).
Closing this.
