### ISSUE TITLE
FMI 3.0: TypeDefinitions and ModelVariables have a different definition style

### ISSUE THREAD

**Issue by MartinOtter** [modelica/fmi-standard#561]
In ModelVariables a new variable is defined as:

```
<ModelVariables>
   <Float64 name = "var1"/>
   <Float64 name = "var2"/>
</ModelVariables>
``` 

However, in TypeDefinitions a new type is defined as:

```
<TypeDefinitions>
   <SimpleType name = "Mass">
         <Float64 unit="kg"/>
  </SimpleType>
   <SimpleType name = "Velocity">
         <Float64 unit="m/s"/>
  </SimpleType>
</TypeDefinitions>
``` 

It would be better to use the same style as for ModelVariables and define a type more compactly as:

```
<TypeDefinitions>
   <Float64 name = "Mass" unit="kg"/>
   <Float64 name = "Velocity" unit="m/s"/>
</TypeDefinitions>
```

**Comment by chrbertsch** [comment]
FMI Regular design meeting: 
Makes sense to do this consistently. 
This will also change the modeldescription.xml

Is there a problem that we define a mass for 64bit and 32bit?
It must be unique over the data type. (has to be described in the documentation.)

Use same inheritance for types as for variables as proposed.

Torsten S. will try this out in fmpy and test fmus
