### ISSUE TITLE
dead-link in specification (http://www.cscapes.org/coloringpage/)

### ISSUE THREAD

**Issue by klausschuch** [modelica/fmi-standard#564]
The specification contains a link to an outdated web-page (http://www.cscapes.org/coloringpage/)
This dead-link leads to a failure of the ci-tests.
The linked project seems to be available at https://github.com/CSCsw/ColPack now.
There they even mention:
"The best source for citing this work
Assefaw H. Gebremedhin, Duc Nguyen, Mostofa Ali Patwary, and Alex Pothen, ColPack: Graph coloring software for derivative computation and beyond, ACM Transactions on Mathematical Software, 40 (1), 30 pp., 2013."

**Comment by chrbertsch** [comment]
Close as alredy fixed and merged.

**Comment by klausschuch** [comment]
The issue wasn't closed intentionally.
Only the dead link got fixed by the commit.

We might change the specification text to use "The best source for citing this work".
