### ISSUE TITLE
Regularly create tags for development milestones

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#576]
It would greatly simplify the synchronization between FMI 3.0 prototypes if we could assign fixed versions strings to the modelDescription.xml and create tags when the schema or header files are changed e.g.

```xml
<fmiModelDescription fmiVersion="3.0-alpha.1" ...>
```

Following the rules for [semantic versioning](https://semver.org/) the tags would look like:

- `v3.0-alpha.1` (fist alpha version)
- `v3.0-alpha.2` (second alpha version)
- ...
- `v3.0-beta.3` (third beta version)
- ...
- `v3.0-rc.1` (first release candidate)
- ...
- `v3.0` (release)

During the alpha phase features can still be added, changed or removed.

**Comment by chrbertsch** [comment]
Agreed on at Design Meeting.
Add comment in README

**Comment by andreas-junghanns** [comment]
We do this now, almost regularly. This ticket does not help to remind but started the habit.
I consider this the primary purpose of this ticket and close it as accomplished.
Re-open if you disagree.
