### ISSUE TITLE
Re-factor FMI Standard text considering RFC 2119 before release

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#583]
Once the Pull requests have been merged, the complete text shall be re-factored using the wording of RFC 2119, see #581

**Comment by martinrosingetas** [comment]
Hello @chrbertsch @t-sommer , this task seems to be pending. What is its current state?

**Comment by chrbertsch** [comment]
> Hello @chrbertsch @t-sommer , this task seems to be pending. What is its current state?

As there are still major text changes and extension to be done, i think this rework should be done at a later point  of time.

**Comment by martinrosingetas** [comment]
The current text contains several requirements that are written using "will" or "can". These words/phrases aren't defined in RFC2119. 

I suspect that a refactoring of the text may lead to some subsequent discussions about the appropriate strictness level of those requirements.

I think that refactoring the existing text _early_ offers several benefits:
* Discussions about ambiguous strictness levels of requirements take place early.
* If a future PR uses terms that are undefined in RFC2119, we will fix those issues during the discussion of the PR - and not many months later in a general refactoring.

A final check against RFC2119 before publication is needed anyway.

**Comment by chrbertsch** [comment]
Ticket-view-meeting

Andreas: can be done at the very end. Language checking by a native speaker this could be screwed up.
Torsten: **Should be done at the write-fest**
Klaus: in SSP it is written in upper-case to make people aware
Torsten: this looks strange
Klaus: Italic looks better
Andreas: Italic is used for non-normative.
Andreas: **Underline could work.** There are two tasks: 
1) Re-formulating the whole text using the text
2) Re-formatting with search-and-replace (easy and can be done at the end)

**Comment by andreas-junghanns** [comment]
This needs to stay open as a reminder until we release.

**Comment by chrbertsch** [comment]
Regular Design Meeting: 

Andreas: I could do it, but  could you @pmai  help me, as I have no experience?
TorstenS: Is this also about the formatting? I do not like the upper-case bold, as this is not so well readable
Andreas: we should e.g. replace "should"
Pierre: this formatting makes clear, where you want the clearly defined wording?
TorstenS: we could just replace any wrong wording
Pierre:: Experience tells this is hard enough
TorstenS: Could we perhaps first list examples where the problems are?
Andreas: Shall "should" be in the non-normative text?
Pierre:  https://datatracker.ietf.org/doc/html/rfc2119 gives a meaning to "should"
Pierre: we should go through a section of the standard and mark unclear usage of verbs. This makes sense anyway. Readabbility makes sense also. 
Claudio: we could start with the common concepts
Andreas: We first need an educational phase. This can be done in parallel to protyping.
Pierre: I will pick a section and show it.

**Comment by chrbertsch** [comment]
Webmeeting: 
Pierre: If we want to do this, we should start this now.
Torsten: with the refactored text this **SHOULD** be possible.
Pierre: this could done step by step. We could start with a subsection.  We should note on which sections we have done this already. I would volunteer to review it, if someone else starts.

**Comment by andreas-junghanns** [comment]
Web-design meeting:
TorstenS: we should not refactor to have all upper-case/bold, just mention it in 1.4.
