### ISSUE TITLE
FCP_018: Add specified extra meta-data directory to FMU ZIP archive structure

### ISSUE THREAD

**Issue by pmai** [modelica/fmi-standard#585]
The SSP standard added a specified location for additional meta-data to SSP packages in the form of an `extra` directory with sub-directories using reverse domain notation. This allows tools handling SSPs (including but not restricted to SSP creators) to read, add, modify or delete additional meta-data to the SSP that should travel with the SSP in a specified location that avoids clashes and clearly states processing expectations. This mechanism can be used for layered standards and other domain-specific solutions, similar to, but going beyond, the (vendor) annotation mechanism.

This FCP proposes to add the same mechanism to FMI 3.0 for FMUs, in exactly the same way.

This can for example be used to add standardized meta-data, like the SMMD format meta-data to FMUs in a direct way, but it can also be useful for many other extensions.

A pull request with the actual wording change is upcoming.

**Comment by masoud-najafi** [comment]
Could this new directory be used as a folder for storing generated data by the FMU?

**Comment by chrbertsch** [comment]
This proposal for a new subfolder in the FMU zip-File shall also be aligned with the proposal for an `eFMU` container from the EMPHYSIS project.  One could use `extra/eFMU`
I will forward this ticket to the EMPHYSIS Project. 

A general question: Without this FCP: is an FMU containing a subfolder in the zip-File that is not mentioned in the specification a valid FMU? Or would this only be allowed for subfolders of the docuementation folder (that could contain any content)?

**Comment by pmai** [comment]
@masoud-najafi The FMU has no way of storing stuff somewhere into the FMU, since it will only have access to the unpacked (parts) of the content. There is no requirement that FMU importers update the FMU from stuff written to the unpacked parts.

Also, if the FMU wants to access stuff at runtime, it has to place it into resources, since that's the only part that is required to be available.

**Comment by pmai** [comment]
@chrbertsch I think that FMUs can already contain more directories than mentioned in the ZIP structure, without becoming invalid. The extra directory is intended especially for tools other than the original FMU generator to find and/or add new stuff reliably.

**Comment by pmai** [comment]
@chrbertsch As to EMPHYSIS: Yes, if we adopt this FCP, they could use something under extra, but in order to comply, it must use reverse domain notation of a domain under their control, so should be something like extra/org.fmi-standard.eFMU (if approved by MAP FMI), or extra/org.wherever-emphysis-lives.eFMU, or something of that nature. The whole idea being that there are no inadvertent clashes under extra.

**Comment by MartinOtter** [comment]
What is the difference between a *resources* and an *extra* directory. It seems that the reverse domain notation to avoid name clashes could also be used in the *resources* directory

**Comment by chrbertsch** [comment]
Regular Design meeting: 

Klaus: Resources is for simulation, extra could could be used for other information

**Comment by chrbertsch** [comment]
Closing since already merged as PR https://github.com/modelica/fmi-standard/pull/586
