### ISSUE TITLE
Missing description of Enter and Exit function for ConfigurationMode

### ISSUE THREAD

**Issue by klausschuch** [modelica/fmi-standard#595]
The fmi3EnterConfigurationMode() and fmi3ExitConfigurationMode() functions are not described in the API section. The functions are missing in the header files too.
These functions were (at least) mentioned in the old fmi3 doc file but the current ascii doc description does not mention these functions at all. We have to check if there are other thing missing too.

**Comment by chrbertsch** [comment]
@klausschuch: Could you please check?

**Comment by chrbertsch** [comment]
@klausschuch  and @andreas-junghanns : is this fixed with #599 ?
I find now desciption text for these functions in 2.1.6 and at other places of the docu.

**Comment by andreas-junghanns** [comment]
Yes, I think this ticket can be closed.
