### ISSUE TITLE
License information changed from FMI 2 to FMI 3

### ISSUE THREAD

**Issue by jph-tavella** [modelica/fmi-standard#601]
Regarding the new files fmi3PlatformTypes.h, fmi3Functions.h and fmi3functionTypes.h , there are some changes in the information about licensing:
- The link for the 2-Clause BSD license is different from the fmi2 one but the content of the addressed page seems to be the same: any reason for changing?
- In the fm2 file, there was another condition for use and I think it’s a pity to remove it. For memory the fmi2 text is:
"Neither the name of the copyright holders nor the names of its
contributors may be used to endorse or promote products derived
from this software without specific prior written permission."

Same remarks for the .xsd files.

**Comment by t-sommer** [comment]
The license header has been aligned in `support/v2.0.1` and `master`, as specified in the [FMI Project Rules v2.0](https://github.com/modelica/fmi-design/blob/master/FMI_ProjectRules/FMI_ProjectRules_v2.0_2016_06_21.pdf).

**Comment by chrbertsch** [comment]
The additional sentence you are missing is the third of a BSD-3-clause license, but we decided to have BSD-2 Clause in the project rules, see https://fmi-standard.org/assets/FMI_ProjectRules_v2.0_2016_06_21.pdf
