### ISSUE TITLE
Don't forget to start revision information in .h files

### ISSUE THREAD

**Issue by jph-tavella** [modelica/fmi-standard#602]
Regarding the new files fmi3PlatformTypes.h, fmi3Functions.h and fmi3functionTypes.h , I see revision information are missing (please compare with the fmi2 .h files).

A starting paragraph could be added as a comment with something like :
- August, 2019 : First version by xxxxx

**Comment by t-sommer** [comment]
A summary of the changes to the API (and XSD schema) will be provided in CHANGELOG.adoc (to be done).

To get a detailed list of changes of any file you can run `git log headers/fmi3FunctionTypes.h`.

**Comment by jph-tavella** [comment]
That's fine for me. Thanks.
