### ISSUE TITLE
Harmonize "canInterpolateInputs" flag and "maxOutputDerivativeOrder flag" and with new features of hybrid co-simulation

### ISSUE THREAD

**Issue by jph-tavella** [modelica/fmi-standard#603]
Having a glance into fmi3FMUType.xsd & fmi3ModelDescription.xsd, I see the flags "maxOutputDerivativeOrder" and "canInterpolateInputs" are not harmonized.

Please provide “maxInputDerivativeOrder” as an Integer instead of the Boolean “canInterpolateInputs”.

**Comment by chrbertsch** [comment]
Regular Design Meeting: 

Klaus: I am sure we discussed this already.
Markus: I do not see why we should restrict to a masimum order of interpolation
Andreas: Why should the master have to know?
Klaus: The master could decide whether to take derivatives outputs from other FMUs or to reconstruct history data to reconstruct derivatives.
Markus: I do not think see how this information can be used.  Either the FMU can interpolate to any order of to none. The master should decide which order to use.
Masoud: One could prevent the master from giving too much intermation.
Markus: The decision which order to take is a complicated decision of the master.
Klaus: An FMU could tell the master that an interpolation with order higher than 3 does not make sense.
Klaus: We perhaps have just to clarify what is expected of an FMU that has "canInterpolateInputs=true"
Christian B: Is this an interpolation at all, or an extrapolation?
Markus: could be both, depending on the coefficients
Klaus: Perhaps "interpolation" should be avoided. One could call it "canUseInputDerivatives"
Markus: Should we defines, that the input derivatives must be used for polynomial interpolation?
Klaus: What is the benefit of restricting it? e.g. for error estimation ...
Markus: Could improve stability.
Christian: How is this related to IVA?
Markus: If we do not provide intermediate derivatives in hybrid co-simlation, it can be used complementary.
Andreas: Keep it simple!
Andreas: IAV needs more communication
Markus: And more overhead
Klaus: I would not restrict any of those.
Andreas: Interpolation fits for smoothness, IVA deals with non-smoothness inbetween; so they are complementary.
Markus: Either one provides derivatives before a doStep, then one should also provided derivatives at intermediate inputs, 
Or: one should only use either input derivatives OR intermediate input values
Klaus: is it defined in FMI 2.0 if the order of derivatives can  change.
Markus: Do not think, that it is clearly defined.

Markus: Should be discussed in the Hybrid Co-Simulation group.
Change the Title: Harmonize with new features of hybrid co-simulation.

**Comment by jph-tavella** [comment]
With FMI 2.0, the Master can ask the Slave to interpolate the continuous real inputs between communication steps. For that purpose, the Master uses the primitive fmi2SetRealInputDerivatives() to provide the derivatives of the inputs with respect to time, under the condition the capability attribute canInterpolateInputs is true.
Knowing that higher derivatives allow higher order interpolation, a good Master can be tempted to use order greater than 1 if possible.
But the problem is that this attribute canInterpolateInputs is a Boolean and the Master cannot deduce from it the maximum order of interpolation that can be accepted by the Slave.
In order to avoid useless calls to the primitive fmi2SetRealInputDerivatives() at the Master side, an unsigned integer flag defining the maximum order acceptable by the Slave is more efficient than Simply a Boolean flag.
As getting the derivatives of outputs is already governed by an unsigned integer flag named MaxOutputDerivativeOrder, the proposal for FMI 3.0 is to replace the canInterpolateInputs Boolean flag by a maxInputDerivativeOrder integer one.

**Comment by chrbertsch** [comment]
Regular Design Meeting: 

Andreas P.: It would be good to harmonize input and output maxDerivativeOrder. Would Modelica tools be able to provide maxOutputDerivativeOrder?

Torsten B.: harmonizing is ok. It clarifies something.

**Andreas P: I can write this in the XML.  Do we need a separate pull request? No.

@jph-tavella: could you please add this to the documenation (within the hybrid CS pull request)

Torsten B: We need a clarification by the IVA people. 

Jorge: I will contact them, create a separate ticket**

**Comment by chrbertsch** [comment]
Regular design meeting: 

We have to clarify the implications on intermediate input values.
anyone interested in this issue and IVA (@robbr48, @jph-tavella) : could you please discuss this and come up with a proposal before the Lund meeting?
Pierre: we have to fix the interplay between IVA and and derivatives in any case. We could split the issue in this and the proposal the regarding providing the maximum order
Klaus: We have to better specify what the meaning of the derivativs are (not only with IVA), see #622
Klaus: The argument of Markus was that we should also have unbounded.
Pierre: Suggestion: one could use the max integer that can be represented in the XML.

**Comment by jph-tavella** [comment]
I agree with the argument that we could/should also have unbounded value for the maximum input derivatives. Something like the max integer that can be represented in the XML seems a good idea.

**Comment by chrbertsch** [comment]
see also #345

**Comment by hv3ds** [comment]
I think of this as a refinement of a piecewise linear curve. Possibly, every linear segment is replaced by a Taylor series with a t_start and t_end. I'd make t_start the origin point for a serie. Computing the value at t (t_start<=t<=t_end) could be done like:

delta_t=t-t_start;
value=taylor_series[0];
for (i=1;i<N;i++)
  value+=taylor_series[i]*delta_t^i;

The notion that the receiving FMU should have a limit on N seems odd.

**Comment by jph-tavella** [comment]
@hv3ds: if I follow your reasoning correctly, you say that a Boolean canInterpolateInputs is sufficient and that whatever the order of the derivatives provided by the Master the FMU will always be able to take them into account with a Taylor series as soon as the flag is true.
I think this idea is simple and effective. And as a consequence, the original request on this issue (replacing a Boolean by an integer) is obsolete.
I agree with that, but I propose to add somewhere in the standard that "as far as the Boolean canInterpolateInputs is true, the FMU must be able to take all the input dérivatives possibly given by the Master".
What about this proposal?

**Comment by hv3ds** [comment]
@jph-tavella: I agree.

**Comment by jph-tavella** [comment]
So I will add it in the draft standard after Christmas.

**Comment by chrbertsch** [comment]
Regular Design Meeting: 
@hv3ds I will you add some non-normative text to exaplain it, create a PR

**Comment by hv3ds** [comment]
I prefer t_start to be "currentCommunicationPoint". 

@t-sommer 
Looking at the function signature:

typedef fmi3Status fmi3SetInputDerivativesTYPE(fmi3Instance instance,
                                               const fmi3ValueReference valueReferences[],
                                               size_t nValueReferences,
                                               const fmi3Int32 orders[],
                                               const fmi3Float64 values[],
                                               size_t nValues);

Can we expect N=nValues/nValueReferences, meaning that for every valueRef, we have an equal number of derivatives? I would consider a change:

typedef fmi3Status fmi3SetInputDerivativesTYPE(fmi3Instance instance,
                                               const fmi3ValueReference valueReferences[],
                                               const fmi3Int32 valueCount[],
                                               size_t nValueReferences,
                                               const fmi3Int32 orders[],
                                               const fmi3Float64 values[]);

nValues would be the sum of valueCount[i], so no longer needed.

**Comment by jph-tavella** [comment]
I see valueCount as redundant with orders that already contains the order of the respective derivatives according to FMI 2.0. So sum of orders[i] is already nValues.
But it's a good idea to keep nValues.

**Comment by hv3ds** [comment]
So array size of orders is nValueReferences rather than nValues? That is not obvious from parameter order.

**Comment by jph-tavella** [comment]
Yes I read that from the FMI 2.0 where it is written that (the same) nvr is the dimension of the vectors.
But it should be written more cleary in 3.0.

**Comment by chrbertsch** [comment]
@hv3ds : Will you create a PR? Thanks.

**Comment by chrbertsch** [comment]
Superseded by #921
