### ISSUE TITLE
Flow prefix seems to be missed in .XSD files

### ISSUE THREAD

**Issue by jph-tavella** [modelica/fmi-standard#605]
I did'nt see the prefix "Flow" in variable definition in the .XSD files.
Is it missing?

**Comment by chrbertsch** [comment]
@jph-tavella: Which "flow" are you referring to?

**Comment by jph-tavella** [comment]
The question is to keep in the FMU the information 'flow' that can be added in Modelica when defining RealInput or RealOuput.
E.g. flow Modelica.Blocks.Interfaces.RealOuput iAC_im[3,1];
The prefix flow should then be defined somewhere in the variable definition in .XSD files.
I thought this possibility was discussed and added into FMI 3.0.

**Comment by chrbertsch** [comment]
@jph-tavella: I think this is part of the "terminals and icons" FCP, which is developed in this branch of Christian Schulze's fork: https://github.com/CSchulzeTLK/fmi-standard/tree/feature/terminalsAndIcons. Could you please check?

@CSchulze or other membes of this working group: Could you please start a pull request, so this gets visible and can be discussed within this gitbub repo? Thanks!

**Comment by jph-tavella** [comment]
Yes you are right, I see that in the attribute variableKind (inflow, outflow) of TerminalMemberVariable as part of Terminal of Terminals.
But I don't see where is defined element Terminals in fmiModelDescription.

**Comment by CSchulzeTLK** [comment]
This is the current status. The pull request has been opened.

![grafik](https://user-images.githubusercontent.com/33543611/64439225-c85c3200-d0c9-11e9-8744-b79a1751f2ec.png)

**Comment by chrbertsch** [comment]
@jph-tavella: could you please use the pull request #614 for further comments?
