### ISSUE TITLE
Why is the label fmi3Pending introduced again?

### ISSUE THREAD

**Issue by jph-tavella** [modelica/fmi-standard#607]
Why is the label fmi3Pending introduced again in the fmi3Status enum knowing that the asynchronuous mode is removed?

**Comment by chrbertsch** [comment]
@jph-tavella: could you please point us to the point of the document where you are referring to?

**Comment by jph-tavella** [comment]
I see that in the fmi-standard/headers/fmi3FunctionTypes.h.

**Comment by t-sommer** [comment]
`fmi3Pending` will be removed as part of the Hybrid Co-Simulation feature which has not been merged yet (see https://github.com/APillekeit/fmi-standard/blob/fmi3-hybridcosim-fcp07-10-15/headers/fmi3FunctionTypes.h).
