### ISSUE TITLE
Bad/broken link in CCLA document

### ISSUE THREAD

**Issue by ghorwin** [modelica/fmi-standard#610]
CCLA Document https://github.com/modelica/fmi-design/blob/master/FMI_CCLA/FMI_CCLA_v1.0_2016_06_21.pdf
contains an invalid link to http://www.fmi-standard.org/licenses/

**Comment by chrbertsch** [comment]
Shall we just remove this link? Or replace it by https://fmi-standard.org/development/?

**Comment by andreas-junghanns** [comment]
The document is out in the wild - we need to make this link land on something, like /development.
Is there such a thing as a UNIX link on the platform we live on now?

**Comment by chrbertsch** [comment]
Closing in favour of https://github.com/modelica/fmi-standard.org/issues/182 as this is a website issue.
