### ISSUE TITLE
Question marks in structured names?

### ISSUE THREAD

**Issue by nickbattle** [modelica/fmi-standard#612]
The EBNF for structured names (in 2.0, section 2.2.9 p64) lists a question mark as both a "Q-char" character and an "escape" character. So you can have a name `'?'` as well as `'\?'`. Is that as intended?

The fmuChecker is happy with both names, but it may be a typo?

**Comment by nickbattle** [comment]
The EBNF is the same in the Modellica Specification, as far as I can see.

**Comment by andreas-junghanns** [comment]
I don´t see why we should be more restrictive now in 3.0 than before.
Allowing '?' was clearly not a mistake but an intentional copy from Modelica.
Closing. Reopen if you think this requires further investigation.

**Comment by pmai** [comment]
@andreas-junghanns Just to clarify the isse of the ticket, it is not whether to allow ?, but rather why ? is both a qchar and an escape sequence, while none of the other characters is both:

```
Q-char          = nondigit | digit | "!" | "#" | "$" | "%" | "&" | "(" | ")" |
                                     "*" | "+" | "," | "-" | "." | "/" | ":" |
                                     ";" | "<" | ">" | "=" | "?" | "@" | "[" |
                                     "]" | "^" | "{" | "}" | "|" | "~" | " "
escape          = "\'" | "\"" | "\?" | "\\" | "\a" | "\b" |
                  "\f" | "\n" | "\r" | "\t" | "\v"
```

As you said, this part is a direct copy of the Modelica standard:

```
Q-CHAR  = NONDIGIT | DIGIT | "!" | "#" | "$" | "%" | "&" | "(" | ")" | "*" | "+" | "," | 
          "-" | "." | "/" | ":" | ";" | "<" | ">" | "=" | "?" | "@" | "[" | "]" | "^" |
          "{" | "}"  | "|" | "~" | " "_
S-ESCAPE = "\’" | "\"" | "\?" | "\\" |
          "\a" | "\b" | "\f" | "\n" | "\r" | "\t" | "\v" 
```

So I'd agree that changing it now does not make any sense, its just an idiosynchracy we inherited from Modelica.
