### ISSUE TITLE
Create Changelog for FMI 2.0.1

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#616]
* Improved wording in the whole document by proofreading by a native speaker (thanks Maplesoft)
* fixing typos in the whole document,  #444, #623
* p.85 fixed:  Inconsistent definitions of when fmi2GetDerivatives and fmi2GetNominalsOfContinuousStates may be called, #301 
* p 27f, p.88ff fixed pseudo code examples: 
  * fmi2GetDirectionalDerivative: Inconsistency in specification and pseudocode example, #311 
  * detect a state change during event iteration: wrong in pseudo code bug enhancement, #333 
  *  Wrong call sequence for fmi2SetTime in ME pseudo code example, #296 
  *  Fix Pseudocode Example, #308 
*  p31: Improved ModelStructure description in FMI 2.0 specification, #374 
* p.65 added example for Dependency information for FMUs for ModelExchange and CoSimulation #380
* p.87: fixed: Can fmi2SetReal be used for changing the value of continuous-time state variables? #391, #392, #402  
* p.87: fixed: fmi2SetTime in Event Mode of Model Exchange, #394
* p.60:  Clarified the definition of the number of continuous-time state variables model-exchange, #396 
* p.68 clarified: Location of additional DLLs, #401 
* p.77 fixed: Inconsistent definition of the calling conditions for fmi2SetContinuousStates, #407
* p.80 Clarification for pute discrete FMUs
  * Pure discrete-time FMU with state events, #405 
  * Non-determinism regarding the pure discrete-time FMU variant,  #409 
* p. 69 clarified: Order of scalar variables with respect to structured naming, #413 
* p. 66 Clarification that variable names must be unique enhancement, #415
* p.33, p.68 FMUs must contain all relevant license information, #417
* p. 68 Update text under state chart in FMI 2, #431 
p.66 clarification:  Setting input start values before fmi2EnterInitializationMode (clarification in 2.0.1), #440 
p.68 clarified: Backslash as path separator not be allowed in FMUs, #547 
p.14: clarified:  Who shall define the prefix for source code FMUs?,  #420 
p.52f: Clarification of alias variables (and variability), #436
p.55 clarified: Changing parameter values in the modeldescription.xml file discussion specification, #387
p.22 fixed: inconsistency between description and state machine, #338
p.68 clarified:  Handling international encodings, #95
p.33: Clarifying FMI version string: forward/backwards compatibility; version string, #388 , #498 
p.82: Fixed:  Description of fmi2GetContinuousStates is out of date, #334, #501
p.41: Clarified: not use empty unit definitions, #337 
p.8 Remove references to outdated ImplementationHint document, #352 
p.41 Clarified that all units must be defined in UnitDefinitions (#337), #500
p.3 Clarified BSD version in standard documents, #347, #494 
p. 67Clarified:  Are all of the API functions mandatory?, #411
p.103 fmi2CancelStep clarification, #426, #460 
p.115 Fixed literature links, #478 
p.73 Improve sentence using nextMode, #393, #456 
p.49 Remove reference to fmi2ExitEventMode bug specification, #432, #450
p.99 Clarified mathematical model for co-simulation, #460 

header files: (no functional changes)  
* Add parameter names to function prototypes, #2 
* Clarified BSD version in standard documents, #347, #494 
* fixed:  fmiCallbackFunction structure declare const function pointers, #216 

xsd: files (no functional changes)
* Clarifying FMI version string in xsd documentation string:  #388 , #498  

Todo: 
* Sort page numbers

**Comment by beutlich** [comment]
> Here is a copy from closed issues with milestones 2.0.1 - not yet checked if they have really included in FMI 2.0.1.

You really need to double-check it. For example, a quick test showed that

> * Fix typo in function name, #444

is not fixed in 2.0.1-rc.2. If it is already too late for the final v2.0.1 release you should remove the label then.

**Comment by chrbertsch** [comment]
@beutlich , thanks for reporting. will be fixed in RC3

> You really need to double-check it. For example, a quick test showed that

> is not fixed in 2.0.1-rc.2. If it is already too late for the final v2.0.1 release you should remove the label then.

This must be a community effort. Please everyone, check the latest RC, currently RC2 and comment in #623 
It is not too late, think we might have 2-3 more RC iterations before the release.

**Comment by chrbertsch** [comment]
The list above is not yet complete. I propose not to include the list in the FMI 2.0.1 PDF, but add a link there in the appendix, and we will post the change list on the gitbhub release page: 

> A.3.4	 FMI 2.0.1 Mantenane release: Changes and contributors
> The changes w.r.t to FMI 2.0 (clarifications and bugfixes) are summarized on the release page for FMI 2.0.1
> https://github.com/modelica/fmi-standard/releases/tag/v2.0.1 
> 
> The following partners participated at FMI 2.0.1 meetings (alphabetical list):
> 

@t-sommer : do yo you agree?

**Comment by t-sommer** [comment]
@chrbertsch, please update the [changelog](https://github.com/modelica/fmi-standard/blob/support/v2.0.x/CHANGELOG.adoc). We can reuse the text for the release.

**Comment by chrbertsch** [comment]
@t-sommer: 
from my side the list is now complete in the ticket description above
I checked if all changes with milestone 2.0.1 are contained in the Word/PDF document:
*  sorted out some "wontfix" issues
* one missing issue found that was not included in RC4, fixed for RC5: #392 

todo: 
* sort page numbers
* could you please check and update https://github.com/modelica/fmi-standard/blob/support/v2.0.x/CHANGELOG.adoc and include it in the release text?

**Comment by chrbertsch** [comment]
@t-sommer : https://github.com/modelica/fmi-standard/blob/support/v2.0.x/CHANGELOG.md is ready from my side and can be used both to announce RC6 prerelease and the 2.0.1 release
