### ISSUE TITLE
Remove causalities "inferred" and "triggered"

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#617]
and use "input" and "output" instead for variables of type "Clock" (as discussed at the Clocks & Hybrid CS Face-2-Face meeting 12-09-2019)

**Comment by chrbertsch** [comment]
Regular design meeting: 
Andreas P: Let's do this naming discussion after the merging.

**Comment by t-sommer** [comment]
@HansOlsson, what's your opinion on this?

**Comment by HansOlsson** [comment]
> @HansOlsson, what's your opinion on this?

I think this should be ok. I could see two cases for "output" a periodic clock that has parameters that specify it that are known for the importer, and one that is just internally generated in an unspecified way. I don't know if we should separate them.
