### ISSUE TITLE
Clarification over Directional derivatives for vector variables.

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#618]
I have a concern over directional derivatives for vector and multi dimensional case. Take for example the directional derivatives of a vector output Y which is expressed as:
Delata Y=(del F/del X) *Delata X + (del F/del Ui) *Delta Ui
where Y is an output, X is the state vector and Ui is ith input. 
Unlike in FMI2.0, all Y, X, and Ui can be vector or multi-dimensional.
My question is the meaning of partial derivatives in case of multi-dimensional or matrix elements?
For example how to provide del F/del Ui. Maybe I am missing something, but it leads to tensorial calculus.
Also, I do not remember if matrix state vector is allowed or not? if yes, what is the meaning of del F/del X?
Any comment to clarify this?

**Comment by chrbertsch** [comment]
Regular FMI Design meeting

Everything is allowed: Everything is serialized and then partial derivatives are w.r.t. to these serialized variables (Was discussed in Munich).
@klausschuch : check the meeting minutes of the Munich meetin, see https://github.com/modelica/fmi-design/blob/master/WorkingGroups/03_Array/2017-07-17-Meeting_M%C3%BCnchen/Meeting%202017-07-17-Minutes.doc
We should create an example and add it to the docuemnt, should be a C-Code example 
@masoud-najafi: I will create an example

**Comment by masoud-najafi** [comment]
I noticed that the directional derivative is (should) be done with respect to isolated elements of KNOWN variables. So no partial derivative wrt matrix or vector is required. I attached an example for an FMU that computes the matrix product of its input (matrix) and a constant matrix. This example  demonstrates the way the directional derivative of the output matrix with respect to input is  computed.  That attached zip file is the modified 2_1_common_api.adoc section. Please take a look and share your comments.
[2_1_common_api.zip](https://github.com/modelica/fmi-standard/files/3858315/2_1_common_api.zip)

Then this ticket can be closed after discussion.

**Comment by chrbertsch** [comment]
Hello @masoud-najafi : Could you please either please share a link to your fork you modiefied 2_1_common_api.adoc or open a pull request, so that it is easier to see your changes and discuss them  with Github means ? Thanks!

**Comment by chrbertsch** [comment]
The PR is here: https://github.com/modelica/fmi-standard/pull/677

**Comment by friedrichatgc** [comment]
i think this can be issue can be closed. The current master contains now an example for directional derivatives were the unknowns and the knowns are 2D arrays. It is working well. The issue regarding tensor calculus does not apply for directional derivatives. Tensor calculus is just need for partial derivatives which are not provided directly by FMI: a partial derivative increases the order of the tensor whereas a directional derivative does not increase the order. Hence, the serialization of the sensitivity of a forward directional derivative is the same as v_unknown and the serialization of the sensitivity of a adjoint directional derivative is the same as v_known.
