### ISSUE TITLE
Create "complete package" of FMI 2.0.1

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#624]
zip file also containing headers and .xsd files

**Comment by t-sommer** [comment]
see also #632

**Comment by chrbertsch** [comment]
@t-sommer : would be great if you or someone elso test the new header and xsd files e.g. with fmpy and testFMUs  (should be functionally identical; just to make sure we made no mistake).

**Comment by chrbertsch** [comment]
Now the pdf if is final from my side with RC6, see https://github.com/modelica/fmi-standard/pull/653

**Comment by t-sommer** [comment]
I've added the distribution archive to https://github.com/modelica/fmi-standard/releases/tag/v2.0.1-rc.6
