### ISSUE TITLE
Harmonize FMI 3.0 and eFMI array definition

### ISSUE THREAD

**Issue by MartinOtter** [modelica/fmi-standard#625]
In FMI 3.0 modelDescription.xml file, the dimensions of an array are defined as:

![image](https://user-images.githubusercontent.com/7248038/65433842-12f5e200-de1e-11e9-9053-568ee29627ce.png)

In eFMI production code manifest file, the dimensions of an array are defined as:

![image](https://user-images.githubusercontent.com/7248038/65433954-46387100-de1e-11e9-9899-ce56360dfb4c.png)

These definitions should be harmonized.

The production group argues:

- Elements are not ordered in xml, and theoretically an xml parser can provide the dimension definitions in any order. For this reason `number` is given to uniquely define the number of the dimension (so that it does not depend on the ordering of the definition on the xml-file).
- `start` is a very unusual description for an array size. The usual notation is `size`

@joergn, @Robert.Reicherdt

**Comment by t-sommer** [comment]
> Elements are not ordered in xml

This is not true. In FMI 2.0 e.g. the element index is used to reference the <ScalarVariable> elements from the <ModelStructure> element.

> and theoretically an xml parser can provide the dimension definitions in any order.

What parser does that?

**Comment by jnjaeschke** [comment]
https://stackoverflow.com/a/37831330

As long as there is a "sequence" in the xsd, the order is preserved.
But this "enforces" all parsers to know about the xsd file.

Generally speaking, I think relying on the order of elements in the xml tree is not elegant. Explicitly enforcing the right order by using an "index" attribute clears things up for everyone. And then it doesn't matter if you may use a bad xml parser.

**Comment by andreas-junghanns** [comment]
We have had this argument too many times before. And we use the XML order already, so even if inconvenient, let´s not introduce a new way of doing things (and follow, again, the excellent arguments from above).

**Comment by chrbertsch** [comment]
Regular design meeting

Closed following comments above
