### ISSUE TITLE
Uniqueness of `Attribute “name” of  Annotations with type `fmi2Annotation`. 

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#629]
_Originally posted by @CThuleHansen in https://github.com/modelica/fmi-standard/issues/623#issuecomment-534255666_

On p. 45 regarding VendorAnnotations with type `fmi2Annotation` it is stated `Attribute “name” must be unique with respect to all other elements of the VendorAnnotation list.`
But this is not the case on p. 57 for Annotations with type `fmi2Annotation`. 

This is confusing as the types are the same, `fmi2Annotation` but the invariants are different. 

_chrbertsch: see comments below_

**Comment by CThuleHansen** [comment]
I agree with Nick's proposal -- listed below

> > On p. 45 regarding VendorAnnotations with type `fmi2Annotation` it is stated `Attribute “name” must be unique with respect to all other elements of the VendorAnnotation list.`
> > But this is not the case on p. 57 for Annotations with type `fmi2Annotation`.
> > This is confusing as the types are the same, `fmi2Annotation` but the invariants are different.
> 
> **URGENT:**
> @ALL : I do not know what to do with this. Please comment and come up with a proposal; otherwise this will not be be included in FMI 2.0.1

VDMCheck verifies this, assuming the tool names should be unique in both places. There are no occurrences of a duplicate name in the whole of the FMI Cross Check repository (792 FMUs), so it might be safe to make that the rule?

_Originally posted by @nickbattle in https://github.com/modelica/fmi-standard/issues/623#issuecomment-534611313_

**Comment by chrbertsch** [comment]
Discussed with @TorstenBlochwitz : wont fix for FMI 2.0.1, not critical

**Comment by chrbertsch** [comment]
Regular Design Meeting

Torsten S.: in Lund there was a discussion to replace "VendorAnnotations" by "Annotation". 
We should discuss this issue in that context. @pmai : your opinion?

**Comment by pmai** [comment]
I definitely would like to move to the SSP-way of naming the annotations in a neutral way and putting at least a SHOULD suggestion to use reverse domain notation to ensure uniqueness into the document, as well as unifying the definition of the annotations and potentially allowing them in more places.

Whether this is something people want for 3.0? I don't know.

**Comment by CThuleHansen** [comment]
I think the discussion is shifting a bit from what I, and @nickbattle intended to bring up, but I am also unfamiliar with the ssp way of naming.

Just to clarify:
The main issue in my opinion is, that the description of the type `fmi2Annotation` is not consistent through the standard.

- On page 44 of 2.0.1 RC 6 it states the the name of an instance of type `fmi2Annotation` must be unique within its container. 
- On page 57 of 2.0.1 RC 6 it does not state this, although the type is **exactly** the same. So for the same type, you have two different definitions. 

So I see the following possible solutions:

1. The uniqueness rule should apply to both places, as the type is the same.
2. the Uniqueness rule should be brought up a level in the xml hierarchy and removed from the description of the type `fmi2annotation`.
3. The types should be different.

Both @nickbattle and I propose 1.

**Comment by chrbertsch** [comment]
FMI Design meeting:

Pierre: the quick fix would be to follow proposal 1 (or 2). 

@CThuleHansen  or  @nickbattle  could you please open a PR? Thanks!

**Comment by CThuleHansen** [comment]
Certainly.

**Comment by chrbertsch** [comment]
@nickbattle  and @CThuleHansen : could you please create the PR?

**Comment by CThuleHansen** [comment]
I will wait till after the restructuring.

**Comment by CThuleHansen** [comment]
I have fixed the text, but I need help to fix the text in the image. The text should read EXACTLY:

Name of tool that can interpret the annotation. "name" must be unique with respect to all other elements of the `Annotations` list.

**Comment by chrbertsch** [comment]
> I have fixed the text, but I need help to fix the text in the image.

These image is created automatically form the xsd. Have you checked this file? 
If I understand correctly, we have removed all comments from the xsd-files (e.g., here https://github.com/modelica/fmi-standard/blob/master/schema/fmi3ModelDescription.xsd), so we must place the information in the specification text.

@t-sommer uploaded the image https://github.com/modelica/fmi-standard/blob/master/docs/images/VendorAnnotations_schema.png originally, but perhaps this was just a screenshot of the 2.0 pdf.
@CSchulzeTLK : has xml-spy and is currently working on creating new images.

**Comment by CThuleHansen** [comment]
Hi Christian, okay. Shall we wait with merging this until @CSchulzeTLK has created an image then?

**Comment by chrbertsch** [comment]
I suggest to go on and extend the text as if the comment in the picture was not there.

**Comment by CThuleHansen** [comment]
I have done this. It is in the pull request.

**Comment by chrbertsch** [comment]
fixed with merged PR #828
