### ISSUE TITLE
Add instructions to build FMI 2.0.1 PDF and "Complete Package" ZIP archive

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#632]

**Comment by chrbertsch** [comment]
@t-sommer : where shall I document this? In this ticket? 
I have some hints from @MartinOtter 

For the "complete package": could someone else please provide available info?

**Comment by t-sommer** [comment]
I think https://github.com/modelica/fmi-standard/blob/support/v2.0.x/CONTRIBUTING.adoc is the right place.

**Comment by chrbertsch** [comment]
Has been documented in https://github.com/modelica/fmi-standard/blob/support/v2.0.x/CONTRIBUTING.adoc
