### ISSUE TITLE
Collect contributors to FMI 2.0.1

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#633]
... for FMI 2.0.1 standard document

(alphabetical list):
Christian Bertsch, Robert Bosch GmbH, Germany
Torsten Blochwitz, ESI ITI GmbH, Germany
Robert Braun, Linköping University, Sweden
Andreas Junghanns, QTronic GmbH, Germany
Pierre R. Mai, PMSF IT Consulting, Germany
Masoud Najafi, Altair SA, France
Andreas Pillekeit, dSPACE GmbH, Germany
Torsten Sommer, Dassault Systèmes, Germany
Karl Wernersson, Dassault Systèmes, Sweden
...

Please add yourself and / or others that have contributed. Thanks

**Comment by chrbertsch** [comment]
> ... for FMI 2.0.1 standard document
> 
> (alphabetical list):
> Christian Bertsch, Robert Bosch GmbH, Germany
> Torsten Blochwitz, ESI-ITI GmbH, Germany
> Robert Braun, Linköping University, Germny
> Pierre R. Mai, PMSF IT Consulting, Germany
> Andreas Junghanns, QTronic GmbH, Germany
> Masoud Najafi, Altair SA, France
> Andreas Pillekeit, dSpace GmbH, Germany
> Torsten Sommer, Dassault Systèmes, Germany
> Karl Wernersson, Dassault Systèmes, Sweden
> ...
> 
> Please add yourself and / or others that have contributed. Thanks

Will be included in RC3. Please comment on errors and missing people.

I also suggest to include sentence: For further contributors by comments please refer to the issue tracking system https://github.com/modelica/fmi-standard/milestone/3 . OK?

**Comment by beutlich** [comment]
Some corrections:

* Swap Andreas and Pierre for alphabetical sorting
* ESI ITI GmbH (w/o the dash)
* dSPACE GmbH (lower-case d and rest in capitals)
* Germny -> Germany

**Comment by chrbertsch** [comment]
Closing; if something has to be fixed, reopen or add a commetn to #623

**Comment by masoud-najafi** [comment]
Altair SA -> Altair
