### ISSUE TITLE
Use Numbering instead of indentation and bullet points

### ISSUE THREAD

**Issue by CThuleHansen** [modelica/fmi-standard#650]
FMI 3: Since this is a technical standard I suggest less bulletins and more numberings in general. 
This was also mentioned by @klausschuch on fmi design meeting oct 1 lund

**Comment by nickbattle** [comment]
Yes, I absolutely agree with this. When preparing VDMCheck, it was difficult to concisely reference where in the FMI standard each particular "rule" was defined. Sometimes one section covers several pages without any sub-section numbering or table/figure numbers, so it is difficult to give a simple location, other than by saying, "the second table half way down page 123".

**Comment by andreas-junghanns** [comment]
We have tried a similar attempt in #716 and I even implemented that as a PR. We looked at the result and did not like it: The text is much too dense and it misses the structure of tables.

This proposal here is slightly different as this already has headings, just without numbering.

I suggest you pick a chapter and create a PR such that we can evaluate if this is better or not.

**Comment by pmai** [comment]
My experience with standards that try to do this, especially in the more drastic form of having separately checkable and enumerated semantic rules for the ease of checker development, this usually leads to either an unreadable standard, or duplication, with one set of formal rules and one set of readable text, which then just leads to implementors implementing the readable text, and not the formal one.

Note that I'm not saying that the FMI standard could not be improved considerably through good copy editing, and some more rigor, but keeping the standard readable and understandable must be the main goal.

As @andreas-junghanns says, a PR for a chapter or sub-section that implements this and/or #795 would be a good discussion basis.
