### ISSUE TITLE
Definition of base type

### ISSUE THREAD

**Issue by CThuleHansen** [modelica/fmi-standard#657]
> 2.1.2: `This is a handle to a (base type) variable value of the model. Handle and base type (such as fmi3Real) uniquely identify the value of a variable. Variables of the same base type that have the same handle, always have identical values, but other parts of the variable definition might be different [for example, min/max attributes].`
> 
> This is the first notion and definition of base type, and it seems weird to include this definition in a "side note"

I suggest discussing this at an fmi-design meeting.

_Originally posted by @APillekeit-PR in https://github.com/modelica/fmi-standard/pull/626#issuecomment-541415665_

**Similar:**
> 2.1.2: `This is a handle to a (base type) variable value of the model. Handle and base type (such as fmi3Real) uniquely identify the value of a variable. Variables of the same base type that have the same handle, always have identical values, but other parts of the variable definition might be different [for example, min/max attributes].`
> 
> I am unsure of the word value in this context. But I have the feeling, that it might have been discussed before. And I also think that it is more than the value of a "base type"
> 
> I.e. a valuereference in contxt of `fmi3GetNumberOfVariableDependenciesTYPE` is a handle to the variable for which the number of dependencies should be returned, and therefore NOT a handle to a base type variable value.
> 
> It is also mentioned that `An fmi3ValueReference references one such scalar.`.
> So in this case it is a reference to a scalar.
> 
> For these reasons I think the definition of fmi3valuereference is imprecise

I suggest discussing this at an fmi-design meeting.

_Originally posted by @APillekeit-PR in https://github.com/modelica/fmi-standard/pull/626#issuecomment-541415609_

**Comment by APillekeit** [comment]
Just to not forget the comment below I add this here additionally:

2.1.2: These are the basic data types used in the interfaces of the C functions
basic type or base types?

the documents uses "base" type in other places. Not sure which would be to best choice: @t-sommer which one fits better?

Source: https://github.com/modelica/fmi-standard/pull/626#issuecomment-541417410

**Comment by chrbertsch** [comment]
@CThuleHansen : Could you open a PR to discuss the wording? Thanks!

**Comment by CThuleHansen** [comment]
Yes I can do that.
