### ISSUE TITLE
FMI Functions must not change global settings ...

### ISSUE THREAD

**Issue by CThuleHansen** [modelica/fmi-standard#658]
> 2.1 `An FMI function may change settings of the process/thread in which it is called` - when an fmu is loaded it becomes part of the process of the loading tool, is that not correct?
> If so, then it is contradiction with `FMI functions must not change global settings which affect other processes/threads.`
> 
> I am not an expert in this, so might be an incorrect correct ;)

That very much depends on the implementation of the loading tool. But I agree, this is an explanation that can be improved. I would suggest to keep that in mind for the global rework of the specification.

_Originally posted by @APillekeit-PR in https://github.com/modelica/fmi-standard/pull/626#issuecomment-541412146_

**Comment by chrbertsch** [comment]
Regular Design Meeting

Torsten S: Is this not beyond what we define in FMI?
Christian: For my  understanding together with the second part of the sentence, this is fine

>FMI functions must not change global settings which affect other processes/threads. An FMI function may change settings of the process/thread in which it is called (such as floating point control registers), provided these changes are restored before leaving the function or before a callback function is called.
