### ISSUE TITLE
Add a formal notation for function prefix naming details

### ISSUE THREAD

**Issue by APillekeit** [modelica/fmi-standard#659]
> > 2.1.1: Maybe adapt a formal notation for all these naming details? Similar to what is used in 2.2.10
> 
> This might be a good idea. What is your suggestion for this notation?

Is the postfix `_` to be part of the value of the macro definition FMI3_FUNCTION_PREFIX? Does it matter whether it is part of the macro definition or not?

I do not know. A textual rewrite could be:
- If the FMU is shipped with C source code or with static link library:
In the following paragraph _modelIdentifer_ refers to the value of the `modelIdentifier` attribute within the element `<fmiModelDescription><ModelExchange>` or
`<fmiModelDescription><CoSimulation>`, see Section 3.3.1 and Section 4.3.1.
The constructed function name must be `FMI3_FUNCTION_PREFIX_fmi3GetReal`, where `FMI3_FUNCTION_PREFIX` is a macro definition with the value _modelIdentifier__, note the appended _.
In case of a static link library the name of the library is _modelIdentifier_.dll on windows and lib<i>modelIdentifier</i>.a on Linux.
A simulation environment can therefore construct the relevant function names by generating code for the actual function call.

If you like this way of writing it, I will be happy to go over the last part of 2.1.1 and present a possible rewriting.

_Originally posted by @CThuleHansen in https://github.com/modelica/fmi-standard/pull/626#issuecomment-543648432_

**Comment by pmai** [comment]
Maybe it is just me, but the above definition would lead to identifiers of the form XXX__fmi3GetReal, i.e. with double underscores, since there is an underscore in the macro definition and one in its usage. Is this intended?

**Comment by APillekeit** [comment]
Hi pmai, I think you are right and this is most likely not intended by CThuleHansen.  

Question is I guess: Is it required to improve the definition from the current state in the standard documentation and is the approach useful that CThuleHansen has proposed and should he spend time on such an improvement.

Andreas

**Comment by CThuleHansen** [comment]
> Maybe it is just me, but the above definition would lead to identifiers of the form XXX__fmi3GetReal, i.e. with double underscores, since there is an underscore in the macro definition and one in its usage. Is this intended?

Definitely a typo :)

**Comment by chrbertsch** [comment]
@CThuleHansen : could you  please open a PR or otherwise we shall close this ticket.

**Comment by CThuleHansen** [comment]
I think the mix between model name and modelidentifier is quite confusing, so yes I will.

**Comment by CThuleHansen** [comment]
please close @chrbertsch. The wording has changed in the fmi-doc, so not relevant for now.
