### ISSUE TITLE
Schema allows illegal combinations of <ModelExchange> and <CoSimulation>

### ISSUE THREAD

**Issue by munsivut** [modelica/fmi-standard#660]
According to the schema (modelDescription.xsd file) and standard, the following sequences are valid.

* ModelExchange, CoSimulation, ModelExchange, CoSimulation
* ModelExchange, CoSimulation, ModelExchange
* CoSimulation, ModelExchange, CoSimulation
* CoSimulation, ModelExchange
* CoSimulation, CoSimulation
* Nothing (?)
* etc...

But for example, the following is not valid.

* ModelExchange, CoSimulation, ModelExchange, CoSimulation, ModelExchange, CoSimulation

This is confusing. The condition in the schema (maxOccurs="2") is not explained and its purpose remains obscure. Why limit the number to "2" instead of "1" or even "Unbounded"? The sequence also contains an annotation: "At least one of the elements must be present". This annotation text does not explain what the block is doing or why maxOccurs is 2.

I went through the modelica/fmi-cross-check/fmus/2.0 ([link](https://github.com/modelica/fmi-cross-check/tree/master/fmus/2.0)) directory and the only sequences there were:

* ModelExchange (283 pcs)
* CoSimulation (374 pcs)
* ModelExchange, CoSimulation (92 pcs)

So why does the schema allow other sequences and mixing the order of elements? Why the schema can't be like the one below.

```xml
<xs:choice>
    <xs:sequence>
        <xs:element name="ModelExchange" type="ModelExchangeType" />
        <xs:element name="CoSimulation" minOccurs="0" type="CoSimulationType" />
    </xs:sequence>
    <Xs:sequence>
        <xs:element name="CoSimulation" type="CoSimulationType" />
    </xs:sequence>
</xs:choice>
```

**Comment by nickbattle** [comment]
VDMCheck does not verify the XML against schema, but it does enforce rules about the XML constructs which could, in some cases, be added to the XSD. In this case, the rule we have is:
```
-- @OnFail("2.2.1 Neither ModelExchange nor CoSimulation specified")
( md.modelExchange <> nil or md.coSimulation <> nil ),
```
That is, you can have precisely one of ModelExchange or CoSimulation, and you can have both, but you must have at least one. I think this is correct(?)

If you create multiple CoSimulation or ModelExchange elements in the XML, I think the "simple" parser that VDMCheck uses would just use the last one declared. That could be improved!

**Comment by nickbattle** [comment]
> If you create multiple CoSimulation or ModelExchange elements in the XML, I think the "simple" parser that VDMCheck uses would just use the last one declared. That could be improved!

This is now improved in build 191021. Duplicate coSimulation or modelExchange elements will be treated as errors, regardless of ordering.

**Comment by munsivut** [comment]
Hello

I'm thinking about that number 2. Can it somehow depend on needExecutionTool? The "fmi-cross-crosscheck / fmus / 2.0" directory contains 12 FMUs (AMESIM) where the attribute value is true but does not contain duplicates. I also thought that if it is meant that the source code and the binary CS (or ME) can be divided into two CS (or ME) elements. But all 351 binary & source FMUs in the "fmi-cross-crosscheck / fmus / 2.0" directory packaged the source code and the binary into the same element.

if it was intended that 2 ME + 2 ME is possible, whitout mixing order, and there should always be one element, then i think the sentence would be.

```xml
<xs:choice>
    <xs:sequence>
        <xs:element name="ModelExchange" maxOccurs="2" type="ModelExchangeType" />
        <xs:element name="CoSimulation" minOccurs="0" maxOccurs="2" type="CoSimulationType" />
    </xs:sequence>
    <xs:sequence>
        <xs:element name="CoSimulation" maxOccurs="2" type="CoSimulationType" />
    </xs:sequence>
</xs:choice>
```

**Comment by beutlich** [comment]
@t-sommer Since the FMI v2.0.1 is released, this issue's milestone should be removed/rescheduled to get the [v2.0.1](https://github.com/modelica/fmi-standard/milestone/3) closed.

**Comment by t-sommer** [comment]
@beutlich, should we create a v2.0.2 milestone to collect new issues?

**Comment by beutlich** [comment]
Yes, sound sensible to me.

**Comment by chrbertsch** [comment]
I propose to close this issue.

For FMI 3.0 it is fixed, see https://github.com/modelica/fmi-standard/blob/master/schema/fmi3ModelDescription.xsd

For a possible future release of FMI 2.0.2:  I think it has never been a problem that one defined an FMU with 2* ME or 2*CS. 

And the proposed solution  above 
```
<xs:choice>
    <xs:sequence>
        <xs:element name="ModelExchange" maxOccurs="2" type="ModelExchangeType" />
        <xs:element name="CoSimulation" minOccurs="0" maxOccurs="2" type="CoSimulationType" />
    </xs:sequence>
    <xs:sequence>
        <xs:element name="CoSimulation" maxOccurs="2" type="CoSimulationType" />
    </xs:sequence>
</xs:choice>
```
does not work directly for FMI 2.0.1, as  one would have to restructure 
https://github.com/modelica/fmi-standard/blob/support/v2.0.x/schema/fmi2ModelDescription.xsd
as one does not have a file https://github.com/modelica/fmi-standard/blob/master/schema/fmi3FMUType.xsd to reference type="CoSimulationType" which occurs two times in the proposal above.

And as this problem never occured I think it is not worth fixing.

If anyone considers this important, please provide a PR for https://github.com/modelica/fmi-standard/blob/support/v2.0.x/
