### ISSUE TITLE
Clarification over event management in Co-Simulation

### ISSUE THREAD

**Issue by ValerioDV** [modelica/fmi-standard#665]
Hi,

I have some concerns about event management in Co-Simulation:

- I understood how an FMU can signal an event to the co-simulation master, however what is not clear to me is how this event is propagated to the other FMUs. For example, are all the FMUs pushed to the Event mode, and the event is somehow provided as an input parameter? Or the event is just a way to set a new communication point to update variables values? 

- What is the real difference between a clock tick and an event? I think that what is not really clear is the general concept of Clock Support in Hybrid Co-Simulation mode, and how it really differs from the Early Return.

- Is the function fmi3NewDiscreteStates() used to manage super-dense time?

Thanks.

**Comment by chrbertsch** [comment]
@APillekeit : I will comment on this.

**Comment by APillekeit** [comment]
Hi, 

thank you for your questions. I will use these as an input to improve the documentation with the hybrid co-simulation working group.

First point:
The details on how a cs master transports the event information to another FMU are out of scope of FMI since FMI does not define master algorithms it just provides an interface to enable cs master features.

Second point:
You are right, that has to be clarified and described in a better way for Hybrid Co-Simulation. A maybe superficial view on the difference is that clock ticks are usually accompanied by an event but not all events are clock ticks. Also clock (ticks) can be associated to certain model parts (i.e. variables) and their tick properties (e.g. periodic or aperiodic) are known in advance based on descriptions in the modeldescription.xml. The details related to step/time/state event properties would have to be added by the working group experts, since I'm not an expert in this. I will suggest a clarification rework for the documentation. 

Third point:
The function can be called iteratively and no simulation time increases in event mode. So yes.
What are your concerns related to the third point?

**Comment by ValerioDV** [comment]
Hi,

thank you very much for your reply, below you can find my comments.

> First point:
The details on how a cs master transports the event information to another FMU are out of scope of FMI since FMI does not define master algorithms it just provides an interface to enable cs master features.

Yes, I understand that FMI does not define master algorithm. My question indeed was on the interface that the FMU provides to enable a master algorithm to "set" events coming from other FMUs (if this is possible at all).

> Third point:
The function can be called iteratively and no simulation time increases in event mode. So yes.
What are your concerns related to the third point?

I do not have concerns about this, I just wanted to understand if I got the function behavior correctly.

**Comment by jph-tavella** [comment]
@ValerioDV 
The new FMI defines how an FMU can signal an event to the co-simulation Master. This way an intermediate communication point is created corresponding to the time of this event. Then it is the Master responsability to propagate this event I mean to update all input values for all the other FMUs at this new communication point. Probably the Master will have to resynchronize all the FMUs (except the one that generated the event) thanks to the rollback mechanism.

**Comment by APillekeit** [comment]
WG Clocks & HCS:
Clarification attempt for documentation:
Source was question whether it is possible to have clocksTicked=true and eventOccurred=false. 

Suggestion for clarification:

- clocksTicked should be renamed into outputClocksTicked in function fmi3CallbackIntermediateUpdate()
- eventOccurred should be renamed into stateEventOccurred

Aim is to be more explicit. In this sense stateEventOccurred is only related to state events that require a fmi3NewDescreteStates().

A clock tick is a synchronous time event. Whenever the FMU signals an event (state event, clock tick or indicated that a time event should be handled based on nextEventTime) the FMU would have to be pushed into event mode and fmi3NewDiscreteStates() would have to be called.

This sentence needs to be deleted in the documentation: Additional cases need to be handled if a clock tick is not associated to an event that requires the creation of a communication point for the model partition that generated the event. 

Now it would be possible to have outputClocksTicked=true and stateEventOccurred=false

Needs to be checked at design meeting.

**Comment by chrbertsch** [comment]
Regular Design meeting: 
Should be especially checked by Modelicans

@TorstenBlochwitz,  @HansOlsson, @hv3ds  : Could you please comment on this? Thanks!

**Comment by chrbertsch** [comment]
I propose to only discuss very concrete proposals by AndresP in https://github.com/modelica/fmi-standard/issues/665#issuecomment-601275266 discussed above, try to fix them, and then close this issue.

 > Is the function `fmi3NewDiscreteStates`() used to manage super-dense time?

 Related to the suggestion inhttps://github.com/modelica/fmi-standard/issues/793#issuecomment-629751246  to rename it to `fmi3DoHyperDenseTimeStep` 

(Additionally this is related to writing a general description of clocks, see https://github.com/modelica/fmi-standard/issues/723)

**Comment by chrbertsch** [comment]
Discussion at Webmeeting:
Karl: in CS, I do not see the flag ValuesOfContinuasStates, NominalsOfContinuousStates changed in fmi3NewDiscreteState relevant. We should check all the flags of  fmi3NewDiscreteState
Klaus: Is EventInfo still a structure? Didn't we want to get rid of structures?
Karl: then we should change this for ME also. I Personally the structure is nicer
Klaus: some of the variables do not make sense in co-simulation. We have to clarify this. Would we have two different functions for ME and HCS? Or say, certain flags are not relevnat
Andreas J: the second option. We have done this at other places also.
Klaus: It is an update of outputs from inputs with a delta t of zero.
Karl: Continuous variables can also be changed.
Otto: there is already a sentence for enterEventMode ...
Andreas: This should be moved to the description of the new discrete states
![grafik](https://user-images.githubusercontent.com/16363372/83155198-4a313700-a101-11ea-9961-67db6e72e62f.png)

@andreas-junghanns : I will make a proposal

**Comment by andreas-junghanns** [comment]
@chrbertsch : I am not sure if PR #1038 addresses all the issues raised here. If so, can you please link PR #1038 to this ticket?
