### ISSUE TITLE
Fix formula for directional derivatives

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#668]
In 2.1.9 of FMI 2.0.1 and 2.1.11 of FMI 3. : 
![grafik](https://user-images.githubusercontent.com/16363372/68534234-4a6b1000-0332-11ea-952d-7227ac2b53f8.png)

to my understanding the formula should  contain \Delta v_{known} instead v_{known} on the right hand side, i.e. 
![grafik](https://user-images.githubusercontent.com/16363372/68534227-28718d80-0332-11ea-8f22-e5e3c36f9216.png)

(Should be fixed in FMI 2.0.2 and FMI 3.0)

Do you agree?

**Comment by andreas-junghanns** [comment]
I cannot see the images, can you please test on your end (I am at the far end of the internet)...

**Comment by chrbertsch** [comment]
This was fixed for https://github.com/modelica/fmi-standard/pull/677 for FMI 3.0. 
Keeping the ticket for a possible FMI 2.0.2 release

**Comment by chrbertsch** [comment]
Committed fix to support/2.0.x with https://github.com/modelica/fmi-standard/commit/1f50d0b1f419207cc29a1efadb1528be0fe91802
and to an updated word document with https://github.com/modelica/fmi-design/commit/440a4a6afaeeede44bec58f69c8af5ac7dd01b70

... not knowing if FMI 2.0.2 shall ever be released but in order to close tickets :-)
