### ISSUE TITLE
Add anchors to functions, types and states in the docs

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#671]
All FMI functions and types in the documentation should have an [anchor](https://asciidoctor.org/docs/user-manual/#anchordef) with a pre-formatted xreflabel e.g.

```
[fmi3GetVersion,`fmi3GetVersion`]
[source, C]
----
include::../headers/fmi3FunctionTypes.h[tags=GetVersion]
----
```

so we can use it in the text, e.g.

```
The header file version number for which the model was compiled,
can be inquired in the target simulator with <<fmi3GetVersion>>.
```

and readers can conveniently navigate to the anchors.

**Comment by chrbertsch** [comment]
@t-sommer : this is done, right?  Can we close this? Or are there still anchors missing?

**Comment by t-sommer** [comment]
> this is done, right?

AFAIK, it's still ongoing.

**Comment by andreas-junghanns** [comment]
We do this now as we need the anchors, no need to have a separate ticket.
