### ISSUE TITLE
table cells show non-normative texts wrong

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#690]
Inside table cells, the _[xx]_ markings fail and produce:

[ Example: <Variable name=“spD" valueReference="126" causality=“structuralParameter" variability=“fixed"> <Integer start="3"/> </Variable> ]

**Comment by t-sommer** [comment]
You can try this:

```
_[Example:_

[source, xml]
----
<Int32 name="spD" valueReference="126" causality="structuralParameter" variability="fixed" start="3">
  <!-- no Dimension elements allowed -->
</Int32>
----

_]_
```

However XML should be included from a modelDescription.xml, so it gets validated in CI. The above example is not compliant with the current schema.

**Comment by chrbertsch** [comment]
Regular design meeting:

Andreas J: We should add to the contribution guidelines: do not add C- or XML-codes outside .c or .xml  files that can be validated.

**Comment by t-sommer** [comment]
@andreas-junghanns, can you check if the problem still exists?

**Comment by andreas-junghanns** [comment]
> 
> 
> Regular design meeting:
> 
> Andreas J: We should add to the contribution guidelines: do not add C- or XML-codes outside .c or .xml files that can be validated.
This is now done in the CONTRIBUTING.adoc

**Comment by andreas-junghanns** [comment]
I checked the non-normative texts in table cells and all look ok. Not sure what I saw. All well, closing as invalid.
