### ISSUE TITLE
still strange, excessive formatting in the text

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#691]
e.g. [underline]

**Comment by andreas-junghanns** [comment]
or: *clocked model partitions*

**Comment by chrbertsch** [comment]
Regular Design meeting: 

Torsten S: 
Proposal to remove all underline, bold (that is not a state name) and italic text (that is not non-normative).

Keep only double-quotes where one actually quotes.

Units shall be in set in back-ticks: `Nm`

Torsten S: After this will be merged, I will put this in the formatting rules.

**Comment by chrbertsch** [comment]
Regular design Webmeeting:

There are still e.g. colors in the tables that have semantic meaning.
We should find alternatives.

**Comment by andreas-junghanns** [comment]
> 
> 
> Regular design Webmeeting:
> 
> There are still e.g. colors in the tables that have semantic meaning.
> We should find alternatives.

What is wrong with the colors? I suggest we either leave it as is, or open a new issue for the colors (so we can close this).

**Comment by andreas-junghanns** [comment]
I suggest (again) to drop the color issue from here and close this ticket, reopen if you disagree. If the colors seem important, let´s open a new issue to discuss alternatives to colors.
