### ISSUE TITLE
Hints on graph coloring algorithm missing in documentation.

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#703]
The following paragraph from the FMI 2.0 documentation is missing in the "2.1.11. Getting Partial Derivatives" section of the  FMI 3 docu:

> A so-called graph coloring algorithm is employed to determine the columns of the matrix that can be computed by one call of fmi2GetDirectionalDerivative. Efficient graph coloring algorithms are freely available, such as library ColPack (http://www.cscapes.org/coloringpage/) written in C/C++ (LGPL), or the routines by Coleman, Garbow, Moré: “Software for estimating sparse Jacobian matrices”, ACM Transactions on Mathematical Software - TOMS , vol. 10, no. 3, pp. 346-347, 1984. See e.g. http://www.netlib.org/toms/618.

I think this has been forgotten by mistake, or was it intentionally?

**Comment by t-sommer** [comment]
The enumeration is also broken up in 2.0.1:

<img width="658" alt="Screenshot 2020-01-14 21 39 00" src="https://user-images.githubusercontent.com/2453858/72380795-729e3300-3716-11ea-9153-490ce11c84eb.png">

**Comment by andreas-junghanns** [comment]
can we close this?

**Comment by chrbertsch** [comment]
Fixed with https://github.com/modelica/fmi-standard/pull/714
