### ISSUE TITLE
Check non normative text on pure discrete-time FMUs

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#704]
In FMI 2.0.1 we have the following non-normative text in remark 4 or section 3.1:

_This is an optional optimization for the master, the FMU must support all functions that are required for a continuous time FMU and should run in a master that treats it as such. If a pure discrete time FMU has state events and uses event indicators, it has to enter continuousTimeMode to evaluate these. In fact, it is no longer a Pure Discrete time FMU but this was not clearly defined in 2.0 so this clarification is needed for 2.0.1]_

Check that in FMI 3.0 we have a correction in the normative text and adapt or remove the normative text

**Comment by chrbertsch** [comment]
(The original issue was #409)

I consider it problematic that "pure discrete time FMU" seem to be only defined in non-normative remarks:
- remark 2 of 3.1.2, which deals with "discrete-time FMUs" without the "pure". Is this the same?
- remark 4. of 3.1.2 ![grafik](https://user-images.githubusercontent.com/16363372/75062762-bfc6af00-54e3-11ea-9873-165f663c4176.png)

but then we refer to this definition in normative text (footnote of the table at the end of 3.2.3
![grafik](https://user-images.githubusercontent.com/16363372/75064048-7af04780-54e6-11ea-9dfc-0cf31391c940.png)

I see the following alternatives for FMI 3.0:
- Correct the definition in the remark 4 to "If an FMU has only discrete-time equations (and no variables with variability = continuous **_and no state events and event indicators_**), ..." But still this then should be move to a normative text part
- get completely rid of the definition of "pure discrete-time FMUs", as in FMI 3.0 there are new ways to express discrete-time systems like clocks and the new FMU type SES

I would favour the second option.  Or do I miss something? Or other suggestions?

**Comment by chrbertsch** [comment]
FMI Design Meeting: 

Torsten B: We should get rid of the remark.  
If we have the continuous states or not we use the same the same state machine ...
This makes it hard to check the calling sequence.
Andreas J.: This is an unnecessary simplification that does not ease implementation.
Torsten B: this exception breaks the logic of the state machine
In the current state machine we do no longer have this shortcut.

Poll: Shall we remove the definition of "pure discrete states" and get rid of the exception in the state machine?
Yes: 7
No: 0 
Abstain:5

@andreas-junghanns : will fix it

**Comment by andreas-junghanns** [comment]
I created PR #844 to address this issue.

**Comment by chrbertsch** [comment]
Fixed with #844
