### ISSUE TITLE
Confusing rules for clock input/output causality

### ISSUE THREAD

**Issue by nickbattle** [modelica/fmi-standard#707]
The table that defines default initial values in section 2.2.10 has confusing causality columns, with two input/outputs?

The table above it that defines causality types does have two entries for "input" and "output", the second pair of which seem to be to do with clocks specifically. I note the (F) and (G) cases are only for "clock" variability, but why are these not in the same column as the other input/outputs?  Ditto for the table defining legal combinations - the (18) case does say that these are clock variables, but I cannot see the significance of the separate columns.

(Note, I am working together with Claudio Gomes and Casper Thule from Aarhus University, who will join the design meeting in the end of February).

**Comment by andreas-junghanns** [comment]
I am on it for in a different ticket...

**Comment by nickbattle** [comment]
OK, thanks. I did search for this, but couldn't find an open issue dealing with it.

**Comment by APillekeit** [comment]
> The table that defines default initial values in section 2.2.10 has confusing causality columns, with two input/outputs?
> The table above it that defines causality types does have two entries for "input" and "output", the second pair of which seem to be to do with clocks specifically. I note the (F) and (G) cases are only for "clock" variability, but why are these not in the same column as the other input/outputs?  Ditto for the table defining legal combinations - the (18) case does say that these are clock variables, but I cannot see the significance of the separate columns.
> (Note, I am working together with Claudio Gomes and Casper Thule from Aarhus University, who will join the design meeting in the end of February).

This is just a leftover from the renaming of causality "inferred" and "triggered" to "input" and "output". The table needs to be updated.

**Comment by IZacharias** [comment]
The unnecessary columns have been removed with #938 . Ticket can be closed.
