### ISSUE TITLE
ME state machine API table missing (re)configuration mode

### ISSUE THREAD

**Issue by nickbattle** [modelica/fmi-standard#708]
Section 3.2.3, Fig.6 defines the state machine for ME, which includes a Configuration Mode and Reconfiguration Mode. These are discussed in the text after the figure, but they are not included in the columns of the API table at the end of the section (which together with the 1-7 qualifiers, provides clear unambiguous rules for each API in each state).

The table heading still refers to FMI2, though the API calls do start with "fmi3" - but this is probably just a global replace (eg. it refers to fmi3GetReal, which no longer exists).

**Comment by chrbertsch** [comment]
@nickbattle : could you please propose a PR to fix this?

**Comment by nickbattle** [comment]
When I get a minute :)
