### ISSUE TITLE
CS state machine API table missing various states

### ISSUE THREAD

**Issue by nickbattle** [modelica/fmi-standard#709]
The CS state machine in 4.2.1 includes various states that are not included in the API/state table at the end of the section: (Re)Configuration Mode, and Intermediate Update Mode are not present, while Step In Progress and Step Cancelled are in the table (but which no longer exist).

The API function names also need to be updated in the table - like fmi3GetReal.

**Comment by CThuleHansen** [comment]
Interestingly, this also holds the other way around. The table has states that are not listed in the state machine :)
