### ISSUE TITLE
Scheduled Execution state/API table missing

### ISSUE THREAD

**Issue by nickbattle** [modelica/fmi-standard#711]
Section 4.2.5 defines the state machine for Scheduled Execution Simulation, which includes some new states, but there is no API table (unlike the other state machine sections) that gives clear set of rules about which APIs are allowed in which state. This would be useful and consistent.

There are "allowed calls" and "forbidden calls" listed in different states in the text, but these do not mention every API.

**Comment by chrbertsch** [comment]
The text represenation is there, the table will be created later.
Everyone is welcome to create the table! @nickbattle : could you or your colleagues perhaps create a Pull request?

**Comment by nickbattle** [comment]
I've created a PR, but it only includes some of the rows of the table at the moment.

(I can't find the option here to allow anyone to contribute to the pull branch?)

**Comment by chrbertsch** [comment]
> (I can't find the option here to allow anyone to contribute to the pull branch?)

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by nickbattle** [comment]
I did read the help(!), but the option it refers to isn't on the page when I open the PR - nor when I created the PR itself, as far as I recall. Strange.

**Comment by nickbattle** [comment]
I just see this... 

![Screenshot-2020-2-10 Added table for Scheduled Execution Simulation by nickbattle · Pull Request #743 · modelica fmi-standard](https://user-images.githubusercontent.com/1751423/74193173-cf760600-4c4e-11ea-99f1-be1df3aa7ed3.png)

**Comment by CThuleHansen** [comment]
@chrbertsch I think this issue is related to the fork being under another organisation, into-cps-association. However, we are looking into this, otherwise we will add you to the into-cps-association/fmi-standard fork as a write-member.
