### ISSUE TITLE
Large tables waste a lot of space

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#716]
Some of the tables are badly formatted and waste a lot of space.

By turning the left cells of a line into a heading the cells are listed in the table of content.

**Comment by andreas-junghanns** [comment]
I have trouble merging master into my changes... I am not sure why I get so many conflicts. Help would be appreciated.

**Comment by t-sommer** [comment]
> I have trouble merging master into my changes...

Can you share a link to the branch or open a PR?

**Comment by andreas-junghanns** [comment]
PR #716 is addressing this

**Comment by andreas-junghanns** [comment]
We (Torsten and I) looked at the result and did not like it. At the very least, it is not clearly better than the table solution because tables allow easier location in the text, while headings seem to get lost in the pages and pages of text.
