### ISSUE TITLE
Introductory section to clocks

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#723]
Regular design meeting: 
Andreas J: We need non-nomative text to explain the difference of different clock types.
This should not describe the individual types individually but compare their differences and abilities and disadvantages.
Torsten S.: We also need examples / reference FMUs for this. This goes hand in hand

**Comment by friedrichatgc** [comment]
I also miss a clear definition when a periodic clock ticks the first time.
2.1.8 Periodic Clock Ticks states
"the base clock starts at the start of the simulation tstart or when the controller is switched on plus an offset time toffset"
A clock must have a well defined start time so their cannot be a OR condition for its start. And what does "when the controller is switched on" mean? When is the controller switched on?

Section 2.2.4 has a more precise definition but I still miss a clear definition of the "offset". An offset to what? The simulation start time? The time 0 of the independent variable?, ...

**Comment by chrbertsch** [comment]
@masoud-najafi I will work with @APillekeit  and @IZacharias  on examples and explanation

**Comment by andreas-junghanns** [comment]
@friedrichatgc : Can you provide a PR for the issue you raise "miss a clear definition when a periodic clock ticks the first time"?
Or can I close this ticket?

**Comment by masoud-najafi** [comment]
What we need to make sure that the FMU has got the possibility to declare its very first time-event (clock tick time).
In FMI-2, after ExitInitialization the FMU systematically goes to the event-mode and an event is programmed at T_offset (if any event exists). But recently the FMU goes to Continuous-time mode. I do not know how the first event can be programmed, maybe in ExitInitialization?

**Comment by APillekeit** [comment]
@masoud-najafi: Just an idea: After reading the last master version of the documentation on Github it is currently not clear for me if fmi3Set/GetClock() can be called in Initialization Mode (it is not allowed or forbidden). If these functions can be called (probably useful for networked FMU init, right?), these functions may be used to retrieve initial output clock ticks of an FMU and the master can enter the Event Mode from the Continuous Time Mode for that FMU. If the master calls fmi3DoStep() without handling initial output clock ticks the callback will signal the output clock tick if present at tstart in the FMU anyhow.

Nevertheless I also think it is still required to define in a better wording when the periodic clock ticks the first time and what the base time for the offset is. I do not understand the sub sentence "or when the controller is switched on" either - if it is from the initial version from several years ago, maybe @KarlWernersson can say something about it?

**Comment by masoud-najafi** [comment]
Hi Andreas (@APillekeit),
Happy to see you here again and still interested in FMI. Yes, before entering StepMode,  we need to retrieve the first event/clock times. But, I am not sure, if it is useful during "initilalization", because the input/output of the FMU may change and and the stable inputs are known only  at ExitInitialization. Sue, there is something missing here and should be fixed.

**Comment by chrbertsch** [comment]
Ticket-viewing meeting

This ticket is to unspecific. Re-open with concrete proposals if necessary
