### ISSUE TITLE
Add new Co-Simulation "modes" to fmi3InterfaceType enum

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#725]
since they're mutually exclusive (as proposed at the Regular Design Meeting 2020-02-24)

**Comment by chrbertsch** [comment]
I think this is fixed with https://github.com/modelica/fmi-standard/pull/728 
@t-sommer: can we close this?

**Comment by andreas-junghanns** [comment]
Yes, this is done and merged.
