### ISSUE TITLE
Aliases and start values for variability constant

### ISSUE THREAD

**Issue by APillekeit** [modelica/fmi-standard#729]
The specification states in 2_2_common in line 1774ff:
```
. At most one variable of the same alias set of variables with <<variability>> = <<constant>> can have a <<start>> attribute _[since <<start>> variables are independent initial values.]_ 

. A variable with <<variability>> = <<constant>> can only be aliased to another variable with <<variability>> = <<constant>>.
It is then required that the <<start>> values of all aliased (constant) variables are identical.
```

If the term "alias set" has a special meaning, a definition would be helpful.
If it is just a set of aliased variables it seems that the two points descibe two different solutions for the same problem. You either allow only a start value for one variable of the set or you enforce that all variables of the set have the same start values - in case of variablity equals constant.

**Comment by nickbattle** [comment]
I agree that the text is as you quote in the FMI3 spec. But the equivalent in FMI2 has a "not equal" for the first bullet. This is also how I've interpreted the rule in the VDM model. Does that help? (ie. there is a typo in FMI3 regarding the "=" sign).

2. At most one variable of the same alias set of variables with variability ≠ "constant" can have a
start attribute.

**Comment by t-sommer** [comment]
@APillekeit, does this problem still exist with the definition of "alias set"?

**Comment by APillekeit** [comment]
> @APillekeit, does this problem still exist with the definition of "alias set"?

Not for me, the correction of equal to unequal sign made it clear for me. Now an alias set is just a set of aliased variables as defined by language. So this is fine for me.
