### ISSUE TITLE
Aliases and Dimensions for array variables

### ISSUE THREAD

**Issue by nickbattle** [modelica/fmi-standard#731]
Presumably all variables of in the same alias set (ie. with the same valueReference) would have to have the same Dimensions settings, if the value is an array? If so, this should be added to section 2.2.10 where the restrictions on aliases are described.

**Comment by pmai** [comment]
I agree.

**Comment by nickbattle** [comment]
OK, thanks @pmai. I'll try to prepare a PR for this to check that I'm able to - not submitted one yet.

**Comment by chrbertsch** [comment]
Fixed by https://github.com/modelica/fmi-standard/pull/748
