### ISSUE TITLE
logMessage #vref# behaviour with aliases

### ISSUE THREAD

**Issue by nickbattle** [modelica/fmi-standard#732]
Section 2.1.5 describes the expansion of `#<valueReference>#` values into the name of the referenced variable in log messages. But if the value reference has an alias-set of variables, which variable's name is substituted? Is one is chosen arbitrarily or is it maybe an error to attempt this?

(I think this is also a question with FMI2 - the fmi-sdk seems to pick the first SV it finds with the right vref)

**Comment by pmai** [comment]
As you say, the importing implementation has no way of knowing which of multiple variable names to choose here, as discussed in #435, esp. my comment https://github.com/modelica/fmi-standard/issues/435#issuecomment-433656106. So it will pick an arbitrary name.

It was decided that the ability for FMU exporters to not have to place knowledge of variable names into exported code was deemed more important than removing this complex mechanism with its draw backs. As such I think the rationale for this decision and the consequences should probably be pointed out in non-normative text, A pull request would probably be appreciated.

**Comment by chrbertsch** [comment]
Regular design webmeeting:
A discussion has started if "alias variables" should refer to a variable that is no not an alias. This could then also resolve this issue. @klausschuch plans to create a proposals.
