### ISSUE TITLE
Dimensions and valueReferenced sizes

### ISSUE THREAD

**Issue by nickbattle** [modelica/fmi-standard#733]
The document says (section 2.2.10) that a Dimension size can be specified by a valueReference to a constant or structuralParameter variable.

It says that the variable must be of "integer type". Does this mean any signed or unsigned "Int" type from 64-bits to 8-bits? It later says that they must be positive integers, though perhaps that is a value constraint rather than a type constraint (ie. Int32 could be fine, but perhaps requiring a min value of >=0)?

It also says that reconfiguration changes to the Dimension via the structuralParameter are constrained by that variable's min/max. Does this mean the valueReference may not have an alias-set (since these are permitted to have different min/max values for members of the set)? Or are changes constrained by the "overall" limits of the alias-set, similar to setting values of aliased variables, where I think the most restrictive min/max of the set applies?

**Comment by pmai** [comment]
I think this just reflects the old world where there were only fmi2Integer variables. Given that fixed dimension values are xs:unsignedInt (i.e. fmi3UInt32), I would say that they should all have to be fmi3UInt32 types (and/or the fixed dimension type needs to changed as well).

As to the aliasing, I think the limits should work the same between structuralParameters and other variables, and the sentence probably was originally intended to mirror that.

I think a PR to this effect would be appreciated.

**Comment by chrbertsch** [comment]
see PR https://github.com/modelica/fmi-standard/pull/734

**Comment by nickbattle** [comment]
PR created.
