### ISSUE TITLE
Automatic conversion from FMI 2.0 word document to FMI 3.0 adoc document seems to have a problem with unequal signs beeing changed into equal signs

### ISSUE THREAD

**Issue by APillekeit** [modelica/fmi-standard#735]
I don't know how big this problem is. 
But issue #729 is the second occurrence of this problem after an issue we found in the state machine description of FMI 3.0. It might be worth checking all unequal signs in FMI 2.0 and compare their occurrence in FMI 3.0.

**Comment by chrbertsch** [comment]
Please compare with FMI 2.0.1. :-)
If I remember well, there was at least one bug with an exchanged equal to unequal sign in FMI 2.0 that was fixed in 2.0.1
