### ISSUE TITLE
Attribute "previous" missing in fmi3Variable.xsd

### ISSUE THREAD

**Issue by friedrichatgc** [modelica/fmi-standard#738]
The specification defines an attribute called "previous" for clocked state variables. However, the fmi3Variable.xsd file does not contain a definition for such an attribute.

**Comment by andreas-junghanns** [comment]
AndreasP: This might have slipped your attention. Can you comment at least before you leave?

**Comment by andreas-junghanns** [comment]
Web design meeting: we cannot see why such an attribute is needed (we think it is a leftover of some version of the clocks). We will drop this from the text. See issue #853 for the same issue.

**Comment by chrbertsch** [comment]
@KarlWernersson : will check this again

**Comment by andreas-junghanns** [comment]
@KarlWernersson : any progress here?

**Comment by KarlWernersson** [comment]
@andreas-junghanns : Not yet

**Comment by chrbertsch** [comment]
(Andreas J, Christian B)
@KarlWernersson : would you please propose a PR for the design meeting?

**Comment by andreas-junghanns** [comment]
Karl: This is from the synchronous Modelica. "previous" is the previous value of a state before the clock tick during super-dense time.
Klaus: Why do we need this if we know the current value?
Otto: During algebraic loops, you reset the discrete states, using the previous.
Klaus: Why not have this in master?
Karl: The original FCP describes this...
Klaus: What is previous?
Karl: It is the value of the state of the previous super-dense time instant.

Andreas: Conclusion: We currently see no use-case for the previous value that the master cannot store the previous value itself. Unless we find a use-case where the master cannot know the "previous" value, we should not shift the burden on the FMU to provide this value "just-in-case".
