### ISSUE TITLE
Use UInt64 for attribute "start" in element "Dimension" 

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#740]
to allow large arrays on 64-bit machines where `size_t` is `unsigned long long` (see also #736).

**Comment by andreas-junghanns** [comment]
Go!

**Comment by pmai** [comment]
This should then also change all other definitions of array dimension variables, to provide a consistent set of definitions, right? I.e. all array dimensions will then be 64bit uint, on both 32 and 64 bit platforms.
