### ISSUE TITLE
4.2.4 State: Intermediate Update Mode - wrong diff to 4.2.1.4.6

### ISSUE THREAD

**Issue by CThuleHansen** [modelica/fmi-standard#762]
In 4.2.4 State: Intermediate Update Mode 
it is stated that fmi3DoEarlyReturn differ from 4.2.1.4.6 (Which I think should be 4.2.1.4.7)

I do not understand why fmi3DoEarlyReturn differ from 4.2.1.4.6 (4.2.1.4.7) as fmi3DoEarlyReturn is also allowed in fmi3CoSimulation. 

Is it a mistake in the text, or do I misunderstand?

**Comment by andreas-junghanns** [comment]
We need to move these descriptions to this in 3.1 Common Concepts/FMI API.
This is a similar task to #992.

**Comment by andreas-junghanns** [comment]
This mechanism and all descriptions where updated.
@CThuleHansen : Can you have another look and see if this is solving your issue? If not: Please let us know what is wrong, best: create a PR!

**Comment by chrbertsch** [comment]
This ticket was creatd before the complete restructuring of the xCS Descriptions. I do not understand it and think it has been fixed.
@CThuleHansen : please check and re-open, if it persists
