### ISSUE TITLE
Enable DAE Support in future releasese

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#784]
Is FMI 3.0 suited fro future extension for DAE support, e.g. in a FMI 3.1 release? 
Seen from now: Do we need to change something in FMI 3.0 to make this possible?
Or would this require a 4.0 release?

(see the DAE-working group material at 
https://github.com/modelica/fmi-design/tree/master/WorkingGroups/02_DAE_PartialDerivatives)

**Comment by friedrichatgc** [comment]
The latest proposal for DAE maps well to the current FMI 3.0. For now I do not see any reason why this may not be added to a FMI 3.1 version.

However, the topic regarding discrete event handling (especially discrete continuous state changes during events) is still fully open for DAE. This may even need some research. Hence, regarding this topic is not possible for now to make a statement what will be needed in the future to support this.

**Comment by chrbertsch** [comment]
> The latest proposal for DAE maps well to the current FMI 3.0. For now I do not see any reason why this may not be added to a FMI 3.1 version.

Closing this ticket as there is no action to be taken for FMI 3.0 and we have a draft FCP and interested people are welcome to join and revive the DAE working group.
