### ISSUE TITLE
Do we still need a reference to "FMI for PLM"?

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#787]
In 2.1.5 for fmuResourceLocation, there is a reference to "FMI for PLM": "Reserved: fmi3 for FMI for PLM." without any reference to a specification for "FMI for PLM"

Do we still need this? Is "FMI for PLM" still alive? (Or was it ever?)

Google finds https://svn.modelica.org/fmi/branches/public/specifications/v1.0/FMI_for_PLM_v1.0.pdf  but does anyone use this?

I propose to delete "Reserved: fmi3 for FMI for PLM." in 2.1.5.

**Comment by andreas-junghanns** [comment]
I think this is clear: just to avoid confusion, we must not have fmi3 mean PLM. I agree with removing this entirely.

**Comment by chrbertsch** [comment]
Closing as the reference to "FMI for PLM" was removed in #796.
