### ISSUE TITLE
Maybe use numbered environments in the standard and adopt more rigorous language

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#795]
In the standard, there are multiple helpful environments, such as non-normative text, example, etc.
In technical document, these are normally done with numbered environments.
For example:
```
Definition 1. FMU. An FMU is...
Example 1. Consider the following master algorithm.
Remark 2.1. fmi3Get is not allowed after a fmi3Set without a doStep in between.
```

The beauty of using these is that they can be referred to explicitly throughout the text, without having to refer to a section, without using hidden links, and reducing the redundancy (and therefore inconsistencies) in the text. The current links are problematic as it is not clear to the reader whether they exist or not (without hovering the mouse over them). 
The same applies for references to figures and tables, which should always be explicit (that is, don't use expressions like "Table below").

We could also adopt a more rigorous language (this is not a personal critique to whomever worked hard on the standard... it's all too easy not to be rigorous :p), being careful to define new terms before they are used (using definition environments), or using a table for all terms used.

I could offer some time to improve the text in this way, once there is some consensus about portions of the standard. Naturally, we will need multiple pairs of eyes checking for ambiguities. Words such as "this", "it", should be avoided, and the use of synonyms should be forbidden, except when defining a new term. 

This is related to #650 but affects the content in a more drastic way, and #459

**Comment by chrbertsch** [comment]
@clagms : before applying this to the whole document: Could you prepare individual examples or PRs how this would look like (for figures, equations, ...)?

**Comment by andreas-junghanns** [comment]
@clagms: Are you still planning to propose this? We tried a while back and the PR proposal is still around and the result wasn´t just ugly, it was totally unreadable for humans. Navigation is impossible, the TOC explodes. I am not sure either it helps you, because if we add something the numbering changes, right? Please comment and preferably close this ticket.

**Comment by clagms** [comment]
I am still planning this @andreas-junghanns , but no actual work done here yet. I'm sorry I haven't been very responsive on this. I'm trying to formalize the hybrid cosim interfaces first.

>We tried a while back and the PR proposal is still around and the result wasn´t just ugly, it was totally unreadable for humans.

Can you please point me to that PR? I can take a look and it will help me get a feel for what you are saying.

>Navigation is impossible, the TOC Explodes.

Maybe I'm missing something, but I don't understand why the navigation is impossible.
I think that these environments do not have to show up in the TOC.
So, for instance, if we have the text:
```
[[bookmark-def]] Definition 1.  FMU. An FMU is bla bla bla.
```
and later we wish to remind the reader of what an FMU is, we ought to write something like:
```
... the tool exports an FMU (see Def. <<bookmark-def>>)...
```
and this should be rendered to something like:
```
... the tool exports an FMU (see Def. 1)...
```
where the reader could click on "Def. 1" and go to Definition 1.

Why does this make navigation harder?

**Comment by andreas-junghanns** [comment]
Check here: andreas-junghanns/#716_tables_to_headings.

Just imagine how many definitions you would have to introduce: How would you even validate that your references point to the correct place?

But: Let us not discuss this. Pick a good spot, work it out there and show us. Then we can discuss your approach seeing what you really have in mind.

**Comment by clagms** [comment]
FMI Meeting (discussion with @andreas-junghanns):
- Definitions are not numbered and go to glossary. The reader will implicitly know where to look for them.
- Figures and tables should have numbers and be referred to explicitly by those numbers (e.g., avoid use "see figure above").
I'll prepare a PR for this with the glossary.

**Comment by clagms** [comment]
I started working on https://github.com/modelica/fmi-standard/pull/1044  for this, focusing on references to tables, figures, and code.

**Comment by andreas-junghanns** [comment]
> 
> 
> > But: Let us not discuss this. Pick a good spot, work it out there and show us. Then we can discuss your approach seeing what you really have in mind.
> 
> @andreas-junghanns , could you have a look at #1044 ? That's 50% of the work needed to improve ambiguous references. The other 50% require a more continuous improvement of the text towards less "loose" references.

Good work - let´s not wait until all is done but merge this part already and then create another PR for the second 50%
