### ISSUE TITLE
Clarify the meaning of unbounded

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#798]
The description of unbounded is:
```
If true, indicates that during time integration, the variable gets a value much larger than its nominal value nominal. [Typical examples are .... This information can, for example, be used to increase numerical stability and accuracy by setting the corresponding bound for the relative error to zero (relative tolerance = 0.0), if the corresponding variable or an alias of it is a continuous state variable.]
```
But the meaning of "much larger" is not specified anywhere else. How does one know that an FMU implements this attribute correctly?
If the intent is to use relative error = 0, then we should place the non-normative text as normative text.

**Comment by pmai** [comment]
What clarification do you think is possible here? I'm asking earnestly, since this gives a heuristic hint, and thus is unlikely to be amenable to formalization, even more so in a way that makes this testable. But feel free to surprise me.

**Comment by clagms** [comment]
@pmai I'm sorry that my suggestion was not clear enough:
>If the intent is to use relative error = 0, then we should place the non-normative text as normative text.

In other words, rewrite the meaning of unbounded to be: "If the master algorithm uses any error estimation on this variable, then the relative tolerance should be 0".

**Comment by pmai** [comment]
That is not a clarification, that changes the meaning. Unbounded currently talks about the expected magnitude of a variable, which might give you cause to do many things, error treatment included.

It might first be interesting to discuss the utility of the current definition, and whether it makes sense to drop the attribute completely, maybe... Id replace it with another mechanism, like the ability to directly provide per variable relative error specs...

**Comment by andreas-junghanns** [comment]
I am starting to get worried when I read such fundamental discussions so close to us trying to finish 3.0. @clagms: Are you in Berlin tomorrow?

**Comment by chrbertsch** [comment]
I propose to keep the heuristic hint as it is for FMI 3.0.
Shall we close this ticket?

**Comment by andreas-junghanns** [comment]
I agree: leave as is and close. Reopen, if you do not agree.
