### ISSUE TITLE
use enum in header files for fmi3Clock  and fmi3Byte

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#805]
Instead of defining 
typedef            char fmi3Byte;   
typedef             int fmi3Clock ;  
in the header files, it would be more efficient if we define:

typedef enum {fmi3False=0 , fmi3True }  fmi3Byte;   
typedef enum {fmi3ClockInactive =0 , fmi3ClockActive} fmi3Clock ; 

This has the advantage that the comiler can check the values.

**Comment by chrbertsch** [comment]
@pmai : Could you please comment this?

**Comment by andreas-junghanns** [comment]
web design meeting: We cannot see the benefit to introduce these new enum types.
