### ISSUE TITLE
Update intermediate variable access figure

### ISSUE THREAD

**Issue by robbr48** [modelica/fmi-standard#812]
- Remake figure in draw.io
- Remove the minor arcs, since they are confusing and assuming a Runge-Kutta style solver
- Add arrows on the major arcs, to indicate that the FMU is not allowed to invoke the `inermediateUpdate` callback for previous points after invoking it with `stepFinished=true`
- Rearrange minor points into a more irregular pattern

**Comment by andreas-junghanns** [comment]
@robbr48 : any news here?
