### ISSUE TITLE
Consistency of section headings

### ISSUE THREAD

**Issue by CThuleHansen** [modelica/fmi-standard#819]
Ensure consistency between the section headings.

**An example:**
Model Exchange is called: 
FMI for Model Exchange
But the co-simulation related ones are:
Basic Co-Simulation
Hybrid Co-Simulation
Scheduled Co-Simulation.

Propose to skip `FMI for`. It is redundant

**There are other cases in the standard.**

**Comment by CThuleHansen** [comment]
Rename Basic Co-Simulation to FMI for Basic Co-Simulation
Rename Hybrid Co-Simulation to FMI for Hybrid Co-Simulation
Rename Scheduled Co-Simulation to FMI for Scheduled Co-Simulation
Rename 3.2 FMI Application Programming Interface to 3.2 Application Programming Interface

**Comment by CThuleHansen** [comment]
@chrbertsch assign me to this issue please

**Comment by CThuleHansen** [comment]
Fix labels

**Comment by chrbertsch** [comment]
closed by #826
