### ISSUE TITLE
Shall BCS support Invermediate Variable access and Early return?

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#836]
Or should such "advanced" co-simulation features be moved to HCS?

These questions were raised in comments to different tickets (#797 #820,  #821) , so I created this new ticket to avoid a discussion split over several tickets.

Arguments:

Pro:
- This is what we decided and what is on the  current master branch. Why change it again?
- These two features do not require EventMode (with all the consequences like direct feedthrough at events). So BCS with this feature is more advanced than FMI 2.0 CS, but less advanced than HCS.
- IVA can be used in BCS also only for plotting with more information than only communication points (no advanced co-simulation)
- Early return is a simple extension of FMI 2.0 CS without complex event handling

Contra:
- keep BCS simple

... Plesae extend the list (you can edit this texts or comment)

**Comment by jbernalr** [comment]
> So, do we allow advanced features like early return in Basic Co-Simulation?

I would say, according to my memory of the discussions, no we dont. 
What we do is, that we allow Co-Simulation with Early Return capability to be used as Basic Co-Simulation as well. (At least this is the functionality I would like to have as a user)

|   | Basic Co-Sim **FMU** | Early Return Co-Sim **FMU** |
| ------------- | ------------- |------------- |
| Basic Co-Sim **Master**  | Yes  | Yes (as basic CS)  |
| Early Return Co-Sim **Master**  | Yes (as basic CS)  | Yes |

**Comment by chrbertsch** [comment]
> What we do is, that we allow Co-Simulation with Early Return capability to be used as Basic Co-Simulation as well.

Which FMU type does a "Early Return Co-Sim FMU" have? BCS or HCS?

**Comment by jbernalr** [comment]
> Which FMU type does a "Early Return Co-Sim FMU" have? BCS or HCS?

Not a BCS. 

There may be however more than one of the remaining types supporting/using early return

**Comment by chrbertsch** [comment]
> > Which FMU type does a "Early Return Co-Sim FMU" have? BCS or HCS?
> 
> Not a BCS.
> 
> There may be however more than one of the remaining types supporting/using early return

Which ones? ME and SCS do not have a doStep from which to return early, right?

**Comment by APillekeit** [comment]
The state of the discussion up to now was: Intermediate Variable Access is available for all Co-Simulation modes since it is a realtivly orthogonal to the simulation interface types. It can be turned on and off in each co-simulation interface type and the fundamental way of simulating the FMU would not change, only additional information can be transported.

**Comment by chrbertsch** [comment]
Regular design Webmeeting: 
Andreas: IVA is orthogonal and optional from both ends, so it does not hurt in BCS.
--> Agreement
Markus: this has an influence on #794, where a PR has to be created: If we have IVA in BCS, we may use this mechanism for interpolation of inputs. 
Andreas: I thought input derivatives are a simple way of extrapolating.
Markus: Do we want to use input derivatives for FMUs that do not allow for IVA? Should we allow for two features that do more all less the same?
Claudio: There is the legacy aspect, people hat FMI 2.0 master algorithms using input derivatives.
Markus: I think it is similarly simple.
Andreas: Are there derivative information for IVA?
Markus: do not think so.
Markus: We should collect the use cases
Andreas: We could also forbid IVA in BCS to be similar to FMI 2.0.
Claudio: I think I can do the same as IVA in FMI 2.0 with a smaller stepsize
Markus: then you would exchange the real values, not just an extrapolation.
Andreas: IVA is orthogonal and can be ignored.
Markus: we should discuss in #794  whether to remove the input derivatives.
Claudio: where is the callback implemented? in the master or an FMU?
Markus:  Normally in the master.
Christian: Even if we remove the input derivatives, we would keep the output derivatives so that the master can create the intermediate variable inputs for an FMU
Andreas: I still wonder if he have to drop the input derivatives. 
We want BCS as close to FMI 2.0 CS simple.
Markus: I could use for my uses cases either IVA or input derivatives
Markus: Removing Input derivatives would make BCS simpler. (And one can use IVA for the intention of input derivatives)
Claudio: the interpolation moves to the master
Pierre: what is the benefit of removing from BCS?
Andreas: I would keep it.
Pierre: BCS should be easy for the FMU and the master.
Pierre: one should write the understanding as non-normative text
"BCS should be close to FMI 2.0 CS. To keep simplicity we keep input derivatives. But IVA is **orthogonal and optional and can be easily ignored.** Thus it is added to BCS. BCS should work for 80% of the cases.  This offeres an easy migration path. (This can be a general reational to include features in BCS). "

Poll:
Keep input derivatives in BCS (additional to IVA)?
Yes: Andreas, Claudio, Masoud, Martin, Pierre
No: -
Abstian: Christian, Markus

@friedrichatgc : i will make a proposal

**Early return**
Masoud: this is a matter of taste, whether one wants to keep BCS simple.
Andreas: We saw that people do not use ME, because it is too complicated. 
Let us apply the rationale from above:
"BCS should be close to FMI 2.0 CS. To keep simplicity we keep input derivatives. But  XXX is **orthogonal and optional and can be easily ignored.** Thus it is added to BCS. BCS should work for 80% of the cases.  This offeres an easy migration path. (This can be a general reational to include features in BCS). "
Andreas: we should have a capability flag for early return, we should check.
There is "canReturnEarlyAfter ...." but that is a different thing
Markus: If you have Discard in FMI 2.0 one can query the last succesfull time? 
Claudio: in FMI 2.0.1

> "fmi2Discard - if the slave computed successfully only a subinterval of the communication step. The master can call the appropriate fmi2GetXXXStatus functions to get further information. If possible, the master should retry the simulation with a shorter communication step size. [Redoing a step is only possible if the FMU state has been recorded at the beginning of the current (failed) step with fmi2GetFMUState. Redoing a step is performed by calling fmi2SetFMUState and afterwards calling fmi2DoStep with the new communicationStepSize. Note that it is not possible to change currentCommunicationPoint in such a call."

Claudio: figure 12 shows that with Early return one does not have to roll back in case of an unsucessful step.
Claudio: this works, if the master is sure that only one FMU has this early return.
Andreas: what do we do with FMUs that do not have rollback.
Pierre: We have many use cases, where only one FMU is included in a larger simulation model.
It would also help if you have multiple FMUs with restart capability but one FMU cannot: then it would also help if this FMU can do early return.  One example is if this FMU has interaction with the real world. I think is more useful than one  thinks.
Cladio: An dealing with events is for HCS?
Masoud: this reason I would move Early return to HCS.
Markus: for many tools it may be easier to stop a simulation at a point instead of implementing fmiget/setState.  This is an argument to have Early return in BCS
Claudio: This applies for FMUs in control loops.
Pierre: Early return w/o event handling makes sense in BCS.
Markus: it is similar to discard, but the FMU is in a defined state where one can continue from.
Discard needs a reset to continue.
Claudio: with discard, the FMU does not have to worry ... when you detect and unexpected event, you are already over the event time. You have to return the latest valid state before the event. 
Markus: Many tools with a variable stepsize intergrator have this feature.
Claudio: whoever writes a PR for this should write non-normative text with explanations.
Pierre: Early return in HCS has  the possibility to force the early return form the outside
When doing the PR, we should decide whether this makes sense in BCS.
Pierre: we could include this in BCS, but one can ignore it. The FMU shall stop as early as possible in a clean state.
Andreas: Master calls doStep. FMU wants to get intermediate inputs. Master tells the FMU to return early as possible.
Cladio: what would be the use case?
Pierre: Another FMU returned early.
Claudio: this is asynchronous. 
Pierre: in certain way, not in the way that the FMI interface is asynchronous.
Andreas: the asynchronous features are moved to the master in FMI 3.0
Klaus: Could be a user interaction
Masoud: if we want to implement this in HCS, do we have to implement all the HCS features?
Pierre: no, one can ignore it.
Claudio: in HCS one has to got to event mode and treat the events.
Markus: Early return will only work in BCS will only work when the FMU accepts new inputs after the early return.
Andreas: there are two cases: the FMU returns early, or it is returned early
Pierre: the effect is the same. 
This feature is similar to FMI 2.0 CS but more flexible and ignorable. 

Poll: Shall we have early return (initiated by the FMU or the master) w/o event handling as optional and ignorable feature in BCS? After the early return the FMU is in a defined state at a known time.
Yes: Andreas, Christian, Pierre, Claudio
No: Masoud
Abstain: Klaus, Markus, Martin

@pmai I am willing to do a PR, but will do so after the cleanup of HCS.

**Comment by APillekeit** [comment]
WG Clocks&HCS Meeting:  If we include FMU triggered early return into BCS we currently do not have a signal to transport to the FMU whether the master can/want to support early return in BCS.  
We need either a flag (to keep the feature ignorable): best option 
or we need to add that this feature is not ignorable.

**Comment by chrbertsch** [comment]
Regular design meeting

Torsten: Would allowing Early Return in BCS change the API?
Pierre: I would think that this is a subset of the HCS definition, would require only minor changes.

**Comment by pmai** [comment]
@APillekeit , @chrbertsch: After a quick review (only the BCS part, not looking at the HCS part) it seems to me that:

- Early Return in BCS can only be initiated by the master inside the intermediate update callback, by calling fmi3DoReturnEarly; hence no flag is needed to indicate whether the master wants to support this or not: It can avoid dealing with early return by just not calling fmi3DoEarlyReturn (or even more simple: not supplying an intermediate update callback, if it also does not want to deal with IVA).

- The current description of early return for BCS seems to state fairly clearly that fmi3DoStep will return with fmi3OK in this case, and earlyReturn=fmi3True, which distinguishes this from the discarded approach.

- The discarded approach currently being taken seems superior to the FMI 2.0 approach especially because it does not lead to undefined state. Whether the discarded support, by offering to retransition step state via fmi3EnterStepMode, kind of duplicates some of the early return functionality might be something to discuss in a seperate issue.

In summay all of the complexity can be completely ignored by a master, since it has to deal with fmi3Discarded anyway (it can just abort as it did in FMI 2.0), and other early returns will not happen without its cooperation.

I think the API can remain for now as is (there might be potential to clean up the whole fmi3DoStep vs. earlyReturn vs. GetDiscardedStatus vs. fmi3DoEarlyReturn API to be more explicit and less state-generating, but I think this is a seperate issue).

So I think this issue can be closed, and remaining issues (like do we want to clean up the API, does the newly introduced fmi3EnterStepMode support make sense in the face of early Return, etc.) can be filed as new issues.

**Comment by andreas-junghanns** [comment]
Thanks for the feedback and the analysis.
If we experts have difficulties to know what is allowed, normal readers are likely lost.
I like the idea described in #854 - a table with explicit descriptions will very likely help clarify this to the readers.

@chrbertsch - can we close this issue?

**Comment by chrbertsch** [comment]
A clarification of this topic as part of #854
