### ISSUE TITLE
Possible duplicate reference to fmi3RealVariableAttributes in fmi3Variable.xsd

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#837]
This happens to the definitions `fmi3Float64` and `fmi3Float32`.
The definition of `fmi3Float64`  is as follows:
```
	<xs:complexType name="fmi3Float64">
		<xs:complexContent>
			<xs:extension base="fmi3VariableBase">
				<xs:attributeGroup ref="fmi3Float64Attributes"/>
				<xs:attribute name="start">
					...
				</xs:attribute>
				<xs:attributeGroup ref="fmi3RealVariableAttributes"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
```
Note that it refers to fmi3RealVariableAttributes and fmi3Float64Attributes.
But fmi3Float64Attributes already refers to fmi3RealVariableAttributes:
```
	<xs:attributeGroup name="fmi3Float64Attributes">
		<xs:attributeGroup ref="fmi3RealAttributes"/>
		<xs:attribute name="min" type="xs:double"/>
		<xs:attribute name="max" type="xs:double"/>
		<xs:attribute name="nominal" type="xs:double"/>
	</xs:attributeGroup>
```

Is this intentional? Or shall we remove the reference to `fmi3RealVariableAttributes` from the definitions of `fmi3Float64` and `fmi3Float32`

**Comment by pmai** [comment]
This is a misreading: Note that fmi3Float64Attributes includes *fmi3RealAttributes*, **not** *fmi3Real**Variable**Attributes*, which is something different:

The XXXAttributes are for both types and variables, the XXXVariableAttributes are variable-specific attributes that do not occur in e.g. types.

**Comment by clagms** [comment]
Indeed thank you for spotting this @pmai !
