### ISSUE TITLE
Please clarify the name of the attribute "previous" in Discrete time state

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#853]
This issue comes as a result of a discussion on the solution to #738 .
The name "previous" conveys little meaning as to what this attribute should contain.

In the standard, it says: "Discrete-time states are listed in the ModelStructure and have the variable xml-attribute previous referring to the variable holding the previous value of the state."
I guess that "previous value" means the value of the discrete time state at the previous tick (in the same sense that $x_{j-1}$ refers to the previous value of $x_j$).
Is that correct? 

Or does "previous" mean the value at the previous super dense time instant?

**Comment by andreas-junghanns** [comment]
web design meeting: We could not find any "previous" anywhere in the history of the github repository. We cannot easily find out how it was introduced, we agreed to drop the this attribute from the text.

**Comment by andreas-junghanns** [comment]
Pierre will create a PR to remove this from the text. See also #738
