### ISSUE TITLE
Add feature matrix for interface types

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#854]
to give an overview of the differences and similarities of the four interface types

- Model Exchange
- Basic Co-Simulation
- Hybrid Co-Simulation
- Scheduled Co-Simulation

w.r.t. to the provided features

- solver included / external
- event indicators
- early return / intermediate update
- clocks
- direct feedthrough
- (please add more)

**Comment by chrbertsch** [comment]
Regular Design Webmeeting: 

Torsten : Have a general overview in the introduction.
It helps people e.g. to select the right interface.

Collection: 
* you either have no continuous states or a solver inside the FMU except for ME
* no direct feedthrough in BCS, clarify for HCS (see #793)
* event indicators
* event iteration
* continuous states

--> @t-sommer : I will create a PR

**Comment by andreas-junghanns** [comment]
The beginning is made, during web design meeting we discussed what we want to have in the text and table (references to concept descriptions). A new issue will be created to follow this: #865
