### ISSUE TITLE
Tag v3.0-alpha.3

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#856]
As discussed in the last Regular Design Meeting, I think it's a good point in time to tag a `v3.0-alpha.3` to synchronize the Reference FMUs and alpha implementations of importing and exporting tools.

Any objections?

**Comment by nickbattle** [comment]
I notice the fmiVersion attribute in all of the doc/examples is set to "3.0-dev" (apart from one "3.0-alpha"). Does this indicate that they are conformant to some 3.0-like schema, but not a specific release?
