### ISSUE TITLE
Add concise information on which functions must be defined

### ISSUE THREAD

**Issue by pmai** [modelica/fmi-standard#864]
While going over the current Alpha.3 draft, it seems to me that it would be a good idea to add a table that gives concise information on which functions must be defined by an FMU implementation, depending on the type and optional features of the FMU implementation. Currently this is as far as I can tell, not explicitly stated in a way that makes it easy to check whether everything needed e.g. for Basic Co-Simulation without Early Return and without IVA has been defined. E.g. is implementation for fmi3DoEarlyReturn needed in that case or not? Etc.

I might also be missing something that we decided at some prior design meeting on the need to define functions even if calling them is not supported, but again, if I'm missing that, it is not unlikely that non-design group members will have a harder time than necessary to ensure that everything is covered.

**Comment by nickbattle** [comment]
I agree this would be very useful, though it might be difficult to represent concisely? The "allowed function calls" tables after each state machine are a good start, though the tables are sometimes missing or incomplete (other issues catch this).

**Comment by t-sommer** [comment]
For simplicity (especially when linking statically) I propose to make the _implementation_ of all functions mandatory. The _behaviour_ however may be undefined if a function is not required by the provided interface, e.g. `doStep()` in Model Exchange.

**Comment by andreas-junghanns** [comment]
Result of discussion at FMI Design April 2020: We do require *all* ("every-f$%&-single") functions of a supported FMI interface type to be implemented and to return fmi3Error if called despite announcing to not support this feature.

**Comment by pmai** [comment]
![tenor](https://user-images.githubusercontent.com/91502/79875576-23892d80-83ea-11ea-8c42-fda7226a2a61.gif)

**Comment by t-sommer** [comment]
![oreally](https://user-images.githubusercontent.com/2453858/79875986-bcb84400-83ea-11ea-9917-3effb11ab74e.jpg)

**Comment by chrbertsch** [comment]
(Andreas, Christian)
Already fixed: 
There is already a sentence: `Especially it is required that all functions that are part of the specified FMI interface type are present, even if they are only needed for optional capabilities that the FMU does not support.` in https://fmi-standard.org/docs/3.0-dev/#fmu-distribution.
