### ISSUE TITLE
Add subsections on mathematical descriptions detailing feature matrix.

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#865]
In mathematical description subsection, there should be a subsubsection for each of the features in the feature matrix submitted in the PR https://github.com/modelica/fmi-standard/pull/862 and discussed in https://github.com/modelica/fmi-standard/issues/854

This subsubsection should make it clear why that feature is not supported or supported.

**Comment by andreas-junghanns** [comment]
Nothing has happened in the mathematical sections for long time.
I see little chance that we extend what we have there to define the current terms in the feature table that are not all mathematical either.
