### ISSUE TITLE
Store "Ports & Icons" information in a separate XML

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#870]
As discussed at the Regular Design Meeting on 2020-03-28, it makes sense to move the "Ports & Icons" (P&I) information to a separate XML document that can be used and versioned independently of FMI 3.0.

Pros:

- P&I does not require changes to the API (unlike the other features introduced in FMI 3.0)
- the development would not held be back by the (slow) release cycle of FMI
- P&I can be retro-fitted to FMI 2.0 (or even FMI 1.0)
- the complexity of FMI 3.0 can be reduced

Cons:

- (please add points here)

**UPDATE**: I've changed the title from ~Continue "Ports & Icons" as a layered standard~ because it was misleading. This issue is _not about removing_ P&I from FMI but keeping it separate from the FMI 3.0 schema, so it can be used elsewhere (e.g. in FMI 2.0.2).

**Comment by chrbertsch** [comment]
One could define a  new xml file with the "ports and icons" content and place it in a defined subdirectory of the /extra directory of an 3.0 FMU.

Additional Pro: 
- we would have blueprint for the usage of the /extra directory and the designs of layered standard, which would also promote these new concepts.

The goal would be to release this layered standard together with FMI 3.0 (or even earlier for FMI 2.0, the only requirement  for this would be 2.0.2 release that we could release almost immediately)
Thus for exporting and importing tools and end users, there is practically no difference compared to "ports and icons" being optional features of the "core" FMI 3.0 standard.
If exporting tools consider this feature important (which I do!) , they will ship their first 3.0 FMUs with the "Ports and Icons" content in the /extra directory.
 
The only parts that I would leave in the core FMI standard are the diagram.png, diagram.svg, icon.png and icon.svg files as defined in https://fmi-standard.org/docs/3.0-dev/#fmu-distribution

If there are enough people within the FMI project committing to contribute to this layered standard, we could  continue its development within the FMI project within a working group. (An alternative would be to create a new Modelica Association Project, but perhaps this will create too much overhead)

**Comment by chrbertsch** [comment]
Regular Design Meeting: 

We shall put this on the agenda for next weeks FMI regular design meeting.

Torsten S: We should consider enabling this for FMI 3.0
Christian S: This should be part of FMI 3.0
Torsten S: we could make a it a layerd standard and state in FMI 3.0 that this layerd standard must be supported. It would be good to have a separate document
Christian S: We could have to have a separate xml. 
Torsten: Then it would be independent. From the marketing it could still call it FMI 3.0
Christian S:  I have doubts if it will be maintained if it is not in the FMI 3.0 document.
Pierre: I think perhaps it has better chances to be maintained if it is documented separately.

**Comment by CSchulzeTLK** [comment]
I think the contra-arguments that the protocol is missing are:
- There will be another "Layered-Standard" anyhow. What is described in this proposal is just the minimum agreement we could find for an interface description. It is designed to be extended by other standards, and can be extended by vendors. So this baseline really should be part of the spec
- Compatibility with FMI 1 and 2 has to be checked before claiming it is
- A reference implementation for export and import of 1 and 2 should be done
- Need to define: At what point in time should the backward compatibility be broken when updating the FMI spec
- Clarify: Who has the final say in the decision making when releasing a separate document?


But after the discussion i would conclude: If everything narrows down to moving the elements "Terminals" and "GraphicalRepresentation" to a separate file, and not necessarily pursue the issues above, I don't see an issue from my side.

**Comment by CSchulzeTLK** [comment]
@t-sommer: What are your arguments against a simple solution? We could add the non-normative text "if you want to use the elements Terminals and GraphicalRepresentation in older FMI standards, place these elements as top-level vendor anntations in the fmiModelDescription."
Do you require the XSD?

**Comment by t-sommer** [comment]
The problem with Vendor Annotations is that they cannot be validated easily. A separate XML in a fixed position (e.g. `resources/terminals.xml`) would be easier to validate and version.

**Comment by chrbertsch** [comment]
> We could add the non-normative text "if you want to use the elements Terminals and GraphicalRepresentation in older FMI standards, place these elements as top-level vendor anntations in the fmiModelDescription."

Will the solution for FMI 2.0 be 100% compatible with the one for FMI 3.0? (E.g., due to array variables in FMI 3.0 etc. ) If not, the definition in the FMI 3.0 standard document for FMI 2.0 does not seem to be working.

**Comment by antvl** [comment]
These "pros" arguments do not hold:

- P&I does not require changes to the API (unlike the other features introduced in FMI 3.0)
Reponse: Who decided that if a proposal does not imply modifications to the API, it has to be put into a separate file?

- the development would not be held back by the (slow) release cycle of FMI
Response: The current proposal is fully ready. On the contrary, putting it out of the FMI standard will slow it down! Is it what we want?

- P&I can be retro-fitted to FMI 2.0 (or even FMI 1.0)
Response: that is not a reason to put it aside from the model description. And by the way it cannot be part of FMI 1.0 or 2.0, that are closed and finalized specifications. New versions (FMI x.0.y or x.y with x=1 or 2) are needed to take it into account.

- the complexity of FMI 3.0 can be reduced
Response:  **we precisely designed this proposal to be the least complex of all the new features of FMI 3.0!!**! If complexity has to be reduced let's first begin by removing array variables with reconfiguration mode and the multiple and very complex "hybrid co-simulations".

**Comment by chrbertsch** [comment]
Regular design webmeeting: see discussion here https://github.com/modelica/fmi-design/tree/master/Meetings/2020-04-17-Regular-FMI-Design-Webmweeting#on-issue-httpsgithubcommodelicafmi-standardissues870-ports-and-icons-as-separate-xml-or-layerd-standard

**Comment by andreas-junghanns** [comment]
>     * P&I does not require changes to the API (unlike the other features introduced in FMI 3.0)
>       Reponse: Who decided that if a proposal does not imply modifications to the API, it has to be put into a separate file?
Re-Re: Please, this proposal is not a "has-to-be", but a proposal with good technical reasons that need discussion.
 
>     * the development would not be held back by the (slow) release cycle of FMI
>       Response: The current proposal is fully ready. On the contrary, putting it out of the FMI standard will slow it down! Is it what we want?
Re-Re: The argument is a different one. If you want to improve the P&I in the future, why bind yourself to the slow release cycle of FMI?

>     * P&I can be retro-fitted to FMI 2.0 (or even FMI 1.0)
>       Response: that is not a reason to put it aside from the model description. And by the way it cannot be part of FMI 1.0 or 2.0, that are closed and finalized specifications. New versions (FMI x.0.y or x.y with x=1 or 2) are needed to take it into account.
Re-Re: Why would that be a problem? We release 2.0.2 or 1.0.2 to allow for such extensions (also the source-code build description).

>     * the complexity of FMI 3.0 can be reduced
>       Response:  **we precisely designed this proposal to be the least complex of all the new features of FMI 3.0!!**! If complexity has to be reduced let's first begin by removing array variables with reconfiguration mode and the multiple and very complex "hybrid co-simulations".
Re-Re: This is not about one feature or the other. The question is rather: Can we keep the same functionality with a simpler standard.

Reading your responses, I get the feeling that this is an emotional issue to you.
We are discussing this proposal to improve the standard, not to spite you.
The struggle we go through can create stress that is uncomfortable, but should be familiar by now.
But I believe this struggle helps us making (painful) progress towards a better standard and that is worth it, for sure. Please bear with us, Antoine!

**Comment by CSchulzeTLK** [comment]
I care about:
1. the meta information about the terminals (mathematical aspect)
2. getting this to be actually used (marketing aspect)

I do not care so much about the how the meta information is stored (json, xml, attribute names, or whatever, please don't feel offended when I call it "beauty of the code", I know this doesn't cover the technical aspects). All my comments about this are purely driven by point 2. Obviously we have a different understanding what might people motivate to stick to this specification to describe terminals.

It is difficult to update the list of pro and contra and the answers to them in the comments and protocols.

**Comment by chrbertsch** [comment]
See discussion and decision in https://github.com/modelica/fmi-design/blob/master/Meetings/2020-04-21-22-Online-FMI-Design-Meeting/minutes.adoc#layered-standards 
--> We will keep the description in the standard text, and have a separate xml file
