### ISSUE TITLE
VendorAnnotations or VendorAnnotation (no `s`)

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#874]
Mostly in lists, we use the singular for a single element. Isn´t VendorAnnotations in violation of this principle and should be renamed to VendorAnnotation?

**Comment by KarlWernersson** [comment]
well it contains, 1-inf tool nodes each that contains an arbitrary amount of any nodes, hinting that that the vendorAnotations can contain many annotations

**Comment by andreas-junghanns** [comment]
This is a consistent exception: only first-level elements of fmiModelDescription have container elements if there can be more than one element.
