### ISSUE TITLE
Check, fix, remove TODOs from standard sources

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#881]
We still have 35 TODO comments in the *.adoc files.
We should check which are still valid, which can be fixed and which need a separate ticket to track progress.

**Comment by t-sommer** [comment]
This issue is too general. Please open individual issues for each placeholder we can assign and solve.

**Comment by andreas-junghanns** [comment]
The idea was to use this as a write-fest TODO and work through the text and fix as many of them as possible in one go (separate commits, sure, but one sitting). Many cannot be handled by one brain and splitting them into 35 tickets seems like unnecessary overhead.

**Comment by chrbertsch** [comment]
I agree with Andreas to keep this open as a reminder, until the ToDos have been fixed.
