### ISSUE TITLE
seed and nSeed should be seeds and nSeeds, sensitivity and nSensitivity for GetDirectionalDerivative and GetAdjointDerivative

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#882]
We are quite consistent with the plurals of array arguments - this slipped.

**Comment by andreas-junghanns** [comment]
As this touches code, I am asking Torsten to take care of this to do the change in synch with the examples.

**Comment by andreas-junghanns** [comment]
the same for sensitivity and nSensitivity

**Comment by chrbertsch** [comment]
"seed" is short for "seed vector", so I would stay with seed

**Comment by andreas-junghanns** [comment]
> "seed" is short for "seed vector", so I would stay with seed

But this argument could apply to all other arrays we send as arguments.
Point is: all other places we name arrays with plural. We should here as well to be consistent.

**Comment by chrbertsch** [comment]
In order to calculate e.g. a sparse Jacobian, you need several seed vectors (that you can obtain with colouring algorithms). These multiple seed vectors one could call "seeds", and e.g., https://www3.math.tu-berlin.de/Vorlesungen/SS06/AlgoDiff/adolc-110.pdf, talks about a "seed matrix", consisting of the differnt seed vectors. 
But our interface allows  only for one seed vector. That could get confused when we call it seeds.

> Point is: all other places we name arrays with plural. We should here as well to be consistent.

When we talk about an array x, we call it x and not xs :-)

**Comment by andreas-junghanns** [comment]
If we keep seed, what about sensitivity?

**Comment by chrbertsch** [comment]
> If we keep seed, what about sensitivity?

For me it is the same. "sensitivity" is short for "sensitivity vector". If we would use as inputs seeds in the for of a "seed matrix", we would get as an outputs "sensitivities" in the form of  a "sensitivity matrix".

seed an sensitivity are used in the description as 
![grafik](https://user-images.githubusercontent.com/16363372/78711101-bb7d1680-7916-11ea-93b1-c84b1a3a2265.png)


It think the whole think burns down to the observations, that all the seed values form one seed vector and the sensitivity values form one sensitivity vector.

So perhaps we should change the descriptions 
![grafik](https://user-images.githubusercontent.com/16363372/78711256-f97a3a80-7916-11ea-91de-6aeb696c3c14.png)

to

* seed[]: components of seed vector
* nSeed: length of seed vector
* sensitivity[]: components of sensitivity vector
* nSensitivity: length of sensitivity vector

**Comment by t-sommer** [comment]
@chrbertsch, can you make a PR?

**Comment by andreas-junghanns** [comment]
I found a few more such (perceived?) inconsistencies - maybe it is just me that thought of this as a pattern. More examples:
 - subactive[]
 - interval[]
 - interfaceCounter[]
 - resolution[]

(This is different from serializedState[] - this should remain singular as this is a single state serialized into an array of bytes.)

Pro examples:
 - independents[]
 - elementIndicesOfIndependents[]
 - dependencyKinds[]
 - unknowns[]
 - knowns[]
 - valueReferences[]
 - sizes[]
 - values[]
 - categories[]
 - derivatives[]
 - eventIndicators[]
 - nominals[]
 - orders[]
