### ISSUE TITLE
canNotUseBasicCoSimulation, providesHybridCoSimulation and providesScheduledCoSimulation 

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#884]
These attributes are mentioned in the text, but do not exist in the schema files.

**Comment by andreas-junghanns** [comment]
I do not like two things here:
canNotUseBasicCoSimulation contains a negation which makes it harder to understand.
canNotUseBasicCoSimulation could more consistently also be named providesBasicCoSimulation (like the other two), but have a default of "true" to express our expectation that BCS is always implemented.

**Comment by nickbattle** [comment]
How do these flags relate to the elements that define the various FMU types? For example, does `canNotUseBasicCoSimulation` mean that there cannot be a `<BasicCoSimulation>` element? So why is presence or absence of the `<XXXCoSimulation>` elements not enough?

**Comment by t-sommer** [comment]
I think the attributes are superfluous with the introduction of the `<*CoSimulation>` elements.

**Comment by andreas-junghanns** [comment]
> I think the attributes are superfluous with the introduction of the `<*CoSimulation>` elements.

Ideally, this would be the cleanest solution.
But, right now, the text says (or at least implies) that if you have HCS or SCS elements in the XML, BSC can be used as well, without the XML element present.

I think/suggest this is unnecessarily complicated. If the FMU can do BCS, add the element. No implicit complications.

**Comment by t-sommer** [comment]
Solved with #887.
