### ISSUE TITLE
add note why "TYPE" suffix is necessary in function definitions in fmi3FunctionTypes.h

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#893]
(this is one of the ToDos in the adoc-files comments mentioned in #881)

![grafik](https://user-images.githubusercontent.com/16363372/78933610-ddf36900-7aa9-11ea-9d70-485fed4ec239.png)

(Currently l.45  of https://github.com/modelica/fmi-standard/edit/master/docs/2_1_common_api.adoc. B.t.w. Does someone know how to create a permanent link to a line in an adoc file on Github?)

**Comment by t-sommer** [comment]
> B.t.w. Does someone know how to create a permanent link to a line in an adoc file on Github?)

Try this https://github.com/holman/ama/issues/305#issuecomment-59131677
