### ISSUE TITLE
Change style of references to code labels

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#896]
I've identified this issue while working on https://github.com/modelica/fmi-standard/pull/895.

With the current style, it's impossible to figure out whether there is a link or not to a code definition.
For instance, consider the following picture:
![image](https://user-images.githubusercontent.com/871103/79101670-563b8200-7d69-11ea-86cc-ed3614876d3f.png)

The style of fmi3GetVersion is just the same as fmi3FunctionTypes.h but the former has a link.
The reader has to hover the mouse to know this.

This is caused by the fact that the label of the function is defined as follows:
```
[[fmi3GetVersion,`fmi3GetVersion`]]
```
(find sentence "can be inquired in the target simulator with").

I see three possible solutions for this:
1. Change the definitions of code labels. For instance, the above label definition becomes `[[fmi3GetVersion,fmi3GetVersion]]`.
1. Change the css so that code elements inside anchor elements show a color that informs the reader of it being a link.
1. Change the text around each reference to a code label, so that it becomes obvious that there is a link. For instance, the above reference could changed to 
```
can be inquired in the target simulator with `fmi3GetVersion` (defined <<fmi3GetVersion, here>>).
```

I've briefly explored solution 2, but it seems that the stylecheet already contains styles for code inside an anchor element. It seems that somebody really wanted code references to look like code, and not to look like links.

Maybe this was discussed a long time ago?

**Comment by andreas-junghanns** [comment]
We reduced and simplified the styles used a while back (see contribution guides).
I don´t see this as an issue: if a word is not a link, the click will fail. So what?
If we create a different style (again), it will clutter the text again.

**Comment by t-sommer** [comment]
Functions, types and enums should be xrefs (i.e. "clickable") where ever possible. Seems like the anchors have not been added for all of them.

**Comment by clagms** [comment]
Thanks for the quick reply @andreas-junghanns and @t-sommer !

>I don´t see this as an issue: if a word is not a link, the click will fail. So what?

This is not my problem Andreas. My problem is that there's no way of knowing whether something is a link in the first place, except for hovering the mouse. Suppose I'm reading a paragraph and there's a function being mentioned. I don't know what that function is, and I would like to find out more. If I'm lucky to hover my mouse over the function, I will find out that it is a link and click it.

With the current style, when a link to a section is made, it is clear that it is a link.
Because we have the same style for code and links to code, it's not clear to the reader whether a piece of inline code is a link or not.

>Functions, types and enums should be xrefs (i.e. "clickable") where ever possible. Seems like the anchors have not been added for all of them.

Maybe this is what is causing the confusion. If every declaration points to somewhere, then the reader will soon get used to the convention. 

Also, it would be nice if this rule is mentioned in the preamble of the document, together with the other conventions, no?

**Comment by andreas-junghanns** [comment]
> Functions, types and enums should be xrefs (i.e. "clickable") where ever possible. Seems like the anchors have not been added for all of them.

This would be the proper fix: add those xrefs everywhere (both anchors and xrefs!). Since this is another huge effort and PR, we should find a good time to do it without other big PRs pending (like #895) that would lead to big merge efforts.

**Comment by andreas-junghanns** [comment]
This is an ongoing task (PR #980 fixes more of these issues, others before did as well).
Closing this as the issue raised cannot generally be addressed.
