### ISSUE TITLE
Use fmi3SetupExperiment() to enter Initialization Mode

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#897]
This would avoid the required "self transition" in `Instantiated` and simplify the state machine.

**Comment by andreas-junghanns** [comment]
This would turn {{{fmi3SetupExperiment()}}} into an alternative to {{{fmi3EnterInitializationMode()}}}, right? Why have the later at all (except for the symmetrical name to enter and exit initialization mode?

**Comment by t-sommer** [comment]
> Why have the later at all (except for the symmetrical name to enter and exit initialization mode?

Yes, `fmi3EnterInitializationMode` would become obsolete with this change.

**Comment by andreas-junghanns** [comment]
TorstenB proposes to move the parameters from fmi3SetupExperiment to fmi3EnterInitializationMode and remove fmi3SetupExperiment. Everyone (Pierre, TorstenS, Andreas, Otto) seems to agree.

**Comment by chrbertsch** [comment]
closed with merged PR #920
