### ISSUE TITLE
Replace fmi3Exit*() functions with dedicated transition functions

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#899]
Currently the `fmi3ExitInitializationMode` and `fmi3ExitConfigurationMode` functions transition to different states, depending on the FMI type. Example:

Basic Co-Simulation: `fmi3ExitInitializationMode` -> `Step Mode`
Scheduled Co-Simulation: `fmi3ExitInitializationMode` -> `Clock Activation Mode`

This makes the implementation of a state machine in an FMU unnecessarily complicated, especially when it supports multiple FMI types.

My suggestion would be to use `fmi3Enter<TargetState>`. For example `fmi3EnterStepMode` and `fmi3EnterClockActivationMode`.

**Comment by andreas-junghanns** [comment]
I changed your proposal to what I want you to want. :)

**Comment by chrbertsch** [comment]
Regular design webmeeting: see discussion https://github.com/modelica/fmi-design/tree/master/Meetings/2020-04-17-Regular-FMI-Design-Webmweeting#discussion-on-httpsgithubcommodelicafmi-standardissues899

**Comment by andreas-junghanns** [comment]
We (TorstenS, TorstenB, Otto, Pierre, Andreas) agree that changing one function into three is not a good tradeoff. Closing ticket.
