### ISSUE TITLE
central organization for FMI design meeting

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#901]
WebEx 0: central track for meeting in the large group, discussions and votes

WebEx 1: tech meeting:  current topic: "...."

WebEx 2: tech meeting:  current topic: "...."

WebEx 3: tech meeting:  current topic: "...."

**Comment by chrbertsch** [comment]
will be handled in https://github.com/modelica/fmi-design/tree/master/Meetings/2020-04-21-22-Online-FMI-Design-Meeting
