### ISSUE TITLE
Rename fmi3ExitInitializationMode to fmi3FinalizeInitialization

### ISSUE THREAD

**Issue by pmai** [modelica/fmi-standard#903]
Based on the replacement of `fmi3EnterInitializationMode` in #897 with `fmi3SetupExperiment`, `fmi3ExitInitializationMode` is (with the exception of the symetrical Enter/ExitConfigurationMode) the last function that talks explicitly about exiting a mode, rather than some active thing to be achieved.

The proposal as discussed today, 2020-04-17, would be to rename `fmi3EnterInitializationMode` to `fmi3FinalizeInitialization`.

A pull request will follow if this issue finds approval. This issue is dependent on #897 actually being accepted.

**Comment by andreas-junghanns** [comment]
Pierre will document the proposals discussed and why they were rejected.

**Comment by pmai** [comment]
![tenor](https://user-images.githubusercontent.com/91502/79875496-07858c00-83ea-11ea-85ef-69f21f77f940.gif)

**Comment by pmai** [comment]
WIP (will be edited):

For the renaming of the functions only, the following overall proposal would get rid of all XXXMode functions, and be consistent in formulating an activity, rather than the resultant mode switch itself:

```
   fmi3BeginInitialization()
   fmi3FinalizeInitialization()

   fmi3BeginConfigurationChange()
   fmi3FinalizeConfigurationChange()

```
