### ISSUE TITLE
Clarification of the relation between model partitions and input clocks

### ISSUE THREAD

**Issue by MBlesken** [modelica/fmi-standard#916]
“There is a direct one-to-one relation for a **clock** and a model partition.” 
Suggestion: clock -> **input** clock

Also in the mathematical definition (3.1.8.1.2) it should be mentioned that a model partition is asociated with an input clock.

Note: Output clocks (0..inf) could be ticked by a model partition. 

@clagms 
* Section "3.1.8.1.2. Communication Point Clocks" also  seems to need some clarification. For example, it does not explicitly define what does it mean for a clock to be associated with a model partition.

* An input clock seems to be associated to a model partition in the following way: when the clock ticks, the model partition gets evaluated as defined in Section "3.1.8.1.2". The meaning of the association between an output clock and a model partition is not clear. 
Anything inside the FMU may trigger an output clock. 
So, why does an output clock have to be associated to a model partition?

**Comment by andreas-junghanns** [comment]
See also #929

**Comment by chrbertsch** [comment]
Ticket-viewing-meeting

Do use "model partitions" only for SE or also for CS?
Christian: It thinkg to SE
AndreasJ: "model partition" appears everywhere in the standard (but not in ME)
Klaus: then we have a problem anyway if we do not say to which kind of clock the model partitions belongs to. Why does it then not appear in ME?
AndreasJ: ...
TorstenB.: Communication time clocks were introduce to distinguish to the other types of clocks. There was a reason ...
Andreas: is the a problem in the overview table regarding clocks? Now I do not think so. 
@andreas-junghanns : **I will create a PR**
TorstenB: please keep in mind that there are no model partitions in ME and CS
Klaus: There was a discussion if we need a name like model partitions in ME and CS ...
Andreas: If no one needs it, let's remove this.
TorstenB: from the outside in ME and CS we see only variables that are assigned to a clock.
Andreas: this is the abstraction of ME and CS
Klaus: currently we have normative mathematical discription of CS ...
TorstenB: I read and use the mathematical description .... It tells where which variable get calculated ... . If there are problems, please create a specific tickets.

**Comment by MBlesken** [comment]
@andreas-junghanns @IZacharias I would close this items if you don't have any objections. The findings seem to have been addressed by other issue items or PRs.

**Comment by andreas-junghanns** [comment]
Agreed
