### ISSUE TITLE
Update Scheduled Co-simulation Example description in document

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#918]
We should replace section content of "7.2.5. Pseudo-code Example for Scheduled Co-Simulation" with an description of the Clocks reference FMU.

**Comment by IZacharias** [comment]
XML example is also missing.

**Comment by chrbertsch** [comment]
Ticket-viewing-meeting

Andreas: This is work in progress; the dSpace Collegues and TorstenS are working on that
