### ISSUE TITLE
Fix definitions of configuration and reconfiguration mode, and other common modes

### ISSUE THREAD

**Issue by pmai** [modelica/fmi-standard#922]
Currently the definitions of configuration mode, reconfiguration mode, and some other common modes (like  instantiated and initialization mode) are repeated for each FMU interface type in the API chapters. This leads to lots of repititions and accidental divergence (e.g. currently the basic co-sim chapter only defines configuration mode, but in a way that actually matche reconfiguration mode).

While the divergences can be fixed, I think the basic definition of those states should reside in a common chapter to avoid duplication, and only interface type-specific modifications of those states should be in the type-specific chapters. Since configuration and reconfiguration mode are identical across types, this applies doubly here.

**Comment by andreas-junghanns** [comment]
We have started with this in 3.1 Common Concepts/FMI API and I think this would nicely fit after "Configuration, Initialization, Termination, and Resetting an FMU".
I am happy to help here, directly or as reviewer - your choice.

**Comment by andreas-junghanns** [comment]
This is similar to #762.

**Comment by andreas-junghanns** [comment]
#989 deals with a similar issue, I will create one PR for both these tickets. Closing this here.
