### ISSUE TITLE
Define consistent structure for listing possible values of xml enumerations.

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#925]
In the tables throughout the "FMI Description Schema" section,
the way we explain the different values of an enumeration attribute of an XML element could be made a bit more consistent.
For instance, I like the list-like notation, where every possible value starts with an equal sign. For instance: ```= dependent`: no particular structure,...``. There are multiple places where this notation is already used.

Addressing this would make it clearer to the reader of what the possible values are, and make it easier to locate immediately what the meaning of each value is.

If we all agree this improves the text, then we need to rephrase some of the text in those tables to make it list the different possible values.

**Comment by andreas-junghanns** [comment]
Before I start into this adventure: Should we treat Boolean attributes like enumerations with true and false as well?

**Comment by clagms** [comment]
I think so!

**Comment by andreas-junghanns** [comment]
Fine - I will give this a shot these days.
