### ISSUE TITLE
Remove xref to independent variable when it refers to an independent parameter.

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#936]
In multiple places of the text, there is an invalid reference to independent.
For instance:

>``The symbol without a subscript references <<independent>> <<parameter,`parameters`>>``

For more, find all occurrences of `<<independent>> <<parameter`.

Probably one needs to also double check all other references `<<independent>>`

**Comment by chrbertsch** [comment]
I understand what *the* intependent variable is (time). But what is an "independent parameter" anyway? Should we not avoid "independent" for this anyway, and find a better description? What could this be?

**Comment by clagms** [comment]
@chrbertsch I think that at some point there was a need to distinguish "calculated" parameter from "independent" parameter ("calculated" being synonymous with "dependent").

Perhaps we can indeed remove the "independent" qualifier altogether, and make sure the reader knows that "parameter" means a non-calculated parameter.

**Comment by clagms** [comment]
> Removing "independent" from the parameter descriptions seems ok, until you find that we have also references to "dependent parameters".
> There is a definition:
> "Dependent <<parameter,`parameters`>> (variables with <> = <>) are..."

Afaik, a parameter can be dependent during initialization mode, if it is calculated from other parameter.

>So, are all dependent parameters "dependent"?

Here the "dependent" refers to the dependenciesKind, right?
If so, then the answer is no. 
Calculated parameters can have a linear relationship with their dependencies (in which case they would be "constant").
The rules in the standard seem to indicate that parameters cannot have "fixed", "tunable", or "discrete", dependencies, since those cannot be declared for initial unknowns.

**Comment by andreas-junghanns** [comment]
> The rules in the standard seem to indicate that parameters cannot have "fixed", "tunable", or "discrete", dependencies, since those cannot be declared for initial unknowns.

If that was true, what variables would be "tunable"?
This seems obviously not true, so whatever makes you believe this must be fixed.

**Comment by andreas-junghanns** [comment]
> > There is a definition:
> > "Dependent <<parameter,`parameters`>> (variables with <> = <>) are..."
> Afaik, a parameter can be dependent during initialization mode, if it is calculated from other parameter.

I was under the impression, that dependent parameters are called calculated parameters.
They change, when tunable parameters change that they depend on.
That can happen during event modes as well.

Back the original question: Are all dependent parameters "calculatedParameters"?
If yes, we should pick one term (I propose calculated because it is more descriptive) and use that everywhere.

**Comment by clagms** [comment]
> If that was true, what variables would be "tunable"?

Maybe there's a misunderstanding. Parameters can still be tunable or calculated. This is just about the qualifier of each of the dependencies of calculated parameters.

>This seems obviously not true, so whatever makes you believe this must be fixed.

I've put these two portions together:
- Calculated parameters are considered unknowns in the <InitialUnknown> part:
![image](https://user-images.githubusercontent.com/871103/80806410-e9bee080-8bba-11ea-82c1-7312728a5193.png)
(search for ``The resulting list is not allowed to have duplicates (for example, if``)

- The following possible values don't apply to <InitialUnknown> elements:
![image](https://user-images.githubusercontent.com/871103/80806316-a19fbe00-8bba-11ea-8770-a4184143d1d0.png)
(search for ``not for <<InitialUnknown>> for *Initialization Mode*``)

**Comment by clagms** [comment]
>I was under the impression, that dependent parameters are called calculated parameters.

"dependent" refers to the nature of the dependencies of the calculated parameter.

> They change, when tunable parameters change that they depend on.

They don't have to depend only on tunable parameters. They may depend on other parameters during initialization mode.

>Back the original question: Are all dependent parameters "calculatedParameters"?

Still no (assuming that the "dependent" refers to the dependencies of the calculated parameter). This assumption seems to be correct, because in the document you will have a link to the dependency attribute "dependent".

**Comment by andreas-junghanns** [comment]
If "dependent" is this hard to define, is at least "independent" clear?
I removed independent now from parameters where it was clear they are independent as (now) defined for parameters in text and glossary.

**Comment by chrbertsch** [comment]
>     * The following possible values don't apply to  elements:
>       ![image](https://user-images.githubusercontent.com/871103/80806316-a19fbe00-8bba-11ea-8770-a4184143d1d0.png)

the `dependenciesKind` names are very un-intuitive for a human reader of the xml.
Why does a `dependenciesKind `== constant not mean, that the the corresponding variable is constant, but that there is a linear relationship?

I would rename them to something like

dependent --> generalDependency
constant --> constantFactor
fixed --> fixedFactor
tunable --> tunableFactor
discrete --> discreteFactor

If that is too long for the xml file, one could use something very  short like
dependent --> g
constant --> c
fixed --> f
tunable --> t
discrete --> d

This would avoid the double meaning of dependent for parameters (dependenciesKind and _calculated_ parameters

**Comment by andreas-junghanns** [comment]
I will take the "dependent" issue to a new "issue". Let´s leave this part here simple.
If someone else approves the PR, this is issue here is done.

**Comment by andreas-junghanns** [comment]
> dependent --> generalDependency
> constant --> constantFactor
> fixed --> fixedFactor
> tunable --> tunableFactor
> discrete --> discreteFactor

Or use "Dependency" instead of "Factor" in your proposal (too long, but the general idea is to have them all point to the same "idea"). Maybe #958 is the right place to discuss this?
