### ISSUE TITLE
Properly deal with duplicate XSD element names in Schema

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#940]
This issue was created due to the discussion in https://github.com/modelica/fmi-standard/pull/904

Summary:
1. Some xsd elements have duplicate names (e.g., Float64, GraphicalRepresentation).
1. While item 1 may make conceptual sense, it leads to the following problems:
   1. The tool XSDDiagram has difficulties selecting the right element to export to png when there are two elements with the same name, in the same schema. 
   1. In the adoc, it may be hard to xref a xsd element by name if there are two elements for the same name.
   1. The reader may have trouble distinguishing xsd elements that have the same name (e.g., the Float64 type and the Float64 value).

Items 2.ii. and 2.iii. are "maybe"'s. Item 2.i. is a certainty. 
Moreover, it may lead to difficult to detect problems down the line, where a new XSD element $A$ gets added with the name of an already existing XSD element $B$, and suddenly the png of $B$ gets messed up.
The png of $B$ may be in the other side of the document, and may be even regenerate much later than the change that broke it, so it may be difficult to detect this problem until someone goes over the whole document.

**Comment by andreas-junghanns** [comment]
While I would prioritize the reasons differently, I agree with requiring unique names for all schema elements. If this is consensus, it should also go into the contribution guidelines.

**Comment by chrbertsch** [comment]
@pmai : could you please coment on this?

**Comment by pmai** [comment]
While I think that the tool is just broken, and should not influence schema design, and that one of the few things that XML (and XML schema in particular) actually got right was to allow for hierarchical types (the same way any sane programming language does, btw.), I'm getting too old for this kind of thing, and furthermore I don't really care, so stick some prefix on all of the elements to make them globally unique (i.e. Float64 -> Float64Variable & Float64Type, GraphicalRepresentation -> FMUGraphicalRepresentation & TerminalGraphicalRepresentation, etc.).

**Comment by andreas-junghanns** [comment]
While I love reading your rhetoric, I venture to argue here that this is not about enforcing a single schema-wide namespace for elements. What I might not have clearly communicated is that I was wondering about elements that have quite different semantics and still the same name (or so it seemed to me). It would be silly to name x1, x2, y1 and y2 in the different elements differently, I am sure most of us will agree.

Can we have a discussion about this aspect of the naming?

**Comment by pmai** [comment]
Unless one does enforce the global namespace (or fix/change the tool in question), I think this doesn't solve the problem why this issue was initially raised.

Besides that I think that both cases are very similar, and exactly why it makes sense to reuse the names: A type and variable are different things, but the Float64 element indicates its base type and gives additional information, which varies with context. The GraphicalRepresentation elements give (duh) the graphical representation for the given context (the FMU, the terminal), which again varies a bit (but could/should be made more consistent maybe, but that would be up to the ports and icons group). However this is always a judgement call, i.e. one can of course argue that the relevant uses/semantics are too dissimilar, and thus warrant their own element names.

That's one of the reasons why I don't really care strongly in each instance, however I do care to some degree that these decision not be taken due to tool issues or some mistaken belief that either XML or the human brain cannot be trusted to deal with context, which they are oviously fairly good at (the brain more so than XML, arguably). At least not too lightly...

So I have not seen the argument for the individual cases being done, I have only seen tool and global namespacing appeals. If someone cares about the individual instances, I can very likely be conviced (and my opinion should likely not matter that much anyway). I'm more or less only commenting because @chrbertsch tagged me.

**Comment by clagms** [comment]
@pami I'll have a second look at the tool's implementation.
Maybe I missed something there.

I agree that that changing the names will treat the symptoms and not the root of the problem (the limitation on the tool) and, as a consequence, this will pop up again later.

**Comment by clagms** [comment]
Here's the possible way forward:
I add a new int parameter N (e.g., called Select) to the command line interface, that tells the XSDDiagram to plot to N-th element he found.

So, for instance, the following command
```
Export-Schema GraphicalRepresentation 2 -Select 1
```
prints only the first element in the following figure:
![image](https://user-images.githubusercontent.com/871103/81194846-6ab41880-8fbd-11ea-8fd1-91f1f2e5b791.png)

There is a problem with this approach: suppose a new "GraphicalRepresentation" has been added to the XSD. This might break all pngs that show "GraphicalRepresentation". The user that added "GraphicalRepresentation" must double check those, and adjust the Select parameter accordingly.

I'm betting that in practice, there will not be that many duplicate elements in the XSD that will cause this issue to arise. We will have to trust in the people adding stuff to the XSD.

@pmai , @andreas-junghanns , shall I do this?
We can still discuss Items 2.ii. and 2.iii. above, but at least there won't be tooling issues in the way.

 

I checked other options, but excluded them:
1. Use some kind of namespace to select the correct element based on its parents. This cannot be easily done because the code does not walk the XSD tree. Instead it goes over all elements in the XSD, and filters those that have the same name.
1. Use a filter on the children of each element. This also suffers from being brittle (as children may change), and would require me to have an xpath like parser to identify which child is referred to (an elements can be contained in another element in many different ways).

**Comment by andreas-junghanns** [comment]
Would it not make more sense to add a command line parameter -p <parentElement> to define which element to print? And yes, we would ideally have multiple -p switches in case we have an entire hierarchy duplicated.

**Comment by clagms** [comment]
>Would it not make more sense to add a command line parameter -p to define which element to print?

@andreas-junghanns , maybe I misunderstood your remark, but the main problem lies in how to identify which element to print. So that parameter -p has to be there, but what kind of argument can be passed is not clear (just the name of the element is not sufficient as there are elements with duplicate names).

**Comment by nickbattle** [comment]
@clagms Apologies if I'm not understanding the detail here, but isn't an XPath name exactly what we need here to unambiguously identify a node within a tree?

**Comment by clagms** [comment]
> @clagms Apologies if I'm not understanding the detail here, but isn't an XPath name exactly what we need here to unambiguously identify a node within a tree?

Yes @nickbattle !

The problem is implementing it :p. I think it would take too long to change the XSDDiagram tool to take an XPath inputs, instead of an element. Have a look at the tool's implementation, as you might have better ideas on how to implement this.

**Comment by nickbattle** [comment]
Hmmm... I see what you mean. It's tricky.

Would it be easier to use an external XPath processor to extract the bit of the schema you want to render and then pass that to XSDDiagram? I'm no XPath expert, but the following almost works:
```
xmllint --xpath "//*[local-name()='schema']/*[local-name()='element']/*[local-name()='complexType']/*[local-name()='sequence']/*[local-name()='element']" fmi3TerminalsAndIcons.xsd

<xs:element name="GraphicalRepresentation" minOccurs="0">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="CoordinateSystem" minOccurs="0">
                <xs:complexType>
                    <xs:attribute name="x1" type="xs:double" use="required"/>
                    <xs:attribute name="y1" type="xs:double" use="required"/>
                    <xs:attribute name="x2" type="xs:double" use="required"/>
                    <xs:attribute name="y2" type="xs:double" use="required"/>
                    <xs:attribute name="suggestedScalingFactorTo_mm" type="xs:double" use="required"/>
                </xs:complexType>
etc...
```

**Comment by clagms** [comment]
I think this might be a good lead @nickbattle !
Let me see if I got this straight:
1. We use your trick to get the tree under the "GraphicalRepresentation" element.
1. We save that in a new xsdFile.
1. We feed that file to XSDDiagram

Is this right?

A couple of issues:
- Does xmlint recursively load the XSD schema? For instance, there is a single "GraphicalRepresentation" element in the `fmi3TerminalsAndIcons.xsd` file. But a second one gets referenced as a type ref from the same file, leading to a tree that has two "GraphicalRepresentation" elements. I guess xmlint does not understand XSD. If the second "GraphicalRepresentation" element is not inside the first "GraphicalRepresentation" element, then this is not a big deal. 
- Will step 2 always yield a valid XSD file? I think not, because just extracting the "GraphicalRepresentation" element won't load any of the references (and probably break those in case they are made to siblings of the "GraphicalRepresentation" element.

**Comment by nickbattle** [comment]
I'd have to play with xmllint to be sure, but I think it just views the "XML" you give it as a tree without any particular checks, unless you ask for them. There might be other tools that are more flexible.

But yes, that's what I was suggesting. You might need to wrap some XSD "boilerplate" around the extracted part to make it legal for the diagram tool, but that would be a fixed header? We just want to extract the structure, not to verify the result as legal, so this might work.

**Comment by andreas-junghanns** [comment]
Discussion at web design meeting:
Klaus: It would be easier to reference elements with ambiguous names in the standard text.
Pierre: It is unclear how often we have to be clear in the document because we reference en element across sections (out of place).
Pierre&TorstenS: We could call the type elements as "Int32Type" and keep the variable elements as "Int32".
Pierre: If we fix the types, we should also fix the GraphicalRepresentation elemens: name them TerminalGraphicalRepresentation and leave the FMU GraphicalRepresentation.
