### ISSUE TITLE
Change VendorAnnotations to Annotations?

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#945]
In several tickets like https://github.com/modelica/fmi-standard/pull/904#issuecomment-620631343 it was mentioned, that  `VendorAnnotations `could/should be changed to `Annotations`. To me this sounds logical.

Pro: 

- Why should only "Vendors" created defined annotations for a certain validity scope and not some other organization, consortium, ....?
- This would be compatible with SSP (which also belongs to the "FMI"-family of standards
- ....

Contra: 

- Renaming late in the development process of FMI 3.0
...

Please add arguments

**Comment by andreas-junghanns** [comment]
I think something along those lines happened in PR #905...

**Comment by pmai** [comment]
> I think something along those lines happened in PR #905...

#905 did not rename VendorAnnotations to Annotations... or did I miss something?

**Comment by clagms** [comment]
2020-04-30-Regular-FMI-Design-Meeting

PMAI: Annotations would allow you to place additional information, for eg., for layered standards. Could be used for additional metadata. 

PMAI: Should additional xml files have annotations?

CB: would this be consistent with the extra stuff?

PMAI: Yes.

AJ: Two things: 1 this is a renaming. 2. Is copying all over the place.

PMAI: the 2nd is most important.

AJ: This affects the hashing. 

CB: We should forbid changes to all (except extra).

AJ: We put the annotations everywhere.

AJ: this allows us to be ready for layered standards. These annotations are created by the fmu exporter. Anything except the extra directory is under the control of the exporter.

PMAI: there's an inconsistency with the names.

TS: KW and PMAI, can you put some examples of how the annotations are being used? Can you also show how the validation works?

AJ: I also have no idea on this is done.

PMAI: Each element is associated with a schema that is used to validate it.

KW: we have to be careful to avoid forcing the exporter to have container elements.

Conclusion on renaming:  everybody agrees.

Conclusion on putting it everywhere: everybody agrees.

**Comment by andreas-junghanns** [comment]
related to #937 and #386
