### ISSUE TITLE
Handling international encodings

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#95]
**Reported by iakovn on 25 Sep 2012 05:35 UTC**
Section 2.2 of the specification states: 
> 
> A specific encoding scheme is not required for the fmi XML file (modelDescription.xml).

Proposal: mandate the use of UTF-8 (ASCII is a subset of UTF-8) encoding for the modelDescription.xml files.
Motivation: 
1.	Making encoding free puts an unnecessary burden of supporting a large number of international encodings on each importing tool. The available libraries to handle this are (to my knowledge) not fully portable. Testing with uncommon encodings is also complicated. For a generating tool, on the other hand, converting to UTF-8 from the tool specific encoding is straight forward. Besides, all fmiString-s need to be UTF-8 encoded anyway.
2.	Modelica spec mandates UTF-8 for all the source files

Additionally, Section 2.3 FMU Distribution should explicitly forbid the use of non-ASCII characters in the file names of the files included into the FMU. This is to enable easy transfer of the archives between machines with different default system encodings

----

Migrated-From: https://trac.fmi-standard.org/ticket/95

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 1 Jun 2018 12:34 UTC**
Re-eveluate if non-ASCII names in the resource directory are a problem on different operating systems. (Test with multi-platform FMUs)

**Comment by modelica-trac-importer** [comment]
**Comment by Andreas Nicolai on 1 Jun 2018 15:38 UTC**
I can confirm that this gives problems on Linux (Ubuntu) and MacOS - when you unzip a Windows-created zip file where filenames contain "Umlaute", you'll get garbage since encoding is not stored/transported alongside with FMU.

Workaround: tell master the origin of the FMU (e.g. Windows-created) so that the unzip library can decode this accordingly. Note, in addition you'll need to patch z-lib manually and you can't use the packaged z-lib from Ubuntu repos.

However, it appears that few master simulator writers actually have use cases for cross-platform FMUs (most operate on Windows only?). Or, only latin1 characters are used for filenames???

Still, having at least a statement about this in the standard seems to be a valid request for the next (even minor) release, since it does not require anyone to change any code.

**Comment by KarlWernersson** [comment]
decision
this is a platform / zip issue that the standard cannot fix. we will write non normative text pointing out the problem so users can be aware but we dont want to limit to ascii and make problems for non latin alphabets.

**Comment by chrbertsch** [comment]
The encoding issue was solved in 2.0, the file name topic is solved with a non-normative text in 2.0.1
