### ISSUE TITLE
Q: FMU for multiple platforms

### ISSUE THREAD

**Issue by AHaumer** [modelica/fmi-standard#950]
Excuse my maybe silly question, I'm only a user of FMUs not very familiar with generating them. 
I'l like to generate FMUs for both Windows64 and Linux64. 
I have a tool (Dymola2020) installed and running both on Windows 10 64bit and on Linux Mint 64bit in a Virtual Box, and I can simulate and generate FMUs on both platforms. 
How do I "merge" those 2 FMUs? Just copy Linux64 from binaries to the Windows FMU is not sufficient, they have different guid in the modelDescription.xml.
I'm using FMUs to supply virtual experiments to students in lower semesters that are not yet familiar with modeling and simulation, enabling virtual lab courses without being present in the lab during the Corona pandemic.
I know I could use fpmy to "cross-compile" a source-code fmu, but I'd like to avoid source code.
Thanks in advance - best regards and stay healthy,
Toni

**Comment by clagms** [comment]
Hi @AHaumer! I'm not sure this is the right place to ask support questions.
Perhaps this is an issue that you need to bring up with Dymola itself. 
The fmi supports having the same fmu with different binaries, but, as you mentioned, I think they have to have to same GUID.
If you have control over the instantiation of the FMUs, maybe you can try, as a workaround (or "hack"), passing the right GUID when calling the fmi2Instantiate function. I would guess that the two modeldescription.xml files (windows and linux) are the same, except for the GUID. 

To quote from version 2 of the standard:
>Argument fmuGUID is used to check that the modelDescription.xml file (see section 2.3) is compatible with the C code of the FMU. It is a vendor specific globally unique identifier of the XML file (for example, it is a "fingerprint" of the relevant information stored in the XML file). It is stored in the XML file as attribute "guid" (see section 2.2.1) and has to be passed to the fmi2Instantiate function via argument fmuGUID. It must be identical to the one stored inside the fmi2Instantiate function; otherwise the C code and the XML file of the FMU are not consistent with each other. This argument cannot be null.

Perhaps there's an issue with the Dymola tool, as I would expect that the same model be exported with the same GUID, even for different platforms (as the model is independent of the platform, I think). But there might be a good reason for them to export different GUIDs.

**Comment by chrbertsch** [comment]
@AHaumer : PLease please use https://stackoverflow.com/questions/tagged/fmi tagged with "fmi" or your Dymola support channel for such tool specific questions in the future. 

If you you have a source code export license from Dymola, I would follow the cross-compilation-path with fmpy that you mentioned. You could delete the source code from the FMU afterwards.
