### ISSUE TITLE
Some pseudo code still using guid instead of instantiationToken

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#951]
See, for example:
```
... s1_fmi3InstantiateBasicCoSimulation("slave1", guid, NULL, fmi3False, ...
```

**Comment by chrbertsch** [comment]
As the pseudocode examples are now part of the Reference-FMUs, I see the following problem:
For historical reasons, all of the Reference FMUs contain  a definition of a GUID such as 
`#define MODEL_GUID "{8c4e810f-3df3-4a00-8276-176fa3c9f003}"`

This is then used also in FMI3 examples, e.g., https://github.com/modelica/Reference-FMUs/blob/master/examples/bcs_early_return.c
`fmi3Instance s = fmi3InstantiateBasicCoSimulation("slave1", MODEL_GUID, NULL, fmi3False, fmi3False, fmi3False, fmi3False, fmi3False, &instanceEnvironment, cb_logMessage, cb_intermediateUpdate);`

As these examples are part of the specification, we should use consistently FMI3.0 naming, such as instantiationToken.
    
Anyway, the examples subfolder of the Reference FMUs only apply for FMI3.0 and not for FMI2.0

So I propose to split the Reference-FMU Repo in a Reference Reference-FMU-2.0 repo (where FMI2.0 naming is frozen) and the  Reference-FMU repo that is used for the  development of the FMI standard (currently 3.0)

@t-sommer  and others: what do you think about this?

**Comment by t-sommer** [comment]
The pseudo code example has been replaced with C code from the Reference FMUs.
