### ISSUE TITLE
Add usescases for intermediateUpdate callback

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#965]
The `intermediateUpdate` callback is used for different purposes that should be mentioned in the documentation (including code examples):

- early return from a doStep for an event update
- preemption in cooperative multitasking (replaces asynchronous doStep() in FMI 2)
- intermediate access to variables for improved numerical stability

**Comment by andreas-junghanns** [comment]
I would like to rephrase your points:

intermediateUpdate allows:
* the FMU to inform the importer that an FMU internal clock has ticked (argument clocksTicked)
* the FMU to inform the importer that an FMU internal event occurred (argument eventOccurred)
* the FMU to interrupt to allow importer to get/set FMU variable values for advanced co-simulation algorithms
* the importer to signal to the FMU to stop the doStep() for reasons outside the FMU (importer calls DoReturnEarly())

Once we have the use cases, we should investigate if the current complicated mechanism of doStep()->callback-intermediateUpdate()->DoEarlyReturn().

**Comment by chrbertsch** [comment]
Extensions of 
> the FMU to interrupt to allow importer to get/set FMU variable values for advanced co-simulation algorithms
- using intermediate output values just for inspecting the FMU behaviour and displaying variables of a CS FMU with higher resolution than the communication timestep
- input interpoation (replacing fmi2SetInputDerivative, see https://github.com/modelica/fmi-standard/pull/939)
