### ISSUE TITLE
alternative draw.io

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#973]
draw.io is not working anymore, find alternative

**Comment by chrbertsch** [comment]
> draw.io is not working anymore, find alternative

What does not work? I used it last week and id worked fine.

**Comment by andreas-junghanns** [comment]
I tried yesterday and it did not. :|

**Comment by chrbertsch** [comment]
> I tried yesterday and it did not. :|

I tried now and it work. 
Could you please provide a description, screenshot ... on _what_ is not working for you?

**Comment by andreas-junghanns** [comment]
draw.io forwards me to https://app.diagrams.net/ and there I get an "unknown error" "script error".
When I "OK" it, I get to a page with 3 buttons did not work yesterday, but do work now.

I suggest to forget about this unless we see other issues popping up.
