### ISSUE TITLE
Rework state machine and description for fmi3Errror/fmi3Fatal returns from IntermediateUpdate callback

### ISSUE THREAD

**Issue by pmai** [modelica/fmi-standard#977]
As noted during today's webmeeting 2020-05-08 while discussing #972, the state machine diagrams currently look like a master returning fmi3Error or fmi3Fatal from the IntermediateUpdate callback directly transitions to the relevant terminated or final state, without making it clear if and how the FMU actually returns control, and what its return values are in that case.

A simpler way to describe this part of the machine, as suggested by @t-sommer would be to just state that a return value of fmi3Error or fmi3Fatal from the callback results in the fmi3DoStep call to return directly with the same return value, and hence leads to the same state transitions.

This should be fixed in the document accordingly.

**Comment by t-sommer** [comment]
See also my comment in https://github.com/modelica/fmi-standard/pull/972#pullrequestreview-408446858.

**Comment by andreas-junghanns** [comment]
This was (largely?) addressed with #972. Please reopen, if some aspect of your concerns have been missed.
