### ISSUE TITLE
modelIdentifier naming restrictions

### ISSUE THREAD

**Issue by klausschuch** [modelica/fmi-standard#978]
The current specification says in section "2.1.1. Header Files and Naming of Functions":
> Since modelIdentifier is used as prefix of a C-function name it must fulfill the restrictions on C-function name.

Only for C-code FMUs the modelIdenifier is used as a prefix.
It is not clear (to me) if this restriction must be fulfilled for FMUs that do not ship c-code (only shared objects) too.

**Comment by andreas-junghanns** [comment]
I think for static linking, the modelIdentifier is also used as a prefix to the function names to make the function names unique. This should be made more clear here.
Please submit a PR to make this clear in the text.
