### ISSUE TITLE
Check if all API call restrictions in the different modes are contained in FMI 3.0

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#989]
After merging #982 which removed the API function call restrictions in the different states (and which was fine as they were outdated), we should check that we have not missed porting still valid restrictions that were contained in FMI 2.0.1 to the new description format, see https://github.com/modelica/fmi-standard/pull/982#issuecomment-629201757 and https://github.com/modelica/fmi-standard/pull/982#issuecomment-629205060

**Comment by chrbertsch** [comment]
While in the xCS types there are lists of "Allowed function calls" and "Forbidden function calls" for almost each node, this is completely missing for ME. So with  merging #982 essential information was removed and this needs an urgent fix!

**Comment by andreas-junghanns** [comment]
web design meeting:
Proposal: We should not list disallowed function. We should state in the beginning: "We list what allowed functions do. Calling any other API function in a certain mode will lead to undefined behavior, better implementations will return fmi3Error/fmi3Discard.

**Comment by andreas-junghanns** [comment]
#922 is related and I think I should fix both tickets in one PR. Closing this ticket and pointing here for details.
