### ISSUE TITLE
Odd formatting issue in non-normative text

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#990]
In 2_2_common_schema.adoc (currently line 968) you find:
_`inflow` and `outflow` is only...

This does not work well for ìnflow` - I tried different things, failed.
Could not find an example in the files.
Ideas?

**Comment by t-sommer** [comment]
Try this

```
`inflow` _and_ `outflow` _is only used...
```

since code won't be formatted as italic anyways.
