### ISSUE TITLE
Clarify meaning of IntermediateSteps

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#993]
According to the discussion ( https://github.com/modelica/fmi-design/tree/master/Meetings/2020-05-19-Regular-FMI-Design%20Webmeeting#991-intermediatestepfinished)  in today's regular design webmeeting, we have to clarify the meaning of Intermediate steps.

I propose to further discuss the open point here in order then soon prepare a PR:

**Questions to clarify/define**:

>     What is an intermediateStep?
>     What are the pre- and post-conditions?
>     What about the smoothness constraints of continuous and discrete variables?
>     What about inputs and outputs (all of the above)?

**What is an intermediateStep?**  An attempt:
In BCS and HCS it is assumed, that in stepMode a numerical solver solves differential equations in time.  This might be a variable step solver that tries out solver steps (e.g. to find internally treated discontinuities or based on an error estimation).  These are called temporary solver steps. (If we allow to get intermediate outputs there, they my not be trusted, as they may change). Once the internal solver accepts  time as successfull, the calculated values may no longer change.
Over the whole communication timestep, the inputs are assumed to be smooth functions of time on the current communication interval, provided by the master.   (The master does not have to know the evolution of these input functions for the whole communication interval in advance, but once one intermediate input has been set to the FMU at an intermediate time, the input function must be reproducable if called for a smaller intermediate time). For the calculation of the intermediate inputs the master may take into account intermediate output values  of successfull internal solver steps of the of the current FMU or other information e.g. from succussful intermediate steps of other FMUs.

Additional remarks by @andreas-junghanns:
Citing https://github.com/modelica/fmi-standard/issues/793#issuecomment-630963823: 

>  intermediateUpdate is not to propagate values between FMUs - communication points are for that. So intermediateUpdate is not supposed to (and I think cannot if we describe it right) allow for direct feedthrough outside of the FMU.
> I think we should keep things simple inside intermediateUpdate - if you need more information, you can always stop the doStep with earlyReturn and then properly exchange values.
> The final argument that comes to mind: if you need ultimate control, do ME. xCS is supposed to be simpler. If we allow all kinds of variants and complications, we will have ME2 - and we do not need another).

Thus the following decisions were taken at the regular design meeting today: 

>     1. force order of first Get and then Set (same as for doStep as for intermediateUpdate)
>     2. successive calls to intermediateUpdate must strictly monotonically increase time if intermediateStepFinished==fmi3True

![grafik](https://user-images.githubusercontent.com/16363372/82370235-83d6b380-9a18-11ea-9ef4-93898776bb2b.png)

There was not yet consensus regarding intermediateStepFinished, so there remain several options: 
 

> -   3aI. intermediateStepFinished==fmi3False: calling intermediateUpdate at the same time will always receive the same input values from the master
> -  3aII. any calling intermediateUpdate at the same time will always receive the same input values from the master
> -  3b. calling intermediateUpdate at the same time and the same output values of the FMUs values, the master gives the same time input values (inputs do not only depend on time, but also on the outputs of the FMU at the same time!)
> -    3c. remove receiving outputs if intermediateStepFinished==fmi3False (dashed lines)

As we have agreed to change the sentence

>It is not allowed to call intermediateUpdate for a simulation time point prior to a previous call with intermediateStepFinished 

to

> It is not allowed to call intermediateUpdate for a simulation time point prior to _*or equal to*_  a previous call with intermediateStepFinished 

I do no longer see the difference between  3aI and and 3aII. Can someone help?

**Smoothness of inputs:**
- There shall be a clear difference between  getting and setting values at an intermediate step on the one hand and doing the same at a communication points on the other hand: At the latter, possibly discontinuous values can be set to the inputs, forcing an internal numerical solver to re-initialize.
- Thus setting discrete input variables at intermediate steps is forbidden
- At intermediate steps, the master can provide smooth inputs e.g. based on an interpolation polynomial (that could e.g. also come from TLM (transmission line method). Currently it is not specified what kind of smoothness of the interpolant the master must provide to get the maximum convergence order of an internal solver (e.g. a higher order BDF multistep method).  This is not problem, if the the intermediate inputs are calculated with a polynomial, as this is infinitely often smoothly differentiable (C<sup>∞</sup>). But if the master would e.g use piecewise linear functions or cubic splines within a  communication interval, this would only be C<sup>0</sup> or C<sup>3</sup>.  Shall we need an information of the FMU to signal to the master "I need  C<sup>n</sup> smoothness?" Or shall the master signal to the FMU "I provide C<sup>n</sup> smoothness?" . This issue pops up, as in FMI 2.0 the interpolation (polynomial) was up to the FMU, but since https://github.com/modelica/fmi-standard/pull/939 we use IVA instead. Or shall we always provide C<sup>∞</sup> intermediate inputs within one communication step?

**Comment by robbr48** [comment]
The use-cases for `intermediateStepFinished==fmi3False` is when intermediate outputs from the FMU are required to compute the intermediate inputs. This is useful only for transmission line modelling I think. In practice, a small part of the equation system is placed in the master simulation tool in order to keep the interface cleaner. Instead of FMUs exchanging hard-to-understand variables such as "wave variable" and "characteristic impedance", they can exchange intuitive variables like "force" and "speed". Thus, the creator of the FMU will not need to understand the detail of the coupling technique used for the co-simulation.

**Comment by andreas-junghanns** [comment]
What I read here from @robbr48 (please correct if wrong!):
The reading of intermediate outputs (== dashed line in the picture) is required for the transmission line modeling use case.

If correct, this means we cannot forbid reading outputs (fmi3Get{VariableType} for outputs) even if intermediateStepFinished==fmi3False.

@robbr48 : please confirm! thanks you!

**Comment by robbr48** [comment]
@andreas-junghanns Confirmed. 

In fact, the only reason for having the `intermediateStepFinished` flag is to distinguish temporary output variables from non-temporary ones. Forbidding reading outputs when this flag is true would make the flag meaningless.

**Comment by andreas-junghanns** [comment]
> In fact, the only reason for having the `intermediateStepFinished` flag is to distinguish temporary output variables from non-temporary ones. Forbidding reading outputs when this flag is true would make the flag meaningless.

Actually, the idea was to forbid it when intermediateStepFinished==fmi3False.
Can you confirm that this is the understanding (you wrote "true" above, which confused me).

**Comment by robbr48** [comment]
My mistake, I meant to write "false".

We can already forbid reading outputs by setting `intermediateVariableGetAllowed == fmi3False`. What would the purpose be of having another flag that also forbids reading outputs?

In either case, reading outputs when `intermediateStepFinished == fmi3False` is required for the  transmission line method.

**Comment by chrbertsch** [comment]
(Discussion Andreas J, Christian B)
Input must be smooth on whole interval, may not depend on information on unfinished steps from this or other FMUs.

**Comment by andreas-junghanns** [comment]
To be clear: smooth in the entire interval, but the interpolation may change at points when the FMU reported "intermedateStepFinished" (the black dots).
If a discrete change of inputs is required, the master must force a communication step with earlyReturn.

**Comment by chrbertsch** [comment]
> To be clear: smooth in the entire interval, but the interpolation may change at points when the FMU reported "intermedateStepFinished" (the black dots).
> If a discrete change of inputs is required, the master must force a communication step with earlyReturn.

@robbr48 and others: 
Which degree of smoothness are typical for TLM Co-simulation for the whole communicatoin interval [tc_i, tc_{1+1}] ? C^∞?

@klausschuch  and others: are there other Co-Simulation schemes around, that would not provide  C^∞ smoothness of intermediate input values on the  whole communication interval, i.e. only C^k smoothness, k < \infty?

This is important, because during in communication interval, we want to take advantage higher order numerical integrators (e.g. BDF multistep methods w/o resetting them and forcing lower order steps. For simple polynomial based inter- or extrapolation on the whole interval, this is no problem.

**Comment by robbr48** [comment]
@chrbertsch The master interpolates intermediate inputs from a data table, so the degree of smoothness will depend on which interpolation technique is used. Our current master tool provides linear and hermite interpolation. Linear interpolation would give C^0, while (if I remember correctly) hermite spline interpolation would give C^1. Of course higher order interpolation is possible as well.

**Comment by chrbertsch** [comment]
> hrbertsch The master interpolates intermediate inputs from a data table, so the degree of smoothness will depend on which interpolation technique is used. Our current master tool provides linear and hermite interpolation. Linear interpolation would give C^0, while (if I remember correctly) hermite spline interpolation would give C^1. Of course higher order interpolation is possible as well.

Just to be sure: you mean C^0 resp. C^1 at inermediate time points, not for communication time points, right?

Then for many advanced solvers you will have a problem with higher order solvers. 
Image, a BCS FMU has internally a higher order BDF solver like CVODE. We do not want to interrupt and reset the solver at any intermediate points, but only at real communication points. Having low smoothness of the intermediate input variables will extremely slow-down the co-simulation.

If we cannot expect C^∞ inputs for the whole communication interval, we need some mechanism for the FMU of telling: "in order to be simulated effiziently I need smoothness of order C^k of inputs for the whole commucation interval." The Master then should provide a warningn if this requirement is not fulfulled.

**Comment by robbr48** [comment]
It would actually be quite easy to change the interpolation technique in the master so that it provides C^∞ smoothness, e.g. using polynomial interpolation over the entire doStep. We have not done so yet simply because we have not encounter any significant performance issues. 

Can we just formulate it as "For best performance the smoothness of intermediate inputs should be C^∞", to keep it simple?

**Comment by chrbertsch** [comment]
> It would actually be quite easy to change the interpolation technique in the master so that it provides C^∞ smoothness, e.g. using polynomial interpolation over the entire doStep. We have not done so yet simply because we have not encounter any significant performance issues.
> 
> Can we just formulate it as "For best performance the smoothness of intermediate inputs should be C^∞", to keep it simple?

I think there are use cases where it would be really benefical if the master would provided the recommended order of the input interpolation:

E.g., if the FMU does not contain a variable step solver, but perhaps internally does a certain number of equidistant explicit Euler steps (1st order ODE solver). If the the master somehow has knowledge of the inputs of the FMU for certain measurement points, then linear interpolation C^0 between those values would give much better results than building a higher order C^∞ for the whole communication interval (overshoot!)

So I propose to introduce a new optional flag:  `minInputSmoothness` with a default value of ∞.
This can be seen as the counterpart of `maxOutputDerivativeOrder`.
Its meaning is: if k=`maxOutputDerivativeOrder`, then the inputs on the current communication interval must be C^k smooth.

**Comment by robbr48** [comment]
Sounds reasonable. But I think the name `minInputSmoothness` can be confusing, since a lower order would in fact still work, but with reduced performance. How about something like `minRecommendedInputSmoothness` or `minDesiredInputSmoothness`? Or, since too high order of interpolation can affect stability due to overshoot, just `recommendedInputSmoothness`?

**Comment by chrbertsch** [comment]
> Sounds reasonable. But I think the name `minInputSmoothness` can be confusing, since a lower order would in fact still work, but with reduced performance. How about something like `minRecommendedInputSmoothness` or `minDesiredInputSmoothness`? Or, since too high order of interpolation can affect stability due to overshoot, just `recommendedInputSmoothness`?

Agreed. But perhaps we should mention `intermediate` in the flag name to clarify that this is not referrring to inputs in the classical FMI 2.0 CS sense. So what about  `recommendedIntermediateInputSmoothness`?

**Comment by robbr48** [comment]
Yes, that is much better I think.

**Comment by chrbertsch** [comment]
Regular Design Meeting: 

Karl: I agree on `recommendedIntermediateInputSmoothness`
Masoud: we have so many flags
Christian: We should make it optional

**Comment by chrbertsch** [comment]
> Karl: I agree on `recommendedIntermediateInputSmoothness`
> Masoud: we have so many flags
> Christian: We should make it optional

What shall be the value of `recommendedIntermediateInputSmoothness`?


??: no smoothness recommendations input data on a given communicatoin ingerval: I would use the type="xs:int" for `recommendedIntermediateInputSmoothness` and decode this with "-1"
0: C^0 means "smooth"
1: C^1 means one time continuously differentialble (1st derivative smooth)
2: C^2 means two time continuously differentialble (2nd derivative smooth)
??  C^∞: How do we docdoe this in the xml? I would use the type="xs:int" for `recommendedIntermediateInputSmoothness` and decode ∞ with a value of 1000 (theres is no "INF" for integer values".  I do not expect numerical solvers to expect  input smoothness requriments higher than 8.

I would  set the default to "1".

Other suggestions or comments?
