### ISSUE TITLE
Add description of intermediate{VariableGet,InternalVariableGet,VariableSet}Required

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#998]
(three TODOs in https://fmi-standard.org/docs/3.0-dev/#creation-destruction-and-logging)

Besides the instantiation functions I do not find any description or reference to these functions

    fmi3Boolean                    intermediateVariableGetRequired,
    fmi3Boolean                    intermediateInternalVariableGetRequired,
    fmi3Boolean                    intermediateVariableSetRequired,

**Comment by andreas-junghanns** [comment]
Is now obsolete?

**Comment by chrbertsch** [comment]
They have been renamed are now clearly described
